### ISSUE TITLE
Parse TZif files into ICU4X data formats for TzdbDataProvider

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#1000]
One of the formats we should be able to generate ICU4X TimeZone data from is [TZif](https://tools.ietf.org/id/draft-murchison-tzdist-tzif-00.html).

We can use the [libtzfile](https://crates.io/crates/libtzfile) crate to parse this data into native Rust objects and then serialize the data to the ICU4X format of our choice. 

This will then match the combined `--tz-src-format tzif` and `--tz-src-path` in the `datagen` crate 

For more context see
* #1008

**Comment by sffc** [comment]
@nordzilla Please assign this to a specific sprint in 0.6.
