### ISSUE TITLE
Unicode Locale Identifier (ULI) spec inconsistencies & naming issues

### ISSUE THREAD

**Issue by nciric** [unicode-org/icu4x#103]
@zbraniecki @macchiati 

I was reviewing #47 and I am seeing slight problems with naming and definition of ULI fields in the spec.

I am looking at the EBNF in the [ULI section](https://unicode.org/reports/tr35/#Unicode_locale_identifier) of the spec.

### -u section
> keyword (Also known as uvalue) = key (sep type)?
- We call _type_ "value" everywhere (Ecma402, ICU), including in #47. Should we update the spec to reflect that?

> attribute = alphanum{3,8}
 - see below for issues with parsing/sorting

> type (Also known as uvalue) = = alphanum{3,8} (sep alphanum{3,8})*
 - Also known is the same as for keyword. Error?
 - How do we distinguish _type_ from _attribute_ when parsing and sorting?

### -t section
> tfield = tkey tvalue
 - Here _tfield_ is what _keyword_ was for -u-. Why not the same name?
 - Here _value_ is what _type_ was for -u-. Why not the same name?
 - tvalue and type have different, but functionally equivalent, EBNF definition. Could we unify them?

In general I don't see anything show stopping, but language/naming in the spec affect the naming and parsing decisions in #47.

**Comment by zbraniecki** [comment]
Great. Thank you for starting the conversation!

I was following the EBNF syntax, but I agree that the naming scheme and subtle differences in syntax are mischievous.

I'm ok with all naming changes, but I'd say that even more important for a good implementation of the syntax API is understand when `foo-bar-baz` is a `multi-part key` and what is a `list of keys`. In EBNF it may look the same or very similar, but in API it becomes very different.

**Comment by macchiati** [comment]
We provide attributes in the BCP47 data that specify when a value can be a list of subtags, and what the relationship is between them.

**Comment by macchiati** [comment]
Clearly all this needs to be documented better, so please file CLDR tickets (or add comments to existing spec tickets) when you find problems.

**Comment by FrankYFTang** [comment]
> ### -t section
> > tfield = tkey tvalue
> 
> * Here _tfield_ is what _keyword_ was for -u-. Why not the same name?

This is NOT true
tfield = tkey tvalue;
tkey = alpha digit ;
tvalue | = (sep alphanum{3,8})+ ;

keyword  = key (sep type)? ;
key  = alphanum alpha ;
type  = alphanum{3,8}  (sep alphanum{3,8})* ;

so tkey and key are clearly mutually exclusive, by the second char of the token
and type is optional but tvalue is mandatory

**Comment by FrankYFTang** [comment]
> > type (Also known as uvalue) = = alphanum{3,8} (sep alphanum{3,8})*
> 
> * How do we distinguish _type_ from _attribute_ when parsing and sorting?

_attribute_ must appear between the "u" singleton and  _key_ , according to the grammar.
