### ISSUE TITLE
Evaluate Unicode Regex

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#105]
We have at least two regex related crates:
* https://github.com/ridiculousfish/regress
* https://crates.io/crates/regex

It may be useful to run a perf test comparing it to ICU Regex.

**Comment by zbraniecki** [comment]
Some (non-unicode) benchmarks between regex, regress and others - https://github.com/ridiculousfish/regress/blob/master/perf.md

**Comment by BurntSushi** [comment]
See also: https://github.com/rust-lang/regex/blob/master/UNICODE.md

**Comment by sffc** [comment]
Adding to backlog.

**Comment by sffc** [comment]
@iainireland will investigate.
