### ISSUE TITLE
`cargo make diplomat-get-rev` fails for me locally

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#1050]
```
➤ cargo make diplomat-get-rev
[cargo-make] INFO - cargo make 0.32.10
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: diplomat-get-rev
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: diplomat-get-rev
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 6 - invalid number at line 1 column 2
[cargo-make] WARN - Build Failed.
```

It fails for me on this line: `metadata = json_parse --collection ${metadata}`.

This command is required for the diplomat install. I worked around it by modifying the command:

```
[tasks.diplomat-get-rev]
description = "Get current Diplomat revision"
category = "ICU4X Development"
script_runner = "@duckscript"
script = '''
echo d98d31bdbdad3af98493ccfdc955b32fca886176
'''
```

I checked the output of `cargo metadata` by running `cargo metadata > metadata.json` and then parsing the JSON in node. The JSON appears well formed. It is quite large though at `1.1M`. I don't know if that is making the duckscript fail due to the size of the file.

**Comment by Manishearth** [comment]
What happens if you update `cargo-make`?

**Comment by gregtatum** [comment]
Yup, that fixed it. Can we enforce versioning for `cargo-make`?

**Comment by Manishearth** [comment]
I'm not sure how we can locally

I really wish Cargo let you specify related tools as cargo deps :)

**Comment by Manishearth** [comment]
cc @echeran @sffc if you have ideas for how to enforce the cargo make version

we _could_ make `tidy` check the cargo make version

**Comment by sffc** [comment]
Right now we install `cargo make` globally.  Is there a way to install it locally in the project, as a dev-dependency, and invoke the local version instead of the global version?

(That is how npm solves this problem: tools are installed in `node_modules/.bin` and automatically in the PATH of any other npm commands)

**Comment by Manishearth** [comment]
> Right now we install `cargo make` globally. Is there a way to install it locally in the project, as a dev-dependency, and invoke the local version instead of the global version?

nope, that was what i wish cargo did :smile:

**Comment by echeran** [comment]
I tried out the config from the [cargo-make documentation here](https://github.com/sagiegurari/cargo-make#usage-installing-version). In the end, it seemed to work (enforce an upgrade of cargo-make), but based on the console output, I suspect it's enforcing the upgrade of cargo-make _after_ the task has executed, _not before_. We could also add a task that creates a warning to users that also recommends "try again, next time should work".

What I did was add the line
```
install_crate = { crate_name = "cargo-make", binary = "cargo", test_arg = ["make", "--version"], min_version = "0.34.0" }
```
to the `[tasks.tidy]` task in `Makefile.toml`, knowing that I still was using v 0.33.0. Even though the above line sets the minimum at 0.34.0, it upgraded to 0.35.0, which is the latest.

The console output was:
```
$ cargo tidy
[cargo-make] INFO - cargo make 0.33.0
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: tidy
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Execute Command: "cargo" "fmt" "--" "--check"
[cargo-make] INFO - Running Task: license-header-check
License headers found in files matching ./**/*.rs 
License headers found in files matching ./**/*.yml 
...
License header check complete 
[cargo-make] INFO - Running Task: generate-readmes
Automatically generating components/calendar/README.md 
Automatically generating components/datetime/README.md 
...
[cargo-make] INFO - Running Task: generated-readme-check
[cargo-make] INFO - Running Task: license-file-check
[cargo-make] INFO - Execute Command: "cargo" "install" "--force" "cargo-make"
    Updating crates.io index
  Installing cargo-make v0.35.0
  Downloaded ...
...
  Downloaded 28 crates (9.5 MB) in 1.24s (largest was `envmnt` at 1.9 MB)
   Compiling ...
...
   Compiling cargo_metadata v0.14.0
   Compiling duckscriptsdk v0.8.5
   Compiling ci_info v0.14.3
   Compiling cargo-make v0.35.0
    Finished release [optimized] target(s) in 1m 28s
   Replacing /home/elango/.cargo/bin/cargo-make
   Replacing /home/elango/.cargo/bin/makers
    Replaced package `cargo-make v0.33.0` with `cargo-make v0.35.0` (executables `cargo-make`, `makers`)
[cargo-make] INFO - Build Done in 93.17 seconds.
```
