### ISSUE TITLE
Remove workarounds for Rust bugs in Yoke, DataPayload

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1061]
There are docs tests in the yoke and icu_provider crate that will begin compiling in Rust 1.56 or 1.57, due to fixes to upstream bugs https://github.com/rust-lang/rust/issues/86703 (fixed in 1.56) and https://github.com/rust-lang/rust/issues/88446 (fixed in 1.57).  This issue is to track steps to update to these Rust versions once stabilized and at the same time update our docs tests.

As part of this bug, also remove the obsolete `with_capture` variants of the functions, and fix alignment between Yoke and DataPayload.

CC @Manishearth

**Comment by sffc** [comment]
This is partially fixed by https://github.com/unicode-org/icu4x/pull/1090 and https://github.com/unicode-org/icu4x/pull/1135, but we are now blocked by the following bugs:

- https://github.com/rust-lang/rust/issues/84937#issuecomment-931935972
- https://github.com/rust-lang/rust/issues/89196

Moving to the 0.5 milestone to revisit.

**Comment by Manishearth** [comment]
There may be a workaround that means we can get rid of `_with_capture`: https://github.com/rust-lang/rust/issues/89436#issuecomment-968211087

**Comment by sffc** [comment]
I'll take another look now that 1.58 is stable.

**Comment by sffc** [comment]
OK, I was able to enable all of the docs tests that we had marked as "to be enabled" after 1.57.

It appears that we still need `YokeTraitHack` and `attach_to_cart_badly`. However, I'm not sure how to test whether we still need `project_with_capture`; it takes a `fn` argument, and I assume we'd need to test against a function signature that takes a function trait argument.

Many of the call sites reference https://github.com/rust-lang/rust/issues/84937, which is closed, but the code still doesn't compile (perhaps for different reasons than the issue was originally raised for). I saw this comment, but I'm not immediately sure how to apply it.

https://github.com/rust-lang/rust/issues/89436#issuecomment-968211087

I'm going to reassign this issue to Manish to take another look at some point before we stamp 1.0.

**Comment by robertbastian** [comment]
1.61 seems to make `attach_to_cart_badly` unnecessary, it's docs test starts compiling.

**Comment by Manishearth** [comment]
Let's keep it around but start migrating

**Comment by sffc** [comment]
Discuss: Should we keep the `badly` methods or not?

**Comment by sffc** [comment]
Discussion:

- @Manishearth - For `_badly`, we should keep them until at least 6 bug-free months have passed.
- @sffc - How about `_with_capture`?
- @robertbastian - Can we upstream our tests to the Rust compiler?
- @Manishearth - We should try to upload minimal working examples, which might be tricky, but yes, I would support that.
- @Manishearth - We should add the buggy version of `map_project` so that we can test it.

AIs:

- @Manishearth to file an issue to track adding the tests.
- @Manishearth to change `map_project` and `map_project_cloned` to use a closure.

**Comment by sffc** [comment]
This is 1.0 because it affects DataPayload APIs.
