### ISSUE TITLE
Cache npm packages in build bots

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1076]
CI runs such as [this one](https://github.com/unicode-org/icu4x/pull/920/checks?check_run_id=3660897876) report the following errors:

```
Error: Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at main (/usr/local/lib/node_modules/wasm-opt/bin/index.js:119:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wasm-opt@1.2.1 postinstall: `node bin/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wasm-opt@1.2.1 postinstall script.
```

This is likely due to npm being flaky when downloading dependencies.  We should create a package-lock.json with our required npm dependencies, and then add a caching step in GitHub Actions like we do with other dependencies.

**Comment by gnrunge** [comment]
Required some experimentation and re-arrangements. Global installation of npm packages ('npm install -g ...') does not seem to put a package-lock.json anywhere into the /usr/local/node_modules/lib/... install directories (nor anywhere else(?)). Had to switch from global to local installation, configuration, etc.
Task still under development. Two components 'wabt' and 'wasm-opt' are installed, each has its own package-lock.json file. Where to put in source hierarchy? New top directories e.g. npm-lock/[wabt/  | wasm-opt/] or similar?

**Comment by sffc** [comment]
If we have our own package-lock.json file, everything in node_modules should correspond to that.  We should cache everything in node_modules according to the content of package-lock.json.  We should also make sure that wabt and wasm-opt are installed into that node_modules.

**Comment by gnrunge** [comment]
In fact we have two package-lock.json files, one each when installing wasm-opt and wabt, respectively. Two different 'npm install ...' command executions. It seems one can only install one component per 'npm install'(?)

**Comment by sffc** [comment]
There are three package-lock.json files currently in the repo:

- https://github.com/unicode-org/icu4x/blob/main/package-lock.json should be deleted. Seems like a mistake.
- https://github.com/unicode-org/icu4x/blob/main/ffi/diplomat/wasm/package-lock.json is the main one.
- https://github.com/unicode-org/icu4x/blob/main/ffi/diplomat/wasm/bench/package-lock.json seems redundant with the one above and we should consider merging their respective package.json files.

In terms of wabt and wasm-opt, we currently install those with `npm install -g`, but perhaps we should instead install them as dev-dependencies in the main package.json file so that they are tracked by the same package-lock.json file and installed into node_modules.

**Comment by gnrunge** [comment]
I had the assumption that consecutive installation of two packages  'npm install ...' in the same directory while result in the package-lock.json of the first install being overwritten by the second install. Realized now (rather, tried out) that this is not the case, existing package-lock.json is updated instead. Good, that's easier.
I did away with global install already but still have to align a couple more parts.

**Comment by sffc** [comment]
What I'm saying is that we should not use `npm install wabt` and should instead add `wabt` as a dev-dependency in package.json, and when we need to use it, we should `npm ci` in that directory.

I'd also be okay considering adding a package[-lock].json file in the top-level tools directory, and that could be where we put all of our tools that happen to be distributed on npm.

**Comment by gnrunge** [comment]
Package installation of all npm packages consolidated as devDependencies into ffi/diplomat/wasm/package.json.
Caching to follow.
