### ISSUE TITLE
Consider passing DataRequest, and other arguments, by value

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1077]
Original issue: There are several places where it would be useful for a DataProvider impl to have an owned DataRequest.  It isn't clear why we're passing it by shared reference.

Scope increase: In general, what should be our style for when to take things by value versus by reference?  DataRequest is an example of something we may as well take by value, but it's not the only one: options bags are borderline, as are locales, etc.

**Comment by sffc** [comment]
Do you agree with changing the DataProvider trait to take DataRequest by value?

- [ ] @Manishearth 
- [ ] @zbraniecki

**Comment by Manishearth** [comment]
Seems fine, the request should 99% of the time be cheap to clone anyway

**Comment by sffc** [comment]
I'm scope-creeping this issue to include options bags and other arguments.  I think we haven't had a deep discussion about when to pass by reference and when to pass by value.

Need updated input from:

- [ ] @Manishearth 
- [ ] @zbraniecki 
- [ ] @gregtatum 
- [ ] @dminor

**Comment by Manishearth** [comment]
Options bags given at Formatter construction time, right? I think those should be by value, but if we ever pass additional options during formatting that should ideally be by reference.

**Comment by sffc** [comment]
I want to use this issue for DataRequest, and spawn a new issue for the options bags and other arguments that we should evaluate in Q1.

**Comment by dminor** [comment]
I agree with Manish.

**Comment by gregtatum** [comment]
Manish's options bag analysis seems reasonable to me.
