### ISSUE TITLE
Restructure AsVarULE or get rid of it

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1078]
Part of https://github.com/unicode-org/icu4x/issues/1082

Depends on https://github.com/unicode-org/icu4x/pull/1065

Currently AsVarULE has an `as_unaligned()` that imposes the requirement that AsVarULE types contian their VarULE counterparts somehow. This is fine for the current set of VarULE types, but in general does not work for e.g. custom VarULE types like

```rust
struct Relation {
   something: u8,
   something_else: u32,
   data: VarZeroVec<String>
}

#[repr(packed)]
struct RelationULE {
   something: u8::ULE,
   something_else: u32::ULE,
   data: [u8]
}
```

We currently only require `as_unaligned()` for the `PartialEq` implementation, which we can get around by adding some comparison methods to `AsVarULE`.

At a more fundamental level, it's worth considering if `AsVarULE` is worth it in the first place: `VarZeroVec<str>` might be just as convenient. We only need `AsULE` for `ZeroVec` for convenient conversions, but `VarZeroVec` promises to provide usable values for a lot of its use cases. Perhaps it is better to get rid of the distinction entirely.

cc @zbraniecki @sffc 

This is needed by @zbraniecki for #615

**Comment by sffc** [comment]
Related: if we change `VarZeroVec<String>` to `VarZeroVec<str>` and `VarZeroVec<Vec<u8>>` to `VarZeroVec<[u8]>`, then we also need to change `ZeroMap<String, Vec<u8>>` to `ZeroMap<str, [u8]>`.  (follow-up to https://github.com/unicode-org/icu4x/pull/1057#discussion_r709821567)

**Comment by Manishearth** [comment]
Yep!
