### ISSUE TITLE
Export Script_Extensions from ICU4C

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1086]
***This is the ICU4X tracking issue for https://unicode-org.atlassian.net/browse/ICU-21762***

ICU4C needs to export Script_Extensions, and then we need to consume it in ICU4X.

**Comment by echeran** [comment]
PR up in ICU at https://github.com/unicode-org/icu/pull/1933

**Comment by echeran** [comment]
Closing this issue, which is tracking the out-of-repo PR unicode-org/icu#1933,  after successfully merging the PR.
