### ISSUE TITLE
ECMA-402 traits discussion

### ISSUE THREAD

**Issue by filmil** [unicode-org/icu4x#110]
This is to point anyone interested in the direction of this pull request: https://github.com/google/rust_icu/pull/110

It's where @zbraniecki is helping me prototype an ECMA-402 inspired abstract API, based on [my earlier proposal](https://github.com/unicode-org/icu4x/blob/master/proposals/pr001-ecma402.md).

Feel free to chime in if you want.  It's been a fun journey so far, most recommended.

**Comment by filmil** [comment]
FYI https://github.com/google/rust_icu/pull/125 contains a Rust implementation for `Intl.ListFormat`, backed by `rust_icu`.

**Comment by sffc** [comment]
Is this issue actionable within the ICU4X repo?  If not, I'd like to close it.

**Comment by filmil** [comment]
Since for now the ECMA-402 implementation work doesn't touch icu4x components, if you want to declutter the issues dashboard, it is OK to close this one.

Be aware though, that implementing ECMA-402 traits will probably require us to make some API adjustment on icu4x so that it can implement the traits.  At that point I think it will be appropriate to open a new issue for that work.

**Comment by zbraniecki** [comment]
>  At that point I think it will be appropriate to open a new issue for that work.

Agree.
