### ISSUE TITLE
Support zip files and caching in datagen

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1105]
CLDR and now ICU ship zip files with their locale data.  I've previously written code that downloads the zip files, unpacks them into the local cache directory, and then reads from the unpacked directory (see #414).  However, moving forward, I would like to read from the zip files directly, without unpacking them first.

This will allow us to add the new `icuexportdata_uprops_sample.zip` file to the ICU4X data tree.  It will also be much of what we need to solve #718, paving the way toward a more user-friendly tool to automate ICU4X data generation.

Blocks #455.

**Comment by robertbastian** [comment]
Yes. Just to confirm this is just for datagen and not for `FsDataProvider`?

**Comment by sffc** [comment]
We should let datagen SourceData point at a zip file, and cache the parsed structures.
