### ISSUE TITLE
Design an ULE solution for enums

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#1123]
#1112 triggered a conversation about handling of enums in ULE. The solution used that is unsafe because in theory someone could use non-sequential indexes and that would lead to UB.

We want to solve it on ZeroVec::ule level for all customers.

**Comment by Manishearth** [comment]
I think this is just part of https://github.com/unicode-org/icu4x/issues/1079

**Comment by Manishearth** [comment]
I added a comment about this there, closing in favor of #1079
