### ISSUE TITLE
Fail with length error in PlainOldULE, CharULE, etc.

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1144]
In these ULEs, we are not currently returning an error for ULE as the safety docs proposed in #1121 insist that we do.  This is a bug that we need to fix now.

Question: What error type should we return in these two cases?  I had proposed UleError with a special variant for length errors, but this was voted down in #1121.  Currently, PlainOldULE is returning Infallible, and CharULE is returning CharTryFromError; clearly both of those will have to change.

Also add tests for this.

CC @Manishearth

**Comment by Manishearth** [comment]
I actually do think UleError is a good idea, I just didn't want the trait to automatically split out this check into a different method.
