### ISSUE TITLE
PluralRules

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#116]
I'd like to donate PluralRules as the next crate for ICU4X.

I think it's an exciting step forward because the crate fits several checkboxes for the right candidate:

* It's relatively mature, in use in production, battle tested, and maintained
* It's a core functionality for a lot of Internationalization operations
* It has a more similar API to canonical "ECMA402" APIs - constructor, and main method (in this case it is `select`, not `format`, but still)
* It requires data, so we'll get to test DataProvider, but it requires very little data (one String with a plural rule for cardinal, one for ordinal per locale)

I'd like to start by donating PluralRules supporting DataProvider JSON provided functions parsed at runtime.

In the process of preparing the PR I'd like to consider a way to handle "static" DataProvider (because plural rules change very rarely), but I'm ok delaying that mode for later, and I think we can make the perf-win from static vs dynamic very minor if we cache the parsed rule.

**Comment by sffc** [comment]
Sounds great; thanks!

Let's not do premature optimization on the data.  About caching in general: I'd like if we can keep caching as a layer that sits on top of the ICU4X data provider infrastructure, rather than deeply engrained into the library code.  That's a discussion for a separate issue, though.

**Comment by zbraniecki** [comment]
I think we agree.

> Let's not do premature optimization on the data.

It's not just about perf optimizations. It's also about delivery and packaging. `pluralrules` today have one dependency - `locale`. I would like to explore the possibility of having a way to ship `pluralrules` without dependency on `dataprovider` as an option in the future.

I don't think we should aim for it now, or optimize for it, but as I'll work on donating this crate, I'd like to see if it's possible to design it so that in the future we may have it working.

**Comment by sffc** [comment]
The data provider crate itself is a no-op; it's only a trait definition.  One could implement a super lightweight implementation of the trait that reads from static memory and plug it into PluralRules.  I think this would be the most extensible option without having duplicate code paths in PluralRules itself, one for static data and one for dynamic data.

**Comment by zbraniecki** [comment]
sgtm!

**Comment by zbraniecki** [comment]
I think this should be Q3.

**Comment by sffc** [comment]
Ok. NumberFormat depends on it (for compact notation and currency long names), so I'd like to see this in the first part of Q3 so we can finish NumberFormat and start on DateTimeFormat also in Q3.

**Comment by zbraniecki** [comment]
Definitely. My plan is to get the PR in within a month. I just don't want to commit to have it done in 2 weeks.
