### ISSUE TITLE
Document the prerequisites for cargo make ci-all

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#1163]
[CONTRIBUTING.md](https://github.com/unicode-org/icu4x/blob/main/CONTRIBUTING.md) says:

> * `cargo make ci-all` runs all tests and lints

I don't see documentation of what commands one should run before that one to expect that command to succeed. On Ubuntu 20.04, I've so far figured out that I need to run

```sh
cargo install cargo-make
cargo install cargo-readme
rustup default nightly-2021-09-22
rustup component add rust-src
cargo install twiggy
```

(It seems to me that having to run the `rustup` commands manually is probably a bug in the CI task.)

Then I've also figured out that installing the Ubuntu-provided Node.js isn't a good idea. However, after installing Node.js in a different way and progressing to the point of discovering that I need to install Emscripten and that Emscripten may come with its own copy of Node.js, I figured that I should stop experimenting and instead file this issue to ask what the right way to obtain the dependencies is.

**Comment by hsivonen** [comment]
CC @echeran

**Comment by echeran** [comment]
For part of the problem -- the tools and crates in the Rust + cargo ecosystem (ex: [this CI job's setup steps](https://github.com/unicode-org/icu4x/blob/main/.github/workflows/build-test.yml#L233-L236)), maybe we could refactor some of that setup into a `cargo-make` command similar to what was done for #1050. However, that wouldn't address the tools outside of the ecosystem, like Node.js

@Manishearth @zbraniecki @sffc  What is the full list of tools and crates (and their version numbers) that you use? How do you recommend the setup instructions for tool dependencies outside of the Rust+cargo ecosystem, like Node.js?
