### ISSUE TITLE
Continous Benchmarking

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#117]
With https://github.com/rhysd/github-action-benchmark we can get https://rhysd.github.io/github-action-benchmark/dev/bench/ for our components.

Seems like a good investment to monitor for performance per-component.

**Comment by echeran** [comment]
This could also include some of the tools mentioned in https://blog.tonari.no/why-we-love-rust, like [`cargo flamegraph`](https://github.com/flamegraph-rs/flamegraph)

**Comment by zbraniecki** [comment]
I started using flamegraph over the last two days and it's pure magic and unicorns. It works great.

I don't know if we'll be able to hook it into continuous visualization but I am going to use it in my work and recommend it to every one :)
