### ISSUE TITLE
Consider renaming ZeroVec::clone_from_slice

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1181]
`ZeroVec::clone_from_slice` and `Vec::clone_from_slice` have the same name but different semantics.

We have three functions that each take a slice of an aligned type and attempt to produce a ZeroVec:

- `ZeroVec::clone_from_slice` always allocates
- `ZeroVec::try_from_slice` borrows if possible and otherwise returns None
- `ZeroVec::from_slice` borrows if possible and otherwise allocates

`try_from_slice` and `from_slice` are only available if the aligned type implements `EqULE`.

There are also two more constructors:

- `ZeroVec::parse_byte_slice` borrows from a byte slice (or returns an error)
- `ZeroVec::from_iter` always allocates

Additionally, the type is a public enum which can be created directly from `Vec<T::ULE>` or `&'a [T::ULE]`.

Some possible naming conventions:

| Current | Option 1 | Option 2 | Option 3 |
|---|---|---|---|
| `clone_from_slice` | `new_owned` | `alloc_from_slice` | `from_aligned_owned` |
| `try_from_slice` | `try_new_borrowed` | `try_from_slice` | `try_from_aligned` |
| `from_slice` | `new_maybe_borrowed` | `from_slice` | `from_aligned` |

Needs feedback from:

- [x] @Manishearth 
- [x] @zbraniecki 
- [x] @echeran

**Comment by Manishearth** [comment]
I also see a need for `borrowed_from_ule_slice()` (https://github.com/unicode-org/icu4x/pull/1182) which fits in that model quite well
