### ISSUE TITLE
Consider requiring all ULEs to be Copy

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1184]
We currently have the `Copy` bound on the `impl ZeroVec`.  However, it may make more sense to move it to the `trait ULE` itself.  I know there is a debate about when to put bounds on the `impl` and when to put them on the `trait`.

Motivating case: `#[derive(Clone)]` does not seem to work on structs containing a `ZeroVec` field.  See e.g. #1161

Needs approval from:

- [x] @Manishearth 
- [x] @iainireland

**Comment by Manishearth** [comment]
Yeah that works for me.
