### ISSUE TITLE
Attempt to simplify ZeroCopyFrom

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1186]
I think we should be able to move the `'b` in ZeroCopyFrom up to the trait and then remove the `Yokeable` bound.  CC @Manishearth 

If we add `FromVarULE` in #1180, we may be able to merge that trait and ZeroCopyFrom.

**Comment by Manishearth** [comment]
Yeah if we implement ZCF on the Output types instead of the input types stuff will be much nicer, and we'll hit fewer of those compiler bugs.

**Comment by Manishearth** [comment]
Oh, we have duplicate issues; oops

https://github.com/unicode-org/icu4x/issues/1255
