### ISSUE TITLE
build.rs compatible datagen api

### ISSUE THREAD

**Issue by devsnek** [unicode-org/icu4x#1188]
I think it would be nice if icu4x provided an api you could call from your build.rs for generating the data your app needs instead of having to clone the repo and run a cli command. it could also do stuff like automatically emitting the `cargo:rerun-if-changed` things for the generated files.

**Comment by sffc** [comment]
The mechanism here should be a postcard blob or json file system with a build.rs file that makes a Crabbake data file.

**Comment by robertbastian** [comment]
I think this request is independent of Crabbake. Having a library version of the datagen binary that could be wired to a crate's `build.rs` does make things a lot easier than downloading the datagen crate and manually generating the data.

**Comment by sffc** [comment]
I think the deliverable here is to build a sample project using a build.rs file and document it with a tutorial.
