### ISSUE TITLE
OmnICU Rust Style Guide

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#12]
@hagbard has been drafting a style guide for OmnICU code in Rust.  We should clean up the style guide and check it in to the docs/ folder as a Markdown file.

**Comment by hagbard** [comment]
There's many more things to be added to the style guide. I'll share the doc publically for collaboration after a tidy up tomorrow. However there's no need to think of it as "finished" or "a set of hard rules" any time soon as I expect it will evolve dramatically as we go forward.

**Comment by sffc** [comment]
The outcome in the short term is to have the SC officially "approve" some form of the style guide.  It will evolve, definitely, but we need a starting point, and then future improvements can be reviewed by the SC as they come in.

**Comment by sffc** [comment]
Fixed by #48
