### ISSUE TITLE
Port UCharsTrie to ICU4X

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#1202]
UCharsTrie is a [data structure in ICU4C](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/classicu_1_1UCharsTrie.html) that will be needed for the Collator implementation.

Similar to https://github.com/unicode-org/icu4x/issues/131, we should port this to ICU4X.

**Comment by sffc** [comment]
From discussion with @markusicu: UCharsTrie and UBytesTrie are similar, but UCharsTrie is more straightforward and he recommends we start there.  The learnings from UCharsTrie should be used to influence UBytesTrie.  We can decide later whether we want both, or whether we want to keep just UCharsTrie.

**Comment by markusicu** [comment]
> Naming: `CodePointTrie` is an immutable data structure that you can use repeatedly. I don't understand why `[U]CharsTrie` is mutable and needs to be recreated every time you try to use it.

The immutable data structure is just an array of u16. It didn't seem necessary in C++/Java to wrap that into a named type.

Walking the structure while matching requires an iterator. The API exposes that "close to the metal". There is a next(CharSequence) but it's still stateful. There could be a const convenience version that starts from the initial state and ends with a match result, but various use cases really do want to know what happens with intermediate matches, so they need the stateful iterator API.

> I feel like the mutable version should be named `[U]CharsTrieIterator`, or if that name is reserved for something else, then maybe `[U]CharsTrieCursor` or something like that.

I agree that calling the stateful thing an ...Iterator makes it clear that that thing is stateful, but it would be nice to just use the same name (modulo language-specific UChars/Chars/U16 prefix) as in C++/Java.

The nested Iterator class in ICU iterates over the contents (sequence/value pairs) reachable from the current trie object state.
