### ISSUE TITLE
Implement Unicode properties required by UAX 29 

### ISSUE THREAD

**Issue by aethanyc** [unicode-org/icu4x#1214]
We need the following Unicode properties:

- Grapheme_Cluster_Break
- Sentence_Break
- Word_Break
- Extended_Pictographic for [GB11](https://www.unicode.org/reports/tr29/#GB11)

**Comment by aethanyc** [comment]
@makotokato Here are the example in the document to use [Word_Break](https://unicode-org.github.io/icu4x-docs/doc/icu_properties/maps/fn.get_word_break.html) property. The [Extended_Pictographic](https://unicode-org.github.io/icu4x-docs/doc/icu_properties/sets/fn.get_extended_pictographic.html) and [Script](https://unicode-org.github.io/icu4x-docs/doc/icu_properties/maps/fn.get_script.html) are also available. Note the getter's return value may change pending on the discussion in #1239.

**Comment by makotokato** [comment]
Thanks a lot.
