### ISSUE TITLE
Implement base16k for byte array serialization

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#124]
From @markusicu: a Unicode-based text encoding for binary data that claims to be more efficient than base64.  We should consider using this in ICU4X:

https://sites.google.com/site/markusicu/unicode/base16k

**Comment by hsivonen** [comment]
The efficiency is worse than base64 in the UTF-8 case. Considering that UTF-8 is the main UTF for interchange and the preferred in-RAM UTF for new code that doesn't have UTF-16 legacy, it seems bad to promote a bytes-as-text encoding that's less efficient than base64 as UTF-8.

**Comment by sffc** [comment]
I discussed this with Markus and confirmed that base16k is intended when UTF-16 is the primary character encoding.  I'm putting this on the backlog.  We should use base64 to start, and we could implement base16k in the future if it seems useful when interfacing with UTF-16 languages.

**Comment by sffc** [comment]
Base64 is fine.  Closing as designed.
