### ISSUE TITLE
Investigate the possibility of u16 lengths in VarZeroVec

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1261]
Currently VarZeroVec assumes that individual entries may have lengths that fit up to `u32` in size. This is quite reasonable, however this is using 4 bytes per element. It may be more efficient to use a `u16` here. `rkyv` uses u16s but is parametrizable.

It's worth discussing whether `VarZeroVec<T>` will ever contain `T`s that are large enough to need more than a `u16`s worth of space (64 KB) to store their byte length. Note that `VarZeroVec`s can be nested.

Independently of this, it's also worth considering if `VarZeroVec<T>` can be made `VarZeroVec<T, N = 2>` so we can allow for arbitrary length sizes.

**Comment by Manishearth** [comment]
Closing in favor of https://github.com/unicode-org/icu4x/issues/1410

**Comment by sffc** [comment]
Subsumed by #1443
