### ISSUE TITLE
CI for rustdoc test

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#127]
I was reading this page: https://doc.rust-lang.org/rustdoc/documentation-tests.html

It would be nice if we ran `rustdoc --test` on all our Rust files to make sure that the examples work as intended.

@zbraniecki @echeran

**Comment by zbraniecki** [comment]
`cargo test` executes doc tests!

**Comment by zbraniecki** [comment]
See for example https://github.com/unicode-org/icu4x/runs/766873472?check_suite_focus=true#step:7:182 - this is where the doc tests start.

**Comment by sffc** [comment]
Great!  I can close this issue, then.
