### ISSUE TITLE
Add test for icu4x-datagen --all-keys --all-locales in CI

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1281]
Two independent times in the last month and a half, `icu4x-datagen` has been changed in such a way that it passes for our test locales, but breaks when run against the full CLDR.  Both of these were small things that were basically mistakes, and they get fixed fairly quickly, but it results in a poor user experience because it takes someone running the tutorial to discover the problem.  We should add an `--all-keys --all-locales` test in CI to prevent this in the future.

The tricky part is how to implement the test in a non-flaky way.  We don't want to add full CLDR JSON to the repo, because it's too much data.  But downloading it on the fly could have flakiness issues.  But maybe if we run this in GitHub Actions, downloading from GitHub as the CDN might work?

CC @iwsfutcmd

**Comment by sffc** [comment]
CC @gnrunge -- would you be interested in taking this?

**Comment by sffc** [comment]
CC @sapriyag

**Comment by robertbastian** [comment]
Fixed by #2021
