### ISSUE TITLE
Include `ur-IN` and `ml` in list data

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#1282]
`ur-IN` contains the list pattern `{1}, {0}` which doesn't make a lot of sense (it rotates the list), so we ignore the locale at the moment.

**Comment by sffc** [comment]
Is there a CLDR issue to track this?

**Comment by robertbastian** [comment]
https://unicode-org.atlassian.net/browse/CLDR-12028

**Comment by robertbastian** [comment]
Also excluding `ml` for now, see the CLDR issue for details

**Comment by robertbastian** [comment]
Found a way to support `ml`, but it'd be a lot cleaner if we made the proposed spec changes.

**Comment by sffc** [comment]
We don't need to support old CLDR versions until we hit 1.0
