### ISSUE TITLE
PluralRules data format

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#130]
*forked from #78*

@zbraniecki said:

> So, substracting that shared piece from my numbers, loading the data into that structure: https://github.com/zbraniecki/icu4x/blob/pluralrules/components/pluralrules/src/data/json.rs#L12-L26
>
> takes:
>
> - JSON: ~162000ns
> - CBOR: ~131000ns
> - Bincode: ~100000ns

Thanks! So, the majority (vast majority) of the time, according to your measurements, is the data deserialization.  In some sense, that's good, because it means that the PluralRules code itself is pretty fast.

I was looking at the definition of your data structure.  I'll copy it here for posterity:

```rust
#[derive(PartialEq, Debug, Serialize, Deserialize)]
pub struct Resource<'s> {
    #[serde(borrow)]
    pub supplemental: Supplemental<'s>,
}

#[derive(PartialEq, Debug, Serialize, Deserialize)]
pub struct Supplemental<'s> {
    #[serde(rename = "plurals-type-cardinal")]
    #[serde(borrow)]
    pub plurals_type_cardinal:
        Option<HashMap<LanguageIdentifier, HashMap<PluralCategory, &'s str>>>,
    #[serde(rename = "plurals-type-ordinal")]
    #[serde(borrow)]
    pub plurals_type_ordinal: Option<HashMap<LanguageIdentifier, HashMap<PluralCategory, &'s str>>>,
}
```

Two suggestions for how to improve this:

1. LanguageIdentifier should not be in this structure.  Your request to the DataProvider should be, "I want cardinal rules for fr-FR", and the response should be just that, without throwing in cardinal rules for every other language identifier.
2. Instead of `HashMap<PluralCategory, &'s str>`, I would use a `struct` with six fields for each of the six standard plural forms.  For example:

```rust
// Main definition
pub struct ByStandardPlural<T> {
  pub zero: T,
  pub one: T,
  pub two: T,
  pub few: T,
  pub many: T,
  pub other: T,
}

// Example for your use case
pub struct PluralRuleStrings<'s> {
  pub rule_strings: ByStandardPlural<Option<&'s str>>;
}
```

Why?

- HashMap is a lot of code and not very `no_std`-friendly
- If you know the keys ahead of time, I structs should be faster than HashMaps

Alternatively, and maybe better, would be to use something like [enum_map](https://docs.rs/enum-map/0.6.2/enum_map/).

**Comment by zbraniecki** [comment]
Good call. I'll adapt your suggestion in the next iteration

**Comment by zbraniecki** [comment]
I ended up having a bit of time today so I dove into this. I went for the simplest data model for now, just to validate the hypothesis that not having to parse all locales and using `struct` in place of a `HashMap` will affect perf.

It does!

I haven't retested CBOR, but I did retest bincode/json:

| Type | Time Old | Time New | Size Old | Size New |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Inline String | 39344 ns | - | ? | - |
| Bincode  | 137845 ns | 84729 ns | 57k | 25k |
| JSON | 201755 ns | 149627 ns | 69k | - |

I'm going to close this and continue working in the PR.
