### ISSUE TITLE
Remove ZeroCopyFrom requirement on data struct

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1301]
ZeroCopyFrom was introduced in order to power RcStruct.  Given #1262, we no longer have RcStruct.  Should we therefore remove the ZeroCopyFrom bounds and auto-implementations everywhere?

- [x] @Manishearth

**Comment by Manishearth** [comment]
Oh I didn't realize this needed my approval. Yeah I'm fine killing the requirement.

**Comment by sffc** [comment]
So actually I think we want to keep the requirement, because it's what we use to enforce that the types are zero-copy (e.g., using `Cow<'data, str>` instead of `String`).  So we should keep this derive until we have some other way to enforce that requirement.
