### ISSUE TITLE
Symlink function in icu_provider_fs and WASM compatibility

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1313]
We have the following code in aliasing.rs:

```rust
#[cfg(target_family = "unix")]
use std::os::unix::fs::symlink as symlink_file;

#[cfg(target_family = "windows")]
use std::os::windows::fs::symlink_file;
```

When targeting something other than unix or windows, such as WASM, this code fails to compile.  This is by design, since icu_provider_fs is hidden behind a Cargo feature that is disabled on WASM.

However, this can still cause problems when compiling this code in a non-Cargo build system like GN.  GN essentially builds all Rust crates with all features and dependencies enabled, bypassing the Cargo-specific configs we have in place to prevent this code from being built on WASM.  GN *does* support cfg-based dependencies; we have one in icu_capi:

```toml
[target.'cfg(not(any(target_arch = "wasm32", target_os = "none")))'.dependencies]
icu_provider_fs = { path = "../../provider/fs/", optional = true }
```

However, `icu_provider_fs` is still pulled in via `icu_testdata` since all features are enabled.

We could:

1. Change the symlink function to be a stub on WASM so the code compiles; this is similar to what `std::fs` does on WASM ([source code](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/wasm/mod.rs))
2. Change icu_provider_fs itself so that it is a stub on platforms without filesystem support
3. Add a target cfg to icu_testdata so that it doesn't pull in icu_provider_fs transitively (but this is only a bandaid)

Thoughts?

- [x] @Manishearth 
- [X] @dminor

**Comment by dminor** [comment]
I think making the symlink function a stub is the simplest solution if we expect most of the time we'll be able to disable icu_provider_fs in the build system.

**Comment by Manishearth** [comment]
To answer the immediate question: I'm not a fan of the wasm stubbing thing the stdlib does, but I think we should just follow suit.

However, I do not think we should in general constrain ourselves by tools that do not support cargo features:

>  essentially builds all Rust crates with all features and dependencies enabled, bypassing the Cargo-specific configs we have in place to prevent this code from being built on WASM. GN does support cfg-based dependencies; we have one in icu_capi:


Is this something GN does or cargo-gnaw? GN should not be reading Cargo.toml files at all. We probably should be able to tweak cargo-gnaw to support this, I think [this](https://cs.opensource.google/fuchsia/fuchsia/+/main:tools/cargo-gnaw/src/graph.rs;l=135;drc=b26e9e73eae2d90d0eb49f2b0118b71ce163b78e;bpv=1;bpt=1) is the relevant code.

**Comment by sffc** [comment]
GNaw throws away optional dependencies and features when it flattens things into a GN file.

GN itself also does not have the concept of features built-in, although there are probably ways to monkey-patch something that works similarly to features by writing one's own `rust_library` targets or by using GN `config`s.  This would require some work either in core GN or by making a "GNaw runtime" that gets dumped by GNaw.

Here is the GN reference page:
https://gn.googlesource.com/gn/+/main/docs/reference.md

**Comment by Manishearth** [comment]
> GNaw flattens optional dependencies and features when printing the GN file.

Right, I'm suggesting perhaps we can ask GNaw to filter some features for some crates (perhaps based on input config). This might be a really complicated ask but it's worth asking, I think; I don't want to lose the ability to use cargo features for what we need here.

**Comment by sffc** [comment]
Oh, you mean pass the feature set *to GNaw itself* when generating the GN files?  That might be more doable.

**Comment by Manishearth** [comment]
Yep! For our use case we don't need the GN files to support a ton of configurability (yet? hopefully?) but it would be nice if we could have it happen at gnaw-time so that we can still use features to their full extent on the icu4x side. Not a blocker, clearly, since we have a workaround for the wasm thing, but it's worth pulling on this thread with the gnaw maintainers in advance.

**Comment by sffc** [comment]
> To answer the immediate question: I'm not a fan of the wasm stubbing thing the stdlib does, but I think we should just follow suit.

The stdlib uses the `!` operator, which seems to be unstable for general use.  How would you suggest stubbing the method in userland?

**Comment by Manishearth** [comment]
you mean the never type? The never type is sugar for `enum Never {}`, you can use such an enum directly. `std::convert::Infallible` is one such enum if you don't want to define it.

Though usually what people do is use `unreachable!()`. `!` is only useful for stubbing _types_, not code.

**Comment by sffc** [comment]
ok, it looks like this is the code that stdlib runs in all the stubs:

https://github.com/rust-lang/rust/blob/0a84708edca7c275cb99ad080317fbc7637516d8/library/std/src/sys/unsupported/common.rs#L19

```rust
pub fn unsupported<T>() -> std_io::Result<T> {
    Err(unsupported_err())
}

pub fn unsupported_err() -> std_io::Error {
    std_io::Error::new_const(
        std_io::ErrorKind::Unsupported,
        &"operation not supported on this platform",
    )
}
```

That's easy enough to replicate.
