### ISSUE TITLE
Port UCPTrie to ICU4X

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#132]
UCPTrie is [a data structure in ICU4C](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/structUCPTrie.html) that maps from code points to integer values.  This data structure is fundamental to various pieces of functionality, including enumerated Unicode properties.  We should port this data structure to ICU4X.

**Comment by kpozin** [comment]
Could this be a wrapper on top of BytesTrie?

**Comment by sffc** [comment]
Implementation design doc: https://docs.google.com/document/d/1JkrL4pv477dIVnfilwlAEwqF9vstb_Uo_5XeUz2WXM8/edit#

**Comment by echeran** [comment]
notes doc for meeting with @markusicu on details & explanations of CodePointTrie implementation : https://docs.google.com/document/d/1yS9emU-G2EhXF9XgSf8suY8RWduYKBZNmDIaFY-qD_I/edit#

**Comment by markusicu** [comment]
FYI UCPTrie is a C API name. If we had a proper C++ API it would follow the naming conventions of Java where it's called CodePointTrie. ICU4X/Rust should probably follow Java naming more closely here.
