### ISSUE TITLE
Consider splitting serialize/deserialize features

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1320]
Currently we have 1-2 serde-related features for our crates:

 1. `serde`: Serializing/Deserializing regular types exported by the crate
 2. `provider_serde`: Serializing/Deserializing data structs used by the crate (needed for most data providers)

https://github.com/unicode-org/icu4x/pull/1306 made `serde-json` an unconditional dependency of Litemap's serialization code (and eventually ZeroMap will be doing the same.

Most users of ICU4X only need the ability to deserialize data structs (typically used by various data providers). It's worth considering splitting the second feature (`provider_serde_serialize` and `provider_serde_deserialize`? or perhaps `provider_serde` and `provider_serde_serialize`) further to reduce code bloat.

Note that we can be reasonably confident in Rust's ability to dead code eliminate unnecessary serialization code; the primary benefits of this are compile times for the vast majority of our users who do not need serialization. A downside is that adding more features will increase the runtime of our `features` CI job.

Thoughts?

Input requested from:

 - [x] @sffc 
 - [x] @zbraniecki 
 - (feel free to add yourself if you want me to block on the resolution of this issue on your thoughts)

**Comment by zbraniecki** [comment]
I think I am missing something. How is `serde-json` needed for serialization but not for deserialization?

**Comment by Manishearth** [comment]
@zbraniecki We need to be able to test what kind of object it is: if it's stringlike or integerlike. The alternative is to implement our own custom serializer and that is extremely annoying to do (it's a _lot_ of finicky code); `serde_json::Value` gives us this for cheaper.

**Comment by sffc** [comment]
Maybe we should consider two features:

- `icu4x_serde_se`
- `icu4x_serde_de`

These would be used for all serde purposes (both exported library types and the data provider types).  The serde feature would only exist as an optional dependency.

The annotations in code would become

```rust
#[cfg_attr(feature = "icu4x_serde_se", derive(serde::Serialize))]
#[cfg_attr(feature = "icu4x_serde_de", derive(serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(borrow))]
```

**Comment by Manishearth** [comment]
I prefer this, I don't see a strong reason to separate data structs from exported types, the actual derives are cheap; it's just a matter of which dependencies are being pulled in

**Comment by sffc** [comment]
And then make `icu4x_serde_de` default and not `icu4x_serde_se`, correct?

**Comment by Manishearth** [comment]
Yeah, something like that!

**Comment by sffc** [comment]
Decision:

- `serde` enables Serialize and Deserialize on library types, plus Deserialize on provider types
- `datagen` enables Serialize and Bakeable on provider types, as well as everything currently covered by `icu_tranform_internals`
- Both of these features should be disabled by default.

Approved by: @Manishearth, @mihnita , @iainireland

**Comment by Manishearth** [comment]
I think nobody is currently working deeply on the code here so I'll pick this up next.

**Comment by robertbastian** [comment]
There are two similar features whose names we should maybe also update:
* `icu_list/icu4x_human_readable_de`: should we call that `serde_human` or `serde_text`?
* `litemap/serde_serialize` is not mentioned above. This feature covers the whole serialization impls, even though the dependency it's "protecting" (`serde_json`) is only used for text formats in some cases. We could narrow the feature to something like `serde_human_ser` to provide machine serialization even without it. Wdyt? Alternatively here we could also try to avoid the dependency.

**Comment by Manishearth** [comment]
I think in the case of litemap/zeromap we want consistent serialization, but the thing is _most_ users don't need serialization, only deserialization, so we have it as an additive feature

**Comment by robertbastian** [comment]
Such a feature would bleed into the icu_uniset and icu_codepointtrie crates as well though. I think it'd be best if we got rid of the dependency somehow.

**Comment by Manishearth** [comment]
@robertbastian sure, but then it turns into the `datagen` feature elsewhere

We could get rid of the feature but we'd need to write another crate for that. I don't know if I'll have time but we can plan for that eventually!

**Comment by Manishearth** [comment]
Yeah thinking about it more I'd like to drop that dep, might hack something together

**Comment by robertbastian** [comment]
What do we think about `serde_human`?

**Comment by Manishearth** [comment]
i think it's fine!
