### ISSUE TITLE
Create OWNERS files for each component

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#133]
Follow-up from #72: I think it would be useful to record in each component tree who the "owners" are of that component.  The owners would be the people responsible for reviewing PRs to that component.  Google's Bazel build system does this using a file called OWNERS with a line-separated list of usernames.

**Comment by nciric** [comment]
I think the ownership in rust is expressed in crates.io, not at the crate level.

**Comment by Manishearth** [comment]
I think the crates.io owners should just be a GitHub team (`icu4x:cargo-publish`). Having "code owners" for review makes sense.

**Comment by sffc** [comment]
Related: #25

**Comment by sffc** [comment]
Take a look at code owners and see if it satisfies our use case:

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by kpozin** [comment]
Relevant: https://github.blog/2017-07-06-introducing-code-owners/

> **An extra layer of code security**
> For projects with more rigorous review processes, we’ve also added a new protected branch option to ensure the right people have a chance to review.
> With protected branches enabled, a code owner for each owned file has to leave a review before anyone can merge a pull request to that branch.
