### ISSUE TITLE
Add clippy lints to catch more panics

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1363]
We should enable the following clippy lints:

- `indexing_slicing` https://rust-lang.github.io/rust-clippy/master/#indexing_slicing
- `expect_used` https://rust-lang.github.io/rust-clippy/master/#expect_used
- `unwrap_used` https://rust-lang.github.io/rust-clippy/master/#unwrap_used
- `panic` https://rust-lang.github.io/rust-clippy/master/#panic

Ideally we can limit this to library code only.  We don't want these in test code or offline tooling code.

As usual, in cases where the usage of these operators is valid, an `#[allow(clippy::indexing_slicing)]` can be used, with a comment explaining why it is OK.

The goal here is to better enforce this section of the style guide: https://github.com/unicode-org/icu4x/blob/main/docs/process/style_guide.md#best-practice

I can't talk about panics without also referencing https://github.com/unicode-org/icu4x/issues/1183

- [x] @Manishearth 
- [x] @dminor 
- [ ] @iainireland

**Comment by robertbastian** [comment]
I don't agree with `expect` over `unwrap`. If either are justified because it's obvious that the value is `Ok`/`Some`, using `expect` puts a pointless string in the binary.

**Comment by Manishearth** [comment]
It's not really pointless because it tells you more about where in the code the problem happened. Fortunately, unwrap/expect now use `#[track_caller]` so they're not 

---

I'm over all positive about adding these lints; I think they'll work out well!

**Comment by sffc** [comment]
> I don't agree with `expect` over `unwrap`. If either are justified because it's obvious that the value is `Ok`/`Some`, using `expect` puts a pointless string in the binary.

I want to forbid both.

**Comment by dminor** [comment]
This makes sense to me.

**Comment by ozghimire** [comment]
I can add these clippy lints. Is anyone else working on this at the moment?

**Comment by sffc** [comment]
Yes it is. Nothing has changed since I filed the issue.

**Comment by sffc** [comment]
Looking at @ozghimire's PR, I'm wondering if we should restruct `unwrap` and `[]`, but allow `expect`, since the point is to have an affirmative comment that the panic is safe, and `expect` already gives that to us.

**Comment by robertbastian** [comment]
> since the point is to have an affirmative comment that the panic is safe

We're not saying the panic is "safe" (which has a special meaning in Rust), we're saying it's *impossible*. We shouldn't include a message in the binary that will never be used.

I also think we should be consistent and either always `expect` or always `unwrap`.

**Comment by gregtatum** [comment]
> We shouldn't include a message in the binary that will never be used.

But logic errors do come up, and the assumption that it'll never be shown can be wrong.

**Comment by sffc** [comment]
Fixed in #1650
