### ISSUE TITLE
Unify BlobDataProvider/StaticDataProvider impls with new deserializer code, including FFI

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1368]
Make BlobDataProvider and StaticDataProvider have a pass-through impl like FsDataProvider; something like:

```rust
impl<M> DataProvider<M> for BlobDataProvider
{
    fn load_payload(&self, req: &DataRequest) -> Result<DataResponse<M>, DataError> {
        self.as_serde_provider().load_payload(req)
    }
}
```

At the same time, remove the specialized types from FFI and use just BufferProvider over there.

However, when doing this, be careful about code size.  In theory, there shouldn't be a code size hit, but in practice, one needs to be careful about features in order for this to work.

**Comment by robertbastian** [comment]
This has been added and subsequently removed.
