### ISSUE TITLE
API and Features for Segmenter

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1379]
We should have a discussion about the API surface for Segmenter, as well as Cargo features to enable/disable the different parts of it.

I can think of at least 3 features we should have:

1. Enable UAX 14 code
2. Enable UAX 29 code
3. Enable LSTM code

Instead of features, we could instead think about just depending on DCE for this, and making sure that the API surface is amenable to that.

The APIs should also be ergonomic, well-documented, and easy to find in both Rust and FFI.

**Comment by sffc** [comment]
I think adding the data provider forces us to answer this question.

In ECMA-402, the new Intl.Segmenter is an immutable object, and it has a `.segment()` method that creates the iterator.  I think we should follow a similar model in ICU4X, not only to align with ECMA-402 but, more importantly, to handle the data lifetime better.

For example, I forsee call sites like this:

```rust
use icu_segmenter::LineBreakSegmenter;

// Data provider to load the rules from your choice of data source
let provider = icu_testdata::get_provider();

// Immutable object that pre-loads the data
let segmenter = LineBreakSegmenter::new(&provider);

// Mutable object that is cheap to create
let iterator = segmenter.segment("The quick brown fox jumps over the lazy dog");
```

**Comment by aethanyc** [comment]
As of #1652, all the segmenters support the data provider, and the callsites are similar to what's describe in previous comment. Examples in https://unicode-org.github.io/icu4x-docs/doc/icu_segmenter/index.html

**Comment by sffc** [comment]
The features are currently:

```
[features]
default = []
lstm = ["ndarray", "num-traits", "serde"]
serde = ["dep:serde", "zerovec/serde", "icu_codepointtrie/serde"]
datagen = ["serde", "databake", "zerovec/databake", "icu_codepointtrie/databake"]
lstm-grapheme = ["lstm", "unicode-segmentation"]
```

I think this is fine. DCE should take care of LineBreakSegmenter vs WordBreakSegmenter.

One possible enhancement would be to add a "dictionary" feature, but I believe that enabling "lstm" also disables the relevant dictionary keys. Note how the `try_new` signatures are different depending on the feature:

https://github.com/unicode-org/icu4x/blob/1602d46878fa471d1e79dfcf5af5fbc2134d0fcf/experimental/segmenter/src/line.rs#L107

I don't think there is any other particular action required on this ticket. @aethanyc?

**Comment by aethanyc** [comment]
> One possible enhancement would be to add a "dictionary" feature, but I believe that enabling "lstm" also disables the relevant dictionary keys.

Yes, for those languages having both dictionaries and lstm models, enabling "lstm" feature disables relevant dictionaries, but note that we always want to load CJ dictionary with "lstm" enabled because there's no lstm model for CJ. See 

https://github.com/unicode-org/icu4x/blob/bebc548ce9f09a6b2639c39dcc40284acfc6cfc8/experimental/segmenter/src/word.rs#L35-L57

> I don't think there is any other particular action required on this ticket. @aethanyc?

Current public APIs and features look good to me. @makotokato do you have other changes you'd like to make to the API or features?

**Comment by aethanyc** [comment]
Close this issue assume that we are good with the current features and API.
