### ISSUE TITLE
ICU4X as an org so we can create teams

### ISSUE THREAD

**Issue by nciric** [unicode-org/icu4x#138]
We need various github teams under icu4x. One for reviews, one for pushing crates to crates.io.

One option is to ask unicode-org to create team every time we need one - is that time consuming? Who can do it?

**Comment by sffc** [comment]
I think we should create groups under unicode-org.  I don't think we need many of them.  The chairs of this subcommittee should all be owners of those groups so it's easy to add people.

**Comment by nciric** [comment]
As @kpozin pointed out in pull request #137 we already have team unicode-org/icu4x-sc. We have full control of creation of subteams, so we can have things like:

unicode-org/icu4x-sc/crates-publish

**Comment by Manishearth** [comment]
Wait, GitHub has subteams now? Interesting! We should make sure cargo supports that, but that's great!
