### ISSUE TITLE
Fix code size issues in DataError::new_resc_error

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1383]
The following function is used widely throughout ICU4X:

```rust
impl DataError {
    pub fn new_resc_error<T>(err: T) -> Self
    where
        T: core::fmt::Display,
    {
        Self::Resource(alloc::format!("{}", err))
    }
}
```

This function causes the `core::fmt::Display` impl to be pulled along for whatever error type it is called on, which carries significant code bloat.

The error itself is useful, so we should try to keep it.  For example, it is how I/O errors are surfaced.

Options:

1. Add a feature to the crate called `"small"` that replaces this function with a no-op
    - Pro: Keeps current behavior and bubbles all information up to the user in an error case
    - Con: I want to avoid poking holes in ICU4X to solve code size issues
2. Remove the `String` from `DataResource::Error`
    - Pro: Small code
    - Con: Does not retain useful information from errors, making debugging harder
3. Add more variants to `DataError` to cover more use cases, and migrate all clients to use the new variants
    - Pro: Small code
    - Pro: More standardized / type safe than trying to make sense of the String form of the error
    - Con: Less flexible than a string
4. Other?

Looking for feedback/advice from:

- [x] @Manishearth 
- (anyone else who can make a suggestion)

**Comment by Manishearth** [comment]
In general I like (3) and I think we should be moving towards it as much as possible, perhaps making that enum `#[non_exhaustive]` so that we can still add variants post-1.0.

_Ideally_ the type is such that it never even needs to allocate!

I think it might be fine to mix in a little bit of (1), where we still have a Custom variant that is strongly discouraged that can be disabled via a feature.

**Comment by sffc** [comment]
> Ideally the type is such that it never even needs to allocate!

#1396

**Comment by sffc** [comment]
I was thinking about a DataError that looks something like

```rust
#[derive(Copy, Clone)]
pub enum DataErrorKind {
    MissingResourceKey,
    Deserialization,
    // ...
}

#[derive(Copy, Clone)]
pub enum DataErrorMetadata {
    None,
    Type(core::any::TypeId),
    StaticStr(&'static str),
    ArrayStr(arrayvec::ArrayString<48>),
}

#[derive(Copy, Clone)]
pub struct DataError {
    kind: DataErrorKind,
    metadata: DataErrorMetadata,
}
```

But perhaps we could do without the `arrayvec::ArrayString` and suggest that those users invoke `log::warn!()` instead, as @Manishearth suggested in #1396.

**Comment by sffc** [comment]
Discussion:

- @zbraniecki - I'm very much in favor of `log::warn!()` rather than `ArrayString`.
- @nciric - These errors are usually one-off when building the package.

**Comment by sffc** [comment]
For comparison, here is std::io::Error:

```rust
pub struct Error {
    repr: Repr,
}

enum Repr {
    Os(i32),
    Simple(ErrorKind),
    // &str is a fat pointer, but &&str is a thin pointer.
    SimpleMessage(ErrorKind, &'static &'static str),
    Custom(Box<Custom>),
}

#[derive(Debug)]
struct Custom {
    kind: ErrorKind,
    error: Box<dyn error::Error + Send + Sync>,
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[stable(feature = "rust1", since = "1.0.0")]
#[allow(deprecated)]
#[non_exhaustive]
pub enum ErrorKind {
    /// An entity was not found, often a file.
    #[stable(feature = "rust1", since = "1.0.0")]
    NotFound,
    /// The operation lacked the necessary privileges to complete.
    #[stable(feature = "rust1", since = "1.0.0")]
    PermissionDenied,
    /// The connection was refused by the remote server.
    #[stable(feature = "rust1", since = "1.0.0")]
    ConnectionRefused,
// ...
}
```

I think we want something a bit similar to `Custom` + `ErrorKind`, but it should be `Copy`.

**Comment by sffc** [comment]
@Manishearth For the static string, should we do `&&str` like std::io::Error, or should we do `&str` ?

**Comment by Manishearth** [comment]
A fat pointer should be fine: if this isn't going to be allocated it doesn't matter that much and also half the time the Ok branch of the result will need just as much space so optimizing the error isn't really necessary.

We could double ref if we really want to but I don't see much of a benefit
