### ISSUE TITLE
Convert Japanese calendar data to zero-copy

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1393]
Main issue: #856

Followup from https://github.com/unicode-org/icu4x/issues/1116

Currently `JapaneseErasV1` uses `LiteMap`, it should use `ZeroMap`.

Because it uses `TinyStr`, doing so will worsen the experience of using `zerovec` until https://github.com/zbraniecki/tinystr/issues/56 is landed; after which we should be able to do this pretty easily.

**Comment by robertbastian** [comment]
Had a quick stab at this, a straight up replacement from `LiteMap` to `ZeroMap` is not possible, because we actually use the `LiteMap` as a binary-searchable slice to get the closest era to a given year. `ZeroMap` doesn't support this, for `ZeroVec` there's #1589

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/1605
