### ISSUE TITLE
Should we consider marking our Error types as Copy?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1396]
Currently, our Error types have basically no restrictions, except that by convention they all implement `Display` as well as `std::error::Error` when available.

However, here are two very concrete reasons why we should consider restricting our `Error` types to be `Copy`:

1. Based on code size analysis, a fairly large fraction of code size is spent in `Drop` impls in destructors.  I expect that much of this code is the result of implicit `impl Drop for Error`.  Using `Copy` means that we get rid of the implicit `impl Drop`.
2. If we had flat types with no allocation (`Copy + 'static`), we could expose errors more directly over FFI, which is currently an unsolved problem.

Even if we don't apply this restriction to *all* errors, we could at least make it a recommendation to do when possible.

Thoughts?

- [x] @Manishearth 
- [x] @zbraniecki

**Comment by Manishearth** [comment]
I feel like my answer here is similar to #1383: We should try hard to achieve this and treat this as the "default" option but a couple exceptions should be fine.


Note that exposing errors defined in other crates over FFI can only be done opaquely anyway; unless a conversion is introduced.

**Comment by sffc** [comment]
The main reason to allocate is when you want to attach metadata to an error, such as a filename. What do you think about using `Copy` but allowing a string of up to a certain fixed length, like 48 bytes or something like that?  We could use `heapless::String`, since we already transitively depend on `heapless`.  (pending https://github.com/japaric/heapless/issues/230)

**Comment by Manishearth** [comment]
That seems pretty good. I'd prefer to avoid strings as much as possible anyway though.

We can also perhaps use the `log` crate and `debug!()` metadata that's dropped on error conversion. The nice thing about `log` is that the actual logging system can be chosen by the caller. We may want to use a shim that makes it possible to disable completely in release builds though.

**Comment by zbraniecki** [comment]
I agree we should make `Error` `Copy`. Further, I think we should avoid using `String` at all in errors. Instead, we should provide a `Copy` struct and maybe a method that can produce a string from data.

**Comment by sffc** [comment]
@Manishearth If I do DataError first (#1383), would you be willing to take this ticket and drive the migration of the remaining Error types in Q1?  This would also be something we could delegate to our 20%ers.

**Comment by Manishearth** [comment]
Yeah that sounds good!

**Comment by dvc94ch** [comment]
I don't think backtraces are copy. The rust ecosystem seems to have forgot the nightly feature which hasn't landed yet, but not having backtraces is extremely annoying, especially when debugging someone elses code.

**Comment by Manishearth** [comment]
This doesn't match my experiences around backtraces: They tend to be useful in specific kinds of code, but typically I find that the're very hit or miss when dealing with third party libraries. They work out better when used in application code.

The use of `log!()` at error sources in debug builds will help with this. The useful part of ICU4X's backtrace stack is going to be quite shallow anyway given that most of the library is broad, not deep, so logs should be fine.

**Comment by dvc94ch** [comment]
Logging the errors at the source location seems useful and like it would reduce the need for backtraces. However most of the time a file not found error gets logged in main() leaving you completely clueless as to what file wasn't found. really don't like the pervasive use of thiserror, much prefer using anyhow for fatal errors and enums/options for errors that are expected to be handled by the consumer

**Comment by Manishearth** [comment]
> However most of the time a file not found error gets logged in main() leaving you completely clueless as to what file wasn't found

This won't happen here; because we're logging the full error at the source site.

Complex error handling libraries in my experience make more sense at the application layer: ICU4X is intended to be low level and any cost on error handling needs to be justified strongly. We are also avoiding fatal errors; we're using enums a lot.

**Comment by sffc** [comment]
I think backtraces are a separate issue. We already don't have them, except in the places we use Eyre (tooling). Adding log statements is an overall improvement, actually, on tracing where an error originated in code.
