### ISSUE TITLE
Check that all options bags are taken by value

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1415]
Follow-up to discussion in #1077 to verify that we take arguments by value where appropriate and by reference where appropriate, with a focus on options bags.

**Comment by sffc** [comment]
I scope-creeped this to look at all functions that take by value or reference.

There are a number of places where we take Copy types by reference, especially by self reference:

- `try_add` and `try_sub` and `number` on Copy types such as `IsoHour`, `NanoSecond`, etc: should it take `self` or `&self`? Currently it takes `&self`
- `AnyCalendarKind::as_bcp47_*`: it takes a `&self` but should it take `self` since it is Copy?
- `CodePointInversionListBuilder::*_range_*`: it takes `&impl RangeBounds` but should it take `impl RangeBounds`?
- Also [icu](https://unicode-org.github.io/icu4x-docs/doc/icu/index.html)::[collections](https://unicode-org.github.io/icu4x-docs/doc/icu/collections/index.html)::[codepointinvlist](https://unicode-org.github.io/icu4x-docs/doc/icu/collections/codepointinvlist/index.html)::[deconstruct_range](https://unicode-org.github.io/icu4x-docs/doc/icu/collections/codepointinvlist/fn.deconstruct_range.html#)
- The icu_locid Copy subtags have `as_str`, `strict_cmp`, and `normalizing_eq`; should they take `self`?
- [icu](https://unicode-org.github.io/icu4x-docs/doc/icu/index.html)::[properties](https://unicode-org.github.io/icu4x-docs/doc/icu/properties/index.html)::[maps](https://unicode-org.github.io/icu4x-docs/doc/icu/properties/maps/index.html)::[CodePointMapDataBorrowed](https://unicode-org.github.io/icu4x-docs/doc/icu/properties/maps/struct.CodePointMapDataBorrowed.html#) and similar classes are Copy; should their methods take `self`?
- GmtOffset functions
- DataKey, DataKeyPath, DataKeyHash, and DataKeyMetadata functions

Thoughts on the above? @Manishearth

**Comment by Manishearth** [comment]
I would default all of those to `self`, except the ones below

> `CodePointInversionListBuilder::*_range_*`: it takes `&impl RangeBounds` but should it take `impl RangeBounds`?

nope, RangeBounds doesn't require Copy and the main Range types aren't Copy



> The icu_locid Copy subtags have `as_str`, `strict_cmp`, and `normalizing_eq`; should they take `self`?

No strong opinion here, really, probably prefer `self` as a general style rule

**Comment by sffc** [comment]
I'm making a PR for this issue and opening #2637 for utils crates.

**Comment by sffc** [comment]
I think the subtag `as_str` functions need to be `&self` because they borrow from themselves to make a string (i.e. TinyAsciiStr::as_str). I'm putting the rest into a PR.
