### ISSUE TITLE
Migrate LSTM segmenter to zero-copy

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1426]
We currently serialize and deserialize types from the `ndarray` crate.  Those are useful at runtime, but they can't be deserialized zero-copy.  We need to think hard about what are the best types to use and what algorithm to use with them.

**Comment by sffc** [comment]
The decision here is very important because it involves the runtime performance of the LSTM segmenter.  We already know that the LSTM is not very fast.  Zero-copy will make it faster, but I also fear that it may force us to write our own matrix multiplication algorithms, which could be slower than the optimized ones present in `ndarray`.

Any changes should be based on benchmarks.

**Comment by sffc** [comment]
Discussion with @Manishearth, @sffc, @iainireland, @robertbastian, @aethanyc:

Here are some options we considered:

1. Store as f16 array and always allocate/copy into f32
2. Store f32 slices in a side table in the blob provider (without serde for the side table)
3. Serialize f32 arrays by serializing a u8 array with extra space for alignment slop; stick an identifiable hash at the front; do a second pass at serialization to fix up the array with the right data. And during deserialization, require the buffer to be aligned, and if not, copy the data (or return an error?)
4. Store the data multiple times at each alignment
5. Store a `ZeroVec<f32>`, and allocate if the data does not happen to be aligned

We're leaning toward treating LSTM as an odd case where we are operating outside the explicit design parameters of ZeroVec: we have floats, which are not stable across processors, and we need alignment. Therefore, we can leverage ZeroVec for optimal storage, and allocate into a system-dependent `f32` upon creation of the LSTM.

More specifically: we make an enum that is either `ZeroVec<f16>` (serde) or `&[32]` (crabbake). In the serde case, we have a utility function that converts `&ZeroSlice<f16>` to `Vec<f32>`, and then feed that into the CowArray constructor of ndarray. Note that we could store `ZeroVec<u16>` instead of `ZeroVec<f16>`.

**Comment by sffc** [comment]
I want to elaborate on option 2 and how it could be implemented.

Upon loading the buffer: The BlobDataProvider constructor should be changed to require a buffer aligned to 4 bytes (or 8 bytes if we choose). The first word of the buffer indicates how many words of aligned data follow; it gets referenced as a `&[u32]`. If on a BE platform, we could perform an in-place byte swap at this point. All data that trails the aligned data at the front of the buffer are passed into Serde.

Upon a resource request: Certain keys, perhaps `segmenter/lstm_raw_tables@1`, are special keys that return aligned data. **They cannot contain any structured data:** the data struct for these keys is always `Cow<[T]>` where `T` is `u16`, `u32`, or perhaps `u64`. When such a key is requested, we look up the start and end offsets in the aligned side table, and return it as a `Cow::Borrowed`.

We'd need to think about how to work this into the data provider trait system. We have `BufferProvider` but that doesn't know how to talk about aligned data.

To be clear, I think this is a moot point, because I would like to store `f16` for the reduced data size anyway, and we need to allocate to get the `f32` vectors. I am writing this down for posterity.

**Comment by sapriyag** [comment]
We're missing size label for this issue.

**Comment by sffc** [comment]
@younies Assigning this to you; it will be fixed when we migrate to `i8`.
