### ISSUE TITLE
Migrate LSTM segmenter to no_std

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1427]
In #1425, I temporarily disabled the LSTM because it didn't yet support no_std.  We should make it no_std and re-enable the LSTM in the main crate.

**Comment by aethanyc** [comment]
I'm not familiar with changing a crate to `no_std`, but I guess we need to:

1. Add`#![cfg_attr(not(any(test, feature = "std")), no_std)]` to segmenter_lstm's `lib.rs` like [this line](https://github.com/unicode-org/icu4x/blob/9e7e21843237dade01c42947fa3e4166a911fcb1/experimental/segmenter/src/lib.rs#L86) in segmenter's `lib.rs`.
2. Replace `std` features and external crates that don't support `no_std` with alternatives.
3. Change [this line](https://github.com/unicode-org/icu4x/blob/9e7e21843237dade01c42947fa3e4166a911fcb1/experimental/segmenter/Cargo.toml#L61) in segmenter's `Cargo.toml` to `default = ["lstm"]`.

**Comment by sffc** [comment]
That sounds correct.  The main thing I'm uncertain about is (2); LSTM has a number of dependencies and I don't know if they are all no_std.  It looks like `ndarray` is no_std, but I don't know what features that disables.  For example, if it makes the algorithm slower if it can't use system GPU, we should think about what to do.  At least, if the std feature actually does something useful in `ndarray`, we should add an `std` feature to both segmenter and segmenter_lstm.

**Comment by makotokato** [comment]
LSTM segmenter uses `ndarray::s!` that is `std`. https://github.com/rust-ndarray/ndarray/pull/1154
