### ISSUE TITLE
Rename ZeroVec::from_slice to ZeroVec::from_slice_or_alloc

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1431]
We had a discussion on #1181 that centered around `clone_from_slice`, which is now `alloc_from_slice`.  However, I think we should rename `from_slice` to more clearly state what it is doing under the hood.

Here's why I think we should do this:

1. The word "slice" is being overloaded.  It could mean a slice of T, a slice of T::ULE, or a ZeroSlice.
2. The "default" slice type should *not* be `&[T]`.  It should be ZeroSlice.
3. We should not be encouraging people to use this method.  It is mostly convenient when mutating or when creating a ZeroVec at runtime from data from another source.

This will make the trio of methods:

- `alloc_from_slice` (always available)
- `try_from_slice` (available for EqULE)
- `from_slice_or_alloc` (available for EqULE)

Needs approval from:

- [x] @Manishearth 
- [x] @echeran

**Comment by Manishearth** [comment]
works for me

**Comment by echeran** [comment]
Yep, looks good to me, too
