### ISSUE TITLE
ZeroMap and GIGO

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1433]
How much work we put in for deserialization has been a somewhat contentious topic (#1290).

In `ZeroMap2k` (#1432), I am checking all the most crucial invariants, such as array lengths.  However, my question is what extend we should be checking for the vectors being *sorted*.

Obviously, checking that the elements are in sorted order is, in the common case, a no-op, which is part of @iainireland's concerns.

However, the more crucial question is: *do we actually need to enforce the sort order?*

Rust's `binary_search` has GIGO-like behavior: if presented with an unsorted vector, it will return a deterministic, but often incorrect, element from somewhere in the list.  Therefore, by not enforcing sort order, we're not "really" causing any safety problems, according to my three-point safety benchmark in #1290 (memory-safe, panic-safe, and termination).

Obviously, failing to enforce the sort order could cause queries into the ZeroMap to return the wrong result, and this property could be manipulated by an attacker.  However, if the attacker already has enough access to the data source to give us syntactically-correct-but-semantically-incorrect data, then they can just as easily manipulate the data to have the same behavior even if we enforce the sort order.

If there are situations where the sort order causes us to violate a three-point safety problem, then we should of course continue checking the order.  My question is limited to those cases in which the sorting requirement is only to prop up `binary_search`.

Do you think we should drop the sorting requirement in ZeroMap serde::Deserialize?

- [x] @Manishearth 
- [x] @iainireland

**Comment by Manishearth** [comment]
> However, the more crucial question is: _do we actually need to enforce the sort order?_

I'm totally fine with "no" here.

An important thing worth noting on the three-point scale is that I _believe_ that in the current implementation the key and value arrays being a different _length_ can cause panics. We probably should check this in the deserializer and document it somewhere.

Perhaps we should debug assert sortedness?

**Comment by sffc** [comment]
> An important thing worth noting on the three-point scale is that I _believe_ that in the current implementation the key and value arrays being a different _length_ can cause panics. We probably should check this in the deserializer and document it somewhere.

Yes, we absolutely should check for invariants that cause 3-point safety problems.  My question is strictly scoped to whether we should check for sortedness when the *only* reason is binary search.

> Perhaps we should debug assert sortedness?

SGTM

**Comment by iainireland** [comment]
My understanding is that we enforce the sort order as we construct a ZeroMap, and it's not possible to create an out-of-order ZeroMap without deserialization shenanigans. Assuming that's true, then I agree that it's unnecessary to check for sortedness when deserializing. Adding a debug assert seems sufficient.
