### ISSUE TITLE
writeable_to_string --> write_to_string

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1453]
We should make all three of the Writeable functions have the same naming scheme.

- `write_to` for the sink
- `write_len` for the length
- `write_to_string` for the string

Also consider `write_to_str` since we return a `Cow<str>` after #1452.

Needs approval from:

- [x] @robertbastian

**Comment by robertbastian** [comment]
I'd prefer
* `write_to`
* `size_hint` (compare `Iterator::size_hint`) or `len_hint` (as we return a different type than `Iterator`)
* `to_str` or `as_str`, as there might not be any writing going on

**Comment by sffc** [comment]
We used the prefixes to try to avoid conflicts with std functions, because if there's a name conflict, you need to use fully qualified syntax, which is annoying. So something as generic as "as_str" probably won't work.

**Comment by robertbastian** [comment]
I prefer `writeable_to_str` over `write_to_str` then.

**Comment by sffc** [comment]
Also note `to_string_lossy` which returns a `Cow<str>`

**Comment by sffc** [comment]
Decision: `write_to_str`.
