### ISSUE TITLE
Make calendars work better with static data slicing

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1461]
When I run the new `icu4x-key-extract` tool on `work_log`, I get

```
datetime/lengths@1
datetime/skeletons@1
datetime/symbols@1
plurals/ordinal@1
```

This is correct (the plurals are presumably pulled in for counting weeks).  However, there is no indication about which calendar system to use, even though a calendar system is explicitly specified:

```rust
let dtf = DateTimeFormat::<Gregorian>::try_new(locale, &provider, &options.into())
```

This is "by-design", of course: I expect the general case to be an `AnyCalendar`.  However, for cases where one particular calendar is being used, ideally we can get that info from the static data slicing tool.

Here's one idea.  Once data deduplication is implemented (#838), we can have multiple resource paths pointing at the same data, with no impact to data size (except for the index array).  When a calendar-specific DTF is created, it loads the calendar-specific key, and when an AnyCalendar DTF is created, it loads the all-calendar key.

This is not too different from the approach we're taking in Unicode Properties.  We have both pre-computed sets as well as all-inclusive CPTs, and it's expected that only one of those keys will be shipped.

Thoughts?  Any other ways to solve this problem?

- [x] @Manishearth 
- [x] @zbraniecki

**Comment by Manishearth** [comment]
I think your solution is fine.

Another way to potentially do it is that when, say, the Buddhist calendar is loaded, we also "in secret" load a `ICUCAL[[buddhist     ]]` string into the date time formatter object. The relevant static string is laundered through an `#[inline(never)]` function so that ICU4X doesn't simply optimize it away. Then data slicing can just slice the combination of keys and calendars used. If we really care about cases where, say, the Gregorian calendar only needs lengths and the Buddhist calendar only needs symbols we can include both in the ICUCAL symbol though that would get a bit more complicated.

**Comment by sffc** [comment]
I guess another way to do this, once #1148 is done, is to just have separate data keys for each calendar, but have them share the same data struct, so we carry only one `Deserialize` impl and all code is shared.  When you parameterize your DTF, you get only the one key, and when you use an AnyCalendar DTF, then we have a `match` that results in all of the resource keys being compiled into code.

**Comment by zbraniecki** [comment]
What's the downside of the separate data keys for each calendar?

**Comment by sffc** [comment]
> What's the downside of the separate data keys for each calendar?

Data keys cannot be constructed dynamically; by using separate data keys for each calendar, adding new calendar data requires touching the ICU4X library code.  With variants of the same key, the calendar can be chosen in userland code and matched in the data file; ICU4X doesn't need to know about the identity of the calendar.

However, I'm now thinking that it is acceptable, and even advantageous, for us to control the set of supported calendars in code.  In particular, it does not make sense to have data-driven formatting without also having data-driven arithmetic, but since every calendar has a unique arithmetic algorithm, we will always need to modify the code anyway when adding a new calendar.

If adding calendar systems is always code-driven and not data-driven, then I think we can and should use separate keys instead of variants.

**Comment by zbraniecki** [comment]
I support separate keys.

**Comment by sffc** [comment]
Documenting how to solve this:

1. Data paths change from `datetime/datesymbols@1/en-u-ca-buddhist` to `datetime/buddhist/datesymbols@1/en` or equivalently `datetime/datesymbols/buddhist@1/en`
2. Japanese and Japanext need to be separate calendar types
3. The CldrCalendar trait gets a method to return the correct data keys
4. Add a standalone method to map from AnyCalendarKind to the correct data key
