### ISSUE TITLE
Write common framework for calendar arithmetic

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1470]
Part of https://github.com/unicode-org/icu4x/issues/534

Currently we reimplement the `offset_date()` and `until()` `Calendar` functions for each calendar, with Gregorian proxying to ISO. Most calendars are quite similar here:

 - Gregorian and Julian just differ by _when_ the leap years occur
 - Indian National differs by the exact month sizing
 - Coptic/Ethiopian occasionally have an extra epagomenal month in the year.

All of this can be analyzed as calendars having different month sizing.

It would be ideal if this arithmetic did not need to be reimplemented each time.

Furthermore, dealing with the ISODay/etc types is kind of annoying; it's nice for the types to be typesafe for the user but there's plenty of conversion arithmetic/etc going on.

First, I propose we have a single internal type for all solar dates. It can later be expanded to handle lunisolar and lunar calendars.

```rust
struct ArithmeticDate<C: CalendarArithmetic> {
    year: i32,
    month: u8,
    day: u8,
}

struct ISODateInner(ArithmeticDate<ISO>);
struct JulianDateInner(ArithmeticDate<Julian>);
// etc
```

We also have an internal trait `CalendarArithmetic` that works the following way:

```rust
trait CalendarArithmetic {
   fn month_lengths(year: i32) -> [u8; 12]; // later, &[u8]
}
```

Finally, `ArithmeticDate` has implementations of `offset_date()`, `until()`, `days_in_year()`, `days_in_month()` that rely on the month length information to perform calculations. Calendars using it (currently: ISO and Julian, since Buddhist and Gregorian just use ISO) can just proxy to it.

New calendars that fit this model will be pretty easy to implement: you still have to implement the conversion function to/from ISO (if we want we can add `foo_from_fixed()`/etc to `CalendarArithmetic` to consolidate further), but after that you can just implement `month_lengths()` and do a simple wrapper.

This will make it really easy to implement the Indian national calendar. Coptic and Ethiopian would need an extra short month. Islamic will have a more complex implementation of `month_lengths()` but it'll be much the same.

Hebrew _potentially_ could be handled by allowing for one of the `month_lengths()` to be zero, there are just a bunch of tricky bits in writing `offset()` and `until()` functions that can work with that.

**Comment by pandusonu2** [comment]
Would it also make sense to have a "fixed" inside the ArithmeticDate struct?

**Comment by Manishearth** [comment]
@pandusonu2 probably not since it's only used for conversions and this is for storage

**Comment by justingrant** [comment]
> Coptic/Ethiopian occasionally have an extra epagomenal month in the year.

These calendars always have an intercalary month in every year. Leap years have a 6-day intercalary month while non-leap years have a 5-day intercalary month. But it's always there.

> ```rust
>    fn month_lengths(year: i32) -> [u8; 12];
> ```

A 12-element array won't work for Chinese which is sometimes 12 and sometimes 13 months.  And unlike Hebrew,  the leap month can be anywhere in the year except it can't be the first or the last month.. 
 
> Hebrew _potentially_ could be handled by allowing for one of the `month_lengths()` to be zero

This would break the size-12-array assumption too.

> All of this can be analyzed as calendars having different month sizing, especially if we treat the coptic/ethiopian epagomenal month as just 6 extra days on December (and reify it when formatting)¹.

As discussed in https://github.com/tc39/proposal-temporal/issues/1994#issuecomment-1006296409, I'm skeptical about treating the intercalary month as part of the 12th normal month for arithmetic purposes.

> there are just a bunch of tricky bits in writing offset() and until() functions that can work with that.

One "tricky bit" to consider is how these methods will be optimized. When adding 12000 months months to a Chinese date, is it OK to call `month_lengths()` a thousand times?  What about `until()` between dates a million years apart with largestUnit of month?

To get O(1) `offset()` and `until()`, I suspect that in addition to `month_lengths()` I think you'd also need an O(1) `offset_months()` implemented for each calendar. The latter would be straightforward for lunisolar calendars (using the cyclical pattern of leap months) and trivial for solar/lunar.  But I don't know how you can get to O(1) without it.

> First, I propose we have a single internal type for all solar dates. It can later be expanded to handle lunisolar and lunar calendars.

Another alternative could be to start from the most complicated ICU calendar: Chinese.  If a common implementation works for Chinese, then it should work for every other current ICU calendar.

Not sure if the design needs to think about the Hindu calendar that merges months, but that's not a current ICU calendar so it may not matter.

> It would be ideal if this arithmetic did not need to be reimplemented each time.

👍 If it's helpful, here's the Temporal polyfill equivalent of `offset()` and `until()` that works for all calendars. This could be made a lot more efficient!  https://github.com/js-temporal/temporal-polyfill/blob/1e7910d4a170e1e7b9729de133125d7aab18fe97/lib/calendar.ts#L1117-L1191

**Comment by Manishearth** [comment]
> A 12-element array won't work for Chinese which is sometimes 12 and sometimes 13 months. And unlike Hebrew, the leap month can be anywhere in the year except it can't be the first or the last month..

Yes, this is an internal private API, I'm deliberately simplifying the API a bit so that @pandusonu2 does not have to design for all cases just yet: just the cases we already have implemented and plan to implement in the near future.

I think you're getting a bit ahead of the plan here, as I mention later in the issue we can expand the array so that Hebrew/etc are handled.


Chinese is a tricky case for another reason since the exact position of the leap month varies. It can be handled, but



> One "tricky bit" to consider is how these methods will be optimized. When adding 12000 months months to a Chinese date, is it OK to call `month_lengths()` a thousand times? What about `until()` between dates a million years apart with largestUnit of month?

Yeah that's part of my concern

**Comment by justingrant** [comment]
> I would rather not discuss this here just yet. this issue is more about a refactoring for the existing code that handles a couple of the upcoming cases, not the end-all framework. Let's not expand the scope right now.

SGTM

> Yeah that's a concern I have. I suspect further optimizations can be done by exposing an `add_months()` function to ArithmeticDate, and large `add_days()` can be done via conversion to/from fixed.

Yep, agree. I suspect that the minimal additional per-calendar logic would be something like: (guessing at Rust syntax for returning a struct)

```
add_months(year: i32, month: i8, months: i32, month_must_exist: bool) -> { year: i32, month: i8, days_in_month: i8 }
// OR
add_months(year: i32, date: ArithmeticDate<T>, month_must_exist: bool) -> ArithmeticDate<T>
```
