### ISSUE TITLE
Rename Yoke::project functions to ::map_project

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1486]
The word "project" has been a source of confusion, both because it is a homograph with another word common in programming (the noun "project") and because the verb "project" is not particularly common.

The word "map" roughly corresponds to the operation that the function is performing, and it is more common in Rust.  Should we consider "map"?

Another option, which I have adopted in DataPayload, is "map_project".

Is there some other good option here?

- [x] @echeran 
- [x] @zbraniecki 
- [x] @Manishearth

**Comment by Manishearth** [comment]
I like `map_project`. It's not _just_ a map since it's restricted into "projecting" on to a subpart, but `map_project()` seems nice to me.

**Comment by echeran** [comment]
Another option for a synonym to project-as-a-verb is "select". IIUC on our usage of project, [Clojure's select-keys](https://clojuredocs.org/clojure.core/select-keys) is similar -- takes a map, provides a map with a subset of keys --, and it is probably named that way from SQL's select, which obviously does the same for a set of database columns.

**Comment by sffc** [comment]
Let's also discuss the naming between the moving version and the borrowing version. We currently use the names `map_project` and `map_project_cloned`. I think the `_cloned` is misleading because we aren't actually cloning anything.

Should we call it `map_project_borrowed` instead? Something else?

- [ ] @Manishearth

**Comment by Manishearth** [comment]
FWIW we're cloning the cart, but I think `_borrowed` is fine especially since CloneableCart is guaranteed to be a cheap clone.

**Comment by zbraniecki** [comment]
In APIs that handle ownership/borrowing I think of the word "project" as a social contract that communicates that no allocation is necessary - almost like casting - with some shape change. Kind of like SQL's "view".

Map indicates to me that the some change happens between input and output. So `map_project` would indicate that the inputs will be different than outputs, and that no allocation will happen.
For example, maybe the `map` part will take IDs of items, and return references to those items with maybe some shape change but no allocation.

If that is roughly what you're doing, then I think `map_project` is clear.

**Comment by Manishearth** [comment]
Yeah, that's roughly what projectin is doing

**Comment by sffc** [comment]
@yzhang1994 is interested in this.
