### ISSUE TITLE
Remove the unicode_width crate dependency from segmenter

### ISSUE THREAD

**Issue by aethanyc** [unicode-org/icu4x#1505]
Currently, line breaker uses `unicode_width` crate to query the char width to implement the following part of the line break strictness in the [CSS Text spec](https://drafts.csswg.org/css-text-3/#line-break-property).

- The following breaks are allowed for loose if the writing system is Chinese or Japanese and are otherwise forbidden:
  - breaks before suffixes:
  Characters with the Unicode line breaking class PO [UAX14] and the East Asian Width property [UAX11] Ambiguous, Fullwidth, or Wide.
  - breaks after prefixes:
  Characters with the Unicode line breaking class PR [UAX14] and the East Asian Width property [UAX11] Ambiguous, Fullwidth, or Wide. 

Here is the relevant code in line breaker:
https://github.com/unicode-org/icu4x/blob/05235a6119b6ecd5b3aae2d55e328879950376c6/experimental/segmenter/src/line_breaker.rs#L296-L309

ICU4X now support [East Asian Width property](https://unicode-org.github.io/icu4x-docs/doc/icu_properties/maps/fn.get_east_asian_width.html), so we should be able to remove the dependency.

**Comment by aethanyc** [comment]
We can probably fix this as part of #758 or #1372. When we rework on generating the line break property tables using Rust, we might consider add extra line breaking values such as:
- `PO_EAW` denoting line break class `PO` and the East Asian Width property Ambiguous, Fullwidth, or Wide.
- `PR_EAW` denoting line break class `PR` and the East Asian Width property Ambiguous, Fullwidth, or Wide.

@makotokato does this sounds reasonable? We've use similar technique like `OP_EA` [here](https://github.com/unicode-org/icu4x/blob/05235a6119b6ecd5b3aae2d55e328879950376c6/experimental/segmenter/tools/generate_properties.py#L97-L99).

**Comment by makotokato** [comment]
Yes, we can fix this by more rules for `PO_EAW` and `PR_EAW`. I will fix this soon.
