### ISSUE TITLE
Export key registry from icu_datagen

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1512]
We should consider making icu_datagen invokable as a library, instead of *only* as a command-line tool.  icu_datagen is unique in the sense that it is the only place in the code base that has access to all struct definitions for all data keys.

Benefits of doing this:

1. Enables tooling that uses a Postcard or JSON directory as a data source for conversion to other data serialization formats like CrabBake (see #1506)
2. Enables detection of hash conflicts globally for all ICU4X data keys

FYI, the probability of a hash collision [reaches 50% at about 75000 keys](https://octav.onl/hash-collision-2-64), assuming a perfect hash function.  So, fairly distant, but definitely high enough for us to worry about it.

CC @robertbastian @Manishearth

**Comment by sffc** [comment]
This is blocked by #1560 and #1561.

**Comment by Manishearth** [comment]
It would be _nicer_ to be able to use ResourceMarker here, but it's by no means necessary, the macro that constructs the registry will just need to be a little bit more involved.

**Comment by Manishearth** [comment]
Also, to give an idea of what the macro would look like, it would take something like

```rust
create_registry!(CldrRegistry, 
    JapaneseErasV1Marker::KEY => JapaneseErasV1Marker,
    DatePatternsV1Marker::KEY => DatePatternsV1Marker,
   ....
);
```

and turn it into

```
struct CldrRegistry;

impl KeyRegistry for CldrRegistry {
    fn apply_for_concrete_data<R>(&self, key: ResourceKey, callback: &mut impl ConcreteDataCallback) -> Result<R, DataError> {
         match k {
              JapaneseErasV1Marker::KEY => callback.callback::<JapaneseErasV1Marker>(),
              DatePatternsV1Marker::KEY => callback.callback::<DatePatternsV1Marker>(),
              ....
              _ => Err(MissingResourceKey)
         }
    }

}
```

And we might have a convenient KeyRegistry impl for tuples that chains multiple registries together.

**Comment by Manishearth** [comment]
I have a draft here https://github.com/unicode-org/icu4x/pull/1664

**Comment by sffc** [comment]
There are two traits that are interesting as part of the data exporter:

- `serde::Serialize`
- `crabbake::Bakeable`

The global registry should enable us to "traitify" an AnyProvider or BufferProvider into either of those two exportable traits.

So, essentially, my mental model of the global registry is something more along the lines of

```rust
trait Dynify<M: DataMarker> {
    fn dynify_buffer(key: ResourceKey, payload: BufferPayload) -> DataPayload<M>;
    fn dynify_any(key: ResourceKey, payload: AnyPayload) -> DataPayload<M>;
}
```

And then the source providers like CLDR and UProps would have

```rust
impl Dynify<SerializeMarker> for CldrJsonDataProvider
impl Dynify<BakeableMarker> for CldrJsonDataProvider
// ...
```

except that these impls would be generated as part of the pre-existing `impl_dyn_provider!()` macro, which is similar to your `create_registry!()` macro.

To support the #1661 use case, we could have another marker trait like `EmptyMarker` so that we don't need to allocate a trait object box. You would do your test as

```rust
measure_allocations(|| {
  let _: DataPayload<EmptyMarker> = everything_provider.dynify_buffer(key, buffer)?;
}); 
```

All that said, we should explore the idea of a callback function with a generic parameter. It's a different way of achieving this goal.

**Comment by Manishearth** [comment]
> except that these impls would be generated as part of the pre-existing `impl_dyn_provider!()` macro, which is similar to your `create_registry!()` macro.

I don't think this part is possible, fwiw, Rust doesn't let you piecewise build up a function based on possible generic return types.


You have to have a separate registry that has a list of keys and types; it cannot be done by individual macros. But this can be made a part of your model by implementing `Dynify` on separate registry types instead.

**Comment by Manishearth** [comment]
Here's an immensely illuminating drawing from a meeting between shane and I. I'm going to prototype this next.

![image](https://user-images.githubusercontent.com/1617736/156844141-d207887c-7ddc-404e-be7f-40dd24a4c794.png)

**Comment by Manishearth** [comment]
Got my attempt at https://github.com/unicode-org/icu4x/pull/1669

**Comment by Manishearth** [comment]
PR: https://github.com/unicode-org/icu4x/pull/1670

**Comment by robertbastian** [comment]
I was expecting something like @Manishearth's design. The registry itself should be kept simple and just be a way to iterate over keys with the correct marker types.

**Comment by Manishearth** [comment]
Ah, this built the registry but didn't export it, I see.
