### ISSUE TITLE
Re-consider uprops key structure given new ResourceKey

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1515]
Given #1511, we now support longer, multi-leveled resource keys.  We should reconsider the keys like `sc=Latn@1` and consider changing them to something like `sc/Latn@1`.

This issue also tracks whether we can remove or rename the `ResourceKey::get_last_component_no_version` function.

**Comment by markusicu** [comment]
I rather like `sc=Latn` in the key :-)
