### ISSUE TITLE
Revisit iter_components and improve handling of variant and locale

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1516]
We currently have `iter_components()` methods on ResourceKey and ResourceOptions.  However, these are only used for two purposes:

1. Directly, to construct a PathBuf, which is used by FsProvider
2. Indirectly, via the Writeable impl, which is used by BlobProvider

These functions cause potentially needless allocations, and they are not as easy to use as they should be.  Consider alternatives.

**Comment by robertbastian** [comment]
The Writeable impl doesn't use `iter_components()`.
