### ISSUE TITLE
Add clippy test for std dependencies

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#152]
Follow-up from https://github.com/unicode-org/icu4x/issues/77#issuecomment-635584927:

> We will investigate Clippy-based solutions to restrict our usage of std libraries. I suggested a Clippy test that takes a whitelist of allowed std dependencies and fails if you use one that isn't whitelisted. @Manishearth also said @fitzgen may have written tests that ensure WebAssembly compliance.

**Comment by sffc** [comment]
Thoughts, @Manishearth @fitzgen?

**Comment by Manishearth** [comment]
@fitzgen mentioned that such tools didn't exist yet

We can write clippy lints for this, someone will need to do that work

**Comment by sffc** [comment]
We are now `no_std` so this is obsolete.
