### ISSUE TITLE
Improve icu4x_key_extract

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#1533]
In #1480 we use `strings`, which might not be available on all systems.

**Comment by sffc** [comment]
It makes me uneasy to think that a pivotal part of the ICU4X data pipeline rests on piping `strings` to `sed`. I'd rather have a tool that takes an executable and returns the key list.

**Comment by sapriyag** [comment]
what should be the size of this issue? S-medium or S-large? Can you please add the size label to this issue.

**Comment by sffc** [comment]
For the purposes of 1.0, we want this to be well-documented and runnable by users without having to clone the icu4x project repo.
