### ISSUE TITLE
Add CI copyright headers check

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#155]
This task is split off from #84 to represent just the requirement of doing checks on copyright headers on source files.

We want every file to have headers indicating that indicates that the file is a part of ICU4X and references a link to the license.

Anything else I'm missing? @hsivonen

**Comment by hsivonen** [comment]
I created a [PR](https://github.com/unicode-org/icu4x/pull/252) that updates `CONTRIBUTING.md` to document the license header language that was discussed.

For CI, this means checking that `.rs` files start with

```
// This file is part of ICU4X. For terms of use, please see the file
// called LICENSE at the top level of the ICU4X source tree
// (online at: https://github.com/unicode-org/icu4x/blob/master/LICENSE ).
```

and `.toml` files start with

```
# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/master/LICENSE ).
```
