### ISSUE TITLE
Finalize PluralRules constructor structure

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1571]
In https://github.com/unicode-org/icu4x/pull/1554 I'm adding new functions `PluralRules::try_new_ordinal` and `try_new_cardinal`.  We should discuss this at more length outside the context of https://github.com/unicode-org/icu4x/pull/1554.

The reason we need to split the constructor into an ordinal version and a cardinal version is for data slicing to work over FFI.  Since FFI needs separate functions, I think we should probably do the same in Rust.  I don't think `PluralRulesType` leads to significantly better ergonomics, so we should err on the side of consistency.

I think we should consider:

1. Get rid of `PluralRules::try_new` and `PluralRulesType`
2. Rename `PluralRules::try_new_cardinal` to `PluralRules::try_new` (assuming that cardinal is the much more common use case)

Needs approval from:

- [x] @zbraniecki

**Comment by zbraniecki** [comment]
I'm ok with this change, but have some reservations about the broader direction - I would like to minimize situations where we design an API in line with best practices, then introduce a degraded API for FFi and then degrade the original APi to match it.

Can we do better?

**Comment by sffc** [comment]
> I'm ok with this change

Great!

> but have some reservations about the broader direction - I would like to minimize situations where we design an API in line with best practices, then introduce a degraded API for FFi and then degrade the original APi to match it.
> 
> Can we do better?

Here's how I see it.  Consistency between Rust and FFI is one of many factors that should influence the Rust API.  If the Rust API is really good for other reasons, then that can outweigh the consistency with FFI.  But, absent a compelling reason, we should try to make Rust and FFI consistent.  My position is that PluralRules is one such case.

**Comment by zbraniecki** [comment]
I think I disagree but the difference is not substantial..i do think this change degrades Rust API. It is an inferior design and if FFI compatibility was not a consideration I'd quite strongly be pushing for rejecting such change on that basis.

In result I'd say we are slightly regressing the design here to increase consistency with FFI. I'd like to avoid scenarios where we degrade substantially for the same goal because I do believe that Rust API will end up being the one most important and commonly used on the scale of 10-12 years and such degradation will stay with us the way ICU4C design decisions for compatibility with cases dominant 20 years ago but unimportant today affect every ICU4C user today   (i do realize how vague such claim is, it's just my intuition)

**Comment by sffc** [comment]
- @nordzilla - I see the modular constructors as the easiest path forward for a 1.0 release that works across Rust and FFI, and the all-in-one constructors as a nice-to-have.
- @zbraniecki - Modular works nicely for FFI, and options bag scales to all components. Builder doesn't make sense for all components. I'd like options bag as the default, and modular as an optimization when it's needed.
- @sffc - I think we agree in the sense that we use `try_new` when there is no data and modular constructors when there is data.
- @zbraniecki - The other concern I have about a builder pattern is whether there's a state of a builder that's not finalized? I've seen issues in ICU4C having a malformatted state of a builder that is nonsensical.
- @QnnOkabayashi - We can use the type system to check at compile time that everything has been set.
- @robertbastian - It's hard to do that over FFI unfortunately.
- @sffc - I want to clarify that modular constructors are useful for Rust clients as well as FFI clients for modularity purposes.
- @zbraniecki - I think we can ship 1.0 without modular constructors and add them later, because it's an additive feature.
- @robertbastian - I wouldn't say that FFI is a fully additive feature. We may need to make Rust changes to make FFI work or be ergonomic.
- @sffc - I hope this is a problem for future components. For the purposes of ICU4X 1.0, we should ship everything together.
- @Manishearth - Yeah, I think it's an interesting question of whether we could ship CurrencyFormat, for example, as a stable Rust version and add FFI later.

Conclusion: Ship 1.0 components with everything they need, and revisit the stability policy for construtors when we start adding new features post-1.0.

**Comment by sffc** [comment]
Action now: Make sure that PluralRules constructors are correct, and make sure they are also correct for other components. (DTF is tracked separately.)
