### ISSUE TITLE
Style: Pre-validation of options

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#158]
I was wondering what you all thought of a style such as the following with regard to option validation.

We often take strings or numbers that must meet certain requirements.  For example, a currency code must be 3 ASCII letters, and the significant digit count must be between 0 and 20 inclusive.

What do you think about a pattern where we pre-validate options by wrapping them in our own type before putting them into the options bag?

For example, we would have a CurrencyCode type, and the `currency` field of NumberFormatOptions would be a CurrencyCode instead of an `&'a str`.

```rust
use core::str::FromStr;

#[non_exhaustive]
#[derive(Debug, PartialEq)]
pub enum Error {
    CurrencyCodeError,
}

#[derive(Debug, PartialEq)]
pub struct CurrencyCode {
    code: String,
}

impl FromStr for CurrencyCode {
    type Err = Error;

    fn from_str(input: &str) -> Result<Self, Self::Err> {
        if input.len() != 3 || !input.is_ascii() {
            Err(Error::CurrencyCodeError)
        } else {
            Ok(CurrencyCode {
                code: input.to_ascii_uppercase(),
            })
        }
    }
}

pub fn main() {
    println!("{:?}", CurrencyCode::from_str("Usd"));
    println!("{:?}", CurrencyCode::from_str("argh!"));
}
```

**Comment by zbraniecki** [comment]
I like that.

This will later allow us to use some data to validate it against some lists, and/or add other currency specific operations on the `CurrencyCode` struct. Finally, it'll allow us to add macros like `let usd = currency!("USD");` :)

**Comment by zbraniecki** [comment]
Also, if it's ASCII, then maybe `TinyStr4`? :)

**Comment by sffc** [comment]
Agreed on the suggestion in the OP; Shane to make a PR to the style guide.
