### ISSUE TITLE
Correctly apply single field component bags

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#1581]
This behavior is _not_ specified in the UTS 35 skeleton matching algorithm as far as I can tell, but I have deduced it as follows:

1. If a skeleton has any extra fields, ignore it.
2. Either a) there is a skeleton match with a subset of the fields, or b) There is no skeleton match.

Given A:
1. Use the appendItems algorithm specified in UTS 35 to build up the full match.

Given B:
1. No skeleton matched, use the field directly as the pattern.
2. If there is a stand-alone version of the field, use the stand-alone version.

The work here is to fix the case where "B" is. A is required for append items support.

Here is the example of what ICU4C generates: https://github.com/gregtatum/spec-cpp/blob/5d577ed924a1f3aa019344011162e84fabf0a6f6/src/features/icu.cpp#L400-L517

**Comment by gregtatum** [comment]
In PR #1549 the result looks like:

```
    {
        "description": "Partial match for m -> hm -> h:m a",
        "input": {
            "value": "2002-12-31T08:05:07.000",
            "options": {
                "components": {
                    "minute": "numeric"
                }
            }
        },
        "output": {
            "values": {
                "en": "8:5 AM",
                "fr": "8:5 AM"
            }
        }
    },
```

It should be:

```
    {
        "description": "Single field with no CLDR data: m",
        "input": {
            "value": "2002-12-31T08:05:07.000",
            "options": {
                "components": {
                    "minute": "numeric"
                }
            }
        },
        "output": {
            "values": {
                "en": "5",
                "fr": "5"
            }
        }
    },
```

**Comment by pdogr** [comment]
Referring to the PR #1549, the issue seems to be that when two skeletons with the same distance are observed, only the first one is taken and the others are ignored. Like in this case as we observe "hm" skeleton before "ms" skeleton, only "hm" is taken into consideration. A possible fix for this might be to penalize extra skeleton fields based on their index. The lower the index, the more the penalty. This way skeletons having extras in the least significant fields would be preferred.

**Comment by gregtatum** [comment]
Without doing a deep a dive into the code again, I'm a bit skeptical that the skeleton matching algorithm needs the weighting tweaked. Although maybe I'm thinking about this wrong.

It seems like the flow should go like this:
* Do normal skeleton matching algorithm against all patterns in the provider.
* If there is not an exact match AND the field lengths requested is 1, then:
* Either:
  - Map the field to a standalone field if there is one available, and use that as the pattern.
  - If no standalone field exists, just use the single field as the pattern.

**Comment by pdogr** [comment]
My main concern is that in [get_best_available_format_pattern](https://github.com/unicode-org/icu4x/blob/main/components/datetime/src/skeleton/helpers.rs#L333), when we compare and update closest_distance with the current distance, we use `if distance < closest_distance`.

It means that if there are multiple skeletons with the same distance which is also the closest distance, how do we distinguish which skeleton to take? Sorry If I'm missing something here.

**Comment by gregtatum** [comment]
Basically all matching patterns should be discarded if the requested fields have length 1 and `closest_distance >= SKELETON_EXTRA_SYMBOL`

```
diff --git a/components/datetime/src/skeleton/helpers.rs b/components/datetime/src/skeleton/helpers.rs
index 35661a6b8..6127e3610 100644
--- a/components/datetime/src/skeleton/helpers.rs
+++ b/components/datetime/src/skeleton/helpers.rs
@@ -428,25 +428,36 @@ pub fn get_best_available_format_pattern<'data>(
 
     if closest_missing_fields == fields.len() {
         return BestSkeleton::NoMatch;
     }
 
     if closest_distance == NO_DISTANCE {
         return BestSkeleton::AllFieldsMatch(closest_format_pattern);
     }
 
     // Modify the resulting pattern to have fields of the same length.
     if prefer_matched_pattern {
         #[cfg(not(feature = "provider_transform_internals"))]
         panic!("This code branch should only be run when transforming provider code.");
     } else {
         closest_format_pattern.for_each_mut(|pattern| {
             adjust_pattern_field_lengths(fields, pattern);
         });
     }
 
     if closest_distance >= SKELETON_EXTRA_SYMBOL {
+        if fields.len() == 1 {
+            // There is only one requested field, and no matching pattern here, so the field
+            // should be used as the pattern, only adjusting if a stand-alone field is available.
+
+            // In bad pseudo-code:
+            if is_standalone_available(fields[0]) {
+                return map_standalone_field(fields[0]);
+            } else {
+                return BestSkeleton::AllFieldsMatch(fields.into());
+            }
+        }
         return BestSkeleton::MissingOrExtraFields(closest_format_pattern);
     }
 
     BestSkeleton::AllFieldsMatch(closest_format_pattern)
 }
```

**Comment by gregtatum** [comment]
Or maybe this should return a special `BestSkeleton::SingleField(Field)`. I would need to explore the code more, as it's been a little while since I've looked at the latest architecture outside of here.
