### ISSUE TITLE
Move zero-copy-from to a separate crate

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1590]
It's worth moving ZCF and zcf-derive to a separate crate, perhaps reexported from yoke. ZCF no longer depends on Yokeable (thanks Shane!) and while somewhat related it's not _too_ related IMO.

This way we can use it in zerovec unconditionally without relying on yoke. OTOH I'm not sure if it's worth doing since it would mean _two_ new crates.

Thoughts?

 - [x] @sffc
 - [x] @zbraniecki

**Comment by sffc** [comment]
Yes.  Just noticed this issue.
