### ISSUE TITLE
Make LineBreakPropertyTable and RuleBreakPropertyTable serializable

### ISSUE THREAD

**Issue by aethanyc** [unicode-org/icu4x#1638]
This issue blocks #1373.

Both [`LineBreakPropertyTable`](https://github.com/unicode-org/icu4x/blob/4c22ef7d6aa78aa8d1bc4f7193619ccd03f65976/experimental/segmenter/src/provider.rs#L35-L45) and [`RuleBreakPropertyTable`](https://github.com/unicode-org/icu4x/blob/4c22ef7d6aa78aa8d1bc4f7193619ccd03f65976/experimental/segmenter/src/provider.rs#L121-L131) are behind the `provider_serde` feature, but the feature is not defined in segmenter crate's `Cargo.toml`. Therefore, I made the following change to  Cargo.toml [here](https://github.com/unicode-org/icu4x/blob/4c22ef7d6aa78aa8d1bc4f7193619ccd03f65976/experimental/segmenter/Cargo.toml#L64).
```diff
 [features]
-default = []
+default = ["provider_serde"]
+provider_serde = []
```

Then I got the following build error.
```
error[E0277]: the trait bound `[[u8; 1024]; 128]: Serialize` is not satisfied
   --> experimental/segmenter/src/provider.rs:43:14
    |
43  |     Borrowed(&'data [[u8; 1024]; 128]),
    |              ^ the trait `Serialize` is not implemented for `[[u8; 1024]; 128]`
    |
    = help: the following implementations were found:
              <[T; 0] as Serialize>
              <[T; 10] as Serialize>
              <[T; 11] as Serialize>
              <[T; 12] as Serialize>
            and 30 others
    = note: required because of the requirements on the impl of `Serialize` for `&[[u8; 1024]; 128]`
```

It seems a large array (or a 2d array) is not serializable, at least it's not implemented in serde per [this serde issue](https://github.com/serde-rs/serde/issues/573#issuecomment-251872546). 

The 2d array is a serialized form of this [`properties_map`](https://github.com/unicode-org/icu4x/blob/4c22ef7d6aa78aa8d1bc4f7193619ccd03f65976/experimental/segmenter/build.rs#L248-L249) array in `build.rs`, representing a mapping from codepoint to a break state. I feel this is similar to an enumerate Unicode property. For example, each slot in`LineBreakPropertyTable` stores a line breaking state, which is synthesized from the `Line_Break` property plus other conditions from the line breaking rule. (@makotokato please correct me if I misunderstand it.)

So we can either:
1. Continue to use 2d array, and make them serializable.
2. Store the codepoint -> break state mapping in a CodePointTrie. @echeran Is this possible in ICU4X? This sounds like I'm asking for a CodePointTrie builder.

cc @sffc

**Comment by aethanyc** [comment]
After reading [this VarZeroVec example](https://unicode-org.github.io/icu4x-docs/doc/zerovec/enum.VarZeroVec.html#example), I think we can use`VarZeroVec<'data, ZeroSlice<u8>>` instead of a 2d array to make `RuleBreakPropertyTable` serializable.

**Comment by sffc** [comment]
The easiest solution that should avoids performance penalties is to use a flat `ZeroVec<u8>` and treat it as a matrix in row major order.

VarZeeoVec is not the right answer because it is designed for variable width data, but our data is fixed width.

Can we also solve this at the same time we solve the data deduplication?

**Comment by aethanyc** [comment]
Thanks for the suggestion!

> Can we also solve this at the same time we solve the data deduplication?

I've made [RuleBreakPropertyTable](https://github.com/unicode-org/icu4x/blob/4c22ef7d6aa78aa8d1bc4f7193619ccd03f65976/experimental/segmenter/src/provider.rs#L121-L131) a `ZeroVec<u8>` in #1652, but the PR is large enough. File #1653 as a followup.
