### ISSUE TITLE
Reduce data size of rule-based segmentation

### ISSUE THREAD

**Issue by aethanyc** [unicode-org/icu4x#1653]
I change `RuleBreakPropertyTable` to a `ZeroVec<u8>` in #1652 to make it serializable. But per discussion in https://github.com/unicode-org/icu4x/issues/1638#issuecomment-1055069699, we need to think about how to compress the `RuleBreakPropertyTable`.

In @makotokato's original design of line break data, the property table was a 2d array, and each item is a reference to an array of 1024 items such that the duplicate entries such as `UAX14_PROPERTIES_ID` and `UAX14_PROPERTIES_XX` only occupied the space once. 

https://github.com/unicode-org/icu4x/blob/7769518dc099f1763061aa3be3df86bacffd9cbb/experimental/segmenter/src/property_table.rs#L10-L139

Some possible approaches:
1. https://unicode-org.github.io/icu4x-docs/doc/deduplicating_array/index.html
2. CodePointTrie?

cc @sffc @makotokato

**Comment by makotokato** [comment]
line breaking table value has limit until U+0x20000, but other's limit has U+0xE01F0.  Most planes are Unknown value for word, sentence and grapheme.

**Comment by sffc** [comment]
Using `deduplicating_array` should get us down to the data size we had before with the references.

CC @robertbastian

**Comment by sffc** [comment]
I changed the title of this issue because the end goal is to reduce data size, and there are a couple other avenues we should explore:

1. Can we store the data in a CodePointTrie instead? (suggested by @aethanyc)
2. Should we have an option to generate the rule tables at runtime, and store only the property data? (suggested by @sffc)

**Comment by aethanyc** [comment]
@sffc Thank you for summarizing the discussion on slack.

[`RuleBreakPropertyTable`](https://github.com/unicode-org/icu4x/blob/92a15945dbea37e761e9c8be1eab1edc41f05f9c/experimental/segmenter/src/provider.rs#L25-L27) is the field in `RuleBreakDataV1` contributes to most of the data size. It's deserialize from the [`properties_map`](https://github.com/unicode-org/icu4x/blob/92a15945dbea37e761e9c8be1eab1edc41f05f9c/provider/segmenter/src/transform.rs#L324-L342) array, mapping codepoint to a tweaked property value of one of the `Word_Break`, `Line_Break`, `Sentence_Break`, `Grapheme_Cluster_Break` Unicode Property. These tweaked property values are served as states powering the [rule-break-transition table](https://github.com/unicode-org/icu4x/blob/92a15945dbea37e761e9c8be1eab1edc41f05f9c/experimental/segmenter/src/provider.rs#L29-L31).

Take "word break" as an example, [this code](https://github.com/unicode-org/icu4x/blob/92a15945dbea37e761e9c8be1eab1edc41f05f9c/provider/segmenter/src/transform.rs#L363-L395) fills [`properties_map`](https://github.com/unicode-org/icu4x/blob/92a15945dbea37e761e9c8be1eab1edc41f05f9c/provider/segmenter/src/transform.rs#L324-L342) the ordinary Word_Break property values plus two extra values representing emoji and complex context (codepoints for South East Asian scripts). 

In theory, we can store the tweaked property in a CodePointTrie to reduce the serialized data size, but I'm not sure how much work it would be to write such a function. 

(cc @echeran)

**Comment by robertbastian** [comment]
I think `deduplicating_array` can give us some quick improvement, there even seem to be some duplicates other than `_ID` and `_XX`.

**Comment by sffc** [comment]
Fixed by https://github.com/unicode-org/icu4x/issues/1835
