### ISSUE TITLE
Resolve inline Clippy lints (comment explaining why it is OK or code changes)

### ISSUE THREAD

**Issue by ozghimire** [unicode-org/icu4x#1668]
As part of resolving issue #1363 , codebase needs a lot of inline allow clippy code. This is expected to touch all production code folders.

Solution : The resolution strategy is either a well written comment explaining why it's ok or necessary code change to remove inline allow.

**Comment by sffc** [comment]
@robertbastian will clean up low-hanging fruit, and create child issues for each component

**Comment by Manishearth** [comment]
zerovec and calendars in https://github.com/unicode-org/icu4x/issues/1668

**Comment by sffc** [comment]
@zbraniecki Assigning this to you since the remaining work is all in components you own.

**Comment by zbraniecki** [comment]
Why do we require comment to be added to `panic!()` which has content string?

It feels weird to have:

```rust
panic!("We panic because X");
```

have to be turned to:

```rust
panic!("We panic because of X"); // We panic because of X
```

**Comment by Manishearth** [comment]
@zbraniecki to me, the panic message is for the user, and the comment is for us. If they're redundant it feels fine to not comment it IMO.

**Comment by sffc** [comment]
@zbraniecki I've raised that concern before (also for `expect`) but the consensus of the group has been to require suppressions for all four (unwrap, expect, panic, and indexing_slicing).

**Comment by sffc** [comment]
For example, the following is the style we're going for: the comment and the panic message are disjoint

```rust
/// # Panics
/// Panics if idx is not in bounds
fn get(idx: usize) {
  if idx >= self.len() {
    #[allow(clippy::panic)] // documented
    panic!("index must be in bounds");
  }
  // ...
}
```
