### ISSUE TITLE
AnyCalendar support

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1673]
We should support `AnyCalendar`, which is aware of all `icu_calendar` calendars. This will just be an enum wrapper around specific ICU calendars.

This includes parsing `u-ca` strings

**Comment by Manishearth** [comment]
Current plan is AnyCalendar enum, AnyCalendarFormat (name tbd) wrapper which works with AnyCalendar, which will error on format if the calendar doesn't match the passed-in locale.

If given an ISO locale, it will attempt to load the appropriate calendar to perform conversions.

**Comment by Manishearth** [comment]
There are two ways for AnyCalendar to work:

```rust
enum AnyCalendar {
  Gregorian(Gregorian),
  Julian(Julian),
  ....
}

enum AnyDateInner {
   Gregorian(Gregorian::DateInner),
   ...
}
impl Calendar for AnyCalendar {
...
}
```

or 

```rust
enum AnyDate {
   Gregorian(Date<Rc<Gregorian>>),
   ...
}
```

The latter enforces a particular ownership style (and doesn't integrate with preexisting calendar code), however the former needs to have a ton of double-match statements and it's not great to have invalid states representable by the type system. Personally I prefer the former and am likely to move forward with that design.

**Comment by sffc** [comment]
+1 on the first design

**Comment by Manishearth** [comment]
A thing we may need to do is convert the `until()` function to take a `Date`, not a `DateInner`, and also perhaps return a Result, so that mixing calendars can be handled. Though we can also define it as always being converted to the former date's calendar.

**Comment by Manishearth** [comment]
Steps involved:

 - [ ] Base AnyCalendar type and Calendar implementation https://github.com/unicode-org/icu4x/pull/1802
 - [ ] `u-ca` parsing and runtime construction
 - [ ] formatting infra
