### ISSUE TITLE
intro.md out-of-date for property data

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#1685]
intro.md instructs the reader to obtain the property data from https://github.com/unicode-org/icu/releases/download/release-70-1/icuexportdata_uprops_full.zip . However, `icu4x-datagen` now expects to find `../icuexportdata_uprops_full/small/scx.toml` which is not part of that zip file.

**Comment by hsivonen** [comment]
It appears that running `LD_LIBRARY_PATH=lib bin/icuexportdata -m uprops --all` in the ICU4C build directory doesn't write `scx.toml` but `LD_LIBRARY_PATH=lib bin/icuexportdata -m uprops scx` does.

**Comment by robertbastian** [comment]
This is being fixed in icu#2054
