### ISSUE TITLE
Pull some modules from icu_provider into their own crate

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1690]
Since `icu_provider` is a core crate with a lot of dependents, it would be nice to avoid the extra compile time and version churn of the peripheral utilities it currently contains. The following items could be moved out:

- Filter providers
- Forking providers
- Vertical fallback (upcoming)

What should the new crate layout be?

- [x] @Manishearth 
- [ ] @robertbastian

**Comment by robertbastian** [comment]
Should we put filter and forking behind features? Right now I'd say move them to datagen because that's the only place where they're used, but I understand we want to also expose them for runtime use.

**Comment by Manishearth** [comment]
Hmm, I'll have to look closer at what we have right now (pulling datagen stuff out might be neat, if possible).

But I do think perhaps we should do the datagen/serde feature stuff first? I'm thinking about taking that on soonish:

https://github.com/unicode-org/icu4x/issues/1320#issuecomment-1059431169

Once we finish that I think we'll have a clearer idea of what goes where. It would be pretty cool if all the datagen stuff could be banished to a different crate.

My general idea of where things should go would be:

 - core: data provider, resource provider, data key, markers, etc
 - providers (depends on datagen with a feature): filter, forking, etc
 - datagen: iterable, omni, etc

**Comment by Manishearth** [comment]
I started working on #1320 and I think I more strongly agree with my assessment above.

In general we should move things out of core if they can be. I have a slight preference for datagen stuff living outside but @sffc did point out that basically every ICU4X component will need a datagen dependency which does seem to indicate that it should perhaps just be an optional dep on core.

**Comment by sffc** [comment]
The like I'd like to draw is that if components need it, it lives in core, but if only client code needs it, then it lives in the new "adapters" crate.

**Comment by Manishearth** [comment]
makes sense to me!
