### ISSUE TITLE
Add continuous integration for non-testdata data generation

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#1698]
#1353 added `scx.toml` to testdata, but it's not in the current [`icuexportdata_uprops_full.zip`](https://github.com/unicode-org/icu/releases/download/release-70-1/icuexportdata_uprops_full.zip), so data generation with `--all-keys` has been broken since then, including at the `0.5` cut.

**Comment by sapriyag** [comment]
Robert can this be closed? Is Shane changes sufficient to close this issues?

**Comment by robertbastian** [comment]
Which changes? I'm not aware of anything that could've fixed this

**Comment by sapriyag** [comment]
@Manishearth Can you help elaborate Shane's changes you mentioned would have fixed this issue?

**Comment by Manishearth** [comment]
@robertbastian I was under the impression Shane made some changes to ICU that would fix this, but I don't have full background here.

**Comment by Manishearth** [comment]
Oh, wait, this issue is for adding CI, never mind.

**Comment by sffc** [comment]
My concern here is that it makes our CI rely on downloading the source data from somewhere, which could be flaky.

**Comment by sffc** [comment]
Conclusion 2022-05-20:

- Add as a new CI job
- There should be separate steps for downloading the two ZIP files, which are cached
- Consider running icu4x-datagen in release mode

LGTM: @sffc, @nordzilla, @dminor, @robertbastian, @Manishearth
