### ISSUE TITLE
FixedDecimal: Make immutable

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#171]
Currently I have a method `adjust_magnitude(&mut self, ...) -> Result<(), Error>`.  I think it would be better if the method had the signature `mul_pow10(self, ...) -> Result<Self, Error>`.

```rust
// Old:
let mut dec: FixedDecimal = 123.into();
dec.adjust_magnitude(-2).unwrap();

// New:
let dec: FixedDecimal = 123.into().mul_pow10(-2).unwrap();
```

@Manishearth @zbraniecki

**Comment by Manishearth** [comment]
it's not uncommon to also just have both, but the names need to be carefully picked.

**Comment by sffc** [comment]
Based on the standard library [Mul](https://doc.rust-lang.org/std/ops/trait.Mul.html) and [MulAssign](https://doc.rust-lang.org/std/ops/trait.MulAssign.html), do you think good names might be `mul_pow10` and `mul_assign_pow10`?

**Comment by sffc** [comment]
Would it be advisable to make a new type `struct Pow10(i16)`, and then implement Mul and MulAssign with that type, or is that overkill?  I guess we could do both:

```rust
let dec = FixedDecimal::from(123) * Pow10(-2);
```

**Comment by Manishearth** [comment]
No, I would not use the Mul/MulAssign thing, those are named after the trait and the trait is named after the operator

Typically you can do stuff like `.multiply()` vs `.multiplied()`

Having a separate struct is mostly overkill here imo

**Comment by sffc** [comment]
In #141 I implemented the function names `.multiply_pow10(&mut self, ...)` and `.multiplied_pow10(self, ...) -> Self`

**Comment by sffc** [comment]
Tentative decisions from meeting on 2020-07-17:

- Add both methods for now.  Revisit API surface before releasing version 1.  The names are as good as any other names.
