### ISSUE TITLE
Add is_ascii_alphabetic_lowercase() to TinyAsciiStr

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1712]
In #1694 I added `is_ascii_lowercase()` (and uppercase and titlecase). The functions are defined to mean that if you apply `to_ascii_lowercase()` (or uppercase/titlecase), then you get back the same string.

However, many call sites are ending up looking like

```rust
s.is_ascii_alphabetic() && s.is_ascii_lowercase()
```

I think we should add functions that combine both checks and save a few bitops. The PR should also migrate the appropriate call sites in the icu_locid crate over to the new functions.

**Comment by andrewpollack** [comment]
For this issue, would it be more desirable to reduce code copying by returning `TinyAsciiStr::is_ascii_alphabetic(&self) && TinyAsciiStr::is_ascii_lowercase(&self)`, or would it be more efficient to do two `check_is!` calls? I lean towards the former, but want to confirm!

**Comment by sffc** [comment]
There is a file int_ops.rs. The desirable outcome is to add the three new functions to that file, and use `check_is!` to invoke those new functions. The expectation is new code added to the repo, although we will move call sites over to the new functions, so there should be no net impact on code size.

**Comment by andrewpollack** [comment]
I'm running into some challenges understanding the expansion on `check_is!`. Would you be able to explain the differences between `$check_u8` vs. `!$check_u8`, and why I am unable to substitute the following lines?
```
($self:ident, $check_u8:ident) => {
     if !$self.bytes[0].$check_u8() {
           return false;
     }
}
```
vs.
```
($self:ident, !$check_u8:ident) => {
     if $self.bytes[0].$check_u8() {
           return false;
     }
}
```

Essentially, why does the first macro [here](https://github.com/unicode-org/icu4x/blob/main/utils/tinystr/src/ascii.rs#L169) utilize a `!`, while the other [here](https://github.com/unicode-org/icu4x/blob/main/utils/tinystr/src/ascii.rs#L187) does not?

**Comment by andrewpollack** [comment]
Closing by PR https://github.com/unicode-org/icu4x/pull/1806

**Comment by sffc** [comment]
I think you figured out the question about check_is, but the idea is whether you perform a positive test or a negative test. Alphanumeric is a positive test (all characters must be in that class), and lowercase is a negative test (no character may be in the uppercase class).

**Comment by andrewpollack** [comment]
After playing around more with it, am I correct in that having `!check_u8` in the macro definition does **not** negate the `check_u8` check (i.e. changing `check_u8` into `NOT check_u8`)? Inclusion of `!` if more-so for readability as opposed to actually altering the macro?

**Comment by sffc** [comment]
A ! in the macro invocation results in no ! in the expansion, and no ! in the macro invocation results in a ! in the expansion.

I'm not super happy with this but it's like the 5th try at making the macro more readable.

Also see #1701 and CC @robertbastian

**Comment by macchiati** [comment]
when you define is_X(x) as being to_X(x) == x, you sometimes get some
counter-intuitive results.

is_uppercase("宮崎 駿（みやざき はやお、1941年〈昭和16年〉1月5日 - ）") == true
is_lowercase("宮崎 駿（みやざき はやお、1941年〈昭和16年〉1月5日 - ）") == true

**Comment by sffc** [comment]
We have two versions of the APIs on `TinyAsciiStr`:

- [is_ascii_lowercase](https://unicode-org.github.io/icu4x-docs/doc/tinystr/struct.TinyAsciiStr.html#method.is_ascii_lowercase) is defined to mean that `S == S.to_ascii_lowercase()`
- [is_ascii_alphabetic_lowercase](https://unicode-org.github.io/icu4x-docs/doc/tinystr/struct.TinyAsciiStr.html#method.is_ascii_alphabetic_lowercase) is defined to mean `S.is_ascii_alphabetic() && S.is_ascii_lowercase()`

The main use case is to verify that things like `und` is a valid language subtag, with `is_ascii_alphabetic_lowercase()`

**Comment by andrewpollack** [comment]
> A ! in the macro invocation results in no ! in the expansion, and no ! in the macro invocation results in a ! in the expansion.
> 
> I'm not super happy with this but it's like the 5th try at making the macro more readable.
> 
> Also see #1701 and CC @robertbastian

That makes sense and reflects what I am seeing, thank you for the explanation!
