### ISSUE TITLE
Update introduction tutorial

### ISSUE THREAD

**Issue by ptmphuong** [unicode-org/icu4x#1719]
Hi! I'm new to the project and following the [introduction tutorial](https://github.com/unicode-org/icu4x/blob/main/docs/tutorials/intro.md). 

I was able to replace some outdated components and build with the `0.5.0` version, but have some problems generating data from [icuexportdata_uprops_full.zip](https://github.com/unicode-org/icu/releases/download/release-70-1/icuexportdata_uprops_full.zip): `scx.toml` is missing, and `manisfest.json` is incorrectly generated. Similar to #1698 and #1685. I fixed it manually and got it all compiled finally but wonder if there's a better way to make it work?

The `--all-locales` command of `icu4x-datagen` doesn't generate all locales so `pl` doesn't work either.

I'm also happy to work on updating the tutorial with some instructions!

Firstly generated `manifest.json`:
```json
{
  "syntax": "Json"
}
```

`Cargo.toml`:
```toml
[dependencies]
icu = "0.5.0"
icu_provider_fs = {version = "0.5", features=["deserialize_json"]}
```

`main.rs`:
```rust
use icu::locid::macros::langid;
use icu::locid::Locale;
use icu_provider_fs::FsDataProvider;
use icu::datetime::{mock::parse_gregorian_from_str, DateTimeFormat, options::length};

fn main() {
    let loc: Locale = langid!("ja").into();

    let date = parse_gregorian_from_str("2020-10-14T13:21:00")
        .expect("Failed to parse a datetime.");

    let provider = FsDataProvider::try_new("~/icu/icu4x-data")
        .expect("Failed to initialize Data Provider.");

    let options = length::Bag {
        time: Some(length::Time::Medium),
        date: Some(length::Date::Long),
        ..Default::default()
    }
    .into();

    let dtf = DateTimeFormat::try_new(loc, &provider, &options)
        .expect("Failed to initialize DateTimeFormat");

    let formatted_date = dtf.format(&date);

    println!("??: {}", formatted_date);
}

```

**Comment by Manishearth** [comment]
I'll have a closer look at the errors tomorrow but one thing worth noting is that all of the data can be found pregenerated in `provider/testdata/json` or `provider/testdata/testdata.postcard` and loaded with FsDataProvider.

There's also the `icu_testdata` crate that provides a convenience method for loading this data.

It's quite likely that the instructions in the tutorial for generating data are out of date, good catch!

**Comment by ptmphuong** [comment]
Thanks for the prompt actions! 

I was thinking of using `icu_testdata` as a way to introduce about the concept of data providers. And then datagen is quite helpful to generate locales not included in the `provider/testdata/json`, but perhaps gotta look in why datagen doesn't work with the current export dataset.

**Comment by Manishearth** [comment]
Yeah, that makes sense, and Shane has been suggesting that too. I'll restructure the text to talk about data providers.

**Comment by Manishearth** [comment]
I've updated my PR to mention testdata more directly.
