### ISSUE TITLE
Add CompactOptionULE

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1724]
`OptionULE`, as suggested in #1723, has an inefficient bit pattern. It would be nice to have an OptionULE type that could store a more efficient representation.

My suggestion was to introduce one of the following unsafe traits:

- `NonZeroULE`: a ULE type that is never zero (all 0s)
- `NonMaxULE`: a ULE type that is never the max integer value (all 1s)
- `NoHighBitULE`: a ULE type where the high bit is never used

Let's take `NonMaxULE`. We would pair this with `NonMaxOptionULE`, which would use the anointed bit pattern to represent `None`.

I like `NonMaxULE` because it works for both `TinyAsciiStr` as well as enums that have fewer than 255 variants.

@Manishearth had some more ideas which he may write in a reply below.

**Comment by Manishearth** [comment]
Overall I'm not much in favor of such a system that only selects one bit pattern as a niche, nor really having multiple types. Rust's uncustomizeable NonZero has been a source of much frustration in this space and I'd rather not replicate it.

I think a good path forward would be to have something like

```rust
unsafe trait InvalidBytes {
   const INVALID_BIT_PATTERN: &[u8]; // required to have len == sizeof(self)
}
```

Even better, we could have the bit pattern be specified by:

```rust
enum InvalidBitPattern {
    MaxBytes.
    ZeroBytes,
    Bytes(&[u8])
    Sequence(&[&InvalidBitPattern])
}
```

which we can propagate in the custom derive (have an attribute saying that a field implements InvalidBitPattern, automatically makes type implement it too using Sequence)

**Comment by sffc** [comment]
@Manishearth What is the size for this issue? If it is small, we could do it in 1.0, but if it's nontrivial, we should sit on it.

**Comment by Manishearth** [comment]
Nontrivial since I think there's some work involved in getting a good design, and implementing it.

**Comment by sffc** [comment]
OK, let's put it in 1.1 then.

Is this a good first/second issue?

**Comment by Manishearth** [comment]
good second issue for someone with a strong rust background (comfort in rust code), I think.

**Comment by sffc** [comment]
@pdogr I think there's time for ICU4X 1.0 to optimize the storage at least for the ULE form of TinyAsciiStr. @robertbastian Could you advise on this?

**Comment by robertbastian** [comment]
Note that the all-1 bit-pattern is actually not the maximum value for signed integers.

**Comment by sffc** [comment]
At least for now, I think the NicheOptionULE should show up in ZeroVec bounds. The blanket impl on Option should stay, at least for now (but we can start migrating ICU4X users over to the new model).

NicheOptionULE should have a function like `get` that returns a regular option, which you have to invoke after getting the value out.

**Comment by sffc** [comment]
Yeah, I think the nicest solution is NichedOption that has a Deref to regular Option.

**Comment by robertbastian** [comment]
So something like

```rust
/// N == core::mem::sizeo_of::<Self>()
pub trait NicheBytes<const N: usize>: ULE {
    const INVALID_BIT_PATTERN: [u8; N];
}

pub struct NichedOption<T: AsULE>(Option<T>);

impl<T> Deref for NichedOption<T> {
  type Target = Option<T>;
}

#[repr(packed)]
pub union NichedOptionULE<U: NicheBytes<N>, const N: usize> {
    invalid: [u8; N],
    valid: U,
}

impl<T: AsULE, const N: usize> AsULE for NichedOption<T>
  where T::ULE: NichedBytes<N>
{
    type ULE = NichedOptionULE<T::ULE>;
    
    // ...
}
```

and usage would be 

```rust
impl<const N: usize> NicheBytes<N> for TinyAsciiStr<N> {
  const INVLID_BIT_PATTERN: [u8; N] = [0xFF; N];
}


pub struct Foo<'a> {
  bar: ZeroVec<'a, NicheOption<TinyAsciiStr>,
}
```

**Comment by Manishearth** [comment]
@pdogr yes, you will not be able to have multiple impls, it will have to be a separate type unless we want to completely replace the impl (which we can't). I think that's fine.

Note that you can get around needing the `const N` if you do the `&[u8]` thing I suggested instead. The trait has to be unsafe either way so requiring implementors to get the length right doesn't seem too bad.

**Comment by robertbastian** [comment]
The union cannot be defined without `N`, as `<U as InvalidBytes>::INVALID_BIT_PATTERN.len()` is not evaluable.

**Comment by robertbastian** [comment]
I also think it's a nice hint to the implementor.
