### ISSUE TITLE
Bidi - Add a function to port the Bidi-class data to Unicode Bidi

### ISSUE THREAD

**Issue by younies** [unicode-org/icu4x#1734]
After adding bidi class data #1716 , we need to implement a helper function to export the bidi class data to unicode bidi crate.

**Comment by sapriyag** [comment]
Younies can you please add size label for this issue? Should this be S-medium or S-small?

**Comment by sffc** [comment]
@younies Is this done? Please link the PR that fixed it.

**Comment by younies** [comment]
https://github.com/unicode-org/icu4x/pull/1784
