### ISSUE TITLE
Follow-up: Codecov vs. Coveralls

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#176]
We gathered feedback on the two tools.  I suggested that we enable both tools for a little while and see which tool we like better.

**Comment by zbraniecki** [comment]
@echeran offered to plug Codecov into our repo. Is that still something you're willing to do @echeran ?

**Comment by sffc** [comment]
@echeran I'm adding this issue to the 0.1 Cleanup milestone.  I'm getting tired of Coverall's clunky interface and having to sign in all the time just to see what lines changed.

**Comment by sffc** [comment]
The main problem with code coverage though is more about the backend that generates the coverage data.  Right now we have a pathetic 75% coverage, despite high coverage of business logic.  It counts things like struct fields and debug traits as not covered, which doesn't make any sense (struct fields are not code, and we previously decided that debug traits don't need to be tested).
