### ISSUE TITLE
Figure out what needs to be done with "private" features like "datagen" when it comes to docs

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1771]
We currently have the `"datagen"`  and `"export"` features, and used to have the `"provider_transform_internals"`.  These contain a fair number of APIs that most (if not all) users should not have to care about. They currently show up on docs.rs since we supply `package.metadata.docs.rs.all-features = true` to Cargo.toml.

I've filed https://github.com/rust-lang/docs.rs/issues/1710 to see if we can get denylist support in docs.rs, but it seems to be a nontrivial feature request.

Perhaps we can `doc(hidden)` these APIs, or perhaps duplicate the list of features in the docs.rs line. The major downside of `doc(hidden)`

[docs.rs does support setting `RUSTFLAGS`](https://docs.rs/about/metadata), so we could potentially set RUSTFLAGS to `--cfg=hidden_internal_docs` and use `#[cfg_attr(hidden_internal_docs, doc(hidden))]` everywhere.

Thoughts?
 
cc @zbraniecki @nordzilla @sffc

**Comment by sffc** [comment]
"datagen" is largely but not entirely an internal feature. I think we said it enables serde::Serialize, for example. I don't know for sure whether we should consider the stuff behind "datage" features to be public stable APIs or not.

"export" is a very specific feature in only a few crates and it exists to remove unnecessary dependencies, but I do consider the stuff behind that feature to be public API. I still aspirationally would like us to support people bringing their own source data besides CLDR, and then building it into postcard using the export feature on provider_blob, for example.

> The major downside of `doc(hidden)`

Sentence fragment. What is the major downside?

**Comment by Manishearth** [comment]
@sffc Oh, that we lose docs for ICU4X devs.

Hm, so if `datagen` is not entirely internal, I suspect we should do more to ensure that the `datagen` stuff is all behind a module (we've already done this a bit in `provider/core`) or even separate crates and document them as largely not for end users.

**Comment by Manishearth** [comment]
I feel like the bulk of the answer is to split datagen stuff out into a different crate and keep `core` slim.

**Comment by sffc** [comment]
Conclusion:

- OK to have the `icu_provider::datagen` module
- Slim down the `datagen` features in other crates so that they don't hide functionality; either move the functionality into the `icu_datagen` crate, or make it public stable in the component crate.

**Comment by sffc** [comment]
@Manishearth to make sure this is done.

**Comment by Manishearth** [comment]
I think this has been done
