### ISSUE TITLE
Add benchmarks and examples for Calendar component

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1791]
The Calendar component does not yet have performance benchmarks. We should pick a few operations to benchmark and make a matrix that tests them for each of the calendar systems.

Also add examples, which are used for memory and code size benchmarks.

**Comment by andrewpollack** [comment]
I'd like to tackle this one -- what sort of operations would make sense to benchmark?

Order-wise, I will explore the Calendar component and add examples to the `calendar/src/lib.rs` to familiarize with the code. Afterwards I'll shift focus on the performance benchmarks

**Comment by sffc** [comment]
As discussed, the following operations are good for Criterion benchmarks:

- Conversions to/from ISO
- Arithmetic (e.g. add 1 month)

For a memory / code size benchmarks, you could have a list of ISO dates, convert them to calendar dates, and conditionally print out the components (see other `examples` files for how we conditionally print out the results).

**Comment by andrewpollack** [comment]
I'm running into an issue that I believe is due to some missing casting on my part. I'm trying to utilize `Julian.date_from_iso()` in the following example:
```rust
use icu::calendar::{Calendar, Date, julian::Julian}

let date_iso = Date::new_iso_date_from_integers(1996, 2, 3).unwrap();
let date_julian = Julian.date_from_iso(date_iso);

assert_eq!(date_julian.year(), 1996);
```

However, I get the following error:
```rust
no method named `year` found for struct `JulianDateInner` in the current scope

assert_eq!(date_julian.year(), 1996);
                               ^^^^ method not found in `JulianDateInner`
```

Should I be taking an extra step to cast the returned `JulianDateInner` value into a `Date<Julian>` value? If so, what does that look like?

cc @Manishearth

**Comment by Manishearth** [comment]
@andrewpollack ah, the user should never be seeing the `DateInner` types, you instead want to call `Date::new_from_iso()`.

The `Calendar` functions should, by and large, not be called by users. We should perhaps rename them `cal_foo()` or something to dissuade users from making this mistake, nice catch!

**Comment by andrewpollack** [comment]
This issue is currently covered by PRs:
https://github.com/unicode-org/icu4x/pull/1887 (general benchmarks)
https://github.com/unicode-org/icu4x/pull/1872 (memory + code size benchmarks)

**Comment by andrewpollack** [comment]
With merge of https://github.com/unicode-org/icu4x/pull/1887 (general benchmarks) and https://github.com/unicode-org/icu4x/pull/1872 (memory + code size benchmarks), I believe this issue can be closed. Thoughts @sffc ?
