### ISSUE TITLE
Repository directory structure

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#18]
What should be the directory structure for our monorepo project in Git?

**Comment by Manishearth** [comment]
I'm thinking a `components/` folder with each crate flat within it. We can make subdirectories for crates if we really need to (e.g. if we want to stash a bunch of data loaders somewhere) but I don't think it's necessary.

Also we should probably _not_ use `src/` directories within crates, that convention makes sense for single-crate repos where you don't want to mix your code with your CI files, docs, etc, but if each crate has its own folder we don't need to have a separate smaller folder within it just for the code if there's not going to be much else.

**Comment by nciric** [comment]
@Manishearth what do you think about managing the whole repo as Rust [workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html)?

It defines one output folder, and allows addition of multiple crates. Example directory structure (from the link):

```
├── Cargo.lock
├── Cargo.toml
├── add-one
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
├── adder
│   ├── Cargo.toml
│   └── src
│       └── main.rs
└── target
```

**Comment by Manishearth** [comment]
Yeah I was assuming we'd use a workspace.

I usually prefer not using `src/` with a multi repo situation, but that's mostly a personal preference.

**Comment by nciric** [comment]
> I usually prefer not using `src/` with a multi repo situation, but that's mostly a personal preference.

Could you reformat my example to what you think it's optimal? Is it just removing src/ enough:

```
├── Cargo.lock
├── Cargo.toml
├── number-format
│   ├── Cargo.toml
│   └── lib.rs
├── collator
│   ├── Cargo.toml
│   └── lib2.rs
└── target
```

**Comment by Manishearth** [comment]
Yep. Others in this group disagree with that option though, so what you first posted may be the best path forward. We should def use a workspace though

**Comment by nciric** [comment]
@Manishearth do we care about this?

> If you publish the crates in the workspace to crates.io, each crate in the workspace will need to be published separately. The cargo publish command does not have an --all flag or a -p flag, so you must change to each crate’s directory and run cargo publish on each crate in the workspace to publish the crates.

Would that mean that we have crates.io entry for each of number format, date format, collator,... I don't mind it, it may enforce modularity better.

**Comment by Manishearth** [comment]
This is always true, unless we do a single crate. It's fine, you can write a script for coordinated publishing

**Comment by sffc** [comment]
My impression from last Thursday was that we would have:

```
(top)
├── README.md
├── docs
│   ├── foo.md
│   └── bar.md
└── components
    ├── number-format
    │   ├── Cargo.toml
    │   └── src
    │       └── lib.rs
    ├── langid
    │   ├── langid-impl
    │   │   ├── Cargo.toml
    │   │   └── src
    │   │       └── lib.rs
    │   ├── langid-macros-impl
    │   │   ├── Cargo.toml
    │   │   └── src
    │   │       └── lib.rs
    │   ├── langid-macros
    │   │   ├── Cargo.toml
    │   │   └── src
    │   │       └── lib.rs
    │   └── langid
    │       ├── Cargo.toml
    │       └── src
    │           └── lib.rs
    ├── locale
    │   └── (similar to langid)
    └── collator
        └── (similar to number-format)
```

**Comment by nciric** [comment]
I think all of that stands except for e.g.  src in langid/src (Manish thinks we don't need src part).
Cargo tool auto creates it, and automates some of the tasks there is src, but I don't know if it's very important.

**Comment by Manishearth** [comment]
Oh, you just need to explicitly add a `lib.path` key to make no-`src` work, see https://github.com/servo/servo/blob/33a74a4f4eb9a4df0b6ccf2b6988331e59ae2baa/components/canvas/Cargo.toml#L9-L11

**Comment by sffc** [comment]
Let's document the decision in the Rust Style Guide (#12).

**Comment by nciric** [comment]
I think that missing parts at this point are:
1. Where to put data driven tests
2. Where to put wrapper layer

I assume that for both 1 & 2 top level testing, wrapper folders would be created.

We already have components with internal structure defined by #31
