### ISSUE TITLE
Writeable trait for ICU4X

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#181]
When implementing FixedDecimal, I [discovered](https://unicode-org.slack.com/archives/CUZ62M47Q/p1594951694008700) that, relative to std::fmt::Display, we can increase to-string performance by a considerable margin by pre-allocating string capacity.

Since ICU4X will require a lot of to-string conversion, I was wondering whether we would consider it a good idea to make a new trait similar to std::fmt::Display for use by ICU4X types.

Something like:

```rust
trait Writeable {
    fn write_to(&self, sink: &mut dyn fmt::Write) -> fmt::Result;
    fn write_len(&self) -> usize;

    fn to_string(&self) -> String {
        let mut output = String::with_capacity(self.write_len());
        self.write_to(output).expect("impl Write for String is infallible");
        Ok(output)
    }
}

// Auto-implement std::fmt::Display
impl<T: Writeable> fmt::Display for T {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        self.write_to(f)
    }
}
```

@Manishearth @hsivonen @zbraniecki

**Comment by Manishearth** [comment]
Hmmm. I'd rather not lose Display and ToString.

It's possible to override the ToString impl, however, with specialization. It's nightly only but we can feature gate that.

**Comment by sffc** [comment]
> Hmmm. I'd rather not lose Display and ToString.

We would auto-implement fmt::Display for types implementing Writeable.

> It's possible to override the ToString impl, however, with specialization. It's nightly only but we can feature gate that.

This solves the problem of making ToString more efficient, but @zbraniecki pointed out that it doesn't solve the problem of making an efficient alloc-less to-string.

**Comment by Manishearth** [comment]
> We would auto-implement fmt::Display for types implementing Writeable.

No, because Display implies a ToString impl, so there's a conflict

> This solves the problem of making ToString more efficient, but @zbraniecki pointed out that it doesn't solve the problem of making an efficient alloc-less to-string.

That's what the Display trait does? You don't need to allocate to read from Display. Anything which implements `Write` will do, and you can implement `Write` without allocating.

**Comment by sffc** [comment]
> > We would auto-implement fmt::Display for types implementing Writeable.
> 
> No, because Display implies a ToString impl, so there's a conflict

I don't think there's a conflict; we'd let std::string::ToString get the default Display-based implementation, while also providing our own to-string method.  We could name it `to_string` and force people to call it with a fully-qualified name, or we could name it something different.

> > This solves the problem of making ToString more efficient, but @zbraniecki pointed out that it doesn't solve the problem of making an efficient alloc-less to-string.
> 
> That's what the Display trait does? You don't need to allocate to read from Display. Anything which implements `Write` will do, and you can implement `Write` without allocating.

With the Display trait, you can't know the required capacity ahead of time.  Writing to a std::string::String is a common case, but you may want to write to other sinks and still know the capacity.  For example, if you wanted to write to a SmallString, it may still be useful to know the capacity so that it could heap-allocate if it needed to.  I looked at fmt::Display and fmt::Formatter and couldn't find a way to make them "reserve" a certain number of bytes in the destination buffer.

Also, going through Display is heavyweight for library applications.  Looking at code size, when I directly write to a string via fmt::Write instead of Display, I get significantly smaller code size.  I'm happy to share details.

**Comment by Manishearth** [comment]
> I don't think there's a conflict; we'd let std::string::ToString get the default Display-based implementation, while also providing our own to-string method. We could name it to_string and force people to call it with a fully-qualified name, or we could name it something different.

We'd have to give it a different name, it kinda sucks to do the fully qualified name. And if we do that it won't be as discoverable.

> Also, going through Display is heavyweight for library applications. Looking at code size, when I directly write to a string via fmt::Write instead of Display, I get significantly smaller code size. I'm happy to share details.

I don't understand, `write!(f, "{}", foo)` and Display do the same thing.

**Comment by sffc** [comment]
OK, here's my data.

I compiled the following function with 3 different definitions of Message to_string.

```rust
struct Message {
	message: &'static str,
}

// Variable to_string implementation (See below)

#[no_mangle]
pub fn alert_message_display() {
	let message = Message {
		message: "Hello, world!"
	};
	let string = message.to_string();
	unsafe {
		alert(&string);
	}
}
```

The three versions are:

### Case 1: Rust-standard to_string auto-implemented from Display using the `write!` macro

```rust
impl fmt::Display for Message {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		write!(f, "{}", self.message)
	}
}
```

### Case 2: Rust-standard to_string auto-implemented from Display using the Write trait

```rust
impl fmt::Display for Message {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		f.write_str(self.message)
	}
}
```

### Case 3: Custom to_string implemented using the Write trait

```rust
impl ToString for Message {
	fn to_string(&self) -> String {
		let mut output = String::with_capacity(self.message.len());
		output.write_str(self.message).expect("write_to String should not fail");
		output
	}
}
```

## Results

The WASM code size is the number of bytes in the \*.wasm file generated from wasm32-unknown-unknown using no_std and alloc + wee_alloc.  Click the link to see the compiled output.

| Case | Description | WASM Code Size\* |
|---|---|---|
| 1 | Display with `write!` | [28.4 KB](https://github.com/sffc/rust-wasm-i18n/tree/6820e317779c078fb6238e767e572a767b6e86fa/wasm-no-std/pkg) |
| 2 | Display with `write_str` | [21.6 KB](https://github.com/sffc/rust-wasm-i18n/tree/80aa4c1b40627319538245eb68125bb41cd32dbd/wasm-no-std/pkg) |
| 3 | Custom to_string | [3.72 KB](https://github.com/sffc/rust-wasm-i18n/tree/eb43604a77a3e132ed23fe7dd43668620db03fc8/wasm-no-std/pkg) |

## Commentary

The Display-based to_string bloats up the code size considerably, and so does using `write!` instead of the Write trait.

This is the origin of my proposed Writeable trait, which avoids both `write!` and the Display-based to_string.

**Comment by Manishearth** [comment]
Ah, I see. That's unfortunate.

**Comment by zbraniecki** [comment]
@Manishearth is it something worth discussing on the rust-lang level? It seems like @sffc findings could be useful when designing the language further and the `Writable` trait seems like of generic usability for std.

**Comment by filmil** [comment]
Recording my comments from the discussion from today.

1. Make sure that the difference in code size is representative of realistic uses
2. Is the code size penalty one time or does it get amortized over number of uses.
3. Is it possible that the difference is an artifact of compilation and not a real difference?

**Comment by sffc** [comment]
Just now recording the conclusion from last week's meeting.  IIRC, the plan of action is to proceed with the `Writeable` trait, and implement actual `ToString`, leaving out a definition of `Display`.

**Comment by sffc** [comment]
Still need to migrate FixedDecimal and FormattedDateTime to Writeable.

**Comment by sffc** [comment]
Follow-up: #440
