### ISSUE TITLE
Should we move TinyStr into utils?

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#185]
https://github.com/zbraniecki/tinystr is a utility library for blazing fast ASCII strings - https://github.com/zbraniecki/tinystr/wiki/Performance

The idea came from Raph Levien as he was looking to speed up unic-locale and speed up it did.

In a year since its release it has been successfully used in locale and pluralrules crates that I wrote, but has not been adopted by other projects yet - https://crates.io/crates/tinystr/reverse_dependencies

I think it will eventually find its use outside of locale-related code, so I am motivated to maintain it as a standalone library, but I also recognize that the primary use for it is inside of ICU4X now and would prefer to have it maintained by a larger community.

Would ICU4X adopt it? We would then get our first `util/` piece on its own release cycle (which we can synchronize with ICU4X later).

**Comment by Manishearth** [comment]
Given that Raph is a collaborator and that it already exists out of tree I'd prefer to keep it there. Maybe more people will use it in the future. We can still add icu4x as maintainers, I just don't think we need all of these to be in a large monorepo.

**Comment by sffc** [comment]
Since TinyStr predates ICU4X, I'm fine keeping it in an external repo.

**Comment by zbraniecki** [comment]
@sffc would you be open to be added to tinystr maintainers list (alongside Manish, Raph and me)?

**Comment by sffc** [comment]
> @sffc would you be open to be added to tinystr maintainers list (alongside Manish, Raph and me)?

Works for me

**Comment by zbraniecki** [comment]
ok! closing then. If icu4x org will want access, we'll extend!
