### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#187]
One practice we haven't embrace yet from Rust is to introduce `examples/` directory with a couple small binaries that showcase the canonical use of a library API.

Examples can be as simple as this: https://github.com/zbraniecki/unic-locale/blob/master/unic-langid/examples/simple-langid.rs or show a more complete program: https://github.com/projectfluent/fluent-rs/blob/master/fluent-bundle/examples/simple-app.rs

The benefit of having those examples are not just that potential users can make sense of how the API is meant to be used beyond of what docs examples use, but also that we will have small binaries to use in size/memory testing.

**Comment by sffc** [comment]
Next steps are for the component owners to create these example files in individual PRs.

**Comment by sffc** [comment]
Shane Q: Should the examples directory and lib.rs examples be consistent? How do we deduplicate them?

Zibi: I think the two will eventually diverge.  It could be a starting point.

**Comment by sffc** [comment]
The examples directory should contain code that has common use cases.  For example, it could contain code that generates a UnicodeSet for ASCII alphanumeric characters.

**Comment by zbraniecki** [comment]
I believe the last component missing examples is `uniset`. @echeran .

**Comment by zbraniecki** [comment]
@echeran @EvanJP @sffc - I'm trying to come up with an example that would showcase unicodeset's current feature in a qusi real-world app.

The app should be simple, have a pseudo-real-world value, and we'll use it for size benchmarks, memory benchmarks and it'll be how people learn about what UnicodeSet does.

Do you have ideas on what such simple example may be?

I thought of either something that checks for western+eastern numerals in a string, or iterates over greek characters, or verifies if the characters in a string are of valid identifier (say, starting with a capital A..Z and then a..zA..Z0..9-_)?
Does any of those sound like a good candidate? Other ideas?

**Comment by zbraniecki** [comment]
Used my imagination to come up with some example app for Unicode Set in #302.
