### ISSUE TITLE
Compiler panic while building datetimeformat example in intro.md

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#1896]
With the version of the datetimeformat example in intro.md from https://github.com/unicode-org/icu4x/pull/1895, I get a compiler panic when building locally:

```
dminor@treebeard:~/src/icu-temp/myapp$ cargo build
   Compiling myapp v0.1.0 (/home/dminor/src/icu-temp/myapp)
thread 'rustc' panicked at 'assertion failed: !new_self_ty.has_escaping_bound_vars()', compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1688:9

```

**Comment by robertbastian** [comment]
I believe this is fixed in 1.61: https://github.com/rust-lang/rust/issues/96223

**Comment by sffc** [comment]
@dminor Did you verify whether the update to 1.61 resolves the issue?

**Comment by sffc** [comment]
@dminor Could you verify if this is fixed?

**Comment by dminor** [comment]
Yes, it's fixed, although I think the example code needs to be updated to reflect recent changes.

**Comment by sffc** [comment]
Cool, thanks for confirming. I opened https://github.com/unicode-org/icu4x/issues/2281 to track tutorial updates for 1.0 (surprised we didn't already have an issue for that).
