### ISSUE TITLE
Discuss `Bakeable` name

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#1937]
@Manishearth wants to rename it because Rust traits should be verbs, not adjectives.

**Comment by sffc** [comment]
Just name it `Bake` then?

**Comment by Manishearth** [comment]
I personally prefer CrabBake, Bake is somewhat short and it's nice to match with the crate name. But I'm not strongly against Bake

**Comment by sffc** [comment]
Can we get the "bake" crate? https://crates.io/crates/bake

**Comment by sffc** [comment]
I've not been super excited about "crabbake" because (1) it's too close to "crabcake", (2) a "crab bake" is not really a thing (but "crab boil" is), and (3) the repeated "b" is distracting for prounciation purposes

**Comment by robertbastian** [comment]
Crabbake is a noun though. You don't crabbake something, you bake a crab and get a crab bake.

**Comment by sffc** [comment]
If we switch to just "bake", then we can remove the reference to baking crabs and appeal to vegetarians. :)

**Comment by robertbastian** [comment]
Or `Hardcode`, which is a one-word phrase for 'baking in'

**Comment by sffc** [comment]
I think the `Bake` metaphor is fairly clear, but I'm also okay with `Tokenize`.

**Comment by sffc** [comment]
It seems that we would not be able to reclaim the `bake` crate name. Therefore option 1 is out.

Among the other options, option 2 is in the lead by all of the following measures:

1. Ranked choice voting: with option 1 eliminated, option 2 has the most first-choice votes (second row in the table above).
2. Vetoes: option 2 has the fewest vetoes, tied with option 1.
3. Average Position: option 2 has the highest average position after option 1.

Therefore, it looks like we will move forward with option 2.
