### ISSUE TITLE
Tracking issue: FFI completeness tool

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1945]
This issue is tracking https://github.com/rust-diplomat/diplomat/issues/152

**Comment by robertbastian** [comment]
@sffc can this be closed?

**Comment by sffc** [comment]
@robertbastian Ideally I think I'd like to see the report card checked-in to source control and/or run as part of CI. The current status is that the tool exists but there aren't clear instructions on how to use it.
