### ISSUE TITLE
Discuss stability versioning of utils crates

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1954]
When we move `icu` to 1.0, do we also need to do it for utils?

- `icu_provider` currently re-exports `yoke`; we could stop doing that if necessary
- A lot of public fields have ZeroVecs inside; is this OK if ZeroVec is not API-stable?
- There's a difference between API stability and data format stability

CC @Manishearth @robertbastian

**Comment by Manishearth** [comment]
In general Rust is more lax about transitive dependency stability; I think we should _largely_ consider the zerovec format stable, but I personally do not think util stability is something we have the capacity to take on right now, and would prefer to do it at an appropriate pace for each util.

**Comment by sffc** [comment]
Conclusion: doc-hidden the yoke re-export. Everything else is fine.

LGTM: @Manishearth @robertbastian

**Comment by sffc** [comment]
@Manishearth to ensure that the code is consistent with the decision above
