### ISSUE TITLE
FixedDecimal: Odd that pad_left and truncate_left are off by 1

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1958]
[pad_left](https://unicode-org.github.io/icu4x-docs/doc/fixed_decimal/decimal/struct.FixedDecimal.html#method.pad_left) takes a `u16` number of digits, but [truncate_left](https://unicode-org.github.io/icu4x-docs/doc/fixed_decimal/decimal/struct.FixedDecimal.html#method.truncate_left) takes an `i16` magnitude. This makes some sense but is confusing since the two functions are often called one after the other.

What do you think we should do?

- [ ] @robertbastian 
- [ ] @Manishearth 
- [ ] @dminor 
- [ ] @younies

**Comment by Manishearth** [comment]
`truncate_left_to`?

**Comment by sffc** [comment]
Yeah, so some functions are deltas, some are absolute magnitudes, and others are absolute numbers of digits.

In this case, `pad_left` takes an absolute number of digits, and `truncate_left` takes an absolute magnitude. `multiply_pow10` takes a delta.
