### ISSUE TITLE
Additional FFI APIs in Bidi

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1960]
Followups from https://github.com/unicode-org/icu4x/issues/1735:

 - Level APIs should be at the top level on ICU4XBidiInfo
 - Do we need the ability to pass in a default level to ICU4XBidiInfo?
 - We probably want whole-text APIs that don't operate on paragraphs. What shoudl they look like?

Happy to write these, but would like input on @sffc on Skia's needs for the second two bullet points

**Comment by Manishearth** [comment]
cc @younies 

happy to mentor the addition of such APIs too, once the classes are defined it's quite easy to add and remove diplomat methods

**Comment by sffc** [comment]
Skia's code is here: https://skia.googlesource.com/skia/+/refs/heads/main/modules/skunicode/src/SkUnicode_icu.cpp

Key call sites:

- `sk_ubidi_setPara(bidi.get(), (const UChar*)utf16, utf16Units, bidiLevel, nullptr, &status);`
- `sk_ubidi_reorderVisual(runLevels, levelsCount, logicalFromVisual);`
- `sk_ubidi_getLevelAt(fBidi.get(), pos);`
- `sk_ubidi_getLength(bidi.get());`
- `sk_ubidi_getDirection(bidi.get())`

Note that these functions are all called on the top-level UBidi type, which is equivalent to BidiInfo in Rust.

**Comment by Manishearth** [comment]
> * `sk_ubidi_reorderVisual(runLevels, levelsCount, logicalFromVisual);`

Looking at this closer and I'm not convinced that unicode-bidi has this functionality already. Specifically, unicode-bidi has the ability to [reorder a line for a single paragraph and return a string](https://docs.rs/unicode-bidi/latest/unicode_bidi/struct.BidiInfo.html#method.reorder_line), and it has the ability to return a level array per character (or byte), but I don't see anything about constructing reordering index maps. I figure the crate has the code for this, just not the APIs.

@younies or @sffc, can you please check? I'm happy to make FFI wrappers but I'd rather not get into the weeds of figuring out implementation stuff. it's also possible that Skia's needs can be satisfied with the existing unicode-bidi APIs just used differently.

**Comment by younies** [comment]
@Manishearth , we can have a quick meeting to discuss those cases.

**Comment by Manishearth** [comment]
In that case I think the main thing remaining is this part:

> and it has the ability to return a level array per character (or byte), but I don't see anything about constructing reordering index maps.

Would you be able to add these APIs to unicode-bidi?

**Comment by sffc** [comment]
> **For `sk_ubidi_reorderVisual(runLevels, levelsCount, logicalFromVisual);`** while our discussion, we decided for now to use the `reorder` function on a paragraph instead of using `reorder` on just the levels and the count. Till now, I am not sure why Skia uses this API. we can sync offline though.

I don't understand this. Skia uses the `ubidi_reorderVisual` function. What are you proposing?

1. Add the function to unicode-bidi and icu4x
2. Change Skia so that it doesn't need to use that function any more

**Comment by younies** [comment]
> > **For `sk_ubidi_reorderVisual(runLevels, levelsCount, logicalFromVisual);`** while our discussion, we decided for now to use the `reorder` function on a paragraph instead of using `reorder` on just the levels and the count. Till now, I am not sure why Skia uses this API. we can sync offline though.
> 
> I don't understand this. Skia uses the `ubidi_reorderVisual` function. What are you proposing?
> 
> 1. Add the function to unicode-bidi and icu4x
> 2. Change Skia so that it doesn't need to use that function any more

No.2, change Skia. This function just took the levels and the level count which already in the `ParagraphInfo`, why do they need to extract those info from the `ParagraphInfo` and feed it to the `reorder` function instead of using it directly from `ParagraphInfo`

**Comment by younies** [comment]
@Manishearth , the function that returns the level for a certain character position is here:
```
    pub fn level_at(&self, pos: usize) -> Level {
        let actual_position = self.para.range.start + pos;
        self.info.levels[actual_position]
    }
```

The input is the position of the character not the character itself.

**Comment by Manishearth** [comment]
> The input is the position of the character not the character itself.

Yes, that's how it works in ICU, no?

**Comment by younies** [comment]
> > The input is the position of the character not the character itself.
> 
> Yes, that's how it works in ICU, no?

Yes, you can see the Skia usage in the document
```
sk_ubidi_getLevelAt(bidi.get(), position)
```

**Comment by Manishearth** [comment]
Right, that's what we do in the code too

**Comment by younies** [comment]
@sffc and @Manishearth , after trying to fix the skia code (by following this link: https://skia.org/docs/dev/contrib/submit/), I found two things:

1. For this function `ubidi_reorderVisual`, Skia uses it to have a big array that maps from `visual order` --> `logical order` for all the text. This means, that if they want to use our `reorder` function, they need to keep another array for the reordered text. (I really do not understand why the users need to have a mapper array instead of just a copy of the text in the correct order, but this we can discuss it with them or I can go ahead and implement `sk_ubidi_reorderVisual` function).
2. How to import the C++ headers from ICU4X?

**Comment by Manishearth** [comment]
Yeah, that's what I was referring to as "index maps" earlier.

As for the C++ headers, they're all in ffi/diplomat/cpp/include.

**Comment by sffc** [comment]
Thought: since the `ubidi_reorderVisual` function is stateless (requires no data), and it is only about a dozen lines long, we could _just implement the function in Skia_ in the ICU4X wrapper and not worry about crossing over FFI for it.

**Comment by Manishearth** [comment]
@sffc we still need some kind of intermediate API exposed from unicode_bidi for this, yes? any idea what it should look like?

**Comment by sffc** [comment]
> @sffc we still need some kind of intermediate API exposed from unicode_bidi for this, yes? any idea what it should look like?

What I mean is that this particular function is not too terribly large, and what it does is not really a deep part of the bidi algorithm, so we can basically copy the code out of ICU (or cleanroom it if necessary) into Skia C++

**Comment by Manishearth** [comment]
ah, i see. wouldn't that involve querying the bidi data over ffi in a loop, though? might have perf issues.

**Comment by Manishearth** [comment]
Right, but we still need lower level APIs that produce those level maps, yes?

**Comment by Manishearth** [comment]
Though it's possible that's already exposed by unicode-bidi by virtue of most fields being public

**Comment by sffc** [comment]
It's none of my business how Skia gets the level maps; they must have code somewhere that generates them. Maybe they come from Harfbuzz or elsewhere.

**Comment by Manishearth** [comment]
Ah, I imagined that they got it from ubidi apis

**Comment by younies** [comment]
After merging this PR: https://github.com/servo/unicode-bidi/pull/80, we can close this issue.

**Comment by sffc** [comment]
No, this issue is not done until we also expose `reorder_visual` in the FFI. That is literally the title of the issue :)

**Comment by Manishearth** [comment]
Ah, I was under the impression Younies had done that too (from his comment) and I just hadn't seen the PR. Should have looked closer at the PR link!

**Comment by sffc** [comment]
Turns out we don't actually need reorderVisual to support the client
