### ISSUE TITLE
Ensure that the provider performs correct Norwegian macrolanguage fallback

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#1963]
Ensure that requesting the collation for `nn` or `nb` loads the collation for `no`. (Also check `nn-NO` and `nb-NO` to see that ignoring more specific but irrelevant tags works in the context of macrolanguage fallback.)

**Comment by hsivonen** [comment]
CC @sffc

**Comment by hsivonen** [comment]
The macrolanguage fallback isn't in CLDR's collation files but assumes knowledge of the `Macrolanguage:` field in [the language subtag registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry).

**Comment by hsivonen** [comment]
There are other macrolanguage relationships in the language subtag registry that fall back to languages with non-root collations, particularly `ar` and `sq`. OTOH, the relationship between Serbian, Bosnian, and Croatian collations is handled by a combination of imports and aliases in CLDR.

**Comment by sffc** [comment]
The `nn`/`nb`/`no` mappings are in the CLDR parent locales:

- https://github.com/unicode-org/icu4x/blob/main/provider/testdata/data/cldr/cldr-core/supplemental/parentLocales.json

So this should work by default (as soon as the rest of #1109 is fully implemented). I will add a test specific for collator and then close this issue.
