### ISSUE TITLE
Ensure that the provider performs correct alias mapping for Traditional Chinese locales

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#1964]
Ensure that if a specific (and existing) collation hasn't been specified with `-u-co-`, the following map to `zh-u-co-stroke`:
 * `zh-Hant` regardless of region.
 * `zh` without `Hans` but with any of `HK`, `MO`, `TW`.
 * `yue` without either `Hans` or `CN`.

**Comment by hsivonen** [comment]
CC @sffc

**Comment by hsivonen** [comment]
For clarity: CLDR maps `yue-CN` and `yue-Hans` to `zh-Hans`, i.e. `zh-u-co-pinyin`.

**Comment by sffc** [comment]
There is a list of collation-specific aliases/parents in the LDML-to-ICU converter:

https://github.com/unicode-org/icu/blob/0266970e977b9e2488dfbf788cc280be3a0338ca/tools/cldr/cldr-to-icu/build-icu-data.xml#L263

Obviously, that list isn't making it into ICU4X.

I chatted with @markusicu about this today. He says that it may make sense to introduce a "processing" mode to the locale fallback engine. This mode can be used for both collator and break iterator.

I need to verify whether the set of ICU-specific overrides should apply uniformly to both collator data and segmenter data.

**Comment by sffc** [comment]
I still need to implement the actual zigzag fallback, but this can be done in the Collation fallback mode.

**Comment by sffc** [comment]
Upstream issue involving the ICU-specific fallback aliases: https://unicode-org.atlassian.net/browse/CLDR-16253

**Comment by sffc** [comment]
See some more recent discussion in #3867

**Comment by sffc** [comment]
This might be fixed with #5743 but we should add a test for it.

**Comment by robertbastian** [comment]
> I'll add a test for it.

Did this happen?
