### ISSUE TITLE
Change CharULE to be 3 bytes

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1970]
Currently, CharULE is 4 bytes. We should make it 3 bytes instead.

Part of #1968

**Comment by pandusonu2** [comment]
@Manishearth Just to clarify as we had discussed,

CharULE should be changed from `[u8, 4]` -> `u32` and the `chunk[3]` should be 0 during the `validate_byte_slice()`

**Comment by Manishearth** [comment]
Yes, correct.
