### ISSUE TITLE
Make multiply_pow10 be infallible

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1985]
It's annoying that `FixedDecimal::multiply_pow10` returns a `Result`, because clients have no reasonable way to deal with the result.

I would like to propose that we handle overflows in the same way that we decided to dealing with them in rounding: drop digits that overflow on one side or the other. For example, if `multiply_pow10` causes digits to slip past the maximum or minimum magnitude, then we just drop those digits. We can document this behavior.

The maximum magnitude is `i16::MAX`, or about 32000, and the minimum is -32000, so this is not a case that comes up in normal usage of FixedDecimal. Also, these bounds exceed the bounds required by ECMAScript implementations.

OK?

- [x] @Manishearth 
- [x] @younies

**Comment by Manishearth** [comment]
wfm

**Comment by younies** [comment]
that is make sense and will make our life and the users easier, because we do not need to check the returned error each time  we use those functions.

**Comment by sffc** [comment]
@younies Can you get the PR for this sent out this week?

**Comment by younies** [comment]
@sffc , yes, I am working on it
