### ISSUE TITLE
0.6.0: Examples needed for using providers, and their related structs

### ISSUE THREAD

**Issue by rizzen-yazston** [unicode-org/icu4x#1993]
For version 0.4.0 I managed to figure out how to pass the provider to one of my own struct methods, after sifting through icu source code. In the function calls to various property methods are called such as sets::get_pattern_syntax( provider ) and sets::get_pattern_white_space( provider ); and storing the payloads within the struct for later multiple uses.

With 0.6.0 I am failing miserable to figure out the data type of the provider, seems the API had drastic changes between 0.4.0 and 0.6.0.

Are there any examples on how to pass the provider object to a user function?

What I have figured out that the new struct for 0.6.0 is ResourceProvider, while 0.4.0 used DataProvider.

**Comment by sffc** [comment]
The new `ResourceProvider` API is centered around which ResourceKey you want to load. Every key is associated with a ResourceMarker. For example, if you want to load cardinal plural rules, your bound should be `ResourceProvider<CardinalV1Marker>`.

We are still changing the API in advance of the 1.0 release this summer; it will stop changing for a while once we reach that milestone.

**Comment by sffc** [comment]
If you want to select multiple keys, it's most efficient to do a multi-bound such as

```
P: ResourceProvider<Key1Marker> + ResourceProvider<Key2Marker> + ResourceProvider<Key3Marker> + ...
```

If the keys are all the same type, you may be able to use `DynProvider`, which is closest to the old `DataProvider`. If you replace `DataProvider` with `DynProvider` in your 0.4 code, it might "just work". However, leveraging `ResourceProvider` is recommended, as it is most compatible with the DataBake provider, upcoming in 1.0.
