### ISSUE TITLE
Rename ResourceOptions to ResourceLocale/DataLocale

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1995]
I've never been super happy with the name "resource options". It occurred to me that now that we've settled on a locale-like data model, maybe we should rename it to ResourceLocale or maybe DataLocale.

This would make the type hierarchy look like:

```rust
// Public fields
#[allow(clippy::exhaustive_structs)] // this type is stable
pub struct DataRequest {
    pub locale: DataLocale,
    pub metadata: DataRequestMetadata,
}

// Public fields
#[non_exhaustive]
pub struct DataRequestMetadata { ... }

// Private fields
pub struct DataLocale {
    langid: LanguageIdentifier,
    keywords: unicode_ext::Keywords,
}
```

All of the existing conversions would still work: you can convert a Locale to a DataLocale and back.

Needs approval from:

- [x] @Manishearth 
- [ ] @zbraniecki

**Comment by Manishearth** [comment]
i like this

**Comment by robertbastian** [comment]
Is the `Locale` trait in scope for v1?

`ResourceOptions` is becoming very similar to `Locale`, especially after #2036 (which I knoww is still in draft, but the general direction seems clear). Maybe we should move it into the `locid` crate, with a data-provider-independent name like `LightLocale`.

That said, why are we not using `Locale` in `DataRequest` again? `ULE` is solved (we have `strict_cmp`), so the only thing we seem to gain is that the runtime representation is smaller on the stack (it omits some fields that `Locale` has)[^1]. However we seem to need to duplicate a lot of the logic from `Locale` on this type, which increases code size and maintenance. Also with `ResourceOptions` being a public field, why introduce another type in the API when we could just use `Locale`?

[^1]: Locale is 184 stack bytes, which is quite big. Maybe providing a `LightLocale` that puts more optional things on the heap is not a bad idea anyway?

**Comment by robertbastian** [comment]
I see. In that case I agree with the renaming, but I don't like it being in the API. Can we use `From<LanguageIdentifier>`/`From<Locale>`s for `DataRequest` (and vice versa either with `From` or getters) without exposing this type? If it's a performance optimisation I don't think it should be public.

**Comment by robertbastian** [comment]
Ah I see you also proposed something like this in #2032

**Comment by sffc** [comment]
`ResourceOptions`/`DataLocale` is in the type signature of `ResourceProvider`/`DataProvider`, so although the type itself can't really be private, we can make the internals be private, which is what I did in #1750. All of the APIs on ResourceOptions keep the internals hidden, by design:

https://unicode-org.github.io/icu4x-docs/doc/icu_provider/prelude/struct.ResourceOptions.html

**Comment by robertbastian** [comment]
It's not though? `DataRequest` is.

**Comment by sffc** [comment]
Fair point. Let's wait on the resolution to #1833 first. If it's possible to make ResourceOptions a private field of DataRequest, then that would resolve this issue

**Comment by robertbastian** [comment]
Is this actually blocked? #1833 doesn't do anything with `ResourceOptions`, it merges with `Locale`s only.

**Comment by sffc** [comment]
I'm awaiting a resolution to https://github.com/unicode-org/icu4x/issues/419#issuecomment-1174532077.
