### ISSUE TITLE
Apple builds fail sporadically

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#201]
Builds on macOS sporadically fail with variants of the following error message:

```
error[E0463]: can't find crate for `serde_derive` which `serde` depends on
 --> components/data-provider/src/structs/decimal.rs:2:5
  |
2 | use serde::{Deserialize, Serialize};
  |     ^^^^^ can't find crate

error: aborting due to previous error
```

Sometimes this happens in the locale crate, and sometimes in data-provider.

Example: https://github.com/unicode-org/icu4x/pull/198/checks?check_run_id=957698689

@echeran

**Comment by sffc** [comment]
Copying comment here from #198:

> The macOS test passed at least once in this PR:
>
> https://github.com/unicode-org/icu4x/actions/runs/198964202
>
> The code version on that passing run (b20611b) is identical to the current head of this branch (ed79fef):
>
> https://github.com/unicode-org/icu4x/compare/b20611b..ed79fef

**Comment by echeran** [comment]
I had already tried that exact same experiment (disabling caching build but keeping the other 2 caching steps), but the first run was a failed run.  I also tried turning off caching of the build and caching of the index (the list of known crates), leaving the caching of the registry (list of known crate download sites), and that failed to my surprise, too.
