### ISSUE TITLE
error[E0425]: cannot find function `is_num_or_string` in module `super::serde_helpers`

### ISSUE THREAD

**Issue by makotokato** [unicode-org/icu4x#2016]
When building icu4x with the latest (a6377a6b7c2f264663427182265c5b154cf1b35f) on Windows 11 workstation, build is failure due to the following error. I don't know whether this issue depends on my environment only or all Windows workstation.

```
   Compiling litemap v0.4.0 (C:\Development\icu4x\utils\litemap
...
error: expected item, found `..`
 --> utils\litemap\src\serde_helpers.rs:1:1
  |
1 | ../../zerovec/src/map/serde_helpers.rs
  | ^^ expected item

error[E0425]: cannot find function `is_num_or_string` in module `super::serde_helpers`
  --> utils\litemap\src\serde.rs:31:43
   |
31 |                 if !super::serde_helpers::is_num_or_string(k) {
   |                                           ^^^^^^^^^^^^^^^^ not found in `super::serde_helpers`

For more information about this error, try `rustc --explain E0425`.
   Compiling toml v0.5.8
error: could not compile `litemap` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by makotokato** [comment]
`utils/litemap/src/serde_helpers.rs` seems to be symbolic link, but git for Windows and Windows cannot resolve it.

**Comment by sffc** [comment]
Please build and test with `--all-features`.

**Comment by sffc** [comment]
CC @eggrobin. Do you know the solution to this?

**Comment by eggrobin** [comment]
> Do you know the solution to this?

Ah yes, this happened to me two days ago.

`git config --edit`, under `[core]` set `symlinks = true`, and in Windows developer settings, enable Developer Mode.

Then `git checkout -- utils/litemap/src/serde_helpers.rs` or something along these lines.

See https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/59761201#59761201.

**Comment by Manishearth** [comment]
We should add this to CONTRIBUTING.md

(or perhaps stop using the symlink)

**Comment by Manishearth** [comment]
I don't think so? I think we should just dupe the file and stick a comment on it

**Comment by robertbastian** [comment]
Can we not check in a `.gitconfig` with this flag?

**Comment by eggrobin** [comment]
We’d still need to tell Windows users to set the appropriate system setting.
