### ISSUE TITLE
`ZeroVec::from_slice_or_alloc` requires implementation of `EqULE` which shouldn't be needed as the method 

### ISSUE THREAD

**Issue by pandusonu2** [unicode-org/icu4x#2018]
`from_slice_or_allow` trait shouldn't require EqULE, as only slice method requires that implementation, https://github.com/unicode-org/icu4x/blob/main/utils/zerovec/src/zerovec/mod.rs#L574

**Comment by sffc** [comment]
`EqULE`'s sole purpose of existing is so that `from_slice_or_alloc` can work.

I want to move away from `EqULE` and `from_slice_or_alloc` in favor of const-constructing a ZeroSlice (#1935).

**Comment by Manishearth** [comment]
I'm not 100% sure if the const stuff would cover all use cases of `from_slice_or_alloc` fwiw. It does for our examples, but our examples don't cover everything

**Comment by sffc** [comment]
The use case for which `EqULE`/`from_slice_or_alloc` was introduced was having more readable, aligned data in code files, converted to ULE for runtime use. Const functions in #1935 solve this use case.

Last I looked around the code base at `from_slice_or_alloc` call sites, they mostly fit into this bucket. Any call sites that are for other cases may have separate solutions that are superior.
