### ISSUE TITLE
Strip examples from compiled plural rules

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#203]
We can save space by removing the examples from the PluralRules strings.

**Comment by zbraniecki** [comment]
@sffc how do you currently generate ICU4X JSON? Where should I plug the code that strips examples?

**Comment by sffc** [comment]
Put your cleanup code here:

https://github.com/unicode-org/icu4x/blob/1f14b846e6163bac70ce6defa024bbe5d14ae8c8/components/cldr-json-data-provider/src/transform/plurals.rs#L127

The ICU4X JSON is generated using the binary tool of fs-data-provider. Run the command to see the docs. I want to automate this and save the artifacts somewhere automatically (see #227 )
