### ISSUE TITLE
Improve performance and code size of ResourceOptions::strict_cmp

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2032]
The function `ResourceOptions::strict_cmp` is in the hot path for data loading, so it's important that we optimize it.

Currently, the implementation looks like

```rust
impl ResourceOptions {
    pub fn strict_cmp(&self, other: &[u8]) -> Ordering {
        if self.keywords.is_empty() {
            self.langid.strict_cmp(other)
        } else {
            // TODO: Avoid the allocation
            self.write_to_string().as_bytes().cmp(other)
        }
    }
}
```

We want to avoid the `write_to_string()` if possible.

Some potential solutions:

1. Make all of the `for_each_subtag_str` functions in the `icu_locid` crate public (so that ResourceOptions can see them) and use them to write a new `strict_cmp` impl here
    - Pro: Optimal performance and code size
    - Con: There's been pushback on making these functions public
2. Rename `ResourceOptions` to `DataLocale` and move it into the `icu_locid` crate
    - Pro: We don't need to make the functions public
    - Con: Disruptive change; puts data loading logic into a component crate
3. Expose a `strict_cmp` function on `extensions::unicode::Keywords` and leverage it to write `strict_cmp` on ResourceOptions
    - Pro: No undesirable public APIs in `icu_locid`
    - Con: A bit more complicated and likely suboptimal comparison function, but better than what we have now

Thoughts?

- [ ] @zbraniecki 
- [x] @Manishearth

**Comment by Manishearth** [comment]
I kinda prefer option (1), but I don't have strong objections to the others. It seems like having an API be public is not a huge cost and we can mitigate problems with careful documentation/etc.

**Comment by zbraniecki** [comment]
Can you explain why you think Option (3) leads to suboptimal comparison function?

**Comment by sffc** [comment]
> Can you explain why you think Option (3) leads to suboptimal comparison function?

The whole implementation for a comparison function in Option 1 is:

1. Split the string by the subtag delimiter (`-`)
2. Compare each subtag with the subtag iterator from the structured object
3. Upon finding the first non-equal subtag, return the ordering
4. If all subtags are equal but the iterators are different lengths, return the appropriate ordering
5. Return equality

It's easy to implement and reason about.

For Option 3, the implementation would be more like

1. Split the string into the language identifier component and the Unicode keywords component
    - How do we do this? I guess look for `-u-`?
2. Call `LanguageIdentifier::strict_cmp`. If not equal, return the result.
3. Call `Keywords::strict_cmp`. If not equal, return the result.
4. Return equality.

I haven't tested this but maybe it works fine. I guess the main hitch is that I don't see a way to implement it based on only `strict_cmp` functions without looking for the `-u-` ahead of time, which is one extra step.

**Comment by zbraniecki** [comment]
I know it's not ideal, but could you do Option 4:

1. Split by `-` into iterator
2. Pass the iterator to LanguageIdentifier comparison on iterator of `&str`.
3. When a tag doesn't match, that iterator returns the stateful iterator + last retrieved subtag
4. If that subtag is `u` then you switch to Extensions and pass the iterator there

?

**Comment by sffc** [comment]
Option 4 would involve adding an API such as the following, right?

```rust
struct LanguageIdentifier {
    pub fn strict_cmp_iter<I>(&self, subtags: I) -> Result<I, Ordering> where I: Iterator<Item = &str>;
}
```

It's workable. Do you prefer exposing this API over `for_each_subtag_str`?

**Comment by zbraniecki** [comment]
I think it would be:

```rust
struct LanguageIdentifier {
    pub fn strict_cmp_iter<I>(&self, subtags: I) -> Result<(I, &str), Ordering> where I: Iterator<Item = &str>;
}
```

otherwise you'll need the Peekable overhead.

What do you think?

**Comment by sffc** [comment]
Option 4: https://github.com/unicode-org/icu4x/pull/2111
