### ISSUE TITLE
Add lightweight timestamp-to-ISO conversion function

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2034]
For time zone calculations, we need to store local datetimes (also known as civil datetimes or plain datetimes) for metazone cutoffs in the data provider.

If we store them as an ISO string, like "1988-04-03 04:01", we need either 12 or 16 bytes. It would be more efficient to store them as a "local timestamp", or the duration between the local datetime and 1970-01-01T00:00, most likely measured in minutes and stored in a `u32`. (Note: we should be very careful on using the term "local timestamp", because that can be really confusing terminology.)

I think this conversion function could go in `icu_calendar`.

**Comment by sffc** [comment]
CC @Manishearth

**Comment by sffc** [comment]
Note: I think the desired output for the string-to-integer function is a signed number of minutes since Januay 1, 1970 in local time.

**Comment by sffc** [comment]
@samchen61661 Is this complete?

**Comment by samchen61661** [comment]
> @samchen61661 Is this complete?

Yeah, marked it as closed
