### ISSUE TITLE
Upgrade to postcard 1.0.0-alpha introduces code size regression on x86

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2040]
There appears to be a code size regression across https://github.com/unicode-org/icu4x/commit/c2ae85f86e8faf29cd47cd8044e493828b50afcc:

```
-rwxr-xr-x 1 runner docker    43952 Jun  9 17:37 optim4.elf
-rwxr-xr-x 1 runner docker    32568 Jun  9 17:37 optim5.elf
```

to

```
-rwxr-xr-x 1 runner docker    45232 Jun 10 02:52 optim4.elf
-rwxr-xr-x 1 runner docker    33944 Jun 10 02:52 optim5.elf
```

In order to reproduce, build the project here, with `make`:

https://github.com/unicode-org/icu4x/tree/main/ffi/diplomat/c/examples/fixeddecimal_tiny

You may need to install specific toolchains and tools as explained in CONTRIBUTING.md:

https://github.com/unicode-org/icu4x/blob/main/CONTRIBUTING.md

The main thing is that you need the `nightly-2022-04-05` toolchain and `clang-14` with `lld-14`.

**Comment by Manishearth** [comment]
cc @jamesmunns

(for background; these tests are engineered specifically to measure codesize impact when building in a way that minimizes codesize)

**Comment by jamesmunns** [comment]
So, for context, `postcard` v1.0 added additional `#[inline]` (but NOT `#[inline(always)]` statements across the serialization path - so I am not surprised that there was a slight regression in code size. This decision was made as it generally lead to a large performance gain in standard `release` mode, e.g. `-O3`.

As far as I can tell, the relevant staticlib crate, https://github.com/unicode-org/icu4x/blob/main/ffi/capi_staticlib/Cargo.toml, is compiled with the default release profile, which uses the `-O3` release setting, which is pretty inline-happy.

If the ABSOLUTE smallest build is required here, it might be worth setting/overriding that profile to use `opt-level = 's'` or `opt-level = 'z'`, which I would expect to be less inclined to inline the additional items.

Depending on how much of this is a "deal breaker", I could add a feature that makes those inlines togglable, e.g. `#[cfg_attr(not(feature = "no-inlines"), inline)]`, but I'd generally prefer not to, as they currently should respect compilation/optimizations settings.

**Comment by jamesmunns** [comment]
It's also possible to specifically override ONLY postcard in some/all configurations using specific dependency profile overrides if we want to confirm this does make up the difference in the regression.

Happy to troubleshoot or diagnose more fully, but this doesn't seem *entirely* surprising to me, given the changes. Again, happy to make tweaks/tunable features for y'all if it would help.

**Comment by sffc** [comment]
Good idea! Our code-size build does a whole lot to reduce size (LTO, panic=abort, codegen-units=1, ...), but not `opt-level = 's'`. I opened a PR to add that and it brings the sizes down to

```
-rwxr-xr-x 1 runner docker    43856 Jun 10 19:02 optim4.elf
-rwxr-xr-x 1 runner docker    27480 Jun 10 19:02 optim5.elf
```

I'll need to check on what the numbers would have been with `opt-level = 's'` before the postcard upgrade.

**Comment by sffc** [comment]
Here is `opt-level = 's'` with postcard 0.7:

```
-rwxr-xr-x 1 runner docker    44560 Jun 10 21:55 optim4.elf
-rw-r--r-- 1 runner docker     9576 Jun 10 21:54 optim4.o
-rwxr-xr-x 1 runner docker    27784 Jun 10 21:55 optim5.elf
```

So this looks good! With `opt-level = 's'` we actually get a small size improvement.
