### ISSUE TITLE
Design and implement unit testing for crabbake/databake

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2055]
Currently we don't check that the tokenstream generated by a Bakeable impl actually creates code that compiles in a const context. In #2054, I work around this by carrying the baked code side-by-side in two forms: a string and actual code, but this is not an ideal solution.

A better solution would be to put the baked data in the tests directory, like `tests/databake_modules/foo_sample.rs`, which is both compiled and included as bytes in the test driver, such as:

```rust
// tests/databake_modules/foo_sample.rs

pub const FOO_SAMPLE: mycrate::Foo = mycrate::Foo {
    hello: "world"
};
```

```rust
// tests/databake.rs

use super::databake_modules::foo_sample;

const FOO_SAMPLE_BYTES: &'static [u8] = include_bytes!("databake_modules/foo_sample.rs");

#[test]
fn test_equal() {
    // test that foo_sample::FOO_SAMPLE is equal to expected
}

#[test]
fn test_baked() {
    // test that FOO_SAMPLE_BYTES is equal to expected
}
```

In `test_baked`, it will be necessary to strip off some tokens from the beginning and the end. I think everything before the first `=` and the last `;` can be removed, and everything else can be tested.

It may be necessary to disable rustfmt on the sample file if rustfmt wants to add extra tokens that aren't in the databake output.

OK?

- [ ] @robertbastian 
- [ ] @Manishearth

**Comment by sffc** [comment]
@robertbastian came up with a much simpler solution in #2063 that uses a macro to pass the same code to both the compiler and `quote!`.

**Comment by sffc** [comment]
> In #2063 I'm not testing whether the returned expression is const-constructible.

Good point. Can we fix that by coercing the baked variable into a const context? I think saving the result of `$crate::Bakeable::bake` into a local `const` should work.

> I don't think we _need_ to require this in the API of `Bake`.

It's a good point that Bakeable doesn't need to _require_ const-constructible in the general case, i.e. for clients who don't care as much about preventing heap allocations as we do. I guess one could see Bakeable output being const-constructible as a feature of that particular impl. Not all impls need to do that, but ones that do should not regress without a breaking change.

If desired, the `test_bake` macro could have two modes, one that checks for const-constructible and one that doesn't.

> We don't even really need this for `BakedDataProvider`, instead of statics we could just construct the structs in `load_payload`.

True.

Const construction does have benefits:

1. Compels the use of zero-copy, except with workarounds like breaking the contract of a `ZeroFrom` impl, which is an explicit choice; overall it is much less prone to error
2. Less `unsafe` code, since we can write const constructors that are safe (although we currently still need *some* unsafe code since const functions can't do everything we need yet like calling trait functions to validate a ZeroVec)
3. I _suspect_ that the compiler performs more optimizations when dealing with static objects

**Comment by robertbastian** [comment]
Yes we should test that our structs are const-Bake, however I don't fully agree with your reasoning.

> Compels the use of zero-copy, except with workarounds like breaking the contract of a ZeroFrom impl, which is an explicit choice; overall it is much less prone to error

Zero-copy can be done without const, and const will at some point be able to do allocation, so the concepts of zero-copy and const are not interchangeable.

> Less unsafe code, since we can write const constructors that are safe (although we currently still need some unsafe code since const functions can't do everything we need yet like calling trait functions to validate a ZeroVec)

Isn't it the other way around? Const constructors need a lot more `unsafe` because not enough functionality is available in const.

> We can auto-derive ZeroFrom since the static form of the struct is the same as the runtime form

This is again a zero-copy thing, not a const thing.

> I suspect that the compiler performs more optimizations when dealing with static objects

I suspect that as well but who knows. Maybe we actually get fewer optimizations because compiler doesn't inline both the static and the `zero_from` call.

The const-ness of the `bake` output should be dictated by the requirements of the consumer, not by the trait itself. Should we introduce a marker trait `ConstBake`? Testing this is a bit annoying without https://github.com/rust-lang/rust/issues/76001 though as we need to pass the type to create a const.

**Comment by sffc** [comment]
I don't have a strong opinion yet about whether `ConstBake` should be its own trait. I lean toward making it a promise that an impl of the trait states in its docs.

My justifications for `const` are based on what would be required for a zero-copy, non-const Bake impl that stores only raw strings and buffers in statics.

Elaborating on my four points from earlier:

1. For now I'm saying that `const` requires zero-copy because that's the current state of the world. However, based on the discussion I've seen around const alloc, it would essentially involve using a const allocator that "allocates" the memory at compile time, incurring no runtime cost. I'd have no problem if a Bake impl uses that feature if/when it lands. The actual zero-copying is performed in the `ZeroFrom` impl.
2. A non-const, non-unsafe implementation would require runtime validation, which is one of the motivating reasons behind databake's existence.
3. The auto-derived `ZeroFrom` impls make zero-copy easier and more automatic. If implementing a zero-copy, non-const Bake impl, we'd need a static-friendly data struct and a zero-copy constructor from that struct into the runtime struct, which seems a lot harder to scale than `ZeroFrom`.
4. We seem to agree on this point.

**Comment by sffc** [comment]
To-do items:

- [ ] Include the const test in the crate; make it work with the current Rust version
- [ ] Test all custom Bake impls in the ICU4X repo

Note: We discussed having a custom feature for the test macro, but decided the macro is small enough that it's not worth the extra complexity of feature-gating it.
