### ISSUE TITLE
Return an Error for the rounding modes

### ISSUE THREAD

**Issue by younies** [unicode-org/icu4x#2079]
Many rounding modes can cause a limit error, such as `ceil` and `expand` if the magnitude was equals to `i16::MAX`.

Therefore, the user should receive`Err::Limit` if this happened.

**Comment by sffc** [comment]
Actually, I proposed doing the opposite in https://github.com/unicode-org/icu4x/issues/1985. I think we should make more functions that return `Error::Limit` not return errors and just throw away out-of-bounds digits. I explain my reasoning in #1985.

**Comment by younies** [comment]
@sffc , okay, I agree with you, then, I will close this ticket.
