### ISSUE TITLE
BakedDataProvider should implement AnyProvider

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2088]
Stable APIs will require `AnyProvider`, and we should make sure `BakedDataProvider` supports it.

It is tempting to use `impl_dyn_provider!`, except that this requires an extra allocation, which happens in `UpcastDataPayload` here:

https://github.com/unicode-org/icu4x/blob/3736032598204a86e90273c34460160be5767b5c/provider/core/src/any.rs#L178

Instead, we should generate an impl of `AnyProvider` that uses [AnyPayload::from_static_ref](https://unicode-org.github.io/icu4x-docs/doc/icu_provider/any/struct.AnyPayload.html#method.from_static_ref), avoiding the allocation. This works automatically for all data structs that are const-constructible. We should be able to make it work for things like the skeleton provider by allowing the ZeroFrom impl to copy from a type that is not `M::Yokeable`.

CC @robertbastian

**Comment by robertbastian** [comment]
Can we do this after making skeletons zero-copy? I've spent the better part of a day trying to write the correct macro to use `from_static_ref` for everything except skeletons, and I haven't  had any success and it adds *a lot* of complexity. This is a performance thing, so we can do this in 1.1?

**Comment by sffc** [comment]
Skeletons are behind the experimental flag, yes? (If they aren't, they absolutely should be.) Could we implement AnyProvider only if the experimental flag is turned off?

Alternatively, I'm okay using `impl_dyn_provider!` for the time being (which should be an easy change) and making a follow-up for 1.1. What worries me though is that I don't think we have any solid committment to fix skeletons on the 1.1 timeframe, and I don't want to be semi-permanently crippled by this.

**Comment by sffc** [comment]
> No they're not. I don't think they should be as the allocating workaround is perfectly fine and I wouldn't want to make people pull in serde and ForkByKey just for skeletons.

We can support the databake provider for them, and just special-case remove them from the AnyProvider impl. We don't even really need to gate it on the experimental feature (although we should do that anyway as part of 1.0 cleanup); we just always exclude it from AnyProvider.

I would rather the pain point be "OMG, skeletons don't work with AnyProvider", because it's clearly skeletons' fault that they don't work. I want 1.0 to have a perfect AnyProvider for the vast majority of ICU4X that we've worked so hard over the last year to make work, and not held back by this one feature that is half-baked and doesn't conform to the style guide. It's okay to me if 1.0 is "here are features that work, and here are features that sort-of work but not always and you can contribute to the project to help fix them".

> Is this all that crippling though? Using impl_dyn_provider is as much zc as the serde providers with Any

It is worse because BlobDataProvider does not need to allocate memory. Remember that BlobDataProvider does not implement AnyProvider; it implements BufferProvider instead.

I designed `from_static_ref` specifically for this use case, and I really would rather not block it on something that we know is broken and for which we don't have a timeline for fixing.

**Comment by sffc** [comment]
Here's another option. We use `from_static_ref` for everything except skeletons, and `from_rc_struct` for skeletons. That might actually be the best.

**Comment by robertbastian** [comment]
> Here's another option. We use from_static_ref for everything except skeletons, and from_rc_payload for skeletons. That might actually be the best.

That's what I've been trying to do
