### ISSUE TITLE
Reconsider the name of FixedDecimal truncate_right

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2101]
We named it `truncate_right` because we had `truncate_left`. However, I think maybe it should just be `truncate`, since it is another choice of rounding mode along with `expand`, `floor`, etc.

Should we also rename `pad_right` to `pad`?

Looking for input from:

- [x] @younies

**Comment by sffc** [comment]
- @younies/@robertbastian - I think `truncate` as the normal one. The other one should have a different name, maybe `truncate_high`?
- @sffc - How about pad and strip?
- @younies - Maybe strip should call trim. Maybe pad should be called append_zeros.
- @sffc - Should we call them with left/right, high/low, upper/lower, ... ?
- @zbraniecki - The analogy in a string is like cutting letters or whitespace.
- @sffc - I like high/low.
- @zbraniecki - I think we should keep it parallel with string and use start/end.
- @markusicu - Should we consider round_toward_zero instead of truncate
- @sffc - The ECMAScript rounding mode is called trunc.
- @markusicu - I'd liek to be more clear about rounding modes versus string operations.
- @robertbastian - Note that Rust f64 has a https://doc.rust-lang.org/std/primitive.f64.html#method.trunc method.
- @zbraniecki - How about `shrink_to`
- @sffc - Maybe `cut_start`
- @robertbastian - `shrink` affects the capacity

Proposed:

- [NOT YET DECIDED] `cut_start` (currently truncate_left)
- `trunc` (currently truncate_right)
- `pad_start`
- `pad_end`
- `trim_start`
- `trim_end`

LGTM: @sffc, @markusicu, @younies,

**Comment by sffc** [comment]
More discussion on truncate_left:

- @robertbastian - limit_start? But that sounds like a mathematical operation
- @markusicu - I think cut_start is confusing, because the number value doesn't express what you want to have happen
- @robertbastian - It doesn't "cut 2 digits"; it "retains 2 digits"
- @younies - How aboud delete_start or delete_from_start, or chop_start
- @sffc - with_maximum_integer_digits because that's what it implements from the spec
- @younies - with_max_magnitude?
- @sffc - "magnitude" would be offset by 1.
- @markusicu - set_to_int_digits?
- @sffc - set_integer_digit_count?
- @younies - The function can affect both the integer and the fraction parts

**Comment by sffc** [comment]
I really don't want to make the function use a `magnitude` argument because it's very common to call both truncate_left and pad_left at the same time, resulting in call sites like

```rust
my_fixed_decimal.truncate_left(2);
my_fixed_decimal.pad_left(2);
```

There is such a call site in DateTimeFormatter. I would rather have an awkward name that uses the position-style argument than a better name that uses a magnitude-style argument.

**Comment by sffc** [comment]
Options for truncate_left renaming:

1. `truncate_start`
2. `cut_start`
3. `with_max_magnitude`
4. `chop_start`
5. `delete_from_start`
6. `set_to_int_digits`
7. `set_integer_digits_count`

Between @sffc, @Manishearth, and @nordzilla, we all ranked choice 2 (`cut_start`) as our first or second choice. I'm therefore going to mark that as the decision, unless anyone objects to it, in which case I'll send out a form for ranked choice voting.

**Comment by markusicu** [comment]
I really don't like misleading names. "cut_start(2)" *says* that it cuts 2 from the start, but the function really *keeps* the right-most 2 integer digits, cutting the rest, however many those are.

Of the options in the latest list, only 6 & 7 have their names match reasonably well what this does.

**Comment by sffc** [comment]
The problem with "set_integer_digits_count" is that the function is defined to work on both positive and negative powers of 10. For example, `"12.3456".parse::<FixedDecimal>().unwrap().set_integer_digits_count(-2)` should result in `0.0056`.

The other thing is just the parallelism with `pad_start`. I think it will be common to write

```rust
my_fixed_decimal.set_integer_digits_count(2);
my_fixed_decimal.pad_start(2);
```

and it seems fairly clean to instead write

```rust
my_fixed_decimal.cut_start(2);
my_fixed_decimal.pad_start(2);
```

**Comment by markusicu** [comment]
I actually think it is ok to say "set number of integer digits" and explain that a negative number zeroes out that many fraction digits (= digits before vs. after the decimal point). Much better than referring to "start" when you don't mean that at all.

**Comment by sffc** [comment]
Based on the ranked-choice voting, the least offensive option appears to be `with_max_position(self)` + `set_max_position(&mut self)`. So I will set that as the conclusion and this issue is now unblocked. @younies volunteered to make the changes.

To recap, we are renaming these 6 functions:

- `truncate_left` becomes `set_max_position`
- `truncate_right` becomes `trunc`
- `pad_left` becomes `pad_start`
- `pad_right` becomes `pad_end`
- `strip_left` becomes `trim_start`
- `strip_right` becomes `trim_end`

We are also renaming the moving versions of those functions:

- `truncated_left` becomes `with_max_position`
- `truncated_right` becomes `trunced`
- `padded_left` becomes `padded_start`
- `padded_right` becomes `padded_end`
- `stripped_left` becomes `trimmed_start`
- `stripped_right` becomes `trimmed_end`

**Comment by younies** [comment]
I want to add that we will it change also:

- `half_truncate_right` and `half_truncated_right` to `half_trunc` and `half_trunced`
