### ISSUE TITLE
Enable warn(missing_docs) for all component crates

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2109]
All ICU component crates should be fully documented. To track this, we should enable `warn(missing_docs)` as suggested in boilerplate.md.

Pre-existing sub-issues:

- https://github.com/unicode-org/icu4x/issues/1025
- https://github.com/unicode-org/icu4x/issues/1028
- https://github.com/unicode-org/icu4x/issues/1029

This issue does not track utils or experimental crates.

**Comment by echeran** [comment]
| component            | status             |
|----------------------|--------------------|
| calendar             | incomplete         |
| datetime             | incomplete         |
| decimal              | incomplete (#1025) |
| icu                  | incomplete         |
| list                 | incomplete         |
| locale_canonicalizer | done               |
| locid                | incomplete (#1028) |
| plurals              | in review (#2108)  |
| properties           | done               |
