### ISSUE TITLE
Consider using grapheme cluster breaker in dictionary segmenter

### ISSUE THREAD

**Issue by makotokato** [unicode-org/icu4x#2129]
Related to https://github.com/unicode-org/icu4x/pull/1897 and https://github.com/unicode-org/icu4x/issues/1531. After we move dictionary segmenter  to `DataProvider` and testdata, it is better to use GraphmeSegmenter in dictionary segmenter instead.

**Comment by sffc** [comment]
@makotokato Can you work on this, after the other 1.0 issues are done?

**Comment by sffc** [comment]
Segmenter is going to remain in alpha at ICU4X 1.0 so I'm moving this to 1.1
