### ISSUE TITLE
Remaining properties naming polishes

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#2141]
Carried over from https://github.com/unicode-org/icu4x/issues/1239

With https://github.com/unicode-org/icu4x/pull/2140 and https://github.com/unicode-org/icu4x/pull/2112, the _main_ icu_properties return values are all consistently named. We have `CodePoint[Set|Map]Data(Borrowed)?` as a naming scheme for the main APIs for interacting with this data. Stringy maps and sets can be supported in the future with `[Unicode|CodePoint]{Set|Map]Data(Borrowed)?`

So far, the data structs have not been renamed. They're currently called `UnicodePropertyV1` and `UnicodePropertyMapV1`, which isn't great. Note that these types are not _super_ important since users shouldn't be interfacing with them, but consistent naming woudl be nice.

@echeran suggested `Property[Unicode|CodePoint][Set|Map]V1`. I like having Property in the name there.

Also we have `UnicodeSet`. I don't think we need _as much_ consistency there: that's a specific backend and doesn't need to be named analogously to other backends, but we probably should name it `CodePointSet` or something (and rename the builder type and associated methods).

**Comment by sffc** [comment]
Renaming `UnicodeSet` to `CodePointSet` should be done at some point, either as a standalone PR or as part of the migration to `icu_collections`.

**Comment by andrewpollack** [comment]
For this, I'll create two PRs:

1. Renaming `UnicodePropertyV1 ` -> `PropertyUnicodeSetV1`, and `UnicodePropertyMapV1` -> `PropertyUnicodeMapV1`
2. Renaming `UnicodeSet` -> `CodePointSet`, and all related libraries. This will be done before the migration to `icu_collections`

**Comment by sffc** [comment]
@andrewpollack Is this complete?

**Comment by andrewpollack** [comment]
Completed by [#2198](https://github.com/unicode-org/icu4x/pull/2198)
