### ISSUE TITLE
Remove calendar template argument from TimeFormat

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#2153]
Currently `TimeFormat` takes a template argument to specify the `Calendar` but this is only strictly necessary for `DateFormat` and `DateTimeFormat`. Removing it requires a bit of care with the data import from `CLDR`, because the time data there is currently packaged per calendar.

Also, `TimeFormat` and `DateTimeFormat` share code for loading time data, but the locale used for `DateTimeFormat` will specify the calendar, so with this change, we'll need to add some code to fallback properly to a locale without calendar subtags.

**Comment by Manishearth** [comment]
We can also have DateTimeFormat strip out the calendar tag before passing it down to TimeFormat
