### ISSUE TITLE
Add optional root data for vertical fallback

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2174]
In #1494 we decided not to have a blanket `Default` requirement for data structs. However, this is still useful for data keys that are subject to vertical fallback, which was the primary use case of interest.

One way to do this would be to add an associated constant to `ResourceMarker` that looks like

```rust
pub trait ResourceMarker: DataMarker {
    const KEY: ResourceKey;
    const UND: Option<Self::Yokeable>;
}
```

It would be populated in the macro; something like

```rust
#[icu_provider::data_struct(
    marker(FooV1Marker, und = FooV1::const_default())
)]
```

The only time this would be used would be in the last step of LocaleFallbackIterator.

Needs input from:

- [ ] @robertbastian 
- [ ] @Manishearth

**Comment by robertbastian** [comment]
My concerns from #1494 still apply, I don't see a reason why we'd hardcode the `und` value if we want to be data driven. 

Wouldn't `LocaleFallbackIterator` already try loading `und` before it would fall back to `::UND`? I think that is the right behaviour, and IIUC we don't support generating data without `und` anyway.

The only use case I can see for this is if some fallback algorithm says 
* ...
* use `und`
* use some specific data

in which case we could hardcode the data like you're proposing, but it shouldn't be called `und` (and this seems to be component specific, so the constructors might be a better place for such data).

**Comment by sffc** [comment]
The use case I have in mind for this is that we may have many different data providers each equipped with vertical fallback, but not every data provider necesarilly ships `und` data. Further, clients may wish to to toggle `und` data on and off at runtime so that they can handle last-resort fallback differently. I think it would be useful to have an optional data provider middleware that populates `und` requests with hard-coded data without hitting the filesystem.

> and this seems to be component specific, so the constructors might be a better place for such data

I proposed associating it with the specific ResourceMarker, which is better than the `Default` solution which associated it with a data struct.

I see this squarely as a data provider concern, not a constructor concern. The constructor should propagate missing-resource errors.

**Comment by sffc** [comment]
@robertbastian You said in #1494 that

> The last resort fallback just results in incorrect behavior, especially if the structs don't contain the correct data, like for properties

My proposal here would be that only those structs that participate in vertical fallback (i.e., not properties or segmenter or normalizer) have a non-None default value.

**Comment by sffc** [comment]
This is a 1.0 blocker only in the sense that it changes the definition of `ResourceMarker`. However, if we agree on the design, we could add the associated constant now, and populate it later.

**Comment by robertbastian** [comment]
I also said 
> We'd be baking in data that could change across releases

---

> The use case I have in mind for this is that we may have many different data providers each equipped with vertical fallback, but not every data provider necesarilly ships und data. 

Multiple data providers for the same key with vertical fallback enabled? How would one use those?

> Further, clients may wish to to toggle und data on and off at runtime so that they can handle last-resort fallback differently.

This can be done in a concrete provider implementation.

> I think it would be useful to have an optional data provider middleware that populates und requests with hard-coded data without hitting the filesystem.

Such middleware should get its data from databake, not from use writing data into the ICU4X code. I don't want us to back ourselves into a corner by hardcoding this, and with databake we have the tools to insert `und` data at build time.

**Comment by sffc** [comment]
OK, I'm convinced. Clients who do dynamic data loading can databake only the `und` locale.
