### ISSUE TITLE
Make `AnyPayload` sync

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#2176]
Currently it wraps an `Rc`, it should use an `Arc` if the `sync` feature is enabled. 

This can probably reuse the `RcWrap` type from `data_provider.rs`, but we need to make it generic and plumb through additional methods like `downcast`.

**Comment by sffc** [comment]
Yes; we should use `RcWrap` in all public APIs in the icu_provider crate.

**Comment by snktd** [comment]
This is fixed now with https://github.com/unicode-org/icu4x/pull/2465. Can we close it?
