### ISSUE TITLE
Namespaces in C++

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2182]
Currently we have

```c
// ICU4XFixedDecimalFormat.h
#ifdef __cplusplus
extern "C" {
#endif

typedef struct ICU4XFixedDecimalFormat ICU4XFixedDecimalFormat;

#ifdef __cplusplus
}
#endif
```

and

```cpp
// ICU4XFixedDecimalFormat.hpp
namespace capi {
#include "ICU4XFixedDecimalFormat.h"
}

class ICU4XFixedDecimalFormat {
  // ...
}
```

I think this bad, because if someone includes both "ICU4XFixedDecimalFormat.h" and "ICU4XFixedDecimalFormat.hpp" on their own (without wrapping the `#include` in `namespace capi`), the names collide.

Instead, I think we should change the C++ to be

```cpp
#include "ICU4XFixedDecimalFormat.h"

namespace icu4x {

class FixedDecimalFormat {
  // ...
}

}
```

CC @Manishearth @dminor @gregtatum

**Comment by Manishearth** [comment]
This is blocked on https://github.com/rust-diplomat/diplomat/issues/103 which is a bunch of work.

An alternate option to solve the C problem specifically is to do something like `#ifdef __cplusplus namespace capi {` in the C headers instead.

I would prefer if we could get proper namespaces in C++ however.

**Comment by sffc** [comment]
Decision: do the workaround solution @Manishearth proposed above. If there is time for 1.0 (unlikely), try for real namespaces. Otherwise, consider it for 2.0.
