### ISSUE TITLE
Make Swedish default collation handling able to deal with CLDR 41 and with CLDL 42 or later

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#2183]
Swedish has a naming oddity that's [hard-coded](https://github.com/unicode-org/icu4x/blob/main/provider/datagen/src/transform/icuexport/collator/mod.rs#L63-L82) in datagen. [CLDR is fixing the oddity.](https://unicode-org.atlassian.net/browse/CLDR-15603)

We should have something better than the current hard-coding so that ICU4X 1.0 datagen will be able to deal with CLDR 42 correctly.

**Comment by hsivonen** [comment]
CC @sffc @robertbastian @echeran

**Comment by robertbastian** [comment]
What's our policy on icu_datagen supporting old versions of input data? Do we want to support anything after our 1.0 release, forever?

**Comment by sffc** [comment]
In development we've largely been supporting only one CLDR version at a time but after 1.0 we should try to support multiple CLDR versions. We should definitely support both 41 and 42, and beyond that we should make an evaluation about how many versions back we want to support in the latest datagen release. Note that people will be able to install an older version of datagen to build data for an older CLDR version.

We should probably make datagen print some sort of warning if presented with CLDR or ICU data marked with a version it hasn't been verified to work with.

> I guess the simplest thing that could possibly work would be checking if `sv_reformed_meta.toml` exists and treat it as the default if it does exist and otherwise not activate the Swedish special case.

Yes, something along these lines sounds like the best path forward.

You could also leave a version number in the icuexportdata zip file.
