### ISSUE TITLE
Style guide: When to use crate features?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#219]
When adding enhancements to an ICU4X component, we have a choice about whether or not to hide the enhancement behind a crate feature (such that dependent crates need to enable it in their Cargo.toml file).  How do we decide whether to use a crate feature?

Some possible guidelines:

1. If the enhancement adds new crate dependencies, then it should be behind a feature.
2. If the enhancement involves code that we don't consider to be best i18n practices (e.g., it is primarily useful for debug or development environments), then it should be behind a feature.

An example of case 2 is the InvariantDataProvider that I added in #198.

Are there any other reasons why we would want to put things behind feature flags?

CC @zbraniecki @filmil @Manishearth

**Comment by Manishearth** [comment]
The two existing criteria seem good. There is also "enabling nonstandard hardware features like sse" but we probably don't need that and there are better ways to do that

**Comment by filmil** [comment]
Agreed with the two suggestions.

One additional point that would inform the criteria is whether we want to have a "default" core, from which a user may rarely want to diverge, or whether we want to provide building blocks and let the user mix and match.

I *think* that if it is the former, then (1)+(2) is fine, if latter, perhaps (2) shouldn't be a thing.

My two cents, feel free to disregard in case of doubt.

**Comment by sffc** [comment]
We already will have building blocks in the form of different crates.  The question is whether we want to make our building blocks even more granular than the crate boundary (as crate features).

**Comment by sffc** [comment]
We agreed to start with the 2 points in the OP.  We can iterate later if we get new information.
