### ISSUE TITLE
Name of icu_locale_canonicalizer crate

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2214]
We never discussed the name of the crate. It is the longest name. I was wondering if we would consider shortening it to something like `icu_canonicalizer`.

Not technically a 1.0 issue since we can re-export using both names, but if it's easy, we can make the change now.

CC @dminor

**Comment by dminor** [comment]
Using `icu_canonicalizer` seems fine to me.

**Comment by sffc** [comment]
Another idea: `icu_locid_ops`

**Comment by robertbastian** [comment]
Is the term "canonicalize" ever used for Unicode text (instead of "normalize")? If so I can see this being confusing.

**Comment by sffc** [comment]
> Is the term "canonicalize" ever used for Unicode text (instead of "normalize")? If so I can see this being confusing.

It's possible. Basically ICU4X would be _defining_ that "normalize" refers to text and "canonicalize" refers to locale IDs. But if we don't want to make that definition, we could explore a name like `icu_locid_ops`.

As a reminder: the reason these aren't in the core `icu_locid` crate is because that crate has no data dependencies.

**Comment by sffc** [comment]
Another option is to add a feature to the `icu_locid` crate and move these in. An advantage is that we could integrate more closely with the existing Locale APIs. I think maybe the reasons for trying to keep data out of `icu_locid` are largely obsolete and I'm happy to revisit that years-old decision.

**Comment by robertbastian** [comment]
I don't like `ops` because it's such an abstract term, like `icu_locid_functionality`. 

I think having it in `icu_locid` is most ergonomic.

We could also use `icu_locid_canonicalizer` which would be more aligned with our crate structure as it would mimic `icu::locid::canonicalizer`.

`icu_locid_canon` would be the coolest name. 💣

**Comment by sffc** [comment]
CC @zbraniecki 

I like `icu_locid_canon` :)

**Comment by sffc** [comment]
- @Manishearth - I like having a separation between basic locid and fancy locid.
- @echeran - There's a data-heavy crate and then the function-heavy crate.
- @sffc - Canonicalization is the first data-heavy operation we added, but it is unlikely to be the last. See LocalInfo, DisplayNames, ...
- @echeran - `icu_locid_utils` is fairly generic but maybe what we want?
- @Manishearth - If we can avoid "utils" we should try to avoid it
- @sffc - I like "ops" because these are operations on the locid. std::ops contains operations/operators on standard library types
- @robertbastian - I think there's a big difference between operations and operators
- @sffc - Actually we can't have data-dependent operations in icu_locid because that would be a circular dependency
- @sffc - `icu_locid_data`
- @Manishearth - `icu_locid_manipulation`
- @Manishearth - `icu_locid_operations`
- @robertbastian - `ops` would sound like we implement "Add" on locid
- @Manishearth - But locid is not number-like
- @sffc - `icu_locid_oper`, `icu_locid_operate`, `icu_locid_adapters`
- @echeran `icu_locid_transform`
- @gnrunge `icu_locid_modifier`
- @sffc - How do people feel about `_transform`?
- @Manishearth - Great
- @robertbastian - Makes sense

Conclusion: use `icu_locid_transform`

And re-export as `icu::locid_transform`

**Comment by sffc** [comment]
@sven-oly will take a look at this.
