### ISSUE TITLE
Consider exporting a single type DatagenProvider

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2215]
In icu_datagen, we have `create_exportable_provider!` that returns an opaque type. It may be nicer to have a single struct called `DatagenProvider` and then have `impl DataProvider<FooMarker> for DatagenProvider` throughout the icu_datagen package.

Probably not time for 1.0; it may be possible to do this in an additive way.

CC @robertbastian

**Comment by robertbastian** [comment]
I think this is a fairly small change and would let us get rid of a macro, so I approve.
