### ISSUE TITLE
Provide a C++ interface to the normalizers

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#2219]
The normalizers aren't currently exposed to C++ via Diplomat. They should be.

Only the `ComposingNormalizer` and `DecomposingNormalizer` objects should have C++ counterparts.

`Composition` and `Decomposition` are Rust iterators, which are a bad fit for FFI.

`CanonicalComposition` and `CanonicalDecomposition` are for HarfBuzz. It doesn't make sense to expose them to C++ absent non-HarfBuzz use cases. Instead, their FFI wrappers should be C-linkage-only and should fit the HarfBuzz callback interface exactly. Therefore, these need to be manually-written.

Both `ComposingNormalizer` and `DecomposingNormalizer` should be wrapped as follows (apart from the constructors):

* C++ `bool is_normalized(std::string_view text)`: Rust `is_normalized_utf8()`
* C++ `bool is_normalized(std::u16string_view text)`: Rust `is_normalized_utf16()`
* C++ `bool is_normalized_unsafe(std::string_view text)`: Rust `is_normalized` with documentation note that the call is UB unless the C++ caller has ensured UTF-8 validity.
* C++ `std::string normalize(std::string_view text)`: Create an `std::string` return value. Call `reserve(text.size())` on it. Pass it as `DiplomatWriteable` to Rust `normalize_utf8_to()`. Return the `std::string`.
* C++ `std::u16string normalize_utf16(std::u16string_view text)`: TODO once there's a `DiplomatWriteable` analog for `write16::Write16`: Create an `std::u16string` return value. Pass it as (assumed future) `DiplomatWriteable16` to Rust `normalize_utf16_to()`. Return the `std::u16string`.
* C++ `std::string normalize_unsafe(std::string_view text)`: Create an `std::string` return value. Call `reserve(text.size())` on it. Pass it as `DiplomatWriteable` to Rust `normalize_to()`. Return the `std::string`. Documentation note that the call is UB unless the C++ caller has ensured UTF-8 validity.
* (No other methods.)

**Comment by hsivonen** [comment]
> C++ `bool is_normalized(std::string_view text)`: Rust `is_normalized_utf8()`

To get Diplomat to use `std::string_view` in C++, the argument type of the method on the `#[diplomat::opaque]` `ICU4XComposingNormalizer` should be `&str`, which should immediately get `as_bytes()` called on it.

> C++ `bool is_normalized(std::u16string_view text)`: Rust `is_normalized_utf16()`

[This requires more Diplomat configurability.](https://github.com/rust-diplomat/diplomat/issues/240)

**Comment by Manishearth** [comment]
This issue has been solved for 1.0

We should open a separate issue for 1.x followups for when Diplomat has the functionality.
