### ISSUE TITLE
Consider adding const und() function to LanguageIdentifier

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#222]
Would be roughly equivalent to `langid!("und")`

**Comment by sffc** [comment]
See if using the Default trait works in the relevant call sites.

**Comment by zbraniecki** [comment]
We could alias `LanguageIdentifier::und()` to `Default::default` for discoverability/readability.

**Comment by sffc** [comment]
It would be nice if `LanguageIdentifier::und()` were `const`.  But `Default::default` is not const.  Could we do this by inverting control?  Make `LanguageIdentifier::und()` be const and construct the default LanguageIdentifier, and then `Default::default` calls `LanguageIdentifier::und()`.

**Comment by zbraniecki** [comment]
Yeah! And we can swap later once https://github.com/rust-lang/rfcs/pull/2632 lands.
