### ISSUE TITLE
Clear stale cache artifacts built against old Rust versions

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#225]
Prompted from build issues in PR #220 - @zbraniecki 

Initial idea: if the compatibility of cached build artifacts to the current build also depend on Rust versions matching, then let's add the Rust version to the cache key.

To test: does running the `rustc` command on the Github Actions runner VMs automatically access the latest stable Rust, or do we need to run a rust command (`rustup` via [actions-rs/toolchain](https://github.com/actions-rs/toolchain)?) to get the latest Rust?

**Comment by echeran** [comment]
What's the best way to get the Rust version?  Run `rustc --version` and parse the output?

**Comment by zbraniecki** [comment]
I think so? https://docs.rs/semver/0.10.0/semver/

There's also https://github.com/dtolnay/rustversion

**Comment by sffc** [comment]
How much time does the cache actually save for us?

I think it's useful to cache things that require a download, but for compile artifacts, maybe we should just not perform caching since it seems to cause a number of problems.

**Comment by zbraniecki** [comment]
I'm ok with trying to skip caching and see what happens. 

But we should also consider (maybe later?) caching based on Rust version as per https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions
