### ISSUE TITLE
Add lint for debug impls on exported types

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2266]
Context: https://github.com/unicode-org/icu4x/pull/2250#discussion_r930774402

Our style guide says that we should implement Debug on all exported types; however, we don't currently do that.

@robertbastian suggested the `missing_debug_implementations` rustc lint.

@Manishearth thoughts?

Most likely not time for 1.0 but we should try to land it in 1.1

**Comment by Manishearth** [comment]
Yeah, seems like a good idea!

**Comment by robertbastian** [comment]
Is this 1.2 blocking?
