### ISSUE TITLE
Where to save generated data

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#227]
I would like to save the output of the data exporter tool (#200) such that the CLDR source files are not required when using ICU4X.

Putting this directly into the ICU4X repo has some advantages: fewer moving parts, easy to make synchronous updates to code and data, etc.  However, if we put it into the ICU4X repo, but that would mean a deep directory structure with volatile, generated data.

I was thinking that a separate, independently versioned repo, called icu4x-data, might be more appropriate.  In addition to keeping ICU4X as a pristine source of truth (without auto-generated clutter), it would make it easier to check in multiple types of generated data (e.g., JSON and Bincode for multiple CLDR versions).

We could also use a branch of the ICU4X repo.

Thoughts?

**Comment by zbraniecki** [comment]
Third option would be to not store generated data. We could have data generation as a build step that users do on their own machines.

**Comment by sffc** [comment]
Related: what to do about data for testing. We should probably save it in this repo so that the tests are self-contained. We could either put minimal data into each component's test directory, or we could have a common shared directory for all test data.

https://github.com/unicode-org/icu4x/pull/230#discussion_r484084258

**Comment by sffc** [comment]
Conclusions from 2020-09-17:

- Top-level test data directory with data pulled from specific list of locales; locales should have properties representative of the features we are testing
- The test data should have a helper script to generate it, invoked manually
- For v0.1, have instructions on how to generate full data from a CLDR JSON tag
