### ISSUE TITLE
Migrate ndarray dependency in segmenter to a release version

### ISSUE THREAD

**Issue by aethanyc** [unicode-org/icu4x#2280]
We'll have to switch [ndarray dependency](
https://github.com/unicode-org/icu4x/blob/c73d122c1ffd03fd7b126d7ea41bc7f972106e0f/experimental/segmenter/Cargo.toml#L38) in segmenter to a release version in order to publish `icu_segmenter`. The release must contain Makoto's fix in https://github.com/rust-ndarray/ndarray/commit/31244100631382bb8ee30721872a928bfdf07f44.

@sffc suggests we upload ndarray as `icu_ndarray` as a workaround until the upstream releases a new version. 

cc @makotokato

**Comment by sffc** [comment]
Can we try upgrading to 0.15.5?

https://github.com/rust-ndarray/ndarray/pull/1154#issuecomment-1200289864

**Comment by sffc** [comment]
@aethanyc Assigning this to you to try using the new version
