### ISSUE TITLE
Add docs on how to plug DataProvider for Components

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#229]
While working on #189 I'd like to add docs on how to plug `DataProvider` into a `Component`.

For such documentations I historically preferred Wiki over PR because its easier for people to collaborate on it, and it's not part of the formal codebase.

Would everyone be ok if I added a wiki to this repo and wrote the initial version of the article?

**Comment by sffc** [comment]
The GitHub wiki seems fine for things like this. Thanks!

**Comment by zbraniecki** [comment]
https://github.com/unicode-org/icu4x/wiki/Hooking-up-a-DataProvider

@sffc - can you take a stab at polishing it and cleaning up?

**Comment by zbraniecki** [comment]
There's a basic doc in https://github.com/unicode-org/icu4x/wiki/Hooking-up-a-DataProvider

We can extend as we need.
