### ISSUE TITLE
full-datagen task should be runnable from cargo-make

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#2308]
We have a `cargo make ci-job-foo` for every CI job foo, so that whenever something fails it's easy to reproduce locally. This includes CI jobs that do special things like integrate with GHA's Clippy annotations (we just replicate what the action does as closely as possible).

We should have this for full-datagen, since it's possible for that job to fail and it's kinda annoying to reproduce otherwise.

**Comment by robertbastian** [comment]
`full-datagen` uses GH Actions infrastructure that we cannot replicate locally. `cargo make full-data` is _almost_ the same, the difference is how the downloading and caching happens (in the binary itself). We can point `cargo make ci-job-full-datagen` at that, but it won't be identical.

**Comment by Manishearth** [comment]
That's totally fine, it should _mostly_ be the same. We have something ismilar for clippy.

**Comment by sffc** [comment]
We do want the CI job to cache the downloaded CLDR and ICU data, which I think is why we wrote it separately

**Comment by Manishearth** [comment]
Yeah, I'm aware, I just want there to be some weak correspondence so that we can approximate every CI job locally with a ci-job-foo command, in case stuff breaks. If it doesn't reproduce perfectly that's fine, but for 99% of the test failures we should not have to go spelunking in the GHA file and manually replicate its steps :smile:

**Comment by robertbastian** [comment]
So yeah, just an alias for `full-data`

**Comment by sffc** [comment]
Action: create an alias.
