### ISSUE TITLE
Constructors in the `icu_properties` crate

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2315]
The constructors for `icu_properties` don't immediately follow from the decision in #2136.

We have things like

```rust
pub fn get_script_with_extensions(
    provider: &(impl DataProvider<ScriptWithExtensionsPropertyV1Marker> + ?Sized),
) -> ScriptWithExtensionsResult
```

Questions:

1. Do we rename the function `try_get_...`?
2. How do we extend it to AnyProvider/BufferProvider?

For example, should our names end up being like this?

- `try_get_script_with_extensions_unstable`
- `try_get_script_with_extensions_with_any_provider`
- `try_get_script_with_extensions_with_buffer_provider`

@echeran @Manishearth thoughts?

**Comment by Manishearth** [comment]
No strong thoughts, having three does make some sense.

**Comment by sffc** [comment]
Discussion with @echeran:

- `try_load_...` makes sense because you are not actually "getting" something that behaves like the properties data structure, because you need to call `.as_borrowed()`
- Given the design around `PropertyCodePointSetV1`, we actually probably don't need the any/buffer versions of these functions

**Comment by sffc** [comment]
Two more thoughts:

1. We already use the word `load` in places in ICU4X to mean a fallible function, so maybe `try_load` is redundant and it should just be `load`
2. ScriptWithExtensionsV1 does not have the non_exhaustive data struct like most of the other properties; we may want to have the any/buffer functions just for that one
