### ISSUE TITLE
diplomat-gen should fail on the wrong version of Diplomat

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#2319]
It is possible to run `cargo make diplomat-gen` with an out of date version of Diplomat, and thereby get a misleading & inaccurate diff.  (When Diplomat is out of date, you need to re-run `cargo make diplomat-install`.)

Instead, `diplomat-gen` should have a check for the version number before proceeding, and it should fail early if there is a problem.

One idea to implement this might entail adding a flag to Diplomat that will print out its version.  We can then use that to add a task that prints out that version number and stores it as a file in the repository.  If doing so results in that file's contents having a diff, then we have a version mismatch.

**Comment by robertbastian** [comment]
I think I've discussed this with @Manishearth a while ago, this would only work for published versions. The tool cannot know the Git hash it was built from.

**Comment by Manishearth** [comment]
Also it's quite often that I want to run diplomat-gen with a different version of Diplomat. We could add a warning, but for now we have the CI job.

**Comment by sffc** [comment]
Can `diplomat-tool --version` output the hash it was built from?

**Comment by Manishearth** [comment]
We might be able to hack something in the build script? Tricky though.

**Comment by echeran** [comment]
Ah interesting. The use case for me that prompted the issue was that my PR branch was failing the FFI job, and that re-running `cargo make diplomat-gen` (as [error message says](https://github.com/unicode-org/icu4x/blob/main/tools/scripts/ffi.toml#L41)) wasn't enough was because the version of Diplomat that I had installed locally was different from what was the latest in the repo.

Maybe that can solved by updating the error message to suggest that the user might want to first run `cargo make diplomat-install` unless they need to run with a specific version of Diplomat?

Or should I have been running `cargo make ci-job-ffi` locally, and noticing that the instructions in `contributing.md` include  `cargo make diplomat-install`?  I think the tribal-ish knowledge is knowing that `cargo make diplomat-install` is not just a one-time setup thing.

**Comment by Manishearth** [comment]
Yeah, we should also update that error!
