### ISSUE TITLE
BiDi crate desiderata

### ISSUE THREAD

**Issue by raphlinus** [unicode-org/icu4x#232]
This is a bit of a followup to https://github.com/open-i18n/rust-unic/issues/273, which pointed out issues and concerns with the existing unic-bidi crate. In its current form, it cannot really be used. This is a shame, because I think BiDi is one of the foundational capabilities of a modern text stack, and in the coming years I'd like to see one of those develop in the Rust ecosystem.

That issue summarizes some of my concerns with the unic-bidi crate. Here I'll set out my higher-level wishlist.

First, I'd like to see the scope of the crate focused to serving the needs of a modern text stack. ICU has lots of legacy stuff such as reordering "characters," which I can see would be useful when printing BiDi text on a daisy wheel printer. I'm sure more needs will emerge in time, but basically what I think I need right now is BiDi analysis of a paragraph so we can figure out which runs are LTR and RTL for shaping and line breaking, then visual runs reordering on a per-line basis. As I stated in that issue, even segmentation into paragraphs feels vaguely out of scope to me, as the client is very likely to have done its own paragraph segmentation as part of its higher level text formatting.

Second, I'd like the API to be designed with performance in mind. To me, that means an emphasis on level runs rather than per-"byte" (UTF-8 code unit). I'd prefer that the API doesn't force allocation and copying for basic usage.

On a similar theme, I'd like the API to be "beautiful Rust," not something that was obviously adapted from C (and can likely be traced back to Taligent). To me, that means using iterators as the primary interface. That's very consistent with the above desideratum, as iterators don't have to allocate. Indeed, I think it's a good approach to providing `is_ltr_only()` functionality without a special case: you can query the iterator and get back back a level run that covers the entire paragraph.

The actual hardcore performance tuning could happen later, but that's easy to change, and can be in stages (for example, a fast-path that special cases LTR-only). APIs are harder.

I am hopeful there is a critical mass of interest around these concerns, and look forward to seeing what the community does. I'm happy to provide feedback on design proposals. If nothing happens here, I'll likely fork unic-bidi and make modifications along these lines, without getting too much into the guts of its implementation. Perhaps such an artifact would be useful to provoke design discussions, aside from its expedient use to get BiDi working (which, I should emphasize, is at least several months out in the Druid roadmap).

**Comment by hsivonen** [comment]
> `is_ltr_only()` functionality

It's in a rather odd crate thematically, but [`encoding_rs::mem`](https://docs.rs/encoding_rs/0.8.24/encoding_rs/mem/index.html) has functions for this (the ones whose names had `bidi` as a substring).

**Comment by younies** [comment]
Shall we consider this issue done ?

**Comment by sffc** [comment]
@younies There have been no comments on this thread in over a year. Please post a more detailed explanation for why you feel this issue should be closed.

**Comment by sffc** [comment]
We decided to leverage the existing `unicode_bidi` crate for the algorithms, but powered with ICU4X data. You can see how this works in the docs page here:

https://icu4x.unicode.org/doc/icu_properties/bidi/index.html

@raphlinus Let us know if you have any further suggestions.
