### ISSUE TITLE
Clean up AnyCalendar constructors from locale

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2357]
Failing to turn a `Locale` into a `AnyCalendarKind` shoudn't fail to create an AnyCalendar; we're supposed to fall back to the locale's default. That is all code that should ideally live in Rust, not in the FFI wrapper layer or in the C++/JavaScript calling code.

I guess I would expect a function like `AnyCalendar::try_new_for_locale_unstable(&provider, &locale)`, along with `AnyCalendar::try_new_for_locale_with_any_provider`, ...

_Originally posted by @sffc in https://github.com/unicode-org/icu4x/pull/2344#discussion_r941794055_

CC @Manishearth

**Comment by Manishearth** [comment]
This is also related to https://github.com/unicode-org/icu4x/issues/2038

**Comment by sffc** [comment]
LGTM on the proposal above. Fix this at the same time as #2038
