### ISSUE TITLE
Turn off redundant property maps for 1.0

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#2372]
[From the meeting:](https://github.com/unicode-org/icu4x/issues/2362#issuecomment-1212291138)

> Proposal for the maps getters:
>
> - General_Category, Bidi_Class: Public Stable
> - Canonical_Combining_Class, Script: `"experimental"` feature
> - The five segmenter properties: `"datagen"` feature
> - All tuple structs remain public stable

This issue is for tracking the `"experimental"` and `"datagen"` switches for these.

**Comment by sffc** [comment]
I know that I was part of this discussion, but I don't really see the value in adding experimental flags here with no clear path to make them be non-experimental.

We already have these docs on load_canonical_combining_class:

```
    /// See `icu_normalizer::CanonicalCombiningClassMap` for the preferred API
    /// to look up the Canonical_Combining_Class property by scalar value.
```

If we add similar docs on `load_script`, then maybe that's enough. We don't really need to hide these other properties; they conform to our API standards, and if people want them, they can get them.

**Comment by hsivonen** [comment]
> We don't really need to hide these other properties; they conform to our API standards, and if people want them, they can get them.

How likely will Postcard or FFI users end up with accidentally carrying duplicate data without the `icu_properties` instance of the data getting omitted?
