### ISSUE TITLE
Support more than just Script in CodePointMap ffi (ICU4XCodePointMapData16)

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#2379]
Curently CodePointMap's FFI hardcodes Script, we should support any u16 property in ICU4XCodePointMapData16 and also support ICU4XCodePointMapData8.

**Comment by Manishearth** [comment]
So one  thing I'm not sure about is how we should handle getters to the map types.

I see that there are two ways of doing this:

```
// Option A
impl CodePointMap8 {
    fn get(&self, ch: char) -> u8;
    fn as_gc(gc: u8) -> Result<GeneralCategory, _>;
    fn as_lb(lb: u8) -> Result<LineBreak, _>;
   // ...
}

// Option B

impl CodePointMap8 {
    fn get_gc(&self, ch: char) -> GeneralCategory; // should be Result?
    fn get_lb(&self, ch: char) -> LineBreak;
   // ...
}
```

In both cases the user would be responsible for ensuring they call the right one.

A third option (option C) is to have different types entirely.


A is kinda nice in that JS won't be initializing a string each time you do a get, and you can use fast integer comparisons if you need. OTOH B is more straightforward. Both A and B have problems with mixing types, however.

C leads to more APIs (there are currently 10 enumerated props) but is harder to get wrong. Having it not be type erased might be a problem if users wish to mix maps.

Thoughts? @sffc @echeran

**Comment by sffc** [comment]
My mental model has been that over FFI we return integers, not newtypes like we do in Rust.

These can ideally be paired with static constants, which we can add once Diplomat supports them.

In TypeScript, for example, you should write something like this at the call site...

```typescript
let prop_getter = ICU4XCodePointMapData16::try_get_script(provider);
console.assert(
    prop_getter.get('A') === ICU4XCodePointMapData.GeneralCategory.LOWERCASE_LETTER
);
```

**Comment by Manishearth** [comment]
In the meantime when we don't support static constants, what ought we do?

**Comment by Manishearth** [comment]
One thing I have kinda wanted is the ability to ask an enum in diplomat to be stringy or constanty

**Comment by sffc** [comment]
These are not enums; they are newtypes, because they can change at any time (with new Unicode releases), and there's no portable way to do non-exhaustive enums.

Without static constants, people just have to get the constant integer from somewhere else. Maybe we publish a wiki page with all the numbers.

**Comment by sffc** [comment]
IIRC, the other workaround for static constants was to have a bunch of static functions instead.

**Comment by sffc** [comment]
Also, another way people can get the constants is to `#include <unicode/uchar.h>` from ICU4C. You can get the constants from the header file without needing to link the library. I've done similar things in the past and I may do this in Skia and Harfbuzz.

**Comment by Manishearth** [comment]
Alright, integers it is.

I didn't realize the values are "stable" across libraries

**Comment by sffc** [comment]
Yeah, when introducing the properties values, it was a design consideration to use the same values that ICU4C uses, to make it more of a drop-in replacement. @echeran can confirm.

**Comment by Manishearth** [comment]
Sounds good. This makes the enum code I was working on in diplomat less important but I might as well land it.

**Comment by Manishearth** [comment]
(https://github.com/rust-diplomat/diplomat/pull/222)

**Comment by Manishearth** [comment]
Yeah I remember that discussion now.
