### ISSUE TITLE
BiDi Feature Scoping

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#238]
There are many facets of BiDi handling.  We should make a list of the different facets, and decide which ones are in-scope for ICU4X.

See some scoping guidelines in #42 as well as in charter.md.  Coordinate as necessary in #232.

**Comment by younies** [comment]
Shall we consider this issue done? I have added couple of issues to track the progress?

**Comment by sffc** [comment]
@younies There have been no comments on this thread in over a year. Please post a more detailed explanation for why you feel this issue should be closed.
