### ISSUE TITLE
Allow icu_testdata's BakedDataProvider to be broken down by component and experiment

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2383]
Currently icu_testdata's BakedDataProvider is monolithic and pulls in all ICU4X components, including experimental ones. The feature is generally disabled because of the compile times. Both of these issues could be resolved if we made each part of BakedDataProvider be feature-gated. For example, `"icu_datetime"` could dev-depend on `"icu_testdata/icu_datetime"` (and whichever other components it needs, like `"icu_testdata/icu_decimal"`).

We also want for the `icu_datetime/experimental` feature to be optional.

- [ ] @robertbastian

**Comment by sffc** [comment]
For crates with experimental features, here is what I propose

1. Add a testdata feature called e.g. `icu_datetime_experimental` (optionally remove the "icu_" prefix if you do so for the other features)
2. Tests in `icu_datetime` that need data hidden behind `icu_testdata/icu_datetime_experimental` should use the serde data instead, until https://github.com/rust-lang/cargo/issues/1596 is fixed.

**Comment by robertbastian** [comment]
Fixed by #2364
