### ISSUE TITLE
Allow expect() and panic!()

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2391]
Previous discussion in #1363

We have the global lints that prevent us from panicking in places we don't want to panic:

```
        clippy::indexing_slicing,
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
```

We can suppress these on a line-by-line basis, with the idea that those places are documented properly.

Since both `.expect("...")` and `panic!("...")` are self-documented, maybe we shouldn't include them in this lint. Other panicking macros already not included by this lint are `todo!()` and `unreachable!()`.

An alternative suggested by @robertbastian is to use `.unwrap()` everywhere due to code size issues, and put the explanation in the code comment. This is interesting, but I think not actually an issue since the code size builds use panic=abort, so the errors are not formatted.

CC @ozghimire 

Needs approval from:

- [x] @Manishearth 
- [ ] @robertbastian 
- [ ] @zbraniecki

**Comment by robertbastian** [comment]
> Since both `.expect("...")` and `panic!("...")` are self-documented

`panic!()` can be called without a message as well. I think we should forbid `panic!`, and use more specific macros like `unreachable!` which are self-documenting. Most unannotated `panic!`s seem to actually be `unreachable!`s.

For unwraps we should do `.unwrap()` as the unreachable equivalent, i.e. when the presence is obvious from immediate context. Using `expect` there would definitely be a waste. 
```rust
if foo.is_some() {
  #[allow(clippy:unwrap_used)]
  foo.unwrap()
}
```

But even if only some complex data invariant guarantees the presence of a value, what do we gain from `expect`?
```rust
if something {
  safe.value.expect("value should be present because of this invariant that involves something")
}
```
As we're not documenting any panics as part of our API, this will only happen when there are bugs on our end, and there's nothing that we need to communicate to clients in human-readable form. We just need a code location (`expect` can't interpolate any additional information), which `unwrap` gives us as well.

> since the code size builds use panic=abort

Not every client uses panic=abort, and we'd still like for them to avoid having useless strings in their binaries.

**Comment by Manishearth** [comment]
I was under the impression that the primary purpose of this was to reduce panics, not just for getting them to be documented.

I think it's good to have pressure to avoid panics, especially since Rust panics in a library aren't very fun for whoever is using the library.


I think a pressure towards preferring unwrap over expect might be good, but I'm not sure if we should do it very strongly. Definitely the Rust community has the opposite preference. Perhaps we use unwraps where we don't think a string message is that necessary but still use expect in complex cases?

**Comment by sffc** [comment]
Let's go through the hundreds of TODO(#1668) still in the repo and see if we can agree on a reasonable path forward:

https://github.com/unicode-org/icu4x/search?q=1668

**Comment by sffc** [comment]
This is obsolete due to work on #1668.
