### ISSUE TITLE
Mark all experimental crates, modules, and types clearly in docs

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2409]
Since the docs don't clearly define what is behind which features, we should do a bit more work on our end. I'd like to suggest that everywhere a crate, module, or struct/enum is experimental, we mark it clearly in the docs string. This should include modules and structs/enums that are nested inside experimental modules and crates.

We don't need to be completely perfect, but we should hit all the major cases where people are likely to go wrong.

Suggested markup:

- `🛠️ [Experimental]` at the start of the very first line (yes, with the emoji)
    - Other emoji options: 🚧 ⚙️ 🧰 🏗️ 🚦 🔧 🔬
- As a paragraph in the docs string:

> This code is experimental; it may change at any time, in breaking or non-breaking ways, including in SemVer minor releases. It can be enabled with the "experimental" feature. Use with caution.

OK?

- [x] @Manishearth

**Comment by Manishearth** [comment]
Works for me.

**Comment by Manishearth** [comment]
I think we should do both the emoji and the paragraph (at the end of the first section of docs)
