### ISSUE TITLE
Unicode Conference 44 Presentation

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#241]
At IUC44 we're going to make the initial presentation of ICU4X project.

Goals:
* Introduce ICU4X
* Explain the Problem and Solution
* Outline 0.1 release
* Attract community to test, give feedback and help with 0.2

Since the presentation is going to be fully virtual, we need to prepare slides and record a video of the talk by **September 25**.

The plan is to prepare a slide-deck and narrative for the presentation, delegate parts of the talk to different ICU4X contributors and then @mihnita offered to stitch the video together.

The lead presenter will be @zbraniecki.

Outline:
* Introduction
  * Who are we (Zibi)
  * Unicode, ICU, CLDR, ECMA402 (Nebojsa?)
  * ICU4C vs ICU4J (Shane? Mihai? Nebojsa?)
* Problem Statement
  * Client Side Needs (Shane)
  * Data Management (Shane)
  * Modularity (Zibi)
* ICU4X
  * Rust ecosystem (Zibi)
  * DataProvider (Shane)
  * Crate system (Zibi)
  * FFI/WASM target (Nebojsa?)
* ICU4X 0.1 (Zibi)
  * Scope
    * Locale (Zibi)
    * UnicodeSet (Elango)
    * PluralRules (Zibi)
    * DateTime (Mihai)
  * Features
    * Sync DataProvider (JSON, Bincode) (Shane)
    * Modular design (Zibi)
    * ECMA402 traits (Filip, Konstantin?)
    * Performance/Memory (Zibi, Elango)
* ICU4X 2021 (Zibi)

I'll keep this comment up to date as we adjust the assignees and outline.

The timeline is:
* Sept 11 - Sept 18 - Work together on the slide deck
* Sept 22 - Evaluate the slide deck at the weekly call
* Sept 23 - Record the clips for Mihai to stitch
* Sept 23 - Sept 26 - Mihai combines them together
* Sept 26 - Review of the complete video
* Sept 27 - Submission

**Comment by filmil** [comment]
FYI added content to the ECMA402 slide.

**Comment by filmil** [comment]
... also made a 42 second long video on that slide.

**Comment by mihnita** [comment]
Added slides for DateTimeFormat

**Comment by nciric** [comment]
Added 2 slides under my name. Hoping to get recording to Mihai today or
tomorrow - 720p.

суб, 19. сеп 2020. у 02:45 Mihai Nita <notifications@github.com> је
написао/ла:

**Comment by nciric** [comment]
I've used Pixel audio recorder/transcript generator app & external mic to record audio only for slides 5 and 22. I asked Mihai to use my Unicode photo in the corner.
Audio tracks sent.

**Comment by filmil** [comment]
@zbraniecki @mihnita For the record, I believe I uploaded the video and prepared the slide and speaker notes for my one slide :)  Let me know if there are any issues with those.

**Comment by zbraniecki** [comment]
This is now completed.
