### ISSUE TITLE
Improve docs of icu_properties::bidi

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2412]
Feedback from @markusicu:

> Why is bidi its own module? It's odd that it's inside of properties. It seems like it is higher-level than properties.
>
> I see, it provides data to unicode-bidi. I think those docs are not clear. It is a way to expose bidi properties to a crate that is external to icu4x. The current description makes it sound like you're carrying an implementation of bidi, but that's not the case.
>
> The bidi example appears to be rendered as RTL; not sure it buys you anything.

**Comment by markusicu** [comment]
If you want to make the logical order of the characters visible, you could use hex escapes, or put each character on its own line.

**Comment by sffc** [comment]
> or put each character on its own line.

Yeah, this is what we should do. I think maybe it used to be that way, until we auto-formatted it. We can suppress the auto-formatting by putting `//` at the end of each line.

**Comment by sffc** [comment]
@younies Please review the feedback from Markus and make a PR to improve the docs.
