### ISSUE TITLE
Hide fields of certain structs?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2417]
The fields of the following structs are public. They need to be public for serialization purposes, but should we hide the fields from the docs?

- Char16Trie
- ScriptWithExtensions
- possibly others

Thoughts?

- [ ] @zbraniecki 
- [ ] @Manishearth

**Comment by Manishearth** [comment]
Do they need to be public for serialization purposes, or databake purposes?

But yeah it should be fine to hide.

**Comment by sffc** [comment]
They are public for databake purposes, and also because the structs are `#[derive(Deserialize)]` (no internal invariants)

**Comment by Manishearth** [comment]
Ah, I don't think derive-Deserialize should imply public fields, FWIW, it's just clearer about invariants but we can achieve that with comments too. Ultimately, these types could have their internal structure change but keep the same serde impl, and the same is achievable with databake. So I'd prefer to have it be fully private with databake using a public or hidden constructor (and a comment about serde stability)

**Comment by sffc** [comment]
CC @robertbastian for visibility about impact to databake

**Comment by sffc** [comment]
(It would be nice to not have to do custom Bake impls everywhere)

**Comment by Manishearth** [comment]
Yeah that's fair I guess. I just like avoiding doc(hidden) if possible.

**Comment by sffc** [comment]
Options:

1. `doc(hidden)`
2. Private fields with custom databake impls
3. Inner type like `ScriptWithExtensionsInnerFieldsUnstable` (outer type is a tuple struct wrapping the inner type)

Decision: 1 leaves us flexibility and is the least work.
