### ISSUE TITLE
Improve collator docs

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2418]
Improve collator docs in the following ways:

- [ ] Add example of how locale overrides Strength::Tertiary
- [x] Use the language "potentially ill-formed" and "well-formed" instead of "potentially-invalid" and "potentially-value"
- [x] Fix the utf8 function to say "potentially ill-formed" (it is incorrect currently)

CC @echeran @hsivonen

**Comment by echeran** [comment]
The changes to say "ill-/well-formed" were made in #2475.

@hsivonen which locales override the strength to Tertiary?  Do we already have unit tests that exemplify this behavior?

**Comment by markusicu** [comment]
> @hsivonen which locales override the strength to Tertiary?

Tertiary is the CLDR default. I don't think we currently have a locale that overrides that setting. (You could grep the CLDR data...)
We used to have Japanese set quaternary, but removed that for performance reasons.

**Comment by hsivonen** [comment]
I also am not aware of a locale that would set a non-tertiary strength. Japanese data has an explicit strength, but it is now tertiary. (Also, currently ICU4X does not have code to take the strength from the locale.)

**Comment by echeran** [comment]
Ok, good to know, regarding default collation strength.  And based on that info, I think the first item in this issue's todo list doesn't make sense as written. @sffc Are we ready to close this issue?  All the other tasks are completed.

**Comment by sffc** [comment]
Thiis issue came from the API review with @markusicu. Based on the comments above, it looks like we can close it as fixed by #2475
