### ISSUE TITLE
Names of data provider request fields

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#244]
We have `data_entry: DataEntry` and `data_key: DataKey`.  @zbraniecki said:

> Could we consider renaming it to `key`, and `entry`? I don't think the keys need to indicate that they're data related in a struct called `DataRequest`.

These prefixes originated from the decision in https://github.com/unicode-org/icu4x/blob/master/docs/style-guide.md#exported-type-naming.  I guess we could have `entry: DataEntry` and `key: DataKey`.  However, any variable named `key` just seems overly generic to me.

If we can come up with better terms for these two concepts, then we can avoid this confusion altogether.  Here are the definitions:

https://unicode-org.github.io/icu4x-docs/icu_data_provider/prelude/struct.DataEntry.html

> A variant and language identifier, used for requesting data from a DataProvider.
>
> The fields in a DataEntry are not generally known until runtime.

https://unicode-org.github.io/icu4x-docs/icu_data_provider/prelude/struct.DataKey.html

> A category, subcategory, and version, used for requesting data from a DataProvider.
>
> The fields in a DataKey should generally be known at compile time.

**Comment by zbraniecki** [comment]
>  However, any variable named key just seems overly generic to me.

But it's not a variable, it's a field on a struct. Since the struct has `Data` in the name of the struct, the fields of it don't need to duplicate the (generic already) prefix to the fields imo.

**Comment by sffc** [comment]
I like the names of the struct fields to match the names of variables, so that you can do the shortcut `{ data_entry, data_key }` syntax.  Otherwise, you need to do `{ entry: data_entry, key: data_key }`.

**Comment by zbraniecki** [comment]
Sure, but that doesn't require you to match the type names, you can just do:

```rust
let key = DataKey::foo();
let entry = DataEntry::foo();
DataRequest { key, entry }
```

**Comment by sffc** [comment]
My hesitation is that local variables named `key` and `entry` are too generic.  A key to what?  It could be a hash map key, a private key, a security key, etc.  `data_key` is more specific.

My preferred solution would be if we can throw out the names "key" and "entry" and come up with something more specific that can be used as both the type name and the variable/field name.

**Comment by sffc** [comment]
@hsivonen suggested StaticKey and DynamicKey.

Consensus:

```rust
struct DataRequest {
    pub static_key: StaticKey,
    pub dynamic_key: DynamicKey,
}
```

**Comment by zbraniecki** [comment]
@sffc - I suggest we punt it to Post 0.1 Cleanup.

**Comment by sffc** [comment]
I'd like to send the PR this afternoon and get it into 0.1.

**Comment by sffc** [comment]
Okay, I don't really like the names we came up with above, StaticKey and DynamicKey.

The word "static" is overloaded.  And when you make it into a macro, you end up with something like `static_data_key!()`, which suggests a static variable, when a StaticKey is not necessarily a static variable.  It's static in the sense that it is often known by the programmer at compile time and is the same from request to request.  The word "dynamic" is similarly overloaded.

I also really would rather not use the word "key", which is also overloaded.

Bikeshed for what is currently known as Data[Key/Entry]:

- [Static/Dynamuc]DataKey
- [Static/Dynamic]Key
- [Fixed/Fluid]DataKey
- [Fixed/Fluid]Key
- [Fixed/Fluid]Path
- [Solid/Liquid]Path
- [Fixed/Fluid]UriComponent
- [Fixed/Fluid]Uri
- [First/Second]Component
- Segment/Entry
- Schema/Item
- Scheme/Selection

I will punt this.

**Comment by sffc** [comment]
Struct local variable naming options:

```
DataRequest { res_id, res_options }

DataRequest { resource: { res_id, res_options } }

DataRequest { resource: { id, options } }
```

2020-11-12: name the types ResourceId and ResourceOptions, and name the variables according to the third choice above.

**Comment by sffc** [comment]
Blocked on #196
