### ISSUE TITLE
FFI `ICU4X` prefix

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#2448]
All our diplomat types are prefixed with `ICU4X`. This is probably due to C not having namespacing. However, in other languages, this is not idiomatic. Could a prefix be added as part of Diplomat's C generation instead?

**Comment by sffc** [comment]
Duplicate of https://github.com/unicode-org/icu4x/issues/2182

**Comment by robertbastian** [comment]
Isn't https://github.com/unicode-org/icu4x/issues/2182 much wider in scope, i.e. proper C++ namespacing? I'm thinking of removing the prefix from all names, and just slapping it on every name that is generated for C and C++ (but not for say Dart).

**Comment by sffc** [comment]
I think we had discussed that in the context of #2182 but there was some reason it was hard to do. @Manishearth ?

**Comment by sffc** [comment]
Action: @Manishearth to open or track a Diplomat issue.

**Comment by Manishearth** [comment]
https://github.com/rust-diplomat/diplomat/issues/103

**Comment by robertbastian** [comment]
https://github.com/rust-diplomat/diplomat/pull/416 adds HIR support for custom ABI renames.

**Comment by Manishearth** [comment]
https://github.com/rust-diplomat/diplomat/issues/422 is the issue that would let us make this change _today_ . It is a bit more annoying to implement.

**Comment by robertbastian** [comment]
Fixed by #5228
