### ISSUE TITLE
Do we need TimeZoneFormatterConfig?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2467]
I think everything that `TimeZoneFormatterConfig` can do is already supported by the constellation of `load_` methods. It is mostly used internally and in tests.

I think the original idea behind `TimeZoneFormatterConfig` was to support the UTS 35 fallback logic, but it isn't actually doing that. It does nothing more than feed a `match` statement around all the `load_` functions.

Can we make `TimeZoneFormatterConfig` private for 1.0?

@nordzilla @samchen61661 @Manishearth

**Comment by Manishearth** [comment]
Let's do it

**Comment by nordzilla** [comment]
I believe Sam created `TimeZoneFormatterConfig` as the set of config options that are valid to construct a `TimeZoneFormat` as a stand-alone entity.

**Comment by Manishearth** [comment]
@nordzilla I don't quite understand what you mean by standalone; TZF needs both Config and Options right now and it seems like Config is a subset

**Comment by sffc** [comment]
TimeZoneFormatterConfig is only used to do this:

```rust
        match config {
            TimeZoneFormatterConfig::GenericNonLocationLong => {
                tz_format.load_generic_non_location_long(zone_provider)?;
            }
            TimeZoneFormatterConfig::GenericNonLocationShort => {
                tz_format.load_generic_non_location_short(zone_provider)?;
            }
            TimeZoneFormatterConfig::GenericLocation => {
                tz_format.load_generic_location_format(zone_provider)?;
            }
            TimeZoneFormatterConfig::SpecificNonLocationLong => {
                tz_format.load_specific_non_location_long(zone_provider)?;
            }
            TimeZoneFormatterConfig::SpecificNonLocationShort => {
                tz_format.load_specific_non_location_short(zone_provider)?;
            }
            TimeZoneFormatterConfig::LocalizedGMT => {
                tz_format.load_localized_gmt_format()?;
            }
            TimeZoneFormatterConfig::Iso8601(format, minutes, seconds) => {
                tz_format.load_iso_8601_format(format, minutes, seconds)?;
            }
        }
```

I had remembered discussing that we wanted a way to express the UTS 35 fallback algorithms, but this is not what `TimeZoneFormatterConfig` is currently doing. It does not have any value-add over just using the `load` functions.

**Comment by nordzilla** [comment]
> I don't quite understand what you mean by standalone; TZF needs both Config and Options right now and it seems like Config is a subset

By standalone I just meant TZF apart from Zoned DTF. 

But yes, as Shane pointed out, we did make all those load functions, which are public, and so I think it would be fine to make the Config object private.
