### ISSUE TITLE
icu::datetime::time_zone::ZeroPadding is unused

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2473]
There is no API that consumes values from this enum:

https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/time_zone/enum.ZeroPadding.html

Why not?

We should either make the enum private or add a public function that uses it.

@nordzilla

**Comment by nordzilla** [comment]
Yes, this can certainly be made private. 

This enum was created only for readability and code clarity so as not to pass `true` or `false` to functions.

**Comment by sffc** [comment]
Cool. The action then is to make it private.
