### ISSUE TITLE
Day-of-week calculation in Indian calendar appears broken

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2476]
In Chrome:

```javascript
new Intl.DateTimeFormat("en-u-ca-indian", { dateStyle: "full" }).format(new Date())
// 'Monday, Bhadra 7, 1944 Saka'
```

But in ICU4X:

```rust
assert_eq!(
    "Friday, Bhadra 7, 1944 Saka",
    formatter.format_to_string(&Date::new_indian_date(1944, 6, 7).unwrap())
);
```

CC @zbraniecki @gregtatum @Manishearth

**Comment by Manishearth** [comment]
Our conversion math is wrong; it syncs up the two calendars' month 1, which isn't the case.

**Comment by Manishearth** [comment]
We probably ought to fuzz the calendars crate by converting from random ISO dates and ensuring it's correct (and later, fuzz the offset code, etc)

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/2479
