### ISSUE TITLE
Use extend() with iterator as appropriate in normalizer and collator

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#2482]
[Instead of pushing in a loop, use extend.](https://github.com/unicode-org/icu4x/pull/2481#discussion_r958400225)

**Comment by kelebra** [comment]
I would like to try and tackle this issue. Two questions if you don't mind me asking:

- should I introduce new benchmark for the functionality
- I found another instance of mentioned code pattern (`for ... vec.push`) in the same file, should I replace it too?

**Comment by robertbastian** [comment]
There are a few instances across those two crates, they should all be updated. I don't think benchmarks are necessary.

**Comment by robertbastian** [comment]
I'm pretty sure there were more than 2 instances

**Comment by kelebra** [comment]
I can handle remaining instances later today 👍

**Comment by sffc** [comment]
@hsivonen Can you set an assignee (or "help wanted") and a milestone (or "backlog")?

**Comment by sffc** [comment]
@hsivonen @kelebra Is this issue fixed?

**Comment by kelebra** [comment]
I think I addressed all the remaining cases in the PR before, so should be fixed.

**Comment by hsivonen** [comment]
[One instance left still.](https://github.com/unicode-org/icu4x/blob/fafee0df273ee2b6ff173ce95724eb8205ee942e/components/normalizer/src/lib.rs#L620-L623)

**Comment by kelebra** [comment]
I can take care of that, would you mind assigning this to me?

**Comment by sffc** [comment]
@kelebra I can't assign the issue since you're not currently in the org, but feel free to contribute a PR!

**Comment by sffc** [comment]
I take that this is fixed now; thanks, @kelebra!
