### ISSUE TITLE
We should be using serde_bytes::Bytes instead of [u8]

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2489]
Due to https://github.com/serde-rs/serde/issues/518, everywhere we have `[u8]` gets serialized as a "sequence of u8" rather than as "bytes".

The impact is somewhat limited since `VarZeroVec` has its own `impl Serialize` that calls `serialize_bytes`. However, this shows up in the JSON form of `ZeroMap<[u8], T>`: the `[u8]` gets serialized as a "sequence of u8" and there's nothing we can do about it.

Context: What I was trying to do was to allow `is_num_or_string` to detect ASCII byte strings as strings, but I can't do that because they get captured as a sequence.

Related: https://github.com/serde-rs/json/issues/923

Thoughts?

@Manishearth

**Comment by Manishearth** [comment]
(There's one thing we can do about it: switch to `ZeroMap<ZeroSlice<u8>, ...>` which should behave mostly the same)

**Comment by sffc** [comment]
Even `ZeroSlice<u8>` has the blanket impl that resolves to `serialize_seq` instead of `serialize_bytes`.

**Comment by Manishearth** [comment]
oh, you're talking about human readable serialization, gotcha.

**Comment by sffc** [comment]
I think the impact on Postcard is minimal because it appears that the data model for "sequence of u8" versus "bytes" is identical. I don't know for sure whether the codegen is the same.

But also, for Postcard, this would only kick in if the bytes are the top level type, and most of the time they are inside of a zerovec wrapper like `VarZeroVec<[u8]>`.

**Comment by robertbastian** [comment]
We'd have to use `serde_bytes::Bytes` regardless of whether `serde` is enabled, but it actually pulls it in.

**Comment by robertbastian** [comment]
I also think it makes more sense to use a `LikelyAsciiBytes` type (that we own [for now]). Serializing something that's declared to be just "bytes" to a string based on the value doesn't seem correct.

**Comment by Manishearth** [comment]
Yeah I think having our own type is better here

**Comment by sffc** [comment]
Naming suggestions?

Where should the type live? In `zerovec` or in `icu_provider`?

**Comment by robertbastian** [comment]
`icu_provider::serde::utils::AsciiBytes`

**Comment by sffc** [comment]
> `icu_provider::serde::utils::AsciiBytes`

I think that has the same problem where the `serde` feature is needed to access it?

**Comment by Manishearth** [comment]
Yeah if we do this it has to be a non-featurecfgd util

**Comment by robertbastian** [comment]
I'd still put it under serde path, and just cfg things that actually need serde explicitly.

**Comment by sffc** [comment]
How about `zerovec::ule::LazyStr`?

It is in scope of zerovec because it's something you use to control the ULE validation lifecycle. A `VarZeroVec<str>` is eagerly validated (upon construction), and a `VarZeroVec<LazyStr>` is lazily validated (you get a `LazyStr` upon lookup, which then has a fallible `TryInto<str>`).

**Comment by Manishearth** [comment]
I guess that can work.

What would the serialize impl be? always bytes on binary formats, and choose between bytes and str for human readable formats based on validity?

**Comment by Manishearth** [comment]
I wouldn't call it LazyStr, though, I'd call it something like MaybeUTF8Bytes.

**Comment by sffc** [comment]
> What would the serialize impl be? always bytes on binary formats, and choose between bytes and str for human readable formats based on validity?

Two choices:

1. As you proposed, or
2. Return a serialization error (in both human and non-human) if the bytes are not valid

> I wouldn't call it LazyStr, though, I'd call it something like MaybeUTF8Bytes. Lazy to me sounds like it caches.

This type has several concrete technical advantages, and I want people to be encouraged to use it, so I want a name that is clear and concise.

Depending on the decision to the first question, "maybe" may or not be accurate to describe the type. If the type is intended to be able to hold non-UTF8, "maybe" is correct; if it's intended to be a cheaper version of `str` when the runtime doesn't need to interpret the string form (such as for locale matching), then "maybe" is not really the best term.

Bikeshed:

1. `LazyStr`
2. `MaybeUTF8Bytes`
3. `UnvalidatedStr`
4. `FreeStr`
5. `LateStr`
6. `MaybeStr`

**Comment by Manishearth** [comment]
I'd call it `UnvalidatedStr` yeah

**Comment by sffc** [comment]
`UnvalidatedStr` is clear but a bit long and I don't really like the negative.

Thesaurus word... `ApocryphalStr`?

**Comment by Manishearth** [comment]
heh

I think Unvalidated is pretty clear and I don't think we need a short name for a type that will for most users be niche (even if ICU4X might make heavy use of it)

**Comment by robertbastian** [comment]
This is a serde concept first, not a ZeroVec concept. If we only implemented `VarULE` on this, sure stick it in zerovec, but its Deserialize implementation is usable without the zerovec dependency.

**Comment by robertbastian** [comment]
Although we also don't want to introduce a `zerovec -> icu_provider` dependency, so I think we want to put this in a fresh crate. In fact, the cleanest approach would be to make `serde` on optional dependency of the `serde_bytes` crate, as that already includes exactly this code (https://github.com/serde-rs/bytes/blob/master/src/bytes.rs). `serde_bytes` can then be a non-optional dependency on zerovec, as it itself doesn't pull in anything.

**Comment by sffc** [comment]
I won't touch any `serde` branded crates. We need to do this in our own crates.

I do think this is very strongly related to zerovec due to its use as a ZeroMap key. I think it fits fully in the scope as a first-class type in the zerovec crate.

I'm willing to make a new util crate as a compromise, like we did with `deduplicating_array`, although I really do feel that this fits in the main `zerovec` crate.

**Comment by robertbastian** [comment]
Ok whatever. On naming I agree with `UnvalidatedStr`. On behaviour I think it should be a serialization error if the Unvalidated*Str* is not a `str`, as serialization should do validation; and also because it'd be confusing if some instances serialized with strings and others with bytes slices.

**Comment by robertbastian** [comment]
We have a few instances where we use `TinyAsciiStr` as `UnvalidatedFoo`:

https://github.com/unicode-org/icu4x/blob/main/components/locid_transform/src/provider.rs#L28-L32

https://github.com/unicode-org/icu4x/blob/main/experimental/displaynames/src/provider.rs#L21

https://github.com/unicode-org/icu4x/blob/main/provider/adapters/src/fallback/provider.rs#L27-L29

`TinyAsciiStr` itself is still validated (ASCII and null bytes check). Do we want an `UnvalidatedTinyStr`?

**Comment by sffc** [comment]
Discussion: put `UnvalidatedTinyAsciiStr` in the tinystr crate.
