### ISSUE TITLE
Automate design doc approval rules

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#25]
The [Bylaws](https://github.com/unicode-org/omnicu/blob/master/docs/bylaws.md) state that official decisions for design docs should be made at meetings with consensus.

In order to better stick to that process, we can have a Github PR bot that checks if reviewers from at least 2 member companies have reviewed the PR.  We can reuse or extend a similar Github PR bot [used for ICU PRs](https://github.com/unicode-org/jira-github-pr-check).

**Comment by sffc** [comment]
Please re-open if a more concrete use case arises.
