### ISSUE TITLE
Fix unsafe code block in utils/tinystr/src/ascii.rs

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2504]
> In general I want to move away from relying on the slice layout matching tuples (miri will eventually not like this, but also we'll have better slice APIs by then)
>
> Can you instead take `self.bytes.as_slice()` and just transmute that reference? It should work.
>
> Also, explicitly include the from/to types on the `transmute::<_,_>()` turbofish (and perhaps import `core::mem` somewhere)

_Originally posted by @Manishearth in https://github.com/unicode-org/icu4x/pull/1932#discussion_r962022351_

**Comment by robertbastian** [comment]
We can't transmute the reference because we need to change the length. And `slice::from_raw_parts` is const on >1.64 only.

I don't think adding the turbofishes when using `transmute` as a stand-in for `slice::from_raw_parts` adds any clarity.

**Comment by Manishearth** [comment]
> I don't think adding the turbofishes when using `transmute` as a stand-in for `slice::from_raw_parts` adds any clarity.

It's more from a safety redundancy POV, but we can also just wait for that to be const.

**Comment by sffc** [comment]
I think 1.61 is going to be our MSRV through 1.0. We could update it next year at 2.0.

I don't feel strongly about this; @Manishearth should reopen the issue if we want to add the turbofishes.

**Comment by Manishearth** [comment]
Hmm, that's unfortunate, since miri's not a fan of this kind of cast (though right now it's fine with it).

**Comment by sffc** [comment]
> Hmm, that's unfortunate, since miri's not a fan of this kind of cast (though right now it's fine with it).

If there's a _technical_ (not style) reason that we should upgrade past 1.61, then we should discuss it at the team meeting. My understanding is that 1.62-64 add a handful of convenience functions but nothing that can't be done in 1.61, whereas 1.61 actually adds functionality to the language that lets us achieve things we couldn't do in previous versions.

**Comment by Manishearth** [comment]
yeah it's not a style reason as much as it's _technically_ UB but not _practically_ UB and miri doesn't catch it _yet_ but might in the future. (This becomes a more annoying problem in const)

It might be fine for us to do it this way for now.
