### ISSUE TITLE
Meta Zone -> Metazone

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2507]
@Manishearth, @samchen61661, and @markusicu prefer Metazone as one word instead of Meta Zone as two words.

I have a slight preference for two words to be consistent with Time Zone, but there are valid arguments that Metazone should be one word, including:

1. "Meta" is a prefix, not an adjective (although some dictionaries do list it as an adjective)
2. UTS 35, while inconsistent, tends to use one word more often than two words

As part of this, I'd like to also make sure that camel case `MetaZone` is `Metazone` and snake case `meta_zone` is `metazone`.

**Comment by robertbastian** [comment]
I think this broke the WASM demo. The CI job shows failed right after uploading a PR, but then it disappears and I can't find it again. Anyway, this was the error.

```
TS2551: Property 'getTimeZoneOffset' does not exist on type 'Date'. Did you mean 'getTimezoneOffset'?
```
