### ISSUE TITLE
Writeable::write_len naming is confusing

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2510]
Feedback from @markusicu:

> write_len’s doc string starts with “Returns a hint…”.  Why “hint”?  Doesn’t match the function name.  Why not rename it `write_len_hint` ?  I wouldn’t use the “write_” prefix when it doesn’t actually write anything

I prefer sticking with the `write_` prefix for consistency and because `write_len` is not a function most people should be using. But I'm open to hearing what other people think.

@Manishearth 
@robertbastian 
@zbraniecki

**Comment by markusicu** [comment]
I think it's confusing to name a function write_xyz() when it does not write anything. Something like length_hint() would be better.

**Comment by Manishearth** [comment]
I would call it `writeable_len`. I agree that `write_foo()` gives off the impression it's writing something. `write_len_hint` is also fine, but really I don't think the `write_` prefix is a positive add here

**Comment by sffc** [comment]
I like `write_len_hint` but can also live with a `writeable_` prefix

**Comment by Manishearth** [comment]
In general I'd suggest that we avoid using unprefixed names for "internal" trait methods since they tend to pollute diagnostics and cause clashes.

**Comment by sffc** [comment]
Please cast your votes:

https://docs.google.com/document/d/1zm_pQsrO7kTBjHbtmoQiriFNedUyd1_AjJ2Um3u_kD4/edit#

**Comment by sffc** [comment]
I think I prefer `*_length_hint` over `*_len_hint` because the type is called LengthHint, not LenHint. I think it's weird to extend the abbreviation "len" to apply to the first word of a two-word type name. I added this as an option in the voting.

**Comment by sffc** [comment]
Also... according to https://github.com/unicode-org/icu4x/issues/1453, we had decided on `write_to_str` instead of `write_to_string`, but the PR https://github.com/unicode-org/icu4x/pull/1663 implement it as `write_to_string`. CC @echeran

**Comment by robertbastian** [comment]
Rust uses `len()`, not `length()` though.

**Comment by robertbastian** [comment]
Nice names are also nice when implementing them. And why shouldn't users call `len_hint` to unlock optimisations on their end?

**Comment by sffc** [comment]
With 4 votes cast (the four of us discussing in this thread), the fairly clear winner is `writeable_length_hint`. It has the highest average position and no vetoes.
