### ISSUE TITLE
icu_provider_fs benches are gated on features that don't exist

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2525]
In `provider/fs/benches/provider_fs.rs`, there are feature gates for `deserialize_bincode_1` and `deserialize_postcard_07`, but those features are on the icu_provider crate, not the icu_provider_fs crate.

**Comment by kelebra** [comment]
Hello, I wanted to try and fix the first issue, I hope you don't mind 😅 

It looks like introducing two features `deserialize_bincode_1` and `deserialize_postcard_07` in `provider/fs` should do the trick. I opened a PR, lmk if I am on the wrong track here. fwiw I was using `ffi` module as an existing example of the proposed solution.

**Comment by sffc** [comment]
Thanks for the contribution!

Adding the features to the icu_provider_fs crate does indeed solve the issue. I wonder if there's a way to solve it without adding more features though. I'd like to reduce the number of features floating around.

CC @Manishearth @robertbastian

**Comment by kelebra** [comment]
That's fair and was my first thought too. fwiw I could not find any way to use a feature of a dependency in `cfg` without re-declaring it in `toml`. I am not that experienced in rust fwiw so if there is a way I would love to learn about it.

**Comment by robertbastian** [comment]
The features used to be on `icu_provider_fs` but were removed, I think the idea was that clients can enable them on the `icu_provider` crate. That said, clients won't usually depend on `icu_provider` directly, so it makes sense to have them on `icu_provider_fs`.

Also, `deserialize_postcard_07` should be `deserialize_postcard_1` across the board now.

**Comment by robertbastian** [comment]
Actually to fix the benchmarks, just remove the `cfg`s. The `icu_provider` dev-dependency includes the postcard and bincode functionality.

**Comment by kelebra** [comment]
Thanks for the alternative approach @robertbastian . PR was updated.

**Comment by sffc** [comment]
Fixed by #2527
