### ISSUE TITLE
Stabilize Case Mapping

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2535]
Previous issue: https://github.com/unicode-org/icu4x/issues/1226

We need to ensure that the case mapping crate conforms to the ICU4X style guide, including documentation and FFI.

I'd also like to see whether we can make the data more zerovec-like.

CC @iainireland to add anything else that we should plan before we promote case mapping.

**Comment by Manishearth** [comment]
I finished this earlier this month
