### ISSUE TITLE
Fill in MIT copyright notices before first release

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#255]
In the `LICENSE` file, we still have "[Copyright notices to be filled in as crates are imported]" that hasn't been filled in. For Mozilla's part, our notice is "Copyright Mozilla Foundation". I'll let Googlers figure out how what should go in the copyright notice slot on Google's part.

**Comment by hsivonen** [comment]
@sffc , can you figure out what notice should go there on Google's part? Not having a year would ease future administrative burden.

**Comment by sffc** [comment]
Google is fine leaving out the year, but I looped in @alolita to advise from Unicode's perspective.

**Comment by echeran** [comment]
This issue is now unblocked, following the resolution of #252.

**Comment by hsivonen** [comment]
Was this closed accidentally? AFAICT, the `LICENSE` file still says `[Copyright notices to be filled in as crates are imported]` instead of something like

```
Copyright Mozilla Foundation
Copyright Google Inc.
```

(Google notice for illustration purposes imitated from another project--I'd still prefer Googlers to say if that's the right notice.)

**Comment by sffc** [comment]
Reopening to investigate https://github.com/unicode-org/icu4x/issues/255#issuecomment-707545362.
