### ISSUE TITLE
Cargo.toml in icu_collections has no license entry

### ISSUE THREAD

**Issue by makotokato** [unicode-org/icu4x#2559]
All? Cargo.toml adds license entry as Unicode-DFS-2016 by https://github.com/unicode-org/icu4x/pull/2303. But https://github.com/unicode-org/icu4x/blob/main/components/collections/Cargo.toml#L13 has no license entry. Is this bug?

**Comment by sffc** [comment]
Looks like a bug. @srl295

**Comment by srl295** [comment]
> Looks like a bug. @srl295 

Assign to me
