### ISSUE TITLE
Names of functions in icu_testdata

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2585]
This is a follow-up from https://github.com/unicode-org/icu4x/pull/2364#discussion_r961956445

Discussion: I would still prefer `icu_testdata::postcard()` over `icu_testdata::buffer()`. Even `icu_testdata::blob()` would be more precise.

Postcard is a special case of Blob\* which is a special case of Buffer.

We have two different types of buffer providers we can expose: the FsDataProvider JSON one and the BlobDataProvider Postcard one.

I also think naming the functions with their actual data source has educational benefit.

I feel less strongly about `icu_testdata::unstable()` vs `icu_testdata::baked()` but I would slightly prefer `::baked()` for the same reasons. It's also 3 characters shorter.

\* I realize that Blob supports only Postcard at this time.

@robertbastian

**Comment by robertbastian** [comment]
My main arguments against this were
* the symmetry of `Foo::try_new_with_buffer_provider(&icu_testdata::buffer())`
  * related: new users won't know that "Postcard is a special case of Blob* which is a special case of Buffer"
* we can change the internal representation of `icu_testdata::buffer` in the future, we shouldn't make guarantees about which serialization we use if it doesn't matter to the user

**Comment by sffc** [comment]
- @echeran - The fact that we're using postcard isn't the most important thing in the ::buffer function; we have changed the repr in the past (JSON to Postcard)
- @Manishearth - Users reading the docs shouldn't be distracted by the icu_testdata functions; the only purpose of the functions is for docs tests, anyway, so that's what the naming should be tailored to

Decision: Close this issue. Less work to do. :)
