### ISSUE TITLE
Consider naming of PluralCategory string parsing functions

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2587]
From @markusicu:

> Rename method names `from_tr35_…` to `from_uts35_…`
> Could omit the `_tr35_` infix altogether, and then just document, and maybe implement the `From<>` trait
> Could also use `from_ldml_…`
> Could also use `from_cldr_…`
> Should also change the docs for the methods accordingly
> Note: It used to be that everything was a TR, but then some things were elevated to a UTS. Then others were on the side - UAXes.  Also, the proper way to write them is “UTS #35”.  That makes it troublesome in Github markdown.  And unicode.org/reports do not show it, but the title for each TR shows the proper styling of the formal title

CC @zbraniecki

**Comment by zbraniecki** [comment]
I vote for `from_cldr` - CLDR is a better known name than UTS35 or TR35 and it's unlikely those two will diverge and we'd have CLDR with two string formats.

**Comment by sffc** [comment]
My proposal:

`pub fn try_from_cldr_id(category: &[u8]) -> Result<PluralCategory, PluralError>`

This is a parsing function, not a matching function. It corresponds to a FromStr or TryFrom impl, but with a more specific name.

OK: @zbraniecki @sffc @echeran
