### ISSUE TITLE
Add benches for data provider constructors

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2600]
The data provider constructors are a big part of our startup cost. We should measure them and improve them if possible.

I think it's fine for the tests to measure the testdata versions of the providers.

**Comment by zbraniecki** [comment]
I have initial tests from my harness against datetime component, simple datetime formatting.
Params:
 * style Medium, Medium
 * locale "en"
 * provider: StaticDataProvider (--all-keys, --all-locales): 12.4mb
 * date constructed from epoch
 * format to Rust string

Breakdown:
* ICU4C
  * constructor: 12.881 µs
  * format: 1.4387 µs
  * total: 27.600 µs
* ICU4X
  * provider: 42.943 µs
  * constructor: 6.1462 µs
  * format: 346.61 ns
  * total: 50.025 µs

Note: ICU4C total is larger than constructor+format which can be explained by caching. If I extract dtf constructor out of bench loop it probably performs some operations lazily on the first format and caches them.
ICU4X is more predictable - the total is the sum of 3 parts and extracting each one gives predictable total.

Summary - StaticDataProvider doesn't seem to be zero-cost and we should evaluate why and document it.

**Comment by zbraniecki** [comment]
(if we extract provider constructor, then ICU4C is 27us, and ICU4X is 6.4us)
