### ISSUE TITLE
PatternPlurals::expect_pattern can panic

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#2627]
In review of #2572 @sffc raised concern about `PatternPlurals::expect_pattern` being panicy.

The method has been added together with introduction of `PatternPlurals` specifically for WeekOf in #918 .

It introduced a level of complexity which is necessary for a rare case (WeekOf) but applies on all patterns, so the author, @mildgravitas introduced this extractor to avoid having to turn every caller fallible.

@sffc believes we should do it and make all uses of PatternPlurals handle plural scenario, probably gracefully fallbacking and propagate it around the codebase.

**Comment by sffc** [comment]
It doesn't need to propagate around the codebase so long as there is a reasonable default behavior. GIGO > Panic. #2351

**Comment by sffc** [comment]
For example, the code currently reads

```
    pub fn expect_pattern(self, msg: &str) -> Pattern<'data> {
        match self {
            Self::SinglePattern(pattern) => pattern,
            #[allow(clippy::panic)]
            _ => panic!("expect_pattern failed: {}", msg),
        }
    }
```

Why can't we handle it more like

```
    pub fn expect_pattern(self, msg: &str) -> Pattern<'data> {
        match self {
            Self::SinglePattern(pattern) => pattern,
            Self::MultipleVariants(plural_pattern) => plural_pattern.other()
        }
    }
```

**Comment by zbraniecki** [comment]
> Why can't we handle it more like

My argument is that if there is ever code that executes that `pick default` branch, then the developer likely made a mistake. Your suggestion will hide it.

**Comment by sffc** [comment]
> > Why can't we handle it more like
> 
> My argument is that if there is ever code that executes that `pick default` branch, then the developer likely made a mistake. Your suggestion will hide it.

Two things to pick apart here: (A) whether this is a developer mistake, and (B) what we should do if the developer makes a mistake.

On (A): I'm not convinced this is a developer mistake.

1. This is a function that returns a single pattern out of an enum that may contain multiple patterns based on plural form. The correct thing to do in that case is to return the "other" plural variant.
2. Although week formats are currently the only data that make use of plural patterns, there may be (actually, are likely to be) more such patterns added in the future. Older ICU4X code should be able to read newer data and not crash.

On (B): An unconditional panic is not the best way to inform a developer of a mistake.

1. One option is to follow the recommendation in #2351 and perform a debug panic with GIGO in release mode.
2. Another option is to check for these invariants at deserialization time.

Whether you agree with either (A) or (B), the current behavior is undesirable.
