### ISSUE TITLE
[uniset] Consider `IntoIterator<Item = char>` on UnicodeSet for ergonomics and `FromIterator` for `UnicodeSetBuilder`

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#263]
`UnicodeSet` introduces `iter()` method which allows for iteration over the characters in the `UnicodeSet`.

Since the struct *is* a set, and this iterator is the main iterator, it may make sense to implement a helper trait `IntoIterator` for it.

Many functions that operate on sets and iterators take anything that implements `IntoIterator` including `for` loops:

```rust
let s = UnicodeSet::default();
for ch in s {}
```

but also:

```rust
let s = UnicodeSet::default();
chars.append(s);
```

and so on.

It's not necessary, just a nice ergonomics boost if we want it.

In case you think you'll want to have *other* iterators coming out of it (say, over ranges etc.) then one could chose which iterator is "the default" and implement `IntoIterator` on it, and use `.iter_other_thing()` for others.
It may be even possible to specialize `IntoIterator<Item = char>` and `IntoIterator<Item = (char, char)>` or `IntoIterator<Item = Range<char>>`

**Comment by zbraniecki** [comment]
We also could consider adding `FromIterator<Item=u32>`  or `FromIterator<Item=(char, char)>` as an alternative to `from_inversion_list` to allow building the struct from an iterator.

**Comment by zbraniecki** [comment]
Actually, maybe even `FromIterator<Item=RangeBounds<char>>` to allow for `&['A'..'F', 'X'..'Z'].into()`

**Comment by zbraniecki** [comment]
Actually, educating myself more on the topic, the `FromIterator` may be better for `UnicodeSetBuilder`, than `UnicodeSet`.

**Comment by sffc** [comment]
The problem with IntoIterator is that it consumes `self`.  As far as I understand, it's better to have a function that returns an Iterator as long as `self` isn't consumed.

**Comment by sffc** [comment]
2020-11-12: We won't do this because iterating over all chars in a UnicodeSet isn't intended to be a common use case.
