### ISSUE TITLE
Do we need the icu::datetime::input module?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2630]
[icu](https://unicode-org.github.io/icu4x-docs/doc/icu/index.html)::[datetime](https://unicode-org.github.io/icu4x-docs/doc/icu/datetime/index.html)::[input](https://unicode-org.github.io/icu4x-docs/doc/icu/datetime/input/index.html#) looks basically the same as [icu_calendar](https://unicode-org.github.io/icu4x-docs/doc/icu_calendar/index.html)::[types](https://unicode-org.github.io/icu4x-docs/doc/icu_calendar/types/index.html#). Is this intentional? Or were we supposed to migrate to the icu::calendar versions of the types?

@Manishearth

**Comment by Manishearth** [comment]
Those are all reexports I think; we should get rid of them. It made more sense in the past.

We need the module for the `FooInput` traits and a couple other small things, nothing else.

**Comment by sffc** [comment]
Indeed, there is a comment in the code that says

```
// TODO (Manishearth) fix up imports to directly import from icu_calendar
```

but with no issue linked.

I'm making a PR to remove the public re-export for 1.0 and updating the TODO to point to this issue to clean it up in the code later with lower priority.
