### ISSUE TITLE
Is it wrong to return DataError instead of crate errors?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2639]
Something like half of our functions that take a DataProvider and return a `Result` return the `DataError` directly. Is this correct, or should we be wrapping the `DataError` in the crate's error type for consistency and extensibility?

@Manishearth @zbraniecki

**Comment by sffc** [comment]
This is related to one of our oldest issues that remains unresolved: https://github.com/unicode-org/icu4x/issues/153

**Comment by Manishearth** [comment]
I think it's fine to return the most specific error. I think we should be wary of having a crate return too many different error types, but "DataError + CrateError + fmt::Error" seems rather fine, and they can Into into each other.

**Comment by sffc** [comment]
My concern is that if a constructor returns DataError, but in the future we add more features, we might need to return a different type of error, and it's more extensible to use an error enum, even if for now it has only 1 variant.

**Comment by Manishearth** [comment]
Ah, that's fair and a reasonable reason to not use DataError.
