### ISSUE TITLE
[uniset] Document that UnicodeSet::contains_range returns different result from ICU4C

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#264]
```rust
let best_ex = vec![65, 70];
let best_sample = UnicodeSet::from_inversion_list(best_ex).unwrap();
best_sample.contains_range(&('A'..'A');  // false
```

```cpp
auto bestSample = new icu::UnicodeSet('A', 'F')
bestSample->contains('A', 'A');  // true
```

**Comment by zbraniecki** [comment]
This may be intentional, since:

```rust
let best_ex = vec![65, 70];
let best_sample = UnicodeSet::from_inversion_list(best_ex).unwrap();
best_sample.contains_range(&('A'..='A');  // true
```

If that's the case, it would be good to document that discrepancy

**Comment by filmil** [comment]
This may be WAI, since the Rust range is half-open, while the `UnicodeSet::contains` range is closed per the [documentation for `contains`][doc]

[doc]: https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1UnicodeSet.html#a962122dc4ef08a350279bd34a46223c3

**Comment by zbraniecki** [comment]
There's also a discrepancy on the worst_caste range scenario:

```cpp
    auto worstSample = new icu::UnicodeSet(0, 1);
    for (u_int32_t i = 2; i < 1114111 + 1; i+=2) {
        worstSample->add(i, i+1);
    }

    auto total = 0;
    for (u_int32_t i = 0; i < 100; i++) {
        auto c = worstSample->charAt(i);
        if (worstSample->contains(0, c)) {
            total += 1;
        }
    }
    
    total; // 100
```

```rust
    let worst_ex: Vec<u32> = (0..((char::MAX as u32) + 1)).collect();
    let worst_sample = UnicodeSet::from_inversion_list(worst_ex).unwrap();

    let zero = char::from_u32(0).unwrap();

    for c in worst_sample.iter().take(100) {
        if worst_sample.contains_range(&(zero..c)) {
            total += 1;
        }
    }

    total; // 0
```

**Comment by zbraniecki** [comment]
Ah, it's the same issue.

In C++ `worstSample->contains(0, 0)` returns `true`, while in Rust it returns `false`.

**Comment by EvanJP** [comment]
As @filmil I believe we concluded this works as intended? Should we close or is there still an issue to be had?

**Comment by echeran** [comment]
mtg discussion:  given the above discussion, this basically entails adds documentation that indicates difference in behavior between ICU4C/J and ICU4X, since it is significant enough
