### ISSUE TITLE
`icu_segmenter` feature doesn't work for datagen

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#2664]
We would like to be able to generate data with `icu_segmenter` but without other experimental features.

Unfortunately, in several places we gate datagen on `experimental` making it all-or-nothing:

* https://github.com/unicode-org/icu4x/blob/ed5f96813c6e9a7366bb6cc848846beacff35c94/provider/datagen/src/registry.rs#L23
* https://github.com/unicode-org/icu4x/blob/main/provider/datagen/src/transform/mod.rs#L7
* https://github.com/unicode-org/icu4x/blob/ed5f96813c6e9a7366bb6cc848846beacff35c94/provider/datagen/src/registry.rs#L188

The first two are easy to fix, but the last one is a macro in a macro in a macro. I tried to generalize `registry!` to accept number of feature gated blocks, but then I need to branch off depending on which features are on and off and it doesn't carry over well.

Once we have statements in attributes ( https://github.com/rust-lang/rust/issues/15701 ) we should be able to make it work, but for now, I'm not sure how to resolve the macro branches to enable segmenter without enabling other experimental features.

**Comment by Manishearth** [comment]
In general our "public" features tend to be the ones in the features list, not the extra ones that appear due to having optional dependencies. I don't think we've _so far_ attempted to have per-component gating, though I do want this eventually, and I want it for

 - `icu`
 - `icu_capi`
 - `icu_datagen`
 - maybe even `icu_testdata` though i care less about that

**Comment by Manishearth** [comment]
(I'd prefer we file a catch-all issue about that and close this one)

**Comment by zbraniecki** [comment]
I prefer to keep this one because catch-all may require much more work and this one currently makes it hard/impossible to measure Segmenter without affecting DateTime (Shane says that enabling experimental datetime feature affects performance of datetime).

**Comment by Manishearth** [comment]
@zbraniecki that's for datetime-the-component, not datetime-the-datagen. no?

for datetime-the-datagen you just get extra data you won't need. If you're measuring segmenter you probably aren't generating datetime data anyway

**Comment by Manishearth** [comment]
For benchmarking I would suggest:

 - Run icu4x-datagen with `--experimental` but specific keys listed, that way it won't generate a bunch of the random nonsense
 - Benchmark individual crates with data generated for them only

**Comment by zbraniecki** [comment]
> @zbraniecki that's for datetime-the-component, not datetime-the-datagen. no?

I'm not sure how the experimental feature affects keys. If the datagen `experimental` does not affect the performance of datetime, then I'm comfortable with moving this to catch-all issue.

**Comment by Manishearth** [comment]
Yes, that's the case. Turning `experimental` in datagen will enable support for more keys (and build them if you're using `--all-keys`), but it doesn't change existing ones

**Comment by sffc** [comment]
@Manishearth Please triage or close this issue.

**Comment by Manishearth** [comment]
This issue arises from a misunderstanding of what the experimental feature does, and a perceived tradeoff about experimental datagen: experimental datagen simply enables more keys, it does not change datagen's behavior for the existing keys. The main tradeoff is in compile time of building datagen.

Closing, but opened https://github.com/unicode-org/icu4x/issues/2754 for improving docs
