### ISSUE TITLE
[uniset] Should `UnicodeSetBuilder::add_range` accept owned `RangeBounds`?

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#267]
At the moment `add_range` accepts a reference to range bound which, when written by hand, looks like this:

```rust
let mut builder = UnicodeSetBuilder::new();
builder.add_range(&('A'..='F'));
```

What are the common use cases here? Is it common that user will store the ranges somewhere on a vec and then do:

```rust
let mut builder = UnicodeSetBuilder::new();
for r in ranges {
    builder.add_range(r);
}
```

in which case the reference makes sense to avoid asking them to `clone`?

If not, if this API is mostly useful by hand, then I think it doesn't really buy us anything, and it costs ergonomics. We could switch to `impl RangeBounds` and get:

```rust
let mut builder = UnicodeSetBuilder::new();
builder.add_range('A'..='F');
```

**Comment by zbraniecki** [comment]
@Manishearth I know `Range` ergonomics and lack of `Copy` is a hot issue. Is there a natural way to accept both? I tried `AsRef<impl RangeBounds<char>>` and `Borrow<impl RangeBounds<char>>` but it complains about lack of annotations when passing `&('A'..='F')`.

**Comment by zbraniecki** [comment]
Same question about `contains_range` which also accepts reference.

I know there are some APIs in Rust stdlib that require reference even on copy values (`contains` of collections of copy values), so maybe we should stick to it?

**Comment by Manishearth** [comment]
@zbraniecki i think it is okay for people to have to `.clone()` ranges (it's a cheap stack copy). I suspect most people will use this API with literals, not something from an array

**Comment by sffc** [comment]
This question came up during the code review.  I prefer starting with the correct type rather than the ergonomic type, and when we get real users, we can judge whether the ergonomic type is worthwhile.

In this case, a borrow is more technically correct than a move, since we do not need to take ownership of the range for any reason.

**Comment by sffc** [comment]
In terms of use cases for the method: as I've said before, I do not think most people are actually going to use UnicodeSetBuilder in real code.  If anything, they will start with pre-built UnicodeSets from #217 and union them together to suit their needs.  Therefore, most of the callers of this method will be ICU4X-internal, or perhaps low-level crates building on top of ICU4X like a potential IDNA or BiDi crate.

**Comment by Manishearth** [comment]
It occurs to me: perhaps RangeBounds should be implemented on &T where T implements RangeBounds? Might be worth proposing that.

**Comment by Manishearth** [comment]
> In this case, a borrow is more technically correct than a move, since we do not need to take ownership of the range for any reason.

I kind of feel like this is splitting hairs since the range is not conceptually an "owned" type, it is a value type that happens to not be `Copy` because of footguns involving copyable iterators. It's the same question as whether a function should borrow or "move" an integer, except we never ask that because integers are `Copy`.

But I don't hold strong opinions on this

**Comment by sffc** [comment]
The difference is that RangeBounds is a trait that could be implemented by third-party structs that aren't necessarily `Copy`.  It's silly to borrow an i32, but it's not silly to borrow a trait object.

**Comment by Manishearth** [comment]
Oh, that's fair. In that case, yes, we should borrow.

**Comment by zbraniecki** [comment]
thank you! closing.
