### ISSUE TITLE
Data generation part of intro needs more detail

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#2676]
https://github.com/unicode-org/icu4x/blob/main/docs/tutorials/intro.md#generating-data is not complete enough for the reader to learn how to actually get all the details in such an order that their app can use generated data a) as postcard or b) as baked instead of `icu_testdata`.

The doc needs more text, either inline or by reference to another doc, to give a step-by-step guide for getting to the point of using ICU4X with data as designed (i.e. postcard or baked).

**Comment by robertbastian** [comment]
Fixed by #2678
