### ISSUE TITLE
Remove icu_segmenter_lstm on crates.io or redirect it to icu_segmenter (crate graveyard)

### ISSUE THREAD

**Issue by aethanyc** [unicode-org/icu4x#2682]
https://crates.io/crates/icu_segmenter_lstm/ was a standalone crate, but it has been merged into segmenter crate in #2087. We should probably remove it from crates.io or redirect it to https://crates.io/crates/icu_segmenter.

cc @Manishearth @sffc who are familiar with crate publishing.

**Comment by Manishearth** [comment]
I think the thing to do would be to make a PR adding an `icu_segmenter_lstm` crate to `experimental/` that fails to build in non-doc mode and redirects you to the new crate (see https://github.com/unicode-org/icu4x/pull/2681).

And then another PR removing it entirely.

**Comment by Manishearth** [comment]
Basically, any published crate must be published from main, and to get something published you should just make a PR and cc someone with publish access to review and publish it (I can be that person).

For hard-deprecating crates; we can use the two-step process above. We don't _have_ to do the failing build script (@sffc , @zbraniecki , thoughts?)

**Comment by sffc** [comment]
We have many crates with this issue. We should discuss to decide what to do.

**Comment by sffc** [comment]
Discuss with:

- @robertbastian 
- @sffc 
- @Manishearth 

@echeran says that we should focus on documentation on crates.io; doesn't need to be part of the discussion

**Comment by Manishearth** [comment]
Proposal: we  do this for each one of them


> I think the thing to do would be to make a PR adding an icu_segmenter_lstm crate to experimental/ that fails to build in non-doc mode and redirects you to the new crate (see https://github.com/unicode-org/icu4x/pull/2681).
> 
> And then another PR removing it entirely.


and document it in our process.

**Comment by sffc** [comment]
Can we make a place to permanently keep graveyard crates? So we don't need to look up in the history how to do this each time?

Maybe in an empty branch in this repo or in icu4x-docs or under tools

**Comment by robertbastian** [comment]
Let's not use a separate branch when a folder in the main branch will do. We only need a single graveyard crate whose name we can change whenever we need to kill a crate.

**Comment by Manishearth** [comment]
That works for me too. I don't really want to have a folder that accumulates graveyard crates, but one crate will do.

**Comment by sffc** [comment]
`/tools/graveyard` as the crate root?

**Comment by robertbastian** [comment]
Works for me

**Comment by Manishearth** [comment]
yep
