### ISSUE TITLE
Test to lock and audit runtime dependencies

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#2697]
I just found this whilst running `cargo tree`: https://github.com/unicode-org/icu4x/pull/2696

We should use `cargo tree -e no-build,no-dev,no-proc-macro` to ensure that:

 - `icu`, `icu_provider_blob`, `icu_provider_adapters`, `icu_provider_fs` don't have unapproved runtime dependencies
 - `--features serde`, `--features experimental`, `--features deserialize_foo` when applied to relevant crates above also do not have unapproved runtime deps for those features

We could also audit build/proc deps if we really want, though that might be more work.

This test should probably be written in Rust instead of duckscript.

**Comment by sffc** [comment]
Can we check in the output of `cargo tree` and enforce it via a diff, or are we getting to have too many of these diff-based checks in our repo?

**Comment by Manishearth** [comment]
@sffc we could, but then that will break each time we add a dependency between any existing component and any other existing component I can easily imagine the serde change slipping through review.

IMO it's more robust if we have a small list that changes very very rarely so that it's super easy to audit.

**Comment by sffc** [comment]
> I can easily imagine the serde change slipping through review

Yep, ok, I'm convinced.  An error like "disallowed dependency 'serde' us now required by the 'icu' crate" is more actionable by a diverse team moving forward than a diff to a cargo tree file that you likely ignore along with the Cargo.lock file.

**Comment by Manishearth** [comment]
I'll probably get around to this at some point.

This will be our first non-datagen test written in Rust: I'm wondering if we should take the opportunity to do the same for licensecheck since it's kinda awkward in duckscript.

**Comment by Manishearth** [comment]
What I might do is write this test and then file a help-wanted for licensecheck.

**Comment by Manishearth** [comment]
so one thing I'm hoping to do is to start a new crate under `tools/` that can run a lot of tests like this. Eventually licenseck should move there too.

Do we want it to have minimal deps? This tool, for example, can totally be written with _just_ `cargo tree` (parse the 
 tree output), however it is probably more robust if written on top of `cargo guppy`, which can do what `cargo tree` does but has a nice Rust API.

It would certainly be ideal to make it so that this tool can be compiled an run quickly. We can shove more of the tidy tasks into it then.

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/3079
