### ISSUE TITLE
Exclude zh-u-co-gb2312 and zh-u-co-big5han from generated data (at least by default)

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#2709]
1. Run `icu4x-datagen --cldr-tag latest --icuexport-tag latest --out my-data --format dir --all-keys --all-locales`
2. Run `find my-data/ | grep unihan | xargs ls -lh`)
2. Run `find my-data/ | grep big5han | xargs ls -lh`)
3. Run `find my-data/ | grep gb2312 | xargs ls -lh`)

`*-u-co-unihan`, `zh-u-co-gb2312`, and `zh-u-co-big5han` collations are generated.

[Chromium filters these out](https://source.chromium.org/chromium/chromium/src/+/main:third_party/icu/filters/common.json;l=1295;drc=bbdc7d8936bd9b896ff9c9822b697554b73c1c9d) with the comment "big5han and gb2312han collation do not make any sense and nobody uses them."

`icu4x-datagen` should have an easy way to optimize data size by excluding these on the assumption that Chromium is correctly reflective of user demand for these collations. (It should probably also be possible to exclude `big5han` and `gb2312` without excluding `unihan`.)

**Comment by hsivonen** [comment]
CC @FrankYFTang who applied the Chromium filter according to blame.

**Comment by hsivonen** [comment]
There is some discussion in https://unicode-org.atlassian.net/browse/CLDR-2319 that didn't result in removal of `ja-u-co-unihan` and `ko-u-co-unihan` from CLDR.

**Comment by hsivonen** [comment]
> There is some discussion in https://unicode-org.atlassian.net/browse/CLDR-2319 that didn't result in removal of `ja-u-co-unihan` and `ko-u-co-unihan` from CLDR.

So in the CLDR issue, the discussion indicated that `unihan` for Chinese was considered important but `unihan` for Japanese and Korean less so. OTOH, it turns out that Chromium filters excludes `zh-u-co-unihan` but retains `ja-u-co-unihan` and `ko-u-co-unihan`. [Demo](https://hsivonen.com/test/moz/zh-collations.html)

**Comment by markusicu** [comment]
About the `unihan` tailorings:

They are relatively small since I pushed the radical-stroke order of Han ideographs into the CLDR collation root (CLDR-7176).

The UCA-default "implicit" order of Han characters is by (a) Unicode Han block and then (b) code point. Important here is that within each block the characters were assigned in radical-stroke order, and the original Unicode Han block (4E00..9FFF) includes the ideographs that are most commonly used in CN/TW/JA/KR.

That is, for many common characters the "implicit" order *is* the radical-stroke order.

This is not true for a few hundred characters in the original Han block that had bugs in their radical-stroke values; and the implicit order of ideographs in other Han blocks (and those added later to the end of the original block) relative to the ones in the original block is useless.

The version of the root collation with the real radical-stroke order is based on the latest radical-stroke character properties data. It is a slight permutation of the original Han block, with all of the other 70k or so (and growing) ideographs interleaved.

**Comment by markusicu** [comment]
About the zh-u-co-gb2312, and zh-u-co-big5han collation tailorings: I just submitted https://unicode-org.atlassian.net/browse/CLDR-16062 “consider removing the zh-u-co-gb2312, and zh-u-co-big5han collation tailorings”

**Comment by hsivonen** [comment]
> About the zh-u-co-gb2312, and zh-u-co-big5han collation tailorings: I just submitted https://unicode-org.atlassian.net/browse/CLDR-16062 “consider removing the zh-u-co-gb2312, and zh-u-co-big5han collation tailorings”

Thank you.

If it seems that the removal discussion on the CLDR side doesn't turn up use cases, perhaps the way forward on the ICU4X side until a CLDR version that removes zh-u-co-gb2312 and zh-u-co-big5han is to add a special-case exclusion to datagen.

`unihan` at least has the dictionary connection even if not popular as a digital dictionary search result sort order as opposed to a paper dictionary index order and the `*-u-co-unihan` tailorings are small enough that I guess they don't belong in this issue. Resummarizing the issue to scope this to zh-u-co-gb2312 and zh-u-co-big5han.

**Comment by FrankYFTang** [comment]
> CC @FrankYFTang who applied the Chromium filter according to blame.

The filtering was there in different form before I moved to the ICU Data fileter rule. I am not sure how useful to keep them around. But I could see some usage of it althought which may not be important at all anyway.

**Comment by sffc** [comment]
How about a new flag `--include-extended-collations gb2312,big5han,search,searchlj` and fix #2709 at the same time?

**Comment by sffc** [comment]
A few API design questions:

1. Should we by default have an includelist or excludelist of collations that we apply to the ones that come in from icuexportdata?
2. What should we name the options to include or exclude more things on the datagen command line?
3. Is there a better way to design this includelist/excludelist-with-config?

**Comment by hsivonen** [comment]
> How about a new flag `--include-extended-collations gb2312,big5han,search,searchjl` and fix #2709 at the same time?

Seems good to me.

> Should we by default have an includelist or excludelist of collations that we apply to the ones that come in from icuexportdata?

I think we should exclude `*-gb2312`, `*-big5han`, and `*-search*` by default instead of having an include list by default so as not to forget to add a new `standard` collation to an include list when CLDR adds support for another language.

**Comment by markusicu** [comment]
I wouldn't control the search tailorings with the same flag as the legacy tailorings.
Excluding both sets by default is fine, but it should be easy to include search tailorings without legacy ones.

**Comment by sffc** [comment]
Maybe something like this?

```
--include-search-collations
--include-more-collations big5han,gb2312
```

In the future, add something like:

```
--include-specific-locales zh-u-co-big5han,ko-u-co-searchjl,ar-u-ca-islamicc
```
