### ISSUE TITLE
Declare `to_string` a code smell in the style guide and lint for it

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#2711]
`to_string` pulls in `fmt::Display`'s formatting code, which we want to avoid for code size reasons. Currently we use `to_string` on (at least) the following types:

1) `&String` -> can be `Clone::clone`
1) `&str` -> can be `String::from`, or `ToOwned::into_owned`
1) `char` -> can be `String::from`
1) our output types -> should be `Writeable::write_to_string` (followed by `into_owned` if needed)
1) `std` types -> `to_string` should probably be justified at each call site. For some types (e.g. `usize`), `writeable` can be used, for others (e.g. `Path`), the code size hit is probably not relevant

(1) - (3) actually don't pull in `fmt`, as they are specialized impls that don't go through `Display`. However, we should be explicit about this and use the alternatives. Also, `&&str` for example isn't specialized.

We also have doc tests that compare items (such as `Locale`s) by comparing their string representation. I think that's a bad practice as well, both because it doesn't check structural equality, and because it teaches our users to use `.to_string()`. Those should be changed to test for structural equality.

We can use `clippy::disallowed_methods` to enforce this

**Comment by zbraniecki** [comment]
Are you suggesting avoiding `to_string` in lib code, or in examples/tutorials?

For tutorials/examples I think pulling `Display` in is acceptable, as it's a convenience method and anyone caring about size to the point where that would matter can be expected to understand that tradeoff and be able to inspect the payload and recognize that why `Display` is pulled in.

**Comment by robertbastian** [comment]
Both really. Internally we should definitely use writeable, but even in docs we should advertise our better way of creating strings. `to_string()` will work if people use it, but they should be familiar with `write_to_string`

**Comment by sffc** [comment]
+1 to avoid `to_string` at least in library code.

In docs examples, we should avoid the question by testing `format_to_string` or using `assert_writeable_eq` when available. In cases where converting to a string is unavoidable, I have a preference for `write_to_string`.

> We also have doc tests that compare items (such as Locales) by comparing their string representation. I think that's a bad practice as well, both because it doesn't check structural equality, and because it teaches our users to use .to_string(). Those should be changed to test for structural equality.

There are cases where string equality testing is more clear and robust; perhaps some of these should change to structural equality, but "avoid string comparison at all cost" is not a generally applicable principle.

**Comment by Manishearth** [comment]
(2) also doesn't pull in fmt fwiw

ToString internally uses specialization; so it's only non-stdlib types that have this problem

**Comment by robertbastian** [comment]
(2) is included in (1) - (3) 😉 

Relying on specialization is iffy, because things like `&&str`, which you can accidentally get in iterators for example isn't specialized.

**Comment by Manishearth** [comment]
In that case can we use ToOwned over String::from? Postfix syntax tends to be nicer and composes better, and we'd have smaller diffs.

**Comment by Manishearth** [comment]
We could also probably get a clippy lint that lints for non-specialized ToString impls.

**Comment by robertbastian** [comment]
I think `ToOwned` isn't in the `#[no_std]` prelude, so it would have to be imported explicitly or called as `ToOwned::to_owned(str)`.

Disallowing `to_string` and using alternatives is basically that lint. There isn't one that distinguishes between specialized and non-specialized invocations, and even with a lint this is not obvious to a reader.

**Comment by Manishearth** [comment]
I'd rather import it than using String::from

> There isn't one that distinguishes between specialized and non-specialized invocations

there could be, though, this would not be hard to write in clippy

**Comment by robertbastian** [comment]
`"foo".into()` (or `"foo".into::<String>()` if the type can't be inferred) is another alternative that requires no imports.

**Comment by robertbastian** [comment]
Alright, `into()` is annoying when the type cannot be inferred, and also hides the allocation more than `to_owned()`, so I'll go with that.

**Comment by robertbastian** [comment]
Style guide suggestion:

---

### Avoid `to_string` :: suggested

`to_string` delegates to the `Display` trait which is bad for code size as it pulls in a lot of formatting code.

There are three types on which the standard library has *specialized implementations* for `to_string` that do not go through formatting logic: `&str`, `String`, and `char`. It would generally be acceptable to use `to_string` on these types, however types might not always be obvious to a reader, and implicit types might change with surrounding code (such as from `&str` to `&&str`, which is *not specialized*), so use `str::to_owned`, `String::clone`, and `String::from(char)` for clarity.

Any other invocation of `to_string` should be carefully evaluated. It is usually better to work with values that implement `Display` and/or `Writeable` than to eagerly format and allocate strings.

When comparing items in unit tests or docs, prefer semantic equality over stringified equality.

**Comment by robertbastian** [comment]
Fixed by #2727

**Comment by robertbastian** [comment]
Interesting ACP related to this: https://github.com/rust-lang/libs-team/issues/363
