### ISSUE TITLE
Fuzz the calendars crate

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#2713]
We have a lot of bugs like #2254, https://github.com/unicode-org/icu4x/pull/2704, https://github.com/unicode-org/icu4x/issues/2703

We should use [`cargo fuzz`](https://rust-fuzz.github.io/book/cargo-fuzz.html) to write fuzzers that:

 - Test that calendar conversions roundtrip
 - Test that calendar arithmetic APIs work

`cargo fuzz` is super easy to use and does expected type conversion for you; which ought to be highly useful for this.

For the roundtrip tests we can either write one test per calendar, or perhaps have an `Arbitrary`-deriving enum that selects between calendars (we could also use AnyCalendarKind for this but then it would have to impl `Arbitrary` behind a feature)

**Comment by sffc** [comment]
Here are some more good links on fuzzing in Rust:

https://rust-fuzz.github.io/book/

https://google.github.io/oss-fuzz/getting-started/new-project-guide/rust-lang/
