### ISSUE TITLE
Consider using TinyStr keys in era symbol data

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#2725]
https://github.com/unicode-org/icu4x/blob/f0592c39779594403fd7704a8911d44f8315c251/components/datetime/src/provider/calendar/symbols.rs#L92-L108

This code is using `ZeroMap<str, str>`, however era codes are always TinyStr16. TinyStr lookups tend to be faster; and usually take up less codesize/data size. It might be worth investigating this.

For non-Japanese calendars the `str` ZeroMap might still be shorter since there are only 1-2 eras, which amounts to just six bytes extra for the VZV metadata, but the TinyStr16 version will end up paying the sixteen byte size cost each time.

VZV lookup is still far more code than ZV lookup so we would win on binary size.

This would be a breaking change (unless done with some kind of enum situation; tricky), so can only be considered for 2.0.

**Comment by sffc** [comment]
I vote for `UnvalidatedStr`.

We can make that change without touching the serialization format. Does that mean it's something we can change now?

**Comment by sffc** [comment]
We use VZVs everywhere, and when they are a ZM key, they should ideally use `[u8]` or `UnvalidatedStr`. So I would hope for code size to not be a problem. Date formatting as a whole is fairly code-heavy anyway.

**Comment by Manishearth** [comment]
We can make that change, I'd actually argue for `[u8]` since there is no need to _ever_ validate

(TinyStr might need a PartialEq impl with byte slices if it doesn't already)

**Comment by sffc** [comment]
UnvalidatedStr is better than [u8] because JSON is nicer.

**Comment by Manishearth** [comment]
oh right. And we can just access it as a slice

**Comment by Manishearth** [comment]
A slight issue is that our provider types are fully public; so this would technically affect that. How stable do we consider manually constructing provider types?

**Comment by sffc** [comment]
We decided in https://github.com/unicode-org/icu4x/issues/2749 that we can change the API of the data structs so long as the serialization format remains stable. This means we can swap str for UnvalidatedStr.

**Comment by sffc** [comment]
@Manishearth to make this a good first issue and post instructions on how to proceed.

**Comment by Manishearth** [comment]
Essentially, the fix here is to replace the `str, str` in the code listed below with `UnvalidatedStr, UnvalidatedStr` from [here](https://icu4x.unicode.org/doc/zerovec/ule/struct.UnvalidatedStr.html)

https://github.com/unicode-org/icu4x/blob/f0592c39779594403fd7704a8911d44f8315c251/components/datetime/src/provider/calendar/symbols.rs#L92-L108

This will need this code to be changed, and then code using it in the same crate will have to compare it using `as_bytes()`.

Datagen will need to be changed to produce these instead of strings.
