### ISSUE TITLE
Fix benchmark CI job data branch for merges to main

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#2735]
## Background

Github uses the `gh-pages` branch as a special branch for people to store content for Github's implicit static website service.

The [Github Action for continuous benchmarks](https://github.com/marketplace/actions/continuous-benchmark) that we're using requires a branch in the repo in which to store the historical benchmark data.  That action was also created with the assumption that the repo using the action will want to serve its benchmarks as its main website, and that such a website will be served from the `gh-pages` branch.  So that action for continuous benchmarks uses `gh-pages` as the default branch, and includes it in its setup instructions.

Using `gh-pages` to store historical benchmark data had 2 problems:

1. We wanted to exclude data points from work-in-progress PRs from inclusion in the benchmark graphs, but yet still run the benchmarks on those PRs to flag potential alerts to size/time increases during development, and also have the rest of the CI jobs run the same on WIP PRs and post-merge commits.  So we needed 2 branches for historical data so that the post-merge-to-main data remains clean
2. We created the `icu4x-docs` repo to store API docs, similar to what ICU does, which allows the main `icu4x` repo to be able to create a landing page website in the future. Such a future website would probably be served out of `gh-pages`

## Issue

Currently, the work-in-progress PRs use the [`unmerged-pr-bench-data` branch](https://github.com/unicode-org/icu4x/blob/main/.github/workflows/build-test.yml#L715).  But post-merge CI instances use the [`gh-pages` branch](https://github.com/unicode-org/icu4x/blob/main/.github/workflows/build-test.yml#L737), which is inconsistent and problematic.

This can be cleaned up by:

- [ ] clone the current state of `gh-pages` into a new branch. let's call it `merged-bench-data`
- [ ] ensure no other commits to main
- [ ] change all instances of `gh-pages-branch: gh-pages` to `gh-pages-branch: merged-bench-data`
- [ ] change [`git checkout gh-pages`](https://github.com/unicode-org/icu4x/blob/main/.github/workflows/build-test.yml#L1108) to `git checkout merged-bench-data` when collecting docs to copy to the `icu4x-docs` repo

@robertbastian @Manishearth @sffc

**Comment by robertbastian** [comment]
> We wanted to exclude data points from work-in-progress PRs from inclusion in the benchmark graphs, but yet still run the benchmarks on those PRs to flag potential alerts to size/time increases during development, and also have the rest of the CI jobs run the same on WIP PRs and post-merge commits. So we needed 2 branches for historical data so that the post-merge-to-main data remains clean

CI knows whether it's running on an unsubmitted PR or a commit to main. Can't we just disable to output in the former case?

> We created the icu4x-docs repo to store API docs, similar to what ICU does, which allows the main icu4x repo to be able to create a landing page website in the future. Such a future website would probably be served out of gh-pages

Wouldn't a future landing page also want to host docs? Do we need to distinguish between ICU4X's website, and the current website which is just docs?

**Comment by echeran** [comment]
> CI knows whether it's running on an unsubmitted PR or a commit to main. Can't we just disable to output in the former case?

There's not enough granularity in the controls for the continuous benchmark action to do that.  All in one go, it will:  run the benchmark command, format the output into JSON, and store it in the configured branch.  (It also initializes a lightweight HTML page, if it doesn't already exist, that creates the dashboards by reading in and stylizing that JSON file.)  If you don't give it a branch, the action won't run.  All we do conditionally for unsubmitted PRs is to avoid doing copying the output to the place we look at.

> Wouldn't a future landing page also want to host docs? Do we need to distinguish between ICU4X's website, and the current website which is just docs?

By "docs", we could either mean API docs or other types of documentation.

If you mean API docs, then in the ideal case, yes, but I don't know how feasible that is.  `rust doc` is a static site generator.  At the same time, the most likely way to create a nice landing site would also be through a static site generator (ex: Hugo, Jekyll).  Ex: [the ICU User Guide](https://unicode-org.github.io/icu/) uses a Jekyll theme because Github Pages has built-in support for Jeykll-based generated static sites.  Hugo and Jekyll take Markdown as input for pages, a site wide theme, and generate all the static pages from them.  Is there a way for the output of Rustdoc to be in the form that Jekyll/Hugo/etc. could use?  That's the part that I'm not sure about.  ([`cargo-rdme`](https://github.com/orium/cargo-rdme) seems to only handle crate-level conversion of Rustdoc to Markdown, but doing so for API docs might remove the navigational coolness that makes Rust API docs pages really nice.)

But if by "docs", you mean other types of documentation, like tutorials, explainers, FAQs, etc., then the landing page could very well host that.  The [demo/example site for Docsy](https://example.docsy.dev/docs/) exemplifies that.  Such content is stuff that we can & already do author directly in Markdown.

**Comment by robertbastian** [comment]
> Is there a way for the output of Rustdoc to be in the form that Jekyll/Hugo/etc. could use?

Yes, static HTML. Jekyll is able to compile markdown to html, but if you give it an html file it will just pass it through.
