### ISSUE TITLE
FixedDecimal panics on parsing fractional value without leading "0"

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/icu4x#2739]
The project icu-conformance has revealed a problem with parsing a string to a Fixed decimal. Here's the code that is failing:

    // TODO: Handle if the parsing to a number fails.
    let input_num: FixedDecimal = input.parse().expect("valid input format");
    let result_string = fdf.format(&input_num);

Below is the code which works with all strings such as "0.1234". However it fails when input is one of these 4 string inputs:
"0.01"
".00123456"
".0012345678"
".0012300000"
These 4  are the only test inputs out of 7000+ in the data set that omit a zero before the decimal. When I manually prepend "0." to each of them the panics go away (see below).

Here's the panic output
!!!!! processBatchOfTests: "platform error": "!!!! ERROR IN EXECUTION: 101. STDERR = thread 'main' panicked at 'valid input format: Syntax', src/numberfmt.rs:46:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: executor::numberfmt::run_numberformat_test
   4: executor::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
"

This looks like a serious bug in the parsing for FixedDecimal.

**Comment by sffc** [comment]
This isn't a bug in ICU4X; it returns an `Error` result from the parse function, and the executor is incorrectly unwrapping that result. At least, what should be done here is that the executor should print an error message.

Now, regarding the actual behavior, as far as I know, there is no specification in UTS 35 that says exactly what _input_ decimal syntaxes are allowed. I think ICU4C uses the `decNumber` syntax, and Node.js uses the `StringNumericLiteral` syntax. ICU4X uses a third variant of this syntax, which apparently requires a leading `0`.

A couple outcomes:

1. The conformance test could cite a syntax for input decimal strings and declare that conformant UTS 35 implementations must obey that syntax. Then, the bug becomes that ICU4X is not conforming to that spec.
2. Without that requirement, the ICU4X executor wrapper could modify the string to conform to ICU4X's syntax.

**Comment by Manishearth** [comment]
The way I see it both possible behaviors make sense based on use cases, omitting the leading zero is a syntax that is accepted in some cases but not always.

So to me there are two things we can do here:

 - Retain current behavior, and document it
   - People who wish to handle `.1234` must check for it and manually prepend a `0`. @sven-oly you can do this in your error handling code if you desire.
 - Handle `.1234`, document it
    - People who wish to _not_ handle `.1234` can check for it and reject it

I prefer the second option since the complexity impact on people doing it the other way is minimal.

There is a potential for the second option being slower for everyone involved. I _suspect_ that won't be the case but we should try implementing it and seeing what complexity it introduces. AIUI it shouldn't be a big deal.

**Comment by sffc** [comment]
- @sffc - I want to emphasize that this is the grammar for FixedDecimal, not FixedDecimalFormatter output, which would be free-form localized parsing.
- @sffc - If we go for lenient parsing, should we go all the way to ECMA-402 StringNumericLiteral? Note that this code path is used by Ryu. We should avoid adding complexity to the parsing code.
- @zbraniecki - FixedDecimal should be minimal. I can't see a rational compelling reason to drop the leading zero. We can be lenient, and once we're lenient, it's an open-ended leniency. I think StringNumericLiteral deserves its own function.
- @Manishearth - There's an implicit assumption that there's more complexity, but it's not clear to me that it is an increase. The other thing is that the reason to drop the leading zero is... there's a use case for both. For example, Python supports decimals with a leading dot. If ICU4X supports the leading dot, and you want to reject it, that's easy on the user side, but if ICU4X doesn't support it, and you want to parse it, you need to mutate the string, which is much more expensive.
- @zbraniecki - Adding support for non-digit start is increasing code complexity. It's very arbitrary. Is there a spec around this? I cannot find such a spec. If you were writing new code, could you justify this?
- @Manishearth - To a certain extent, this is how people write numbers.
- @zbraniecki - ".2", "2.", ".", "", "2.0.0"?
- @sffc - If someone opens a PR to add support for this, I won't reject it, but it doesn't get us closer to a long-term resolution.
- @zbraniecki - We support exponents. That's complexity. Should we have a flag to turn that off?
- @sffc - We could consider FromStr the lenient parsing function, all of StringNumericLiteral. And we could add additional functions for stricter parsing, like what Ryu needs.
- @zbraniecki - I was thinking FromStr would be the most strict, and new functions would support the additional cases. We can have `FixedDecimal::parse_with_bells_and_whistles(input, options)`
- @zbraniecki - As a general rule, we should be able to parse what we produce. FromStr and ToString should be parallel.
- @sffc - Should FromStr be strict, lenient, or something in the middle?
- @zbraniecki - I vote for strict.
- @sffc - Note: FromStr is the parse function, too: `"132312".parse::<FixedDecimal>()`
- @zbraniecki - `[0-9]+(\.[0-9]+)?`
- @echeran - The middle ground fuzziness seems fine. It should round-trip, but should it be a perfect 1:1? In language, there's always part you understand even if you don't say them.
- @sffc - My concrete proposal would be to make FromStr support StringNumericLiteral minus hex/octal and whitespace. This is basically what we have now, after we drop the leading zero requirement. How did we get here? Based on what users needed. We can then add a full StringNumericLiteral parsing function on the side, and additional smaller functions as needed.
- @Manishearth - @sffc's position is good and consistent.
- @younies - I don't have anything to add.
- @zbraniecki - I made my counter but I'm not strongly opinionated.

Decision: Do as @sffc suggested above.

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/2937
