### ISSUE TITLE
icu_testdata should know its data version even if Cargo.toml isn't available

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2740]
We currently use `cargo metadata` which looks for `Cargo.toml` at runtime to implement the icu_testdata version getters. However, these are flaky since we don't always know the path to Cargo.toml (or such a path may not exist).

To solve this, I suggest making a unit test that ensures a hard-coded static string is consistent with the Cargo.toml file.

**Comment by sffc** [comment]
CC @Manishearth Thoughts on this?

**Comment by sffc** [comment]
Discussion:

- Don't run cargo metadata in generally available public APIs (doesn't work in statically compiled binaries)
- Solution: Bring the version string into the binary at compile time, either with `include_str!` on the toml, or just hard-coding the tag string
- Make a test to ensure that it is all consistent

**Comment by sffc** [comment]
Putting it in Rust source is the solution proposed above on October 19

**Comment by robertbastian** [comment]
Yes, but I don't see why we need to sync it into Cargo.toml as proposed on Oct 19.

**Comment by Manishearth** [comment]
Yeah, I'm proposing a separate sources.toml

**Comment by sffc** [comment]
sources.toml seems fine.

I just want to keep the source of truth of configurations not in code files.

**Comment by sffc** [comment]
If we made another toml file for this, we should probably also move the glob patterns and stuff in there, not just the tags.

**Comment by Manishearth** [comment]
Yeah that's what I was thinking

**Comment by robertbastian** [comment]
If we don't want to duplicate this we can have a build script read source.toml and dump the tag into a const.
