### ISSUE TITLE
"the trait `DataProvider<WordBreakDataV1Marker>` is not implemented"

### ISSUE THREAD

**Issue by ccleve** [unicode-org/icu4x#2742]
The sample code for for word breaking in the icu_segmenter generates a compiler error.

```
use icu::segmenter::WordSegmenter;

 let segmenter =
     WordSegmenter::try_new_unstable(&icu_testdata::unstable())
         .expect("Data exists");

 let breakpoints: Vec<usize> =
     segmenter.segment_str("Hello World").collect();
 assert_eq!(&breakpoints, &[0, 5, 6, 11]);

```
produces:

```
11  |         WordBreakSegmenter::try_new_unstable(&icu_testdata::unstable()).expect("Data exists");
    |         ------------------------------------ ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `DataProvider<WordBreakDataV1Marker>` is not implemented for `UnstableDataProvider`
    |         |
    |         required by a bound introduced by this call

```

**Comment by sffc** [comment]
The fix is to enable the feature `icu_testdata/icu_segmenter` in your Cargo.toml file.

Action is to either document this better or add that as a default feature

**Comment by ccleve** [comment]
@sffc Thanks, this works.

For others who find this issue, my cargo.toml now contains:

```
icu = { version = "1.0.0", features = ["serde"] }
icu_testdata = { version = "1.0.0", features = ["icu_segmenter"] }
icu_provider = { version = "1.0.1" }
icu_segmenter = { version = "0.7.0" }

```

This requirement would have to be documented in each of the subprojects: segmenter, normalizer, etc. A better way would be to add an intelligent error message somewhere so no one would have to read the documentation. I do not know if it is possible to add more info to a _compiler_ error message.

**Comment by sffc** [comment]
Consolidating this into #2853
