### ISSUE TITLE
Document stability guarantees involving provider modules

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2749]
I would like to treat `provider` modules as things that could potentially be unstable (code, not serialization). We should document this somewhere.

Thoughts?

@Manishearth @zbraniecki @robertbastian

**Comment by Manishearth** [comment]
I agree, at least for now.

**Comment by zbraniecki** [comment]
I agree. provider doesn't need API stability yet

**Comment by sffc** [comment]
@robertbastian agrees and will draft a paragraph and send it out for review.

**Comment by robertbastian** [comment]
> ⚠️ This module is considered unstable and may violate Semver at any time. While the serde representation of the data structs is guaranteed to be stable, their Rust representation might not be.

**Comment by sffc** [comment]
Feedback:

> ⚠️ The types in this module are considered unstable and may change over time, including in SemVer minor releases. While the serde representation of the data structs is guaranteed to be stable, their Rust representation might not be.

For reference, here's the language on unstable constructors:

> ⚠️ The bounds on this function may change over time, including in SemVer minor releases.

**Comment by robertbastian** [comment]
Do we put this warning on the module, or on each type in the module?

**Comment by sffc** [comment]
Conclusion:

At the top of the provider modules:

> 🚧 [Unstable] Data provider struct definitions for this ICU4X component.

Inside a yellow box on the modules and types, such that it shows up on every rustdoc page:

> 🚧 This code is considered unstable; it may change at any time, in breaking or non-breaking ways, including in SemVer minor releases. While the serde representation of the data structs is guaranteed to be stable, their Rust representation might not be. Use with caution.
