### ISSUE TITLE
Support loading icu_testdata in a const or lazy_static

### ISSUE THREAD

**Issue by ccleve** [unicode-org/icu4x#2752]
Loading the icu_testdata for use in a segmenter is an expensive operation. It should be done once in a program and stored in a global variable.

Unfortunately, you can't do it as a const or a lazy static.

```
const SEGMENTER: WordBreakSegmenter =
    WordBreakSegmenter::try_new_unstable(&icu_testdata::unstable())
        .expect("Problem loading word break data");

```

generates

```
error[E0015]: cannot call non-const fn `unstable` in constants
 --> src/pipeline/lexer/icu_word_segmenter.rs:8:43
  |
8 |     WordBreakSegmenter::try_new_unstable(&icu_testdata::unstable())
  |                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: calls in constants are limited to constant functions, tuple structs and tuple variants

```

```
lazy_static! {
    static ref SEGMENTER: WordBreakSegmenter =
        WordBreakSegmenter::try_new_unstable(&icu_testdata::unstable())
            .expect("Problem loading word break data");
}

```

generates

```
7  | / lazy_static! {
8  | |     static ref SEGMENTER: WordBreakSegmenter =
9  | |         WordBreakSegmenter::try_new_unstable(&icu_testdata::unstable())
10 | |             .expect("Problem loading word break data");
11 | | }
   | |_^ `Rc<Box<[u8]>>` cannot be shared between threads safely
   |
   = help: within `WordBreakSegmenter`, the trait `Sync` is not implemented for `Rc<Box<[u8]>>`
   = note: required because it appears within the type `Cart`
   = note: required because it appears within the type `std::option::Option<Cart>`
   = note: required because it appears within the type `Yoke<RuleBreakDataV1<'static>, std::option::Option<Cart>>`
   = note: required because it appears within the type `DataPayload<WordBreakDataV1Marker>`
   = note: required because it appears within the type `WordBreakSegmenter`
note: required by a bound in `lazy_static::lazy::Lazy`

```

**Comment by sffc** [comment]
It should work in `lazy_static` if you enable the `icu_provider/sync` feature. Can you verify whether this fixes the issue for you?

We should document this better.

**Comment by ccleve** [comment]
Yes, it works perfectly. The relevant section of cargo.toml is now:

icu = { version = "1.0.0", features = ["serde"] }
icu_testdata = { version = "1.0.0", features = ["icu_segmenter"] }
icu_provider = { version = "1.0.1", features = ["sync"] }
icu_segmenter = { version = "0.7.0" }

**Comment by Manishearth** [comment]
Also, just a note: for all stable components: `icu_testdata::unstable()` should already be doing a cheap load from a static. Segmenter LSTM data does not yet fully zero-copy (we're working on it), but you should not need to use `lazy_static` with "baked" loaded data (which is what `::unstable()` does.

**Comment by sffc** [comment]
Right; for all non-experimental features, the constructors in ICU4X are very cheap, unlike in ICU4C.

(You may get a small amount of win if the constructor involves running the vertical fallback algorithm.)
