### ISSUE TITLE
[datetime] Internal data on FormattedDateTime

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#276]
Hmm.  We should have a discussion about the pros and cons of eagerly versus lazily computing the FormattedDateTime (i.e., whether to keep `'l` references or pre-compute so that the type is self-contained).  Follow-up issue?

_Originally posted by @sffc in https://github.com/unicode-org/icu4x/pull/202#r495544893_

**Comment by sffc** [comment]
2020-11-19: OK for FormattedDateTime to have a reference to the DateTimeFormat, sharing the lifetime.
