### ISSUE TITLE
Update icuexportdata to version release-72-1 to get Unicode 15 data

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#2770]
## Background

The data we get from ICU via `icuexportdata` contains compactly packaged versions of data from Unicode sources for properties, collations, etc.

Currently, ICU4X 1.0 is using the `icu4x/2022-08-17/71.x` release tag of ICU as the snapshot from which to download and use `icuexportdata`.  This tag is a git ref to a commit on the ICU `maint/maint-71` branch because ICU 71 code uses Unicode 14 data, against which ICU4X development was done leading up to 1.0.

ICU 72 was released yesterday, with a relase tag of `release-72-1`.  It contains data for Unicode 15.0.

## Issue

We need to make changes in ICU4X to update to Unicode 15.0 via `icuexportdata` in a couple of ways:

- [x] #1921
- [ ] Update the git tag of the release used for `icuexportdata`.  (Note: PR #2371 is an example that does this.)
- [ ] Update collation test data files used in collator tests (test data files are kept in sync with collation sort key data per version)

For updating the release git tag of `icuexportdata`, I currently see a few places where this should happen:

* CI workflow `build-test.yml` 
  * References directly to the tag (ex: `"release-72-1"`)
  * Filenames that encode the tag name within it (ex: `"icuexportdata_release-72-1.zip"`), in which any slashes in the tag become dashes
* `provider/testdata/Cargo.toml` - a field called `icuexportdata_gitref`
* `provider/testdata/src/lib.rs` - a doc test for `icu_tag()` asserting the git ref string
* `ffi/diplomat/js/examples/node/build.sh` - git ref string when running `icu_datagen` to create dat afor the WASM demo's `.postcard` data

When working on the PR branch locally, remember to run `cargo make testdata-download-sources` to update the test data accordingly.

**Comment by markusicu** [comment]
In the future, you might want to try this (but not merge it) based on an ICU release candidate. If you find something wrong in ICU or in icuexportdata, then we can fix it before ICU is released.
