### ISSUE TITLE
The continuous benchmarking links seem broken

### ISSUE THREAD

**Issue by filmil** [unicode-org/icu4x#279]
For example:
https://unicode-org.github.io/icu4x-docs/dev/locale/bench is a 404

@echeran Is this supposed to work at the moment?

**Comment by filmil** [comment]
Related to https://github.com/unicode-org/icu4x/pull/197

**Comment by sffc** [comment]
Dupe of #262?

**Comment by sffc** [comment]
Also broken: https://unicode-org.github.io/icu4x-docs/icu_locale/index.html

**Comment by echeran** [comment]
Yes, this is a duplicate of #262, which is now fixed, so I will close this issue now, accordingly.  The link above that was broken is now changed to be https://unicode-org.github.io/icu4x-docs/doc/icu_locale/index.html.  The link on the main Readme.md to the API docs works now.
