### ISSUE TITLE
One-step DateTimeFormat (and other formatters)

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#280]
Despite our efforts to encourage developers to adopt the pattern of creating a formatter and using it repeatedly, the majority\* of call sites "create and destroy" the formatter object.  How should we optimize for this type of call site in ICU4X?  There are two things to consider optimizing:

1. Call site (brevity)
2. Efficiency

On point 2, my hope is that an LRU cache in the DataProvider will provide a sufficient performance improvement such that the process of creating a DateTimeFormat/NumberFormat is cheap.  Note: this assumes that the patterns and stuff are pre-parsed in the data struct.

On point 1, it really depends on the target language.  In Rust, we could make a "toLocaleString" trait and implement it on the relevant built-in types.

\* *Based on an analysis of Google code from ICU4J DecimalFormat in 2017*

**Comment by nciric** [comment]
The way I did it for Ecma (to handle toLocaleDate, etc) is to have a somewhat higher level cache than data provider level - I cached actual DateTimeFormat objects by looking at the input params, like locale and options.

I think that would work well for client-side app, where we don't expect locale changes per user.

Second question is how to expose that cache. We could do simple toLocaleDate equivalent, which would check cache or create new formatter and do formatting. Maybe a macro?

**Comment by sffc** [comment]
2020-10-30 discussion:

- Abstract the pattern parsing into the data provider.  Make the data struct store an enum, either parsed or unparsed pattern.
- Use data provider blocks to control the pattern parsing transformations and the caching of the parsed pattern.
- Don't add another API for formatting; have people always create a formatter object.

**Comment by sffc** [comment]
We're discussing this in #523. Closing as a duplicate.
