### ISSUE TITLE
Creating unit tests using icu_testdata

### ISSUE THREAD

**Issue by rizzen-yazston** [unicode-org/icu4x#2800]
For a unit test I am trying to create a data provider using the data of the icu_testdata crate, as it does contain Pattern_White_Space and Pattern_Syntax properties, and has a sample of Grapheme Segmenter data.

I do see 3 small examples, yet can't figure out how to expand the examples to have a single provider that supports: DataProvider<PatternSyntaxV1Marker> + DataProvider<PatternWhiteSpaceV1Marker> + DataProvider<GraphemeClusterBreakDataV1Marker>.

I need to pass a single provider to a function that supports the 3 data types:
```
pub fn try_new<P>( provider: &P ) -> Result<Self, String> 
    where 
    P: DataProvider<PatternSyntaxV1Marker> + DataProvider<PatternWhiteSpaceV1Marker> +
    DataProvider<GraphemeClusterBreakDataV1Marker> + ?Sized,
    {
  /* --- snip details --- */
}
```

I believe a slightly more complex example that uses combination data type provider would help new users of the icu crates to create the unit tests using icu_testdata, and in general extend it to using icu_fs_provider for ICU data included in application.

Though I do see an issue for OS installed ICU data provider being proposed as an enhancement, which could reduce application installation size, and the applications are not concerned of the small changes taking place in the OS installed ICU data as OS updates takes place.

**Comment by rizzen-yazston** [comment]
Is it possible to use BufferProvider (such as FsDataProvider, or icu_testdata::buffer()) as a provider for the following: icu_properties::sets (i.e. sets::load_pattern_white_space()), and icu_segmenter::GraphemeClusterBreakSegmenter::try_new_unstable()?

Or does one need to construct own methods to extract properties data using something similar to
```
provider.load(Default::default()).and_then(DataResponse::take_payload).map(CodePointSetData::from_data)?
```
, and similarly construct own method to obtain segmenter?

**Comment by sffc** [comment]
First of all, if you need segmenter data, which is still experimental (pending #2259), you need to explicitly enable the `icu_testdata/icu_segmenter` feature.

Once you enable the feature, `icu_testdata::unstable()` should implement all of the bounds you need.

If you want to use a BufferProvider, you should use the `_with_buffer_provider` constructors.

**Comment by rizzen-yazston** [comment]
Thanks for advice.

Just noticed for BufferProvider, in buf.rs: Is [`as_deserializing()`]: AsDeserializingBufferProvider::as_deserializing supposed to be commented out? As trying to use as_deserializing() is producing a compile error of does not exists. Also as_deserializing() is used in example above.

Perhaps part of the reason why I am struggling to get icu_testdata and FsDataProvider to work.

**Comment by robertbastian** [comment]
You will need to activate the `serde` feature to use `with_buffer_provider` constructors (and `as_deserializing`).

Also note that the data format is not CLDR data, but a custom format compiled from CLDR (through `icu_datagen`).
