### ISSUE TITLE
Should icu_testdata/buffer enable serde features on the other crates?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2814]

**Comment by rizzen-yazston** [comment]
It would help, in not missing a feature for one of the component crates that does support `BufferProvider`.

**Comment by robertbastian** [comment]
I don't think it should, because `icu_provider_blob` doesn't either. I think it's worth having testdata features be as similar as possible to production data features, so prototyping with testdata and then swapping in production data is smooth.
