### ISSUE TITLE
datagen: Seems `any.rs` not referenced as a module?

### ISSUE THREAD

**Issue by crlf0710** [unicode-org/icu4x#2815]
Hi, i'm trying to use `icu4x-datagen` for creating baked icu data. Then i found it created an `any.rs` but this is not referenced with a `mod any;` from upper module. Is this intended or an oversight? Thanks!

**Comment by Manishearth** [comment]
No, this is intended, `any.rs` contains additional impls you can _choose_ to include if you want AnyProvider to be implemented. You still need to include mod.rs.

**Comment by Manishearth** [comment]
This is documented in https://github.com/unicode-org/icu4x/blob/main/docs/tutorials/data_management.md#mod-and-bakeddataprovider
