### ISSUE TITLE
Wasm size test with icu-locale crate

### ISSUE THREAD

**Issue by nciric** [unicode-org/icu4x#282]
I've used pre 0.1 ICU4X icu_locale crate to test Wasm use and size.

Follow [MDN](https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm) article about compiling Rust to Wasm.

The web site using npm and nodejs is in this repo under *locale-wasm-site* folder.

Results:
1. Rust -> Wasm -> Html/JS works with minor wrapping of the code!
2. Original size of wasm file (default opt) was: wasm_locale_bg.wasm **31.8** KiB
3. Using aggresive size optimization, we got modest gains: **28.7** KiB
4. Further optimization using wasm-opt util from [binaryen](https://github.com/WebAssembly/binaryen) saved ~**50** bytes.
5. Gzipping the wasm file drops the size to **12.1** KiB
6. Speed impact was not measured

Take a look at [code](https://github.com/nciric/experimental/tree/master/wasm-locale) for wrapping icu-locale for wasm-bindgen export, and nodejs [project](https://github.com/nciric/experimental/tree/master/locale-wasm-site) that uses it.

**Comment by sffc** [comment]
Did you run the wasm through twiggy?

I found when experimenting last winter that wasm bindgen produces a lot of things that you don't need, and one of the biggest ways to reduce code size is to use options like panic-abort that eliminate the formatting for error messages.

**Comment by nciric** [comment]
No I haven't used twiggy in this case, but that's good idea for later, when we start focusing on how to implement Wasm bindings and start paying attention to size.

Adding panic="abort" doesn't help much in this case (size is the same).

**Comment by mihnita** [comment]
Closure locale:
https://google.github.io/closure-library/api/goog.locale.html

It is a bit messier, as it has naming support (`getLocalizedLanguageName`, `getNativeLanguageName` and so on)
That can add a lot of data (translated names for hundreds of languages & regions).

**Comment by sffc** [comment]
Here's some previous analysis I did on LanguageIdentifier WASM size:

https://github.com/zbraniecki/unic-locale/issues/49#issuecomment-580069503
