### ISSUE TITLE
Rewrite f32.exp and f32.tanh?

### ISSUE THREAD

**Issue by makotokato** [unicode-org/icu4x#2828]
lstm uses `f32.exp` and `f32.tanh`, so we depends on `num_trait` with std. Should we remove num_trait and std dependency, then rewrite f32.exp and f32.tanh?

**Comment by aethanyc** [comment]
cc @sffc

**Comment by sffc** [comment]
CC @younies

**Comment by robertbastian** [comment]
`num_traits` seems to be unused currently. However it can provide `f32::exp` and `f32::tanh` (through its `Float` extension trait) in `#[no_std]` if we enable the `libm` feature. Alternatively we could use `libm` directly, but it's less ergonomic and `num_traits` is a transitive dependency already.

**Comment by robertbastian** [comment]
I believe the no-stdness of LSTM was the reason it's still behind a feature and not included in the meta crate. Should we include it now?

**Comment by sffc** [comment]
> I believe the no-stdness of LSTM was the reason it's still behind a feature and not included in the meta crate. Should we include it now?

It's one of several blockers; see the meta-issue https://github.com/unicode-org/icu4x/issues/2259

**Comment by robertbastian** [comment]
Those are blockers for stabilizing the whole crate. I'm talking about LSTM, which does not need to be behind a feature anymore (before it had to be because otherwise `icu` with experimental features wouldn't have been `no_std`). Unless we want to keep it behind a feature even after stabilization?

**Comment by sffc** [comment]
The LSTM features are kind-of a mess right now. Enabling LSTM disables Dictionary. That's one of the things that needs to be fixed before stabilizing.
