### ISSUE TITLE
icu4x_datagen throw error with multiple locales

### ISSUE THREAD

**Issue by ouyuran** [unicode-org/icu4x#2831]
I was trying to generate data with multiple locales using the example here https://icu4x.unicode.org/doc/icu_datagen/#command-line . But I got an error.
```
$ icu4x-datagen   --all-keys   --locales de,en-AU  --format blob  --out data.postcard
Error: de,en-AU

Caused by:
    The given language subtag is invalid

Location:
    /Users/yurano/.cargo/registry/src/github.com-1ecc6299db9ec823/icu_datagen-1.0.2/src/bin/datagen.rs:243:56

$ icu4x-datagen --version
ICU4X Data Exporter 0.0.1
```

**Comment by robertbastian** [comment]
The syntax is `--locales de en-AU`

**Comment by sffc** [comment]
It is a Clap 3.x Multiple Values argument.

https://docs.rs/clap/3.2.23/clap/struct.Arg.html#method.multiple_values

**Comment by sffc** [comment]
Maybe we should be explicitly setting a value delimiter

https://docs.rs/clap/3.2.23/clap/builder/struct.Arg.html#method.require_value_delimiter

This may be considered a breaking change, so maybe we just fix the docs
