### ISSUE TITLE
CLDR/ICU beta integrations

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#2860]
In the future, you might want to try this (but not merge it) based on an ICU release candidate. If you find something wrong in ICU or in icuexportdata, then we can fix it before ICU is released.

_Originally posted by @markusicu in https://github.com/unicode-org/icu4x/issues/2770#issuecomment-1284672043_
      
We should define a process for this

**Comment by robertbastian** [comment]
My thought is to update `SourceData::LATEST_FOO` asap with new CLDR betas, and downgrade to stable if we release during a beta period.

**Comment by sffc** [comment]
Works for me
