### ISSUE TITLE
#[derive(Yokeable)] does not work if there are type parameters which use the lifetime

### ISSUE THREAD

**Issue by mstange** [unicode-org/icu4x#2863]
In my example I have the following code:

```rust
#[derive(Yokeable)]
struct MachObject<'data, R: ReadRef<'data>> {
    object: File<'data, R>,
    macho_data: MachOData<'data, R>,
    file_data_for_addr2line_context: R,
    addr2line_context_data: &'data Addr2lineContextData,
}
```

I'm getting this error:

```
error[E0261]: use of undeclared lifetime name `'data`
   --> src/macho.rs:328:37
    |
327 | #[derive(Yokeable)]
    |          -------- lifetime `'data` is missing in item created through this procedural macro
328 | struct MachObject<'data, R: ReadRef<'data>> {
    |                                     ^^^^^ undeclared lifetime
    |
help: consider making the bound lifetime-generic with a new `'data` lifetime
    |
328 | struct MachObject<'data, R: for<'data> ReadRef<'data>> {
    |                             ++++++++++
```

**Comment by sffc** [comment]
CC @Manishearth -- what's the status of Yokeable derive with generics?

**Comment by Manishearth** [comment]
We currently support the Yokeable derive with generics that do not themselves need the lifetime (and we force them to be `'static` iirc). Unfortunately, that's not the case here.

We could potentially support `R: for<'a> Yokeable<'a>` where the struct uses `<R as Yokeable<'data>>::Output`, that's technically safe, though it would almost certainly have to go through the `prove_covariance_manually` route.

The tricky thing about the _trait_ `ReadRef<'data>` is that we don't have a way to obtain lifetime-transformed versions of implementors of that trait. Variance information is very easily lost through traits, it's possible an implementor of `ReadRef` does not even have a lifetime, let alone have a lifetime that's specifically covariant.

I think the way forward would probably be to make `trait StaticReadRef<'a>: Yokeable<'a>  where Self::Output: ReadRef<'a>`, and bound the struct on `R: for<'a> StaticReadRef<'a>`. You'd still need a manual Yokeable impl, but we could extend the custom derive to support that case via the `prove_covariance_manually` (shouldn't be too hard, just need to make sure it gets the bounds right)

**Comment by Manishearth** [comment]
(Also happy to discuss the design of what y'all are building further to figure out how best to fit Yoke in)

**Comment by Manishearth** [comment]
Closing for now since we fitured out how to make it workable without this. I think there potentially is space to do this by allowing it to detect `R: for<'a> Yokeable<'a>` and using the manual covariance path for that (or erroring to ask the user to opt in), but it's still of limited use in general.
