### ISSUE TITLE
Explore alternate top level data structures

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2885]
Currently, each key maps to a map from locale to data blob. Can we do better?

The current approach doesn't scale well to thousands of locale-sensitive keys, because the inner tables need to be replicated thousands of times. Since this is a 2-D mapping, would we benefit from storing it as a densely packed matrix? The key tells you a row and the locale tells you a column; a value of u16::MAX means it is undefined, and otherwise, it selects a blob from a VSV stored to the side.

In addition to a fully expanded dense matrix, there are various data structures in textbooks for efficiently storing matrices.

A potential advantage of this solution is that we can more efficiently load a whole row (many locales for a single key) or whole column (many keys for a single locale) by saving the row or column index from one load operation to the next.

This type of thing makes sense for BlobDataProvider, but maybe not BakedDataProvider, which already has O(1) lookup for the keys (if used directly -- not when used through an AnyProvider).

CC @Manishearth @robertbastian

**Comment by sffc** [comment]
@Manishearth Can you weigh in and suggest alternatives?

**Comment by robertbastian** [comment]
We could just deduplicate the locale lists with one step of indirection. This would also help with my proposal in #2699

**Comment by robertbastian** [comment]
Pushing to 2.0 as it's a performance improvement that nobody is currently asking for. We'll need this for currencies eventually as the number of locales will be locales x currencies.

**Comment by Manishearth** [comment]
Status: we have zerotrie, but it's not yet used for baked

**Comment by sffc** [comment]
ZeroTrie lookup is implemented in both bake and blob.
