### ISSUE TITLE
Change relativetime test case value from -10 to 10

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#2890]
It seems like in [every test currently for icu_relativetime](https://github.com/unicode-org/icu4x/blob/main/experimental/relativetime/tests/tests.rs) uses the following set of input values: -10, -2, -1, 0, 1, 2, -10, like so:

```
...
    [
        (-10, "10 seconds ago"),
        (-2, "2 seconds ago"),
        (-1, "1 second ago"),
        (0, "in 0 seconds"),
        (1, "in 1 second"),
        (2, "in 2 seconds"),
        (-10, "10 seconds ago")
    ],
...
```

The asymmetry is that we have -10 duplicated but no representation of positive 10.  If this is a mistake, it needs to be fixed for all test cases so far.

**Comment by sffc** [comment]
@pdogr

**Comment by pdogr** [comment]
It should have been 10. I'll send a fix for review.
