### ISSUE TITLE
GraphemeClusterBreakSegmenter should be GraphemeClusterSegmenter

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#2925]
The type for grapheme cluster segmentation is called GraphemeClusterBreakSegmenter. I think it should be called GraphemeClusterSegmenter.

In general, the names of types should have the following pattern:

| | GraphemeCluster- | Word- | Sentence- | Line- |
|---|---|---|---|---|
| -Segmenter | `GraphemeClusterSegmenter` | `WordSegmenter` | ... | ...|
| -BreakIteratorUtf8 | `GraphemeClusterBreakIteratorUtf8` | `WordBreakIteratorUtf8` | ... | ... |
| ... | ... | ... | ... | ... |

CC @makotokato @aethanyc

**Comment by aethanyc** [comment]
The rename is done in #2707. We currently use `GraphemeClusterSegmenter` in 

https://github.com/unicode-org/icu4x/blob/4c06df74ba8058870625c0a8c021da05c0ba63f5/experimental/segmenter/src/grapheme.rs#L68-L70

@sffc  Did I miss anything?

**Comment by sffc** [comment]
Hmm

https://github.com/unicode-org/icu4x/pull/2924/files#diff-7ada630f6751436efb40d05798741d43d34423b83f8ba38d8a3cfc034e41dce7R9

**Comment by sffc** [comment]
Was this a recent change, after 0.7? My example is using icu@1.0.0 with the experimental feature, enabling icu_segmenter 0.7.0. That seems like it is the issue.
