### ISSUE TITLE
soundness issue in `yoke` using `#[feature(coerce_unsized)]` on `nightly`: The `Yokeable` derive (in `prove_covariance_manually` mode) does not do sufficient checks.

### ISSUE THREAD

**Issue by steffahn** [unicode-org/icu4x#2928]
Repro:

```rs
#![feature(coerce_unsized)]

use std::{cell::Cell, ops::CoerceUnsized};

use yoke::*;

#[derive(Yokeable)]
struct S1<T>(T);

impl<T, U> CoerceUnsized<S1<U>> for S1<T> where T: CoerceUnsized<U> {}

#[derive(Yokeable)]
#[yoke(prove_covariance_manually)]
struct S2<'a>(S1<Cell<Box<dyn AsRef<str> + 'a>>>);

fn main() {
    let x: S2<'static> = S2(S1(Cell::new(Box::new(""))));
    let x_transformed: &S2<'_> = x.transform();
    let r: &Cell<Box<dyn AsRef<str> + '_>> = &x_transformed.0 .0;
    let s = String::from("Hello World!");
    r.set(Box::new(&s));
    let contents: Box<dyn AsRef<str> + 'static> = x.0 .0.replace(Box::new(""));
    let s_ref: &str = (*contents).as_ref();
    println!("A string: {s_ref}");
    drop(s);
    println!("No more string: {s_ref}");
}
```
[run online in Rust Explorer](https://www.rustexplorer.com/b#%2F*%0A%5Bdependencies%5D%0Ayoke%20%3D%20%7B%20version%20%3D%20%220.6.2%22%2C%20features%20%3D%20%5B%22derive%22%5D%20%7D%0A*%2F%0A%0A%0A%23!%5Bfeature(coerce_unsized)%5D%0A%0Ause%20std%3A%3A%7Bcell%3A%3ACell%2C%20ops%3A%3ACoerceUnsized%7D%3B%0A%0Ause%20yoke%3A%3A*%3B%0A%0A%23%5Bderive(Yokeable)%5D%0Astruct%20S1%3CT%3E(T)%3B%0A%0Aimpl%3CT%2C%20U%3E%20CoerceUnsized%3CS1%3CU%3E%3E%20for%20S1%3CT%3E%20where%20T%3A%20CoerceUnsized%3CU%3E%20%7B%7D%0A%0A%23%5Bderive(Yokeable)%5D%0A%23%5Byoke(prove_covariance_manually)%5D%0Astruct%20S2%3C'a%3E(S1%3CCell%3CBox%3Cdyn%20AsRef%3Cstr%3E%20%2B%20'a%3E%3E%3E)%3B%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20x%3A%20S2%3C'static%3E%20%3D%20S2(S1(Cell%3A%3Anew(Box%3A%3Anew(%22%22))))%3B%0A%20%20%20%20let%20x_transformed%3A%20%26S2%3C'_%3E%20%3D%20x.transform()%3B%0A%20%20%20%20let%20r%3A%20%26Cell%3CBox%3Cdyn%20AsRef%3Cstr%3E%20%2B%20'_%3E%3E%20%3D%20%26x_transformed.0%20.0%3B%0A%20%20%20%20let%20s%20%3D%20String%3A%3Afrom(%22Hello%20World!%22)%3B%0A%20%20%20%20r.set(Box%3A%3Anew(%26s))%3B%0A%20%20%20%20let%20contents%3A%20Box%3Cdyn%20AsRef%3Cstr%3E%20%2B%20'static%3E%20%3D%20x.0%20.0.replace(Box%3A%3Anew(%22%22))%3B%0A%20%20%20%20let%20s_ref%3A%20%26str%20%3D%20(*contents).as_ref()%3B%0A%20%20%20%20println!(%22A%20string%3A%20%7Bs_ref%7D%22)%3B%0A%20%20%20%20drop(s)%3B%0A%20%20%20%20println!(%22No%20more%20string%3A%20%7Bs_ref%7D%22)%3B%0A%7D%0A)
```
A string: Hello World!
No more string: KT�_�Y�p
```

The relevant problem is in the generated code for the derive on `S2`:
```rs
unsafe impl<'a> yoke::Yokeable<'a> for S2<'static> {
    type Output = S2<'a>;
    #[inline]
    fn transform(&'a self) -> &'a Self::Output {
        unsafe { ::core::mem::transmute(self) }
    }
    #[inline]
    fn transform_owned(self) -> Self::Output {
        match self {
            S2(__binding_0) => S2(
                <S1<Cell<Box<dyn AsRef<str> + 'static>>> as yoke::Yokeable<'a>>::transform_owned(
                    __binding_0,
                ),
            ),
        }
    }
    #[inline]
    unsafe fn make(this: Self::Output) -> Self {
        use core::{mem, ptr};
        debug_assert!(mem::size_of:: <Self::Output>() =  = mem::size_of:: <Self>());
        let ptr: *const Self = (&this as *const Self::Output).cast();
        #[allow(clippy::forget_copy)]
        mem::forget(this);
        ptr::read(ptr)
    }
    #[inline]
    fn transform_mut<F>(&'a mut self, f: F)
    where
        F: 'static + for<'b> FnOnce(&'b mut Self::Output),
    {
        unsafe {
            f(core::mem::transmute::<&'a mut Self, &'a mut Self::Output>(
                self,
            ))
        }
    }
}
```

Here, the sanity check for soundness lies in the 
```rs
            S2(__binding_0) => S2(
                <S1<Cell<Box<dyn AsRef<str> + 'static>>> as yoke::Yokeable<'a>>::transform_owned(
                    __binding_0,
                ),
            ),
```
however:
The type
```rs
<S1<Cell<Box<dyn AsRef<str> + 'static>>> as yoke::Yokeable<'a>>::Output
```
is
```
S1<Cell<Box<dyn AsRef<str> + 'static>>
```

whereas the field we want to populate is
```rs
S1<Cell<Box<dyn AsRef<str> + 'a>>
```

The code compiles nonetheless because of the unsize coercion from `S1<Cell<Box<dyn AsRef<str> + 'static>>` to `S1<Cell<Box<dyn AsRef<str> + 'a>>`. However, this transformation is only sound for _owned_ `Cell<…>` values, and _unsound_ behind a shared reference, which is what the implemented `transform` method now offers.

**Comment by sffc** [comment]
@Manishearth

**Comment by Manishearth** [comment]
I wonder if the answer here is to simply generate a non-transmuting `transform()` as well

Nice catch!

**Comment by Manishearth** [comment]
Okay we can't just do that because we're in a manual covariance situation, and transform() doesn't compose the way transform_owned() does. We can add some type assertions though

**Comment by Manishearth** [comment]
Fix is up: https://github.com/unicode-org/icu4x/pull/2936
