### ISSUE TITLE
Debug format for low-level types

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#294]
If I `println!("{:?}", langids)` with a `Vec<LanguageIdentifier>`, I get:

```
[LanguageIdentifier { language: Language(Some("be")), script: None, region: None, variants: Variants([]) }, LanguageIdentifier { language: Language(Some("bn")), script: None, region: None, variants: Variants([]) }, LanguageIdentifier { language: Language(Some("ccp")), script: None, region: None, variants: Variants([]) }, LanguageIdentifier { language: Language(Some("en")), script: None, region: None, variants: Variants([]) }, LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: Variants([]) }, LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("XA")), variants: Variants([]) }, LanguageIdentifier { language: Language(Some("fa")), script: None, region: None, variants: Variants([]) }, LanguageIdentifier { language: Language(Some("fr")), script: None, region: None, variants: Variants([]) }, LanguageIdentifier { language: Language(Some("fr")), script: None, region: Some(Region("FR")), variants: Variants([]) }, LanguageIdentifier { language: Language(None), script: None, region: None, variants: Variants([]) }, LanguageIdentifier { language: Language(Some("zh")), script: Some(Script("Hant")), region: None, variants: Variants([]) }]
```

It would be nicer if LanguageIdentifier had a custom Debug implementation that mirred the Display implementation.

Thoughts? @zbraniecki @Manishearth

**Comment by zbraniecki** [comment]
Shouldn't we just implement `Display`?

**Comment by sffc** [comment]
I'm trying to make an argument about developer experience.  I think it is more useful in debug output to see `fr-FR` rather than `LanguageIdentifier { language: Language(Some("fr")), script: None, region: Some(Region("FR")), variants: Variants([]) }`.  Many different mechanisms use Debug rather than Display: unwrap, assert_eq, std::error::Error, etc.

**Comment by zbraniecki** [comment]
Ah, I see. Yeah, that's a good question. @Manishearth is there a precedence where a struct has a `Debug` that is "human readable" formatted?

If so, how does one "debug" it then if you really want to see internals dumped?

**Comment by Manishearth** [comment]
@zbraniecki sure, when the internal implementation has an obvious one-one mapping to the human readable representation, it's fine to do this. Basically can someone guess the internal implementation from the Debug impl? If so, this should be fine.

It will be exceedingly rare that you actually want to see the internals, but you can tweak the debug impl then because presumably you're debugging something in the internals impl.

**Comment by zbraniecki** [comment]
Great, thank you!

Should we then just use to_string for debug?

**Comment by Manishearth** [comment]
Yeah, should be fine

**Comment by zbraniecki** [comment]
Sounds great. So, the conclusion is that we want `Debug` trait for `LanguageIdentifier` and maybe `Locale` that uses `to_string`.
