### ISSUE TITLE
Use #[derive(Error)] for Error types

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#298]
dtolnay made [thiserror](https://github.com/dtolnay/thiserror) which provides a nice `#[derive(Error)]` to help reduce some of the Error boilerplate.  I've been writing a lot of such boilerplate in my components, and this seems like a good solution.  Among other things, it:

- Implements std::error::Error
- Implements std::fmt::Display
- Implements From traits for relevant enum entries

There are also several other similar crates on crates.io, which all seem to do pretty much the same thing:

- https://docs.rs/err-derive/0.2.4/err_derive/index.html
- https://docs.rs/crate/derive-error/0.0.4
- https://jeltef.github.io/derive_more/derive_more/error.html

**Comment by zbraniecki** [comment]
I think `thiserror` is likely the right library for now. Eventually, I hope Rust Error Handling Project Group will produce an output that we'll switch to, but temporarily `thiserror` seems like a good solution.

https://blog.rust-lang.org/inside-rust/2020/09/18/error-handling-wg-announcement.html

**Comment by sffc** [comment]
Getting rid of the error boilerplate might also help us get our code coverage up.
