### ISSUE TITLE
Support ECMA-402 weekInfo queries

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#2999]
It appears that ICU4X lacks support for the (proposed?) [`weekInfo` feature of ECMA-402](https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.weekInfo). We should add support both for the sake of ECMA-402 coverage and, regardless of ECMA-402, to support the use case of rendering week and month views of the Gregorian calendar in a locale-appropriate way.

**Comment by sffc** [comment]
I think this one is ready to implement. Happy to mentor on it.

**Comment by JhonnyBillM** [comment]
Hi folks, I would like to work on this. Some questions:
1. Will this belong in the `icu_locid` crate ? If so, will it be exposed over `Locale` or via a different entity ?
2. Where can the crate get the data to be able to build this API ? 
2.1. _Sorry, I am trying to get familiar with the project and still have key doubts._

This will be my first contribution to the project, so please feel free to offer any extra guidance or tips. Thank you in advance!

**Comment by sffc** [comment]
Hi @JhonnyBillM!

The place to put this for now is `icu_locid_transform`. In the future I would like to see this crate split into two parts, one for the core components for locale fallback (which everyone needs to depend on) and one for the additional data-driven locale algorithms like week info, text directionality, and full canonicalization. https://github.com/unicode-org/icu4x/issues/3504#issuecomment-1583088322

See `LocaleDirectionality` for some inspiration on how to write this.

The data should come from CLDR-JSON. We already have a lot of CLDR-JSON included in ICU4X. If you need to add more, add the files to `globs.rs.data` and re-run `cargo make download-repo-sources`. You can browse CLDR-JSON here:

https://github.com/unicode-org/cldr-json/tree/main/cldr-json

Please also study the tutorials, especially the one entitled "Writing a New Data Struct". This should walk you through most of what you need to do. 75% of the work here is the data pipeline; the actual API should be easy once you have the data in place.

If you'd like to schedule a call once you have some code written, I'm happy to sync. You can DM me your email.

**Comment by JhonnyBillM** [comment]
Hi @sffc, thank you for the guidance! Now I am ready to sync whenever you have a moment. You can see my progress in [tree/support-locale-week-info](https://github.com/JhonnyBillM/icu4x/tree/support-locale-week-info), or in this PR for easier visibility https://github.com/JhonnyBillM/icu4x/pull/1.

Apologies for the delay, but planning to be more active now.

I am not sure where can I send you a DM, but just in case, here is my email: JhonnyBillM@gmail.com
Some of my questions are already listed in my branch with `// TODO: [CODE REVIEW]`, but I can organize better some things before our meeting.

**Comment by sffc** [comment]
@JhonnyBillM Sorry for the slow reply; was on vacation and a conference! I have an office hours booking page here: bit.ly/sffc-office-hours-a

It's easier to track if you open a pull request against the main repo. Can you do that?

Looking very quickly, it appears you need to run `cargo make testdata` and `cargo make bakeddata components/locid_transform`, and otherwise your code appears to be well structured and in the right place!

**Comment by sffc** [comment]
Hi @JhonnyBillM! Can you open a pull request with your changes so someone from the team can give you a code review?

**Comment by sffc** [comment]
I think this was fixed by #4364,
