### ISSUE TITLE
Running CI per crate instead of on the workspace

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3002]
Running commands like `check` and `test` on the workspace level causes feature resolution to happen on the workspace level. This means crates can be running with dependency features that they didn't activate themselves, which can hide bugs. It is possible to run for each crate in isolation with the `cargo-workspaces` tool:

```bash
cargo ws exec --no-bail cargo check --all-features --all-targets --no-fail-fast
```

In a second step we might be able to then exclude workspace members that are not published. These are tools like `icu_testdata_scripts`, `ffi_coverage`, and `icu_benchmark_macros`, which don't have to pass `cargo check`/`cargo test` because they are used in their own CI.

**Comment by robertbastian** [comment]
This actually discovered a bug in `icu_datagen` (#3000).

**Comment by sffc** [comment]
Is there a speed difference between `cargo test --all-features` and `cargo ws exec cargo test --all-features`?
