### ISSUE TITLE
impl `std::error::Error` for `TinyAsciiStr`

### ISSUE THREAD

**Issue by bheylin** [unicode-org/icu4x#3007]
`TinyAsciiStr` doesn't implement `std::error::Error` and so does not play well with general `Try` based error handling or with the popular `anyhow::Error`.

I understand that `tinystr` wants to not depend on `std` but the `Error` impl could be put behind a feature gate for now until the `Error` trait is moved to `core`.

**Comment by sffc** [comment]
Do you mean [TinyStrError](https://icu4x.unicode.org/doc/tinystr/enum.TinyStrError.html)?

We're open to a PR adding a `std` feature to the tinystr crate.

**Comment by bheylin** [comment]
> Do you mean [TinyStrError](https://icu4x.unicode.org/doc/tinystr/enum.TinyStrError.html)?

That is indeed what I meant to refer to.

> We're open to a PR adding a `std` feature to the tinystr crate.

Check the PR
