### ISSUE TITLE
Could not find `icu4x-datagen` in registry `crates-io` with version `*`

### ISSUE THREAD

**Issue by ajtribick** [unicode-org/icu4x#3034]
The [data management tutorial](https://github.com/unicode-org/icu4x/blob/main/docs/tutorials/data_management.md) states to install the `icu4x-datagen` binary by running `cargo install icu4x-datagen`.

This produces the error: "could not find \`icu4x-datagen\` in registry \`crates-io\` with version \`*\`. Should this say `cargo install icu_datagen` instead?

**Comment by sffc** [comment]
> Should this say `cargo install icu_datagen` instead?

Indeed.
