### ISSUE TITLE
`icu_testdata` needs a diet

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3038]
For the 1.1 release I had to apply some "manual compression" to the baked data to get us under the crates.io limit of 10MB (we published with 9.9MB).

There are a couple approaches here:
* Make baked output less verbose. For example there are better ways to represent byte slices than `&[1u8, 2u8, ...]`. Many of our byte slices are ASCII, so could use byte string literals.
* Remove raw CLDR/ICU data. I personally never liked that they're in the testdata crate, as they're testing data for *datagen*, not ICU4X itself. This would cut size, however they are exposed on the API through `paths::cldr_root` et al
* Remove some data, like segmentation, a few calendars, ...

**Comment by robertbastian** [comment]
We received an exception for 20MB

**Comment by sffc** [comment]
I like using byte literals as some low-hanging fruit.

Moving the source data somewhere else is a possibility. Perhaps we can publish it as `icu_testdata_sources`, and we can re-export it from the main testdata crate such that we can keep the `paths` module working.

In the future we could split things further into smaller testdata crates re-exported from the main one.
