### ISSUE TITLE
build.rs datagen breaks in 1.1

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3046]
This change:

https://github.com/unicode-org/icu4x/commit/15d8e3ac8e2dd1bdbd8ed11c348bc6ac3a71334d#diff-cfc913b878b6f2e1be58c96e01de67c5394609edf38aeb3dbccc66bb44fab241

changed `std::fs::remove_dir_all` to `std::fs::remove_dir`. It means that a build.rs built with the assumption that it can always be re-run without cleanup starts to fail.

CC @robertbastian

**Comment by robertbastian** [comment]
I'd say this is WAI, unconditionally bulldozing stuff was a bug.

**Comment by sffc** [comment]
If this is WAI, can we put the necessary workaround code in the build.rs example? Because build.rs will _fail_ after it runs more than once unless it deletes the directory.

Personally I tend to lean in the direction that the old behavior is better as a default.

**Comment by robertbastian** [comment]
I don't think we should be going around deleting directories unless the user specifically told us to. Most tools need some kind of `-f` to do that.

**Comment by robertbastian** [comment]
Which `build.rs` example do you mean?

**Comment by sffc** [comment]
As discussed: try to make it work while writing to the Cargo out dir.

**Comment by robertbastian** [comment]
I think we might need the deletion step. `OUT_DIR` is [reused](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts:~:text=target%20features%20enabled.-,OUT_DIR,-%E2%80%94%20the%20folder%20in), so if you're iterating on the build script it will see the previous run's data.
