### ISSUE TITLE
Old-style BakedDataProvider breaks in 1.1

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3047]
It seems that 1.1 changed `pub struct BakedDataProvider` to `struct BakedDataProvider`, causing the following to fail:

```rust
mod baked {
    include!("../baked_data/mod.rs");
}

fn main() {
    let rules =
        PluralRules::try_new_cardinal_unstable(&baked::BakedDataProvider, &locale!("ru").into())
            .expect("Locale 'ru' is present in the databake");
}
```

with an error about `BakedDataProvider` not being accessible.

The change is https://github.com/unicode-org/icu4x/commit/b74aafdaecd4053f95ba294361dabe7b2a942cc5#diff-4f1870b43c4e989054059eb1e6453791d251984fce384be5db03bb3bb00d8186 but it takes a long time to load.

CC @robertbastian

**Comment by robertbastian** [comment]
Yeah that should be pub
