### ISSUE TITLE
WAM Demo build is broken

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3049]
The error was previously obscured due to an unrelated GCP permissions error that I fixed today. It uncovered the following error:

```
     Running `/home/runner/work/omnicu/omnicu/target/debug/icu4x-datagen --key-file ../wasm-demo/required-keys.txt --locales full --format blob --out data.postcard`
Error: ../wasm-demo/required-keys.txt

Caused by:
    No such file or directory (os error 2)

Location:
    provider/datagen/src/bin/datagen.rs:279:14
```

See https://github.com/sffc/omnicu/actions/runs/4050456720/jobs/6967862648

Also, the latest WASM Demo that has gotten pushed to GCS has an error in the console

```
Uncaught (in promise) TypeError: _diplomat_wasm_mjs__WEBPACK_IMPORTED_MODULE_0__.Z.ICU4XLocale_create_en is not a function
    at ICU4XLocale.create_en (bundle.js:11717:118)
    at new FixedDecimalDemo (bundle.js:5112:174)
    at Object.setup (bundle.js:5155:30)
    at init (bundle.js:4883:62)
```

See https://storage.googleapis.com/icu4x-pr-artifacts/gha/ed91bab61b41132f0a4c1195268afe4a304920ab/wasm-demo/index.html

**Comment by robertbastian** [comment]
The `en` thing is already fixed on main: https://github.com/unicode-org/icu4x/blame/main/ffi/diplomat/js/examples/wasm-demo/src/ts/fixed-decimal.ts#L17

The key file was named `required_keys.txt` instead of `required-keys.txt`.

Why do these actions run on the commit level instead of on the PR level? They don't get shown in PRs, so it's really easy to miss a breakage.

**Comment by sffc** [comment]
> Why do these actions run on the commit level instead of on the PR level?

Because they need the GCP key and that needs to be run in the repo context instead of the PR context because otherwise anyone could open a PR and harvest the key.

**Comment by robertbastian** [comment]
We could store it as an action artifact and have another job upload it?

> anyone could open a PR and harvest the key.

For outsiders CI should only run after a review.

**Comment by sffc** [comment]
> We could store it as an action artifact and have another job upload it?

Works for me

> > anyone could open a PR and harvest the key.
> 
> For outsiders CI should only run after a review.

I agree, but there's not a way in GHA, last I checked, to make repository secrets available to PRs, in order to protect against this potential vulnerability.
