### ISSUE TITLE
GH pages structure

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3054]
Currently we host all our artifacts (docs, benchmarks) on `https://icu4x.unicode.org`, which is backed by the `icu4x-docs` repo. The last commit to that repo was on Dec 30, so something's broken.

We also have a `gh_pages` branch in the `icu4x` repo, however that only contains benchmarks (no docs), and hasn't seen a commit since Oct 11.

I propose we move forward as follows:
* `icu4x/gh_pages` gets updated on each commit to `icu4x/main`. It should contain
  * Rustdoc
  * FFI docs
  * Benchmark results
  * WASM demo
* `icu4x-docs/gh_pages` gets updated manually from `icu4x/gh_pages` on release.
  * Should it contain all of the above? I guess it doesn't hurt and we don't actually expose links to benchmark results and the WASM demo (although `icu_capi` docs should point to FFI docs).
 
This way `https://unicode-org.github.io/icu4x/` can be our internal site at head, whereas `https://icu4x.unicode.org` is our public site frozen at the latest release.

**Comment by sffc** [comment]
@echeran

**Comment by robertbastian** [comment]
Since implementing the CI improvements my proposal has changed a bit:
* The `icu4x/gh-pages` branch is not required. We can push directly to the repo's GH page from CI. This reduces repository and tree size
* `icu4x-docs/gh-pages`: I'd rather not host anything here until we have a proper landing page. I don't see much value in having the docs there, as we can just redirect to docs.rs which always has the latest released docs (even for out-of-cycle releases), as well as the docs for all previous versions. It would be considerable work to duplicate this (useful) functionality.

Not having any content at `icu4x.unicode.org` means we could actually transfer the domain to this repo. `/` would redirect to docs.rs, but we could still host wasm-demo, ffi docs, etc. under the appropriate URLs.
