### ISSUE TITLE
Supporting runtime property use cases

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3063]
Regex engines like those in the Dart Engine (and Spidermonkey) need to be able to work with properties that have been selected at runtime, from a property string.

This requires the ability to get a unicode set given a property name (and optional value), which may be strings.

ICU4X users can do this manually but they'll have to deal with added properties manually, which isn't great since it doesn't let you update to newer property values in a data driven way.

This will probably need:

 - A mapping for property aliases
 - A mapping from property value names (and aliases) to their indices
 - Potentially some kind of AnyProperty type that works like AnyCalendar

cc @iainireland @echeran @sffc

**Comment by sffc** [comment]
Related: https://github.com/unicode-org/icu4x/issues/842

In particular, see @iainireland's prototype here: https://github.com/mozilla/icu4x_js_regexp

The key design consideration here is that we need to think carefully about making this work nicely with data slicing.

**Comment by Manishearth** [comment]
I think this might be a case where we have a special "auto" key and allow datagen to be configured on a list of properties.

**Comment by Manishearth** [comment]
Here's a plan:

 - We support a UProperty-like enum that can be parsed from string (we currently have `EnumeratedProperty` but it does nothing)
 - We support getting property enumerated value integers from strings.
 - We add an API for querying binary and enumerated properties using a property and property value, but only for the [ECMA262 subset](https://tc39.es/ecma262/#table-nonbinary-unicode-properties), and name it something sufficiently ecma262y


This may need some support for data from PropertyAliases and PropertyValueAliases.txt

**Comment by Manishearth** [comment]
I'm going to get name-to-id (and alias) mappings into icuexportdata

**Comment by Manishearth** [comment]
https://unicode-org.atlassian.net/browse/ICU-22270

**Comment by Manishearth** [comment]
PR at https://github.com/unicode-org/icu/pull/2312

**Comment by Manishearth** [comment]
More fleshed out plan:

 - We have a UnicodeProperty enum, ideally matching UProperty. We hardcode a from-string getter¹
 - It can tell you if something is binary, enumerated, scx, gcm, etc
 - It can tell you if something is ecma402-only².
 - We add a property name-to-enum mapper (https://github.com/unicode-org/icu4x/pull/3103)
 - For the ecma402 subset of enumerated properties and scx, UnicodeProperty is able to load the mapper for that type via `get_ecma402_subset_name_to_value_mapper()` or something². 
 - We add a binary property name lookup function using hardcoded data¹. Binary properties bucket under ones which accept Yes/No and ones which accept Yes/No/True/False, and potentially fancier ones, this will be easy to hardcode.
 - We add ways to get a CodePointSet/Map/etc for the ecma402 subset² of properties. (set for binary , map for enumerated, scx for scx, probably a different map type for gcm.



¹ Hardcoded getters potentially can use baked data, or be otherwise tested against icuexportdata.

² All ecma402 subset apis will be named accordingly

**Comment by Manishearth** [comment]
I've got a first pass for this in https://github.com/unicode-org/icu4x/pull/3169
