### ISSUE TITLE
Support getting ranges for CodePointMaps over FFI

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3064]
Currently over FFI we have the types [`ICU4XCodePointSetData`](https://icu4x.unicode.org/doc/icu_capi/properties_sets/ffi/struct.ICU4XCodePointSetData.html) and [`ICU4XCodePointMapData16`](https://icu4x.unicode.org/doc/icu_capi/properties_maps/ffi/struct.ICU4XCodePointMapData16.html#) for working with property sets.

However, these cannot be used in unicode sets just yet. Regex engines like the ones in the Flutter SDK need the ability to convert these into UnicodeSets and mutate them.

In pure Rust code this is possible by calling [`as_code_point_inversion_list()`](https://icu4x.unicode.org/doc/icu_properties/sets/struct.CodePointSetData.html#method.as_code_point_inversion_list) or [`as_code_point_trie()`](https://icu4x.unicode.org/doc/icu/properties/maps/struct.CodePointMapData.html#method.as_code_point_trie) and then messing with their ranges to build your own set.

This is inconvenient in Rust, and impossible over FFI.

We should probably expose some sort of CodePointSet api that can be mutated and is convenient to use with these.

cc @iainireland @echeran @sffc

**Comment by Manishearth** [comment]
For Dart's needs my understanding is that we need:

 - Construction from ranges
 - Complement
 - Ability to casefold over the set

We ought to be able to implement the construction/complement operations directly without any issues. The casefolding one is trickier but doable.

**Comment by sffc** [comment]
For FFI purposes I think it's fine, easy, and efficient to make a single mutable `CodePointInversionList` type. It doesn't gain us much to split out the builder when talking FFI.

It's trickier to talk about a mutable `CodePointTrie`. Does the client need a mutable map, or only a mutable set?

**Comment by Manishearth** [comment]
I think the client just needs a mutable set, because the only way it uses maps is to turn them into a set first.

I think the main thing we need on the Rust side is convenient construction functions that support complement (etc).

**Comment by Manishearth** [comment]
Actually, all the client needs is iter_ranges() and complement + iter_ranges()

And we can slap on an `iter_ranges_complement()` function for that.

**Comment by Manishearth** [comment]
As a part of this we should also add `CodePointMapDataBorrowed::iter_ranges_for_value()`
