### ISSUE TITLE
Casefolding FFI

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3065]
The casefolding component isn't exposed over FFI, but should be.

The Dart SDK needs this.

**Comment by Manishearth** [comment]
Actually they only need the abiltiy to check if the casefolded set for a _single_ character contains more than just that character.

We can probably have an API returning a list, and perhaps another API that just returns the length.

**Comment by sffc** [comment]
Blocked on #2535

**Comment by Manishearth** [comment]
This happened
