### ISSUE TITLE
Support obtaining BCP-47 ids from metazone names

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3066]
On Fuchsia, the Dart SDK uses  [createTimeZone()](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1TimeZone.html#ae34bbf3a8bef70fa57a1b9fd49a1b47b) with metazone names obtained [from the OS](https://fuchsia.googlesource.com/fuchsia/+/745d7ec4a220/sdk/fidl/fuchsia.intl/intl.fidl?pli=1#54) ([usage site](https://github.com/dart-lang/sdk/blob/main/runtime/vm/os_fuchsia.cc)).

ICU4X currently only supports this stuff with BCP-47 ids. We should have a way to go from metazone names to BCP-47 ids.

I suspect this is already part of [the plan](https://github.com/unicode-org/icu4x/issues/887) but I'm not sure if there's a specific issue filed (@nordzilla?)

cc @sffc

**Comment by sffc** [comment]
In the link you posted, it shows `"America/New_York"`, which is an IANA time zone name, not a metazone name. Did you mean to ask about IANA-to-BCP47 mapping? That would be https://github.com/unicode-org/icu4x/issues/2909

**Comment by Manishearth** [comment]
⇒ https://github.com/unicode-org/icu4x/issues/2909
