### ISSUE TITLE
Removing testdata's lazy_static dependency

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3090]
Testdata depends on `lazy_static` for lazy loading the buffer provider (jntroduced in https://github.com/unicode-org/icu4x/pull/2363)

https://github.com/unicode-org/icu4x/blob/d2633f3dc32676c586c4fbdb8bf5f606bbc9faae/provider/testdata/src/lib.rs#L189-L202

Can we make this a Cargo feature? `lazy_static` in no_std mode pulls in an additional dependency (`spin`), and I'd rather not pull that in, even for testdata.

cc @sffc @robertbastian

**Comment by Manishearth** [comment]
It feels like testdata deps shouldn't matter much but I'd like to prune deps where possible and testdata is still useful for clients (I'm using it in Google3 for, well, testing)

**Comment by sffc** [comment]
I'm surprised that we have issues with `lazy_static` because that's a top 20 crate (probably top 10 of direct dependencies)

**Comment by sffc** [comment]
If we need to remove `lazy_static`, though, I have a slight preference to just dump the lazy_static and re-parse the buffer each time. It's not too terribly expensive, and it's only testdata.

**Comment by Manishearth** [comment]
@sffc No, it's because we're enabling an almost-never-used feature on `lazy_static` that makes it work in `no_std` environments by using a spinlock.

I don't think we should be splitting it that way: people who want to use testdata in no_std mode should just _not_ hit the lazy_static path in the first place, and normal `std` people can use normal lazy_static.

basically, we add a `std` feature to testdata (or a `buffer_lazy` feature), and if it's enabled `testdata` needs std (but uses lazy_static), otherwise buffer provider creation isn't cached.

**Comment by Manishearth** [comment]
(The reason I'm not sure if we should call it `std` is that testdata+fs needs std anyway, so that might be confusing)

Something like this:

```rust
[features]
default = ["buffer_lazy"]
buffer_lazy = ["lazy_static"]
buffer_provider = ...
[dependencies]
lazy_static = {version = "whatever", optional = true}
```

**Comment by sffc** [comment]
Okay. We already have an `icu_testdata/std` feature; can we just gate it on that?

**Comment by Manishearth** [comment]
Sure

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/3091
