### ISSUE TITLE
SentenceBreaker breaks '.\n', it's different from icu4c

### ISSUE THREAD

**Issue by lz1998** [unicode-org/icu4x#3118]
icu4x
Input: `Hello.\n Hello.`
Output: `Hello`, `.\n`, ` Hello.`

icu4c
Input: `Hello.\n Hello.`
Output: `Hello.\n`, ` Hello.`

**Comment by sffc** [comment]
@makotokato @aethanyc What's the expected behavior?

**Comment by makotokato** [comment]
It seems to be bug
