### ISSUE TITLE
`icu_casemapping` feature request: please provide an example

### ISSUE THREAD

**Issue by lucatrv** [unicode-org/icu4x#3162]
I understand that [`icu_casemapping`](https://icu4x.unicode.org/doc/icu_casemapping/index.html#) is still experimental, but it would be useful to include in its documentation a simple example such as [this one](https://icu4x.unicode.org/doc/icu_collator/#examples), so that people could start using and testing it.

I would issue a PR myself if I was able to, but sorry I'm having a hard time figuring out which provider I should pass to [`CaseMapping::try_new`](https://icu4x.unicode.org/doc/icu_casemapping/struct.CaseMapping.html#method.try_new). I tried with all providers included in crate [`icu_testdata`](https://icu4x.unicode.org/doc/icu_testdata/index.html#), but no one works. For instance, the following example does not work:

``` rust
let case_mapping = CaseMapping::try_new(&icu_testdata::unstable()).unwrap();
assert_eq!(case_mapping.full_fold("Pollo"), case_mapping.full_fold("pollo"));
```

I tried also using crate [`icu_provider`](https://icu4x.unicode.org/doc/icu_provider/index.html#) but with no luck. If you agree and give me some hints, I can issue a PR.

**Comment by lucatrv** [comment]
@sffc thank you so much for your hint!

The solution was very simple... I just had to enable the `icu_testdata/icu_casemapping` feature in my `Cargo.toml` file:
```toml
[dependencies]
icu_casemapping = "0.7.1"
icu_testdata = { version = "1.1.2", features = ["icu_casemapping"] }
```

I guess it will become a default feature once `icu_casemapping` is stabilized. Please feel free to close this issue unless you want to track this.

**Comment by sffc** [comment]
Should be done as part of https://github.com/unicode-org/icu4x/issues/3162.

**Comment by lucatrv** [comment]
@sffc is there any plan to make `icu_casemapping` a default feature of `icu_testdata` in future? In that case there would not be need for any added documentation.

**Comment by sffc** [comment]
> @sffc is there any plan to make `icu_casemapping` a default feature of `icu_testdata` in future? In that case there would not be need for any added documentation.

Yes, once the `icu_casemapping` component is stabilized. There's a decent chance that will happen in the 1.3 release in the middle of the year.

**Comment by lucatrv** [comment]
So IMHO we do not need to document the need to manually import that feature, but just keep this issue open until the stabilization happens for reference.

**Comment by Manishearth** [comment]
Bunch of examples got added in https://github.com/unicode-org/icu4x/pull/3553
