### ISSUE TITLE
How to link testdata

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#317]
#306 includes the testdata as:

```rust
    let provider = FsDataProvider::try_new("../../resources/testdata/data/json")
        .expect("Loading file from testdata directory");
```

The crate documentation says:

```rust
let data_provider = icu_testdata::get_provider();
```

Decide what to use in tests and in examples.

**Comment by zbraniecki** [comment]
I decided to use testdata everywhere in code, and document the use of `FsDataProvider` in docs, tutorials and wiki.
