### ISSUE TITLE
CLDR 43 integration

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3181]
* The negative japanese eras need to be ignored because we already insert gregorian eras ourselves: https://github.com/unicode-org/cldr-json/blob/v43.0.0-ALPHA2/cldr-json/cldr-core/supplemental/calendarData.json#L161-L165
* Numbering systems lookup should fall back to `Latn` (broken for `hnj-Hmnp`)
  * Maybe a data error, revert #3201?
* Mixed hour cycles #3212

**Comment by Manishearth** [comment]
Yeah ICU4X already supports these eras but the support is in _code_
