### ISSUE TITLE
DateTime patterns should remove quotes

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#319]
Looks like a small bug; I think you are supposed to remove the quotes.  Can you file a follow-up issue?

_Originally posted by @sffc in https://github.com/unicode-org/icu4x/pull/311#discussion_r502638526_

**Comment by sffc** [comment]
The spec is weak in this area. Upstream ticket: https://unicode-org.atlassian.net/browse/CLDR-10321

**Comment by zbraniecki** [comment]
If I'm not mistaken this text - http://unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns suggests that Literals can be only ASCII. That's definitely not the case :)

**Comment by zbraniecki** [comment]
Ah, no, more nuanced - non ASCII can be as-is, ASCII must be enclosed in `'`. Makes sense.

**Comment by zbraniecki** [comment]
Fixed in #336.
