### ISSUE TITLE
Settle on and implement a principled approach to ffi_coverage allowlist

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3232]
All public APIs must show up in one of three places for the `diplomat-coverage` test to succeed:

 - `rust_link`'d to a Diplomat API, potentially `hidden`
 - in [`missing_apis.txt`](https://github.com/unicode-org/icu4x/blob/main/ffi/diplomat/tests/missing_apis.txt), the "default" place it goes
 - in [ffi_coverage/src/allowlist.rs](https://github.com/unicode-org/icu4x/blob/main/tools/ffi_coverage/src/allowlist.rs), with a comment saying why we don't care about this API right now

In https://github.com/unicode-org/icu4x/pull/3176 I cleaned up `missing_apis.txt` a bit but there was some disagreement on how best to do this. We should discuss this: I'd like to settle on rules for what belongs where and then do a nice cleanup of the allowlist so that we are following those rules.

cc @sffc @robertbastian

**Comment by Manishearth** [comment]
My general take is that the three categories are useful, but we need to get better at organizing them. To me, here's what each thing implies:

 - `rust_link`: This API is directly exposed
 - `rust_link(hidden)`: All the functionality of this API _needed for FFI_ is already exposed. One or more of:
    - The Rust side has multiple ways of expressing this functionality and we are exposing it through a different method (where this attribute has been applied)
    - This API is only useful in Rust to do tasks related to the method this attribute has been applied to
 - `missing_apis.txt`: This is yet to be triaged. One or more of:
  - This is a temporary missing API between PRs
  - We want this missing API to be triaged when the release process happens
- `allowlist.rs`: This is a triaged missing API, and there's a documented reason we are okay with it being missing.
  - This API only makes sense in Rust or handles Rust-specific things
     - Ideally find a method to tag this on as `rust_link(hidden)` instead.
  - We have made a conscious choice to not expose this API over FFI _yet_ (examples: provider APIs, API variants that don't exist because of missing diplomat features like Write16, direct CodePointSet/Map manipulation functions)
     - This should link to an issue and be organized
  - This API is experimental
     - I'm not sure about this one


The reason I do not like having `missing_apis.txt` be full is that it becomes really hard to understand at a glance what needs to be triaged, and the file does not support comments. We have a _lot_ of APIs we haven't exposed yet, usually related to functionality that is not core and center to our crates. To be able to plan work around that we need to understand what the state is.


Note that _currently_ we do not really follow the categorization listed above. In particular, `allowlist.rs` contains a lot of things that should be moved to `rust_link(hidden)`, and it does not have filed issues.  But this would be a concrete cleanup that could be done as long as we agree on how things are to be bucketed.

**Comment by sffc** [comment]
I agree with the above reply.

**Comment by Manishearth** [comment]
Great! I think I would like this to at least pass the eyes of the rest of the team (and ideally want explicit +1 from @robertbastian), and then I would consider this ready to go

**Comment by Manishearth** [comment]
The main advantage is that it's managed in source next to all of the other similar APIs and people doing FFI notice it, it doesn't get forgotten in some allowlist file.

So I'm not against hidden completely, I think it's a very useful tool for cases where it _can_ be grouped with some other API. We have a lot of cases where the Rust side has multiple APIs for purely Rusty reasons,  and instead of trying to group these it makes sense to just hidden-mark them on their related APIs. Basically, that itself serves as a signal for "this functionality is already exposed here" and you don't need a further comment. If you find yourself needing a further comment, use the allowlist.

**Comment by sffc** [comment]
Discuss with:

- @sffc 
- @Manishearth 
- @robertbastian

**Comment by Manishearth** [comment]
Is there need for further discussion here?

**Comment by sffc** [comment]
Also we need to generally review all the lists with a 2.0 lens.

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/4683 contains the result of our discussion.

Potential cleanups:

 - Teach diplomat-coverage to ignore traits and potentially other public items
