### ISSUE TITLE
Update wasmer to 3.1.1

### ISSUE THREAD

**Issue by Razican** [unicode-org/icu4x#3241]
It turns out that `icu_codepointtrie_builder` depends on `wasmer` 2.2.1, which in its dependency tree contains the `mach` dependency. This dependency is no longer maintained, as it can be seen in the below advisory.

The good news is that `wasmer` 3.1.1 no longer depends on `mach`, so an update of the dependency should solve the issue.

----

> mach is unmaintained

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `mach`                      |
| Version             | `0.3.2`                   |
| URL                 | [https://github.com/fitzgen/mach/issues/63](https://github.com/fitzgen/mach/issues/63) |
| Date                | 2020-07-14                         |

Last release was almost 4 years ago.

Maintainer(s) seem to be completely unreachable. 

## Possible Alternative(s)

These may or may not be suitable alternatives and have not been vetted in any way;
- [mach2](https://crates.io/crates/mach2) - direct fork

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2020-0168.html) for additional details.

**Comment by sffc** [comment]
@Razican Would you like to make a PR for this?

**Comment by Razican** [comment]
> @Razican Would you like to make a PR for this?

I was trying to do the PR yesterday, but since I'm not familiar with ICU and washer, I didn't know how to migrate the compile errors

The new version doesn't have some features used by ICU4x, but it seems it now can use other crates to implement the required compilers and engines.

**Comment by robertbastian** [comment]
Wasmer 3.1.1 doesn't even build for me. It's also broken on docs.rs, and in fact still seems to pull in `mach`.

**Comment by robertbastian** [comment]
All we can do here is update wasmer, although that doesn't seem to remove the dependency (https://github.com/unicode-org/icu4x/pull/3367#issue-1677295738)
