### ISSUE TITLE
Make icu_harfbuzz be safe and no_std

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3257]
If/when the upstream harfbuzz crate merges https://github.com/servo/rust-harfbuzz/pull/197, we will be able to make icu_harfbuzz be both safe and no_std.

**Comment by sffc** [comment]
I updated https://github.com/servo/rust-harfbuzz/pull/197 such that the dependency is now std-optional. Just waiting on that upstream PR to be reviewed, merged, and shipped on crates.io.

**Comment by sffc** [comment]
https://github.com/servo/rust-harfbuzz/pull/197 is merged. We should be able to remove most or all of the unsafe FFI bindings on the icu4x side once the crate is released.

**Comment by sffc** [comment]
Waiting for upstream to make a release: https://github.com/servo/rust-harfbuzz/pull/245

**Comment by Manishearth** [comment]
A release just happened

**Comment by Manishearth** [comment]
Going to take a crack at updating to UnicodeFuncs
