### ISSUE TITLE
Benchmark command doesn't recognize CLI flag

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#327]
The benchmark commands are not working currently.  Based on [recent CI runs](https://github.com/unicode-org/icu4x/actions?query=branch%3Amaster+workflow%3A%22Build+and+Test%22), they were working after the recent merge of fixes to API docs and bechmark dashboards, and continued working for a few commits.

The issue seems to have started after introducing the improvements to unify bechmarks and put them into categories `overview` and `detailed` (#325).  The [benchmark actually runs fine, but at the end, it complains](https://github.com/unicode-org/icu4x/runs/1236730145?check_suite_focus=true#step:4:181) about a command-line flag: `error: Unrecognized option: 'output-format'`.  That CLI flag was a necessary change that we made in order to get the criterion output formatted in a bencher-style format in order to be compatible with the Rust support within the GH action for benchmarks.

@zbraniecki lmk if you have suggestions

**Comment by zbraniecki** [comment]
I pushed a fix to clippy warnings, let's see what happens with the benchmark.

**Comment by zbraniecki** [comment]
ah! I think I know what's up. In my #325 I removed a bunch of

```
[lib]
bench = false
```

because they didn't seem to have an impact, but now I remember that they may have on CI. Can you try re-adding them and if it works land a fix with a comment like `This option is required for Benchmark CI`?
