### ISSUE TITLE
RuleBreakIterator status

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3277]
@eggrobin discovered that accessing the rule break status during segmentation is rather tricky because [`RuleBreakIterator::rule_status()`](https://unicode-org.github.io/icu4x/docs/icu/segmenter/struct.RuleBreakIterator.html#method.rule_status) is a method on the iterator (which means it cannot be accessed within iterator adapters since you'd need to hold on to a borrow of the iterator whilst using mutable methods.

This is unfortunate; if you care about rule status it seems useful to be able to call things like `.filter()`. It's not the end of the world, manual iteration with a `while let Some(brk) = iter.nex()` will work fine, but it's not great.

A useful API would be to have a second `RuleBreakWithStatusIterator`, ideally obtainable via `RuleBreakIterator::with_status()` (this way we don't need a duplicated suite of iterator methods).

Filing for future consideration, I don't think we have to have this for 1.0, though it might be nice.

cc @sffc @aethanyc @makotokato

**Comment by sffc** [comment]
Since this is only needed for WordBreak, it seems it would be okay to add `WordBreakWithStatusIterator`
