### ISSUE TITLE
tzif: `LocalTimeTypeRecord`'s `idx` field provides no useful information

### ISSUE THREAD

**Issue by jhpratt** [unicode-org/icu4x#3280]
I am currently trying to statically generate code representing the tzdb such that it can be used with the [`time` crate in Rust](https://github.com/time-rs/time/). `tzif` uses vecs for storage, so I'm functionally copying the API, but using static slices.

In any situation, when trying to use the parsed data, I noticed something odd. `tzif::data::tzif::LocalTimeTypeRecord` [has the `idx` field](https://docs.rs/tzif/latest/tzif/data/tzif/struct.LocalTimeTypeRecord.html#structfield.idx), which is clearly based on the IETF specification, being an offset to a slice of bytes. Which is great…if you're trying to _write_ a tzif file. But when parsing, all information tying that byte offset to a meaningful value is functionally lost, as the parser pulls in the actual strings, discarding the original slice of bytes. I think the most useful thing to do here would be to change `idx` to be an index in the Rust sense (something that can be passed to `time_zone_designations[X]`) rather than the C sense of being a byte offset. This is obviously a breaking change, but it appears as though no one is really using  the`tzif` crate at the moment (outside of this repository).

I am happy to discuss alternate API solutions! As the structs are fully public and not marked `#[non_exhaustive]`, any solution is necessarily breaking. If my proposed solution is acceptable, I can look into creating a PR implementing the change.

**Comment by sffc** [comment]
CC @nordzilla who wrote and owns the tzif crate.

Tentatively it seems that this is a reasonable surface to add to the tzif crate. We'd be open to reviewing a PR, pending feedback from @nordzilla.

**Comment by nordzilla** [comment]
Hi @jhpratt, thanks so much for filing this issue! I apologize for the delay in responding.

I definitely agree with your feedback about the `idx` value itself not having a meaningful use post-parsing. 

My initial and primary intent for this crate was for ICU4X to have a TZif parser that we could utilize for our data generation purposes, so I wrote a parser according to the spec. 

As a path of least resistance, I just created plain data types to match what I saw in the spec and made everything public.

While ICU4X itself is beyond `v1.0`, the TZif crate is currently `v0.2.1` and has not yet been integrated into the ICU4X data-generation process outside of experimentation. I am more than happy to allow any breaking changes that improve the TZif crate, even as far as making the data members fully private and providing a public API for utilizing the Tzif data in more meaningful and easy-to-use ways. 

I do not currently have the resources to prioritize making such changes myself. However, I very much appreciate any feedback and will gladly review any PRs, especially if it makes the crate more usable to the the Rust community.

**Comment by jhpratt** [comment]
Coming back around to this months later.

> My initial and primary intent for this crate was for ICU4X to have a TZif parser that we could utilize for our data generation purposes, so I wrote a parser according to the spec.

Is the crate intended for general purpose use, or primarily for ICU4X? If it's the latter, I'll probably end up writing my own parser (or forking this) to meet my particular needs. I ask because nothing immediately comes to mind in terms of _both_ expanding the functionality to meet my needs _and_ maintaining the functionality that ICU4X presumably needs.

**Comment by Manishearth** [comment]
Triage: We're happy to accept contributions to fix this but are unlikely to fix this ourselves. We're okay if ICU4X needs some refactoring on a future change to this crate.

**Comment by jhpratt** [comment]
At this point, I will almost certainly _not_ be sending a PR for this. I have been working on my own parser for tzif files, which provides me both more flexibility and significantly better performance (hundreds of times faster). For this reason I don't mind if the issue is closed, given that it seems the `tzif` crate is meant primarily for ICU4X.

**Comment by Manishearth** [comment]
Sounds good, glad you found a way through! Feel free to reopen if you ever end up wanted to offload maintenance on this crate instead, in general were happy to maintain this stuff if someone contributes it.
