### ISSUE TITLE
Any interest in adding `rust_icu` to `ecosystem.md`?

### ISSUE THREAD

**Issue by filmil** [unicode-org/icu4x#33]
About https://github.com/unicode-org/omnicu/blob/master/docs/ecosystem.md

At the moment it seems that only one implementation per each `icu::*` is listed.  Any interest in listing other implementations, or just candidates for ICU4X inclusion?

**Comment by Manishearth** [comment]
Perhaps add a new column since each one will be listed there? Having a rust_icu docs.rs link for each entry would be valuable

**Comment by sffc** [comment]
I think it makes a lot of sense to add a column to ecosystem.md showing the corresponding rust_icu solution for each line.
