### ISSUE TITLE
Keys exporting doesn't work for Segmenter LSTM

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#3307]
I have a "minimal" example that does:

```rust
icu_segmenter::LineSegmenter::try_new_auto_with_buffer_provider(provider).unwrap();
icu_segmenter::WordSegmenter::try_new_auto_with_buffer_provider(provider).unwrap();
icu_segmenter::GraphemeClusterSegmenter::try_new_with_buffer_provider(provider).unwrap();
icu_segmenter::LineSegmenter::try_new_lstm_with_buffer_provider(provider).unwrap();
```

which generates a binary with the following symbols:

```
icu4x_key_tagsegmenter/lstm@1
icu4x_key_tagsegmenter/word@1
icu4x_key_tagsegmenter/dictionary@1
icu4x_key_tagsegmenter/line@1
icu4x_key_tagsegmenter/grapheme@1
```

but two of them do not map to anything and the resulting postcard fails on missing:

```
segmenter/lstm/wl_auto@1
segmenter/dictionary/w_auto@1
```

Specifying those two keys manually does work.

**Comment by robertbastian** [comment]
The keys were renamed recently, `segmenter/lstm@1` for example doesn't exist anymore. Did you build your binary at head?

**Comment by zbraniecki** [comment]
Ah, yeah... I was using `target/release` and I rebuilt `target/debug`. Thank you Robert!
