### ISSUE TITLE
Flaky test for cldr-json-data-provider

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#333]
In one of the runs of `cargo test`, it failed on one instance of the test because a test is triggering a [file download, and that timed out](https://github.com/unicode-org/icu4x/pull/326/checks?check_run_id=1243233643#step:4:379):

```
test transform::plurals::test_basic ... ok
test download::io_util::test_download_sync ... FAILED

failures:

---- download::io_util::test_download_sync stdout ----
Error: Reqwest(reqwest::Error { kind: Request, url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", source: TimedOut })
thread 'download::io_util::test_download_sync' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Some sort of caching could make this more robust, and this is what the GH Actions cache is for -- caching non-changing/immutable content, in case it is expensive or flaky to obtain.  I'm not sure yet if the test needs to be rewritten accordingly.

**Comment by echeran** [comment]
Note for later: @srl295 handles this type of thing when [caching a tarball download in the `unicode-org/cldr` repo](https://github.com/unicode-org/icu/pull/1270#discussion_r485094982).

**Comment by sffc** [comment]
We can probably just delete the test, or make it skipped and runnable locally.

**Comment by sffc** [comment]
Next step: update the comment to remove the TODO and explain why someone might want to re-enable the test.
