### ISSUE TITLE
Another feature resolution bug

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3338]
The command

```
cargo run --all-features -- --keys=core/helloworld@1 --all-locales --format=blob --out=/dev/null --overwrite
```

fails when run at the workspace root, due to some problem in the `time` crate. When run from inside the `icu_datagen` crate, it succeeds. Updating `Cargo.lock` does not fix the issue, but using a more recent `simple_logger` does.

This is a problem with the workspace, so does not affect the release.

**Comment by sffc** [comment]
Note that the latest release of `time` requires a version of Rust newer than our MSRV, so I had to manually set it in the lockfile (`cargo update --precise`) to the latest version that is compatible with MSRV.
