### ISSUE TITLE
Remove serialize_none feature when possible

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#335]
When https://github.com/serde-rs/serde/issues/1732 gets fixed, remove the "serialize_none" feature so that the Serialize implementation of data structures does not need to depend on which serializer is being used.

Until then, running the FsDataProvider's export tool with bincode requires three feature flags:

    $ cargo run --features export,bincode,serialize_none

(This issue is not actionable until https://github.com/serde-rs/serde/issues/1732 is fixed)

**Comment by sffc** [comment]
I'm shamelessly adding this to the 0.2 milestone.  I need to document features in #556, and I don't want to have to document this feature.  It is widely misused in ICU4X and causes more harm than good.

Longer term, we should fix the underlying problem in Serde.

**Comment by Manishearth** [comment]
Opened https://github.com/unicode-org/icu4x/pull/613 for the short term fix.

Potential long term fixes are gated on either https://github.com/serde-rs/serde/issues/2012 or  https://github.com/bincode-org/bincode/issues/387
