### ISSUE TITLE
URL for mailing list is not user-agnostic

### ISSUE THREAD

**Issue by lianghai** [unicode-org/icu4x#3352]
I got a “We are sorry, but you do not have access to Google Groups. Please contact your Organization Administrator for access.” error because my second Google account doesn’t allow Google Groups, but the error page shows my first account on the top-right corner. Very confusing.

https://github.com/unicode-org/icu4x/blob/8f611d9c9cd238afbe74ce5df0f8eddcba423221/README.md?plain=1#L15

Note the `/u/1/` part. Should use `https://groups.google.com/a/unicode.org/g/icu4x-announce` instead.

**Comment by sffc** [comment]
Opened https://github.com/unicode-org/icu4x/pull/3353 to fix!

I wonder how many sign-ups we've lost because of this...
