### ISSUE TITLE
Versioning of relative dependencies

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#339]
Cargo.toml files have things like

```
icu-locale = { version = "0.0.1", path = "../" }
```

When developing, the `path = "../"` wins.  However, when deploying, I guess the case is that `version = "0.0.1"` wins?  If that's the case, we should add a lint that the versions are all in sync with each other so that we don't accidentally push crates to crates.io with out-of-date dependencies.

@zbraniecki @Manishearth @filmil @echeran

**Comment by zbraniecki** [comment]
`cargo publish` will bail in that scenario. It's not going to allow you to publish without fixing it.

**Comment by Manishearth** [comment]
What zibi said, when it's lone version it fetches from crates.io. When you have multiple specs (git+version, path+version, it tries the other one if it can, and the version is treated as a constraint)
