### ISSUE TITLE
WordBreakIterator::word_type() returns wrong type

### ISSUE THREAD

**Issue by MichalDolata** [unicode-org/icu4x#3392]
I was testing [an example](https://docs.rs/icu/latest/icu/segmenter/struct.WordSegmenter.html#:~:text=Not%20all%20segments%20delimited%20by%20word%20boundaries%20are%20words%3B%20some%20are%20interword%20segments%20such%20as%20spaces%20and%20punctuation.%20The%20WordBreakIterator%3A%3Aword_type()%20of%20a%20boundary%20can%20be%20used%20to%20classify%20the%20preceding%20segment.) from https://docs.rs/icu/latest/icu/segmenter/struct.WordSegmenter.html and I spotted a bug.

If the last character is `.` preceded directly by word, the word isn't returned in result.

```
use icu::segmenter::{WordSegmenter, WordType};
use itertools::Itertools;

fn main() {
    let text = "one.";
    let segmenter =
        WordSegmenter::try_new_auto_unstable(&icu_testdata::unstable()).expect("Data exists");
    let words: Vec<&str> = {
        let mut it = segmenter.segment_str(text);
        std::iter::from_fn(move || it.next().map(|i| (i, it.word_type())))
            .tuple_windows()
            .filter(|(_, (_, status))| *status == WordType::Letter)
            .map(|((i, _), (j, _))| &text[i..j])
            .collect()
    };

    println!("{:?}", words);
}
```

I expect it to return `["one"]` but it returns empty vector. But if `.` is replaced with other punctation mark, for example `?` it works as expected.

I'm new to `icu4x` so I wasn't able to prepare fix for that :/

**Comment by sffc** [comment]
In `one.` it appears that we do find a breakpoint between the `e` and the `.` -- my initial guess is that the lookahead sees the `.` and returns a different rule status (since it could be an abbreviation, URL, etc) than `?` which is a definite hard stop. @makotokato @aethanyc Can you take a look at what the expected behavior is here?

**Comment by aethanyc** [comment]
I can reproduce this. I'll look into it.
