### ISSUE TITLE
Consider a cargo option to ingest JIS X 0208, Big5, and GB2312 orders from encoding_rs

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#34]
The CLDR collation order for Japanese includes a chunk of data that's just Level 1 Kanji followed by Level 2 Kanji from JIS X 0208. (Starts with `&[last regular]<*亜`)

CLDR includes alternative collation orders for Chinese, `gb2312han` (starts with `&[last regular]<*啊`) and `big5han` (starts with `&[last regular]<*兙`) that appear to be Level 1 Hanzi followed by Level 2 Hanzi from GB2312 and Big5, respectively.

We might want to consider whether it makes sense as a binary size optimization (depending on what data layout the collator needs and whether the `gb2312han` and `big5han` orders are in actual use) to provide a cargo option on ICU4X collator and a cargo option on encoding_rs to use the data that already exists in the data segment of apps that depend on encoding_rs for constructing (the relevant parts of) these collation orders.

(This is just "writing this down". I don't expect us to act on this anytime soon.)

**Comment by hsivonen** [comment]
Filed a [use counter request for Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1630920).

**Comment by sffc** [comment]
Assigning this to you with the "backlog" label (see the upcoming "triaging.md" for what that means).  When this issue becomes actionable, you can reopen it and start work.

**Comment by hsivonen** [comment]
[Chromium source](https://chromium.googlesource.com/chromium/deps/icu/+/refs/heads/master/filters/common.json#1512) has a rule for excluding the big5han and gb2312han collation orders from CLDR and has a comment that says: "big5han and gb2312han collation do not make any sense and nobody uses them."

**Comment by hsivonen** [comment]
This issue is based on a misunderstanding of when this data is used: The data is used before compile time; this issue assumed run-time use. Also, after filing this, Firefox, like Chrome, has unshipped suppor for the Big5 and GB2312 collations.
