### ISSUE TITLE
local-only test-js failure: Serde Deserialization Error / wasm function signature contains illegal type

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3400]
This happens when I run `test-js` locally

`test-js` is run as a part of our CI and there are no problems there.

Unsure what's going on, filing to keep track

```
added 284 packages in 1.328s

> icu4x@0.0.1 test /home/manishearth/dev/icu4x/ffi/diplomat/js/examples/node
> ava


[WARN] ICU4X data error: Postcard deserialize:  
[WARN] Returning ICU4XError::DataCustomError based on original icu_provider::error::DataError: ICU4X data error: Postcard deserialize
  fixed-decimal.mjs › convert a simple decimal to a string

  Error thrown in test:

  TypeError {
    message: 'wasm function signature contains illegal type',
  }

  › Function.create_from_i64 (file://lib/ICU4XFixedDecimal.js:30:39)
  › file://test/fixed-decimal.mjs:10:37

  ─

  1 test failed
npm ERR! Test failed.  See above for more details.
```

**Comment by Manishearth** [comment]
Found whilst working on https://github.com/unicode-org/icu4x/pull/3401 but I could reproduce it without that PR

**Comment by sffc** [comment]
Node version?

**Comment by Manishearth** [comment]
oops, forgot to include it

```
[11:10:22] मanishearth@manishearth-glaptop2 ~/dev/icu4x ^_^ 
$ node --version
v14.19.1
[17:02:50] मanishearth@manishearth-glaptop2 ~/dev/icu4x ^_^ 
$ npm --version
6.14.16
```

**Comment by sffc** [comment]
Can you update to node 16 and report if it fixes it?

https://github.com/unicode-org/icu4x/commit/ee28e44378b7c5b6f356d3c1e375b2027c7d4c5b

**Comment by sffc** [comment]
I'd bet $20 that the problem is the following change in the above CL

https://github.com/unicode-org/icu4x/commit/ee28e44378b7c5b6f356d3c1e375b2027c7d4c5b#diff-c24d9612d2cfcea64e6430f945c6bc2cc990090c474660b267da8b9265981ca0

This was pre-1.0 so I didn't bother to make the test work in both 14 and 16. I made it work in 16 (which didn't work before) and broke 14 in the process.

**Comment by sffc** [comment]
I'm not sure why the error points to Postcard though. Puzzled by that one. My guess is that we don't run the function that takes the i64 and somehow that puts future calls into an invalid state.

**Comment by Manishearth** [comment]
_shrug_ I don't think we should care too much about older Node.

And yeah I think that's just an error bubbling out weirdly through broken invariants

**Comment by Manishearth** [comment]
Yep, works now. I use nvm so despite the APT node updating the one that I actually end up seeing was still old.

I figured it was something like this but felt that it would make sense to file the issue as a breadcrumb for others.
