### ISSUE TITLE
icu_datagen fails to build or install because of issue with matrixmultiply 0.3.5

### ISSUE THREAD

**Issue by autarch** [unicode-org/icu4x#3403]
The issue in question is https://github.com/bluss/matrixmultiply/issues/76

This affects `icu_datagen` because of its dependency on `ndarray`, which in turns depends on `matrixmultiply`:

```
matrixmultiply = { version = "0.3.2", default-features = false, features=["cgemm"] }
```

If you want to fix this locally, you can do so by adding this to the `Cargo.toml` for `icu_datagen`:

```
matrixmultiply = { version = "0.3.2" }
```

**Comment by bluss** [comment]
The workaround is to temporarily enable the std feature on matrixmultiply. New version should be out soon.

**Comment by sffc** [comment]
This just showed up today on our CI. Thanks for working on a fix @bluss!

https://github.com/unicode-org/icu4x/actions/runs/4844196606/jobs/8632324030

**Comment by sffc** [comment]
According to the other thread, this is only an issue with no-default-features. Since we only depend on ndarray in icu_datagen, it would probably be acceptable for us to enable the default features.

**Comment by bluss** [comment]
It should be resolved by now since a new matrixmultiply was posted as version 0.3.6
