### ISSUE TITLE
`icu::list` docs differ from `icu_list` docs

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3433]
While docs are built with `--all-features`, the `icu` crate does not have a `datagen` feature, so we don't actually get all of `icu_list`'s features. At the moment this means that datagen-specific functionality is not documented in the meta-crate.

This applies to all crates, not just `icu_list`.

**Comment by sffc** [comment]
@Manishearth - The question is not should we fix this, but how to we fix this.

**Comment by sffc** [comment]
Additional discussion:

- This is only for features that aren't enabled by the metacrate, which is limited to non-default features and features that don't otherwise have a metacrate feature (like `serde`)
- So the scope here seems sufficiently small that this is WAI
