### ISSUE TITLE
Automate bincode and/or static data generation for benchmarks

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#346]
Loading JSON files from the file system using `std::io` is straightforward and good for testing, but it isn't as useful for performance benchmarks or code size benchmarks.

We should wire up the testdata project to generate data in other formats.  I suggest that we use `build.rs` to generate the other data formats on the fly, based on the content of the JSON files.  This way we keep only the JSON files in source control, and the other files are dynamically generated.

**Comment by gregtatum** [comment]
I'm assigned to this, but I don't really have context for implementing it, and I don't really remember how I got assigned to it. Is the work here to do:

1. Deserialize JSON
2. Write out bincode
3. Run benchmarks with bincode
4. Make the above configurable for other formats other than bincode.

I spent some time profiling JSON vs bincode this week, and it was pretty painful.

**Comment by sffc** [comment]
I'll steal this issue back.  I consider it blocked on #78.
