### ISSUE TITLE
Syntax of the zeroslice macro

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3478]
Right now it is `zeroslice![i16; somefunction; a, b, c, d]`

I think maybe it should be:

1. `zeroslice!(i16; somefunction; [a, b, c, d])`
2. `zeroslice!(i16, somefunction, [a, b, c, d])`
3. `zeroslice!(type: i16, cnv: somefunction, data: [a, b, c, d])`
4. ... ?

Discuss with:

- @skius 
- @robertbastian 
- @sffc
- @younies 

Optional:

- @echeran

**Comment by robertbastian** [comment]
#1935

**Comment by robertbastian** [comment]
I think if we can get rid of the aligned type we should not use named parameters, as that's not very rusty.

`zeroslice![somefunction; a, b, c, d]`

**Comment by sffc** [comment]
I think I prefer the `[]` to surround only the list: `zeroslice!(somefunction, [a, b, c, d])`

**Comment by robertbastian** [comment]
The extra level of nesting might make formatting weird. Also the `vec![]` macro conventionally uses square brackets, which I'd like to mirror, and then `zerovec![somefunction; [a, b, c, d]]` is a bit brackety.

**Comment by Manishearth** [comment]
No strong position, feel like `zeroslice![ty; conversion; a, b, c, d]` could work

**Comment by sffc** [comment]
What makes that syntax desirable? It violates every point I raised in the conversation:

- Semicolon followed by comma-separated list has no precedent and is just weird
- Lack of named arguments means we can't safely elide the conversion function or the type (unless we choose the model where there is never a type, but I'm not ready to make that call at this time)
- Lack of named arguments makes it less readable
- It is not `vec!` and can never be a drop-in replacement; it is a function that transforms things from one state to another

**Comment by sffc** [comment]
The strongest argument I heard in favor of a flat syntax (no nesting) is less indentation when formating. But, does the formatter even know what to do with the semicolon-followed-by-list?

**Comment by Manishearth** [comment]
I think it's not that weird because `[val; N]` syntax uses semicolons to separate heterogenous things. 

I think you can still elide things: one semicolon means `ty; values`, two means `ty; conversion; values`. The zero-value case is the only one where there's potential ambiguity and you don't actually need a conversion function for that.

I think it can be a drop in replacement by adding a zero-semicolon case eventually.

Anyway, it was just a suggestion, not something I am strongly in favor of.

**Comment by robertbastian** [comment]
> We need $ty when assigning to a non-const variable and potentially when special casing primitives

The non-const variable case can be solved with inline const, which iiuc is a lot closer than const traits: https://github.com/rust-lang/rust/issues/76001. I think it's fine to not do `$ty`, and let clients constify until we get inline const.

> VarZeroVec may need yet another named parameter

VZV and ZV can take different parameters without doing named parameters.


> The zero-value case is the only one where there's potential ambiguity and you don't actually need a conversion function for that.

The zero-value case is already special cased to `ZeroVec::new`, where there's no need to involve types, ULE, or intermediate `const`s.

**Comment by sffc** [comment]
- @skius - In areas where the type name or conversion function are rather long, I can see an argument that a clearer separation between arguments and values could be usable. Which could speak for the nested brackets over a simple semicolon.
- @zbraniecki - In my experience macros are using positional arguments. So I would lean toward 1 or 2 over 3 (from the list in the OP).
- @sffc - We never really aligned my hypothesis that we want both of these arguments to be independently optional.
- @Manishearth - We can change things later; it is zerovec. The point of this is to be convenient. So I like syntax 1. Not a huge fan of the nested parentheses but it's clearer.
- @sffc - I'm okay with option 1 if we can say that we'll revisit how to do optional arguments when we are able to do so down the road.

Consensus:

- Syntax: `zeroslice!(i16; somefunction; [a, b, c, d])`
- No consensus on the syntax when either of the first two parameters is omitted

LGTM: @sffc @skius @robertbastian @zbraniecki @Manishearth
