### ISSUE TITLE
Move casemapping over to an idiomatic data model

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3481]
Part of https://github.com/unicode-org/icu4x/issues/3234

`icu_casemap` has a data model that's not as idiomatic as the rest of ICU4X.

Some changes that need to be made:

 - [x] CaseMappingData should have pub fields and do bitpacking in the ULE world (https://github.com/unicode-org/icu4x/pull/3480)
 - [x] `CaseMappingExceptions`  should be a single structured `VarZeroVec` with everything (https://github.com/unicode-org/icu4x/issues/3501)
 - [ ] `unfold` _may_ benefit from being a `ZeroMap<str, str>`

**Comment by Manishearth** [comment]
I am choosing not to tweak `unfold`: unfold data is less commonly read; so storing it as a `str` seems fine.

It is only 455 bytes of ZeroMap value data, so I don't think it's a huge deal either way. (@sffc thoughts?)

Closing as completed since the rest is done, can reopen if we want to redo `unfold`

**Comment by sffc** [comment]
Hm? Isn't it already a ZeroMap?

```
pub struct CaseMappingUnfoldData<'data> {
    #[cfg_attr(feature = "serde", serde(borrow))]
    /// The actual map. Maps from strings to a list of codepoints, stored as a contiguous UTF-8 string
    pub map: ZeroMap<'data, str, str>,
}
```

**Comment by Manishearth** [comment]
Oh sorry, the proposal was `ZeroMap<str, [char]>` . I mistyped in the issue, fixing
