### ISSUE TITLE
`BlobDataProvider` should return `DataErrorKind::ExtraneousLocale` for singleton structs

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3505]
Currently it returns `MissingLocale`, which is not correct, as it will make fallback continue. For example requesting `de-DE` for a singleton with fallback will try `de-DE`, `de`, `und` and actually succeed, where it should be an error because trying `de-DE` for such a key is a bad request.

**Comment by robertbastian** [comment]
Fixed in #3494 for databake.

**Comment by robertbastian** [comment]
We might want to add the singleton-ness of a `KeyedDataMarker` to the key metadata.

**Comment by sffc** [comment]
> We might want to add the singleton-ness of a `KeyedDataMarker` to the key metadata.

+1

**Comment by sffc** [comment]
Discussion:

- Good to add a `singleton` field to the DataKeyMetadata
- _Maybe_ add a `load_singleton` or `load_und` function to DataProvider (with a default implementation that calls `load`), but we're not convinced if it's actually useful
- We could make the singleton part of the type system, but @sffc thinks that's too much machinery and it's fine as metadata

LGTM: @sffc @robertbastian
