### ISSUE TITLE
Where should fallback fit in with the data pipeline?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3539]
Is fallback a data property or something the client can decide?

What are we doing about singleton keys?

Discuss with:

- @robertbastian 
- @Manishearth 
- @sffc 
- @younies

**Comment by Manishearth** [comment]
Can you expand on both of the questions in the issue?

**Comment by robertbastian** [comment]
> What are we doing about singleton keys?

I think this one is fairly straightforward to solve. We put singletonness into `DataKeyMetadata`, and whereever we do fallback we check that bool and skip fallback.

**Comment by sffc** [comment]
As discussed: we can think of 3 modes here for data generation:

- Expand: entries for every locale are inserted into the data bundle such that fallback is not needed at runtime
- Runtime: entries are removed if they have a parent reachable from fallback, and the generated provider has built-in fallbacking. Not supported yet for blob or fs; datagen should return an error if Runtime and Blob are combined.
- Manual: entries are removed if they have a parent reachable from fallback, but the generated provider does not have built-in fallbacking; a fallback adapter must be manually provided at runtime

The above names are not final; they are illustrative.

For default values on the CLI (for API, it should always be explicit):

| Locale Set | Provider Type | Default |
|---|---|---|
| CLDR Set | Bake | Runtime |
| CLDR Set | FS/Blob | Manual |
| Explicit | * | Expand |

LGTM: @sffc @Manishearth @robertbastian
