### ISSUE TITLE
Definition of Latin 1 in tui.rs doesn't seem right

### ISSUE THREAD

**Issue by roubert** [unicode-org/icu4x#357]
https://github.com/unicode-org/icu4x/blob/icu%400.1.0/components/icu/examples/tui.rs#L51

The range U+0000 to U+007F is ASCII, so it doesn't seem right to build `latin1_set` from that range. If I read the code correctly, it'll erroneously print "latin1 only: false" for any valid Latin 1 codepoint in the U+0080 to U+00FF range.

**Comment by zbraniecki** [comment]
If I'm not mistaken it should be just `basic latin` - https://en.wikipedia.org/wiki/Basic_Latin_(Unicode_block)
