### ISSUE TITLE
Organize properties code to be more like the other crates (get rid of free functions)

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3573]
This is probably a 2.0 change (https://github.com/unicode-org/icu4x/issues/2856)

The properties code uses a lot of free functions for loading property maps and such, rather than using constructors on [`CodePointSetData`](https://unicode-org.github.io/icu4x/docs/icu_properties/sets/struct.CodePointSetData.html) and [`CodePointMapData`](https://unicode-org.github.io/icu4x/docs/icu_properties/maps/struct.CodePointMapData.html) as would be tradition in the other crates.

This makes things a bit awkward. We should consider this design again for 2.0.

Some open questions:

 - How do we deal with the fact that CodePointMapData is generic, and that Rust users will be using `CodePointMapData<GeneralCategory>` (etc) whereas FFI uses an erased version?
 - How do we expose default baked data in this regime?

To-do items:

- icu_properties::exemplar_chars fns should not need "exemplar" in the name
- The mapper functions should be named `load_` instead of `get_`

cc @robertbastian @sffc 

Low-priority discussion since it's likely a 2.0 issue.

**Comment by sffc** [comment]
Discuss with:

- @robertbastian 
- @Manishearth 
- @echeran 

Optional:

- @sffc

**Comment by Manishearth** [comment]
Proposal:

CodePointSetData/etc get `const fn propname()` and `fn propname_unstable()` with an option to add buffer/any as needed in the future.

All of these are added on CodePointSetData *even if they return CPSDataBorrowed*

We can alternatively or additionally add: `const PROPNAME: &CPSDataBorrowed`

**Comment by Manishearth** [comment]
@sffc was a bit lukewarm on the marker types originally because he didn't want to have divergence between FFI and Rust, but we already have significant divergence here because of the free functions


He's happy with the per-property ZST approach, however. We can be more careful in FFI docs to help people comparing FFI and Rust.


@robertbastian noted that the BinaryProperty trait may need to be sealed with some hidden methods.

**Comment by sffc** [comment]
I like the marker type approach; but can we be more explicit about how we specify the marker types? For example, we already have `pub struct CanonicalCombiningClass`. Do we add these for all other properties? Maybe make them wrap booleans? Or should we make these be true marker types, `pub enum EmojiProperty {}`?

**Comment by Manishearth** [comment]
@sffc that was the "open question: do we use marker types or just the value type for enum properties"

Personally I think we should use the value type for the enum properties, the only potential downside is if we want to reuse them; but they're "open enum" newtypes _anyway_ so i don't think there's a huge case for reuse.

**Comment by Manishearth** [comment]
- @sffc - We could have a marker type

```rust
CodePointSetData::<Alnum>::load()
```

which would allow a client to ask for a type `CodePointSetData<Alnum>` specifically.

- @Manishearth - intriguing but not sure if worth it
- @sffc - Could potentially move props into separate crate later, named `icu_properties_types`
- - Current proposal in the issue is `CodePointSetData::new::<Alnum>()`;
- @echeran - 
- @hsivonen - Two questions: will this change the API shape for obtaining the sets in the baked data case? If our API has a Rust generic type name, what does this imply for FFI?
- @sffc - Yes it changes Rust code. Over FFI, we already have the functions on CodePointSetData.
- - What do we do about the baked things? Do they live on CPSDataBorrowed? or CPSData?
- @sffc They should live on Borrowed. Actually CodePointSetData has `new_unstable::<Foo>(provider)` (etc) functions and CodePointSetDataBorrowed has `new::<Foo>()` functions. This facilitates feature-gating.
- @sffc - I like this path because it gives us a clear way forward to split `icu_properties` to smaller crates or at least multiple features.
- @hsivonen - I wasn't seriously suggesting one-crate-per-property for icu4x. A feature per property could be an area to explore.
- @sffc - So we could split by property or by functionality. 4 functionalities:
    - Struct (no data)
    - Static property
    - Yoke property
    - Property names
- @sffc - I think we should start with the split in this direction. We could add property-specific features in the future on a case by case basis.
- @hsivonen - This generally sounds good but I don't know if I understand all the implications


Proposal:

 - icu_properties Module structure
     - `CPSData`,`CPSDataBorrowed`,`CPMData`,`CPMDataBorrowed` all live at the top level
     - props
         - `BinaryProperty` and `EnumeratedProperty` sealed traits (could be hoisted to lib.rs?)
         - enumerated props (NOT hoisted anymore at lib.rs)
         - binary props
     - no `maps` or `sets` module at the toplevel (each only has 2 types!!!)
     - `script` can stay, but gets rid of free functions
     - `bidi`/`bidi_data` can stay, but gets rid of free functions
 - `CodePointSetData::new_unstable::<Alnum>()`, `CodePointSetDataBorrowed::new::<Alnum>()`, etc. `CodePointSetData` stays non-generic
 - `CodePointMapData::<GeneralCategory>::new_unstable()`, `CodePointMapDataBorrowed::<GeneralCategory>::new()`, with methods for erasing.
 - Baked functions live on Borrowed. Non-borrowed has `try_new_unstable` etc. Docs properly advertise this.
 - FFI stays basically the same

LGTM: @sffc @Manishearth @robertbastian @echeran (@hsivonen)

**Comment by Manishearth** [comment]
@robertbastian  may have code for this

otherwise i can work on it

**Comment by Manishearth** [comment]
I think this was done by #5548?
