### ISSUE TITLE
Should icu_segmenter fail on MissingDataKey?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3575]
From https://github.com/unicode-org/icu4x/issues/3545

Discuss with:

- @sffc 
- @robertbastian 
- @younies

**Comment by sffc** [comment]
- @sffc - Should we consider it a bug in the provider if it returns MissingDataKey if it was built with no locales for that key? We just changed the behavior of BlobProvider to do that, but I'm not convinced that it was actually a "bug".
- @robertbastian - I think it's a programmer error; the unstable constructor won't compile if the key is not there. It was a bug in the buffer provider when it was returning MissingDataKey for a key that had no locales. If we want to support creating the segmenter that only supports languages without dictionaries, we should add a constructor for that.
- @zbraniecki - The programmer doesn't know if the language they're segmenting requires LSTM, DIctionary, or rule-based. It should be at most an advanced feature to select which type of segmenter. And there might be cases where we can safely fall back to rule-based.
- @robertbastian - We need to draw a line for what is allowed to be omitted and what must be present. The line we currently draw is that the key needs to be there but not the locale.
- @sffc - I can buy the argument that if the unstable constructor does not compile, why should the buffer constructor work?
- @Manishearth - Do all the providers support this mode (MissingLocale for an empty data key)?
- @robertbastian - Not in fs
- @sffc - We can add info to the manifest
- @Manishearth - Or a dummy file
- @Manishearth - Is it a valid use case if you know what script you're getting but segment it using the regular Unicode algorithms?
- @robertbastian - If all the keys are empty, you just get rule-based. Or we could add a constructor for it. But, I think we should fix this on the datagen side: the user thought about the locales that they needed and chose to build it with empty keys.
- @sffc - I feel like this is a decision that can be made when writing your code. I favor reducing the reliance on datagen options as much as we can.
- @robertbastian - I don't like adding 4 more constructors
- @sffc - We already have too many constructors
- @robertbastian - The code does not know what languages it handles; it's wrong to use rule-based
- @Manishearth - And there are embedded platforms or something where maybe we can't carry segmenter data
- @sffc - We could name it `try_new_without_support_for_complex_scripts`
- @robertbastian - `try_new_for_simple_scripts`
- @Manishearth - It's probably not good to expose the names "simple" and "complex" here
- @robertbastian - If we add this it should have a scary name because I don't want people to use it because it is easier

Consensus:

- It is a bug if a provider is built with a key but then returns MissingDataKey at runtime
- We should make fs support this mode
- We should add a constructor that uses only rule-based segmentation, but we need to bikeshed the name of that constructor

LGTM: @Manishearth @sffc @younies (@zbraniecki)

Bikeshed the name of the constructor:

- `try_new_rule_based`
- `try_new_rule_based_only`
- `try_new_without_complex_scripts`
- `try_new_for_simple_scripts`
- `try_new_for_scripts_that_use_spaces`
- `try_new_rbbi`

Consensus: `try_new_rule_based_only`

LGTM: @Manishearth @sffc @robertbastian @younies

**Comment by Manishearth** [comment]
Issues:
 - https://github.com/unicode-org/icu4x/issues/3610
 - https://github.com/unicode-org/icu4x/issues/3612
 - (preexisting) https://github.com/unicode-org/icu4x/issues/2648 for improving the logging story

Closing as completed since the current behavior is already what we want, modulo  caveats from the above filed issues.
