### ISSUE TITLE
Provider-accepting methods on `TimeZoneFormatter`

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3576]
These seem to be the only non-constructor methods in ICU4X that take provider arguments:

https://docs.rs/icu/latest/icu/datetime/time_zone/struct.TimeZoneFormatter.html

Is there a better way to model this? How can we make this work with globaldata?

**Comment by sffc** [comment]
Discuss with:

- @sffc 
- @robertbastian 

Optional:

- @nordzilla

**Comment by sffc** [comment]
Conclusion: keep the methods and create the 4 versions of each of them.

LGTM: @sffc @robertbastian

**Comment by sffc** [comment]
Modification to my above suggestion: to minimize the diff, just add the new functions either without the `load_` prefix, like you're doing in icu_properties, or with a prefix such as `with_`, as in `TimeZoneFormatter::with_generic_non_location_short()`
