### ISSUE TITLE
Look into replacing flat DateTimeSymbols arrays with VarZeroVecs

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3599]
Part of https://github.com/unicode-org/icu4x/issues/3413

Currently DateTimeSymbols data  has a couple of fixed-length arrays. These are big on the stack; it's worth replacing them with VZVs. We'd need to measure if this is actually a major win.

This can be done backwards compatibly but we may wish to consider doing it in 2.0 (https://github.com/unicode-org/icu4x/issues/2856).

**Comment by sffc** [comment]
Likely to be handled as part of #3865

**Comment by sffc** [comment]
This is done. The neo datetime names now use one of the following three structs.

https://unicode-org.github.io/icu4x/rustdoc/icu_datetime/provider/neo/struct.LinearNamesV1.html

https://unicode-org.github.io/icu4x/rustdoc/icu_datetime/provider/neo/enum.MonthNamesV1.html

https://unicode-org.github.io/icu4x/rustdoc/icu_datetime/provider/neo/enum.YearNamesV1.html
