### ISSUE TITLE
Fallback should restore keywords but not variants after region

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3602]
The fallback should be:

Language:

- en-US-fonipa-u-nu-latn
- en-US-fonipa
- en-US-u-nu-latn
- en-US
- en-u-nu-latn
- en
- und

Region:

- en-US-fonipa-u-nu-latn
- en-US-fonipa
- en-US-u-nu-latn
- en-US
- und-US-u-nu-latn
- und-US
- und

**Comment by sffc** [comment]
- en-US-fonipa-u-nu-latn
- en-US-u-nu-latn
- en-u-nu-latn
- en-US-fonipa
- en-US
- en
- und

Region:

- en-US-fonipa-u-nu-latn
- en-US-u-nu-latn
- und-US-u-nu-latn
- en-US-fonipa
- en-US
- und-US
- und

**Comment by sffc** [comment]
Discuss with:

- @sffc
- @zbraniecki 

Optional:

- @echeran

**Comment by robertbastian** [comment]
In 2.0 fallback will operate on `LanguageIdentifier`, so this can be closed.

**Comment by sffc** [comment]
My understanding is that variant need not be restored during fallback once it is stripped. If we need to restore it, that is an easy forward change.
