### ISSUE TITLE
Bikeshed: Naming of mutative data loading functions

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3604]
From https://github.com/unicode-org/icu4x/pull/3591, we have these functions:

- Since 1.0 or 1.1: `TimeZoneFormatter::load_generic_non_location_long(&mut self, &provider)`
- New, not yet released: `TimeZoneFormatter::with_generic_non_location_long(&mut self)`

There's also `load_localized_gmt_format` which has no `with_` version.

ICU4C/ICU4J has a very clear policy of `with` referring to immutable functions and `set` to mutable functions.

@Manishearth suggested "include" instead of "with" and I think I like this better.

CC @robertbastian

**Comment by robertbastian** [comment]
Previous dicussion: #3576
