### ISSUE TITLE
No provider should fail with MissingDataKey if it was built with a key but that key has no locales

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3610]
Spawned out of https://github.com/unicode-org/icu4x/issues/3575

If a data provider is built with a key but the key has no data, it should not error with MissingDataKey, it should error with MissingLocale.

`BlobDataProvider` fixed this in https://github.com/unicode-org/icu4x/pull/3551. The adapters should just work with this (worth quickly checking if forking by key works correctly)

`FsDataProvider` needs to be fixed. Probably with a manifest change or some dummy file.

**Comment by robertbastian** [comment]
> `FsDataProvider` needs to be fixed. Probably with a manifest change or some dummy file.

It actually works already with directory presence, the exporter just has to be updated to create empty directories.

**Comment by sffc** [comment]
Reopening due to requested changes on #3682
