### ISSUE TITLE
Auto-generate or remove README files

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#363]
The README files shipped in 0.1 are largely based on the content of lib.rs.  We should either:

1. Auto-generate the README files from lib.rs
2. Remove the README files
3. Leave stub README files that link to docs.rs

**Comment by zbraniecki** [comment]
We can't remove them, because that's what is used in crates.io - https://crates.io/crates/icu_locid

But! We can autogenerate them from stc/lib: https://crates.io/crates/cargo-readme

**Comment by dminor** [comment]
@zbraniecki I had to tweak a few things, but I have cargo-readme working and I have manually regenerated the READMEs. Any thoughts on automating this, or is a manual step as part of the relase process ok for now?

**Comment by zbraniecki** [comment]
I'm ok with it being a manual command executed prior to release for now. We can automate separately.

**Comment by sffc** [comment]
It should be easy to add the commands you used to Makefile.toml.  That's what it's there for.
