### ISSUE TITLE
Address follow-up issues for Chinese calendar

### ISSUE THREAD

**Issue by atcupps** [unicode-org/icu4x#3661]
PR #3596 was recently merged, adding the Chinese calendar; however, before it was merged, there were a number of comments left to be addressed in a follow-up PR. Since #3596 has already been merged, I am compiling a list of these comments here for discussion

From @sffc:

- [x] ~Suggests renaming `fn standard_from_universal` to `local_from_utc` in astronomy.rs for more consistency with Temporal ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256292358))~
- [x] In chinese.rs (if #3645 is merged it will be in chinese_based.rs), change `fn chinese_date_from_fixed` to return "max date" or "min date" instead of debug-asserting (see other calendars) ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256304587))
- [x] Test for pre-epoch behavior to ensure round-trips to RataDie and back ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256300492))
- [x]  Make `fn major_solar_term_from_fixed` and `fn minor_solar_term_from_fixed` return an unsigned int type ([original](https://github.com/unicode-org/icu4x/pull/3645/files#r1263102789))

From @echeran:

- [x] Fix link in documentation for `fn minor_solar_term_from_fixed` in chinese.rs (or chinese_based.rs) ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256504830))
- [x] Rename `Moment` type parameters to `moment` for consistency ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256509481))
- [x] Define `WINTER` as a constant in `astronomy` instead of referencing 270.0 as a magic number ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256514150))
- [x] Extract `max_iters` from `fn chinese_winter_solstice_on_or_before` as a constant ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256514846))
- [x] Add a unit test for `fn adjusted_rem_euclid` in helpers.rs: use relatively prime numbers, exercise combinations of sign (+/-), and try a case where `y` divides `x` such that `remainder == 0` ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256362040))
- [x] Correct documentation of `fn interval_mod_f64` in helpers.rs to be `[a..b)` rather than `(a..b)` ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256365963))
- [x] Add more test cases for `interval_mod`: a number `x` already contained within [a..b), a number `x == b` (therefore is actually not in `[a..b)`, and a number `x` greater than `b` ([original](https://github.com/unicode-org/icu4x/pull/3596/files/2b64d524548b127f1c59d6833426a0ac63f5e299#r1256365963))

**Comment by atcupps** [comment]
@sffc I am not sure how to approach renaming `standard_from_universal` to `local_from_utc`. It makes sense, but there is already a function called `local_from_universal` in astronomy.rs, because it's based on _Calendrical Calculations_ which defines "local" as being based on longitude and "standard" as being based on standard time zones (so Boise and Las Vegas for instance have very similar "local" time because of similar longitudes, but a one hour difference in "standard"). If `standard_from_universal` becomes `local_from_utc`, then the already-existing `local_from_universal` should be renamed to something else.

**Comment by atcupps** [comment]
@echeran I don't think extracting `max_iters` as a constant makes sense, since I have multiple places where I use a `max_iters` variable (every time I use a `while` loop) and the value is different each time, since I am using it as a bound for the maximum number of iterations a particular loop can have before it exceeds a reasonable amount and is clearly an error.

**Comment by atcupps** [comment]
@echeran suggests extracting all such `max_iters` constants for reuse in other similar situations.

**Comment by sffc** [comment]
Fine to skip the renaming of `standard_from_universal` for consistency with Reingold; the docs are already clear.

**Comment by sffc** [comment]
@atcupps is this done?

**Comment by atcupps** [comment]
Yeah, it was finished in #3645 @sffc
