### ISSUE TITLE
Unsound `Debug` implementation of `Yoke`

### ISSUE THREAD

**Issue by steffahn** [unicode-org/icu4x#3685]
```rs
use std::sync::Mutex;

use yoke::Yoke;

struct S(String);

static X: Mutex<Option<&'static S>> = Mutex::new(None);
impl std::fmt::Debug for &'static S {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        *X.lock().unwrap() = Some(self);
        Ok(())
    }
}
impl std::fmt::Debug for Box<S> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        Ok(())
    }
}

fn main() {
    let x = Yoke::<&'static S, _>::attach_to_cart(Box::new(S("Hello World!".into())), |s| s);
    format!("{x:?}");
    let r: &'static str = &X.lock().unwrap().as_ref().unwrap().0;
    println!("now it exists: {r}");
    drop(x);
    println!("and now it’s gone: {r}");
}
```
```
now it exists: Hello World!
and now it’s gone: �NQc�X�i
```

The `Debug` implementation exposes the `Y` type to user code. In the example above, the type `Y` is `&'static S`. This means the reference with ***fake*** `'static` lifetime is passed to a `Debug for &'static S` implementation.

A sound `Debug` implementation should instead best use only the safe existing API of `Yoke` (instead of being derived), and should require something like a `for<'a> <Y as Yokeable<'a>>::Output: Debug` bound instead of `Y: Debug`.

**Comment by Manishearth** [comment]
heh, I thought I'd reviewed this for all accesses to the field but I def missed the derive
