### ISSUE TITLE
`FixedDecimalFormatterOptions` does not implement the `Copy` trait

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/icu4x#3713]
```
error[E0382]: borrow of moved value: `options`
   --> src/numberfmt.rs:185:56
    |
105 |     let mut options: options::FixedDecimalFormatterOptions = Default::default();
    |         ----------- move occurs because `options` has type `FixedDecimalFormatterOptions`, which does not implement the `Copy` trait
...
158 |         let fdf = FixedDecimalFormatter::try_new_unstable(&provider, &data_locale, options)
    |                                                                                    ------- value moved here
...
185 |         "actual_options": format!("{option_struct:?}, {options:?}"),
    |                                                        ^^^^^^^ value borrowed here after move
    |
    = note: this error originates in the macro `$crate::__export::format_args` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by sffc** [comment]
Thanks Craig for filing this issue!

Shall we have a policy of making our options bags `Copy`?

**Comment by robertbastian** [comment]
I thought we already had one, because we have one to accept them by value.

**Comment by sffc** [comment]
Discuss with:

- @Manishearth 
- @sffc 
- @younies

**Comment by Manishearth** [comment]
@sven-oly your problem can be solved by using `options.clone()` when passing it to `try_new_unstable`.

-----

I think we should follow a policy of "if we do not expect its fields to be Copy, it should be Copy and taken in by value, otherwise it should be taken in by-reference, or contain a lifetime"


Of course "do not expect its fields to be Copy" is hard to determine

**Comment by sffc** [comment]
I think the default behavior for these option bags structs should be to contain only Copy types and borrow anything that isn't Copy. There might be isolated exceptions to that rule, but if there's any doubt, we should use Copy. We can always add another non-Copy options struct with its own constructor if we find that we really need to change it in the future.

**Comment by Manishearth** [comment]
I agree with @sffc's comment.

@younies, what do you think?
