### ISSUE TITLE
Return type of days_in_provided_year

### ISSUE THREAD

**Issue by sotam1069** [unicode-org/icu4x#3716]
While implementing the boilerplate code for the `CalendarArithmetic` trait I noticed that the function `days_in_provided_year` returns u32. In the current calendars implemented, years have at most 300+ days, wouldn't it be a better choice to return a `u16` if we know the value will never exceed `u16::MAX`?  

Or Is there a good reason that `u32` was chosen?

**Comment by sotam1069** [comment]
@sffc @Manishearth

**Comment by sffc** [comment]
I'm fine making it return `u16`

**Comment by Manishearth** [comment]
Yes, we can return `u16`.

**Comment by Manishearth** [comment]
I think it was mostly chosen to avoid having to convert all the time. But it should be fine.
