### ISSUE TITLE
Stabilize LocaleDirectionality

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3722]
- [x] The crate should fully conform with the [ICU4X Style Guide](style_guide.md):
  - [x] The crate should have a complete library header as shown in [boilerplate.md](boilerplate.md) with Clippy passing
  - [x] The names of exported types should conform to the recommendations in the Style Guide
  - [x] All Error types should be `Copy`
  - [x] All constructors should take options structs by value
  - [x] All constructors should take arguments in the following order: Provider, Locale, Options
  - [x] All constructors should have the standard set of overloads for provider types
  - [x] Runtime dependencies should be minimal and able to be disabled with Cargo features if possible
  - [x] Any `TODO`, `FIXME`, `todo!`, `unimplemented!`, or other placeholders should either be resolved or link to an issue number. (It is okay to ship a small amount of code with tech debt comments, but anything having to do with code correctness should be resolved)
- [x] The crate should have a conventional Cargo.toml file:
  - [x] Cargo.toml should use license, not license-file
  - [x] The description should be useful
  - [x] Correct repo link, authors, categories, include
  - [x] Correct docs.rs and cargo-all-features metadata settings
  - [x] A `rust-version` field with the MSRV of this crate in accordance with the current ICU4X policies on MSRV.
  - [x] The crate should have an `std` feature if (and only if) it contains code that depends on `std`, such as file I/O or implementing the Error trait
  - [x] Audit all features so that any `foo/bar` in a feature is `foo?/bar` when `foo` is an optional dep; if you intend to enable `foo`, add two entries
  - [x] Use `dep:` for enabling dependencies
- [x] The crate should be fully documented
  - [x] Every exported function should have docs coverage
  - [x] There should be a crate-level example that illustrates a common use case for the component with the heading `# Examples`
  - [x] All options and conditional code paths should have a corresponding docs test with the heading `# Examples`
  - [x] All functions that are conditional on a Cargo feature should say so (last line before `# Examples`): ```✨ *Enabled with the `alloc` Cargo feature.*```
  - [x] Compiled data constructors should say "with compiled data" in the first sentence and should have a Cargo feature alert following the above syntax.
- [x] The data structs should fully follow ZeroVec style
  - [x] Deserialization should not have a "net violation" in the [verify-zero-copy](https://github.com/unicode-org/icu4x/blob/main/provider/datagen/tests/verify-zero-copy.rs) test
  - [x] Constructors should avoid allocating memory in the common case
  - [x] Opaque blobs of data should be avoided if possible (instead use VarZeroVec, ZeroMap, etc.)
  - [x] Data structs should not be panicky to load/deserialize and conform to [data_safety.md](https://github.com/unicode-org/icu4x/blob/main/docs/design/data_safety.md)
- [ ] The component should be fully integrated with ICU4X tooling
  - [ ] ~There should be an overview Criterion benchmark~
  - [ ] ~There should be individual Criterion benchmarks for interesting or performance critical code paths~
  - [ ] ~There should be at least one example plumbed with the icu_benchmark_macros~
  - [x] The component should be fully covered by FFI with no unjustified suppressions nor entries in missing_apis.txt
- [x] The component should encourage i18n best practices
  - [x] The component should produce correct results in all locales as generated by icu4x-datagen
  - [x] Where applicable, the component should be consistent with ECMA-402 and UTS #35
  - [x] Any gaps in i18n quality should be fixed, or, if that is not possible, they should have tracking issues and a concrete, resourced path forward. The intent is to not ship components with known i18n correctness problems and no plan to fix them in an upcoming release
  - [x] The API design should receive sign-off from a non-ICU4X i18n expert such as Markus Scherer

**Comment by robertbastian** [comment]
Not adding benchmarks as I don't think the ZV lookup is particularly interesting or performance critical.

@zbraniecki
