### ISSUE TITLE
In the DataCategory enum, pluralization is inconsistent

### ISSUE THREAD

**Issue by poulsbo** [unicode-org/icu4x#373]
In the `DataCategory` enum, we currently have values `Decimal`, `Plurals`, and `Dates`. It's not clear why one is singular and two are plural.

It would be more consistent to have these all be singular: `Decimal`, `Plural`, `Date` (or all be plural).

https://github.com/unicode-org/icu4x/blame/master/components/provider/src/data_key.rs#L16

**Comment by sffc** [comment]
Discussion 2020-12-04:

- We think singular is better than plural
- But we have a plural in the crate name for `icu_plurals`
- So we will use names for data categories consistent with the crate names.  Plurals is Plurals, Dates becomes DateTime.

**Comment by sffc** [comment]
I consider this blocked on #257.  We are planning some major refactoring to the date keys, and I want to perform those changes before renaming the category.
