### ISSUE TITLE
Pin Rust version for stable benchmarks

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#374]
Now that we are running more benchmarks on CI, we should set the Rust version to a fixed value, and update it periodically.  The Rust version could have significant impact on both performance and code size benchmarks.  Fixing the Rust version would also help solve #315.

Related: #175

CC @echeran @Manishearth

**Comment by Manishearth** [comment]
We should do this.

**Comment by sffc** [comment]
See https://github.com/servo/servo/blob/master/rust-toolchain

**Comment by Manishearth** [comment]
For stable versions the file should contain a rust version number, e.g. `1.40.0`

**Comment by gregtatum** [comment]
The memory benchmarks will need this as well. Whatever the fix is, it should be able to be applied there as well.

**Comment by gregtatum** [comment]
I have a small test patch I have up for nightly versions.
