### ISSUE TITLE
Make tutorials tests not directly use (Any)DateTimeFormatter

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3757]
The bounds of (Any)DateTimeFormatter are subject to change and churn, which is a challenge given legacy_testdata. People adding formatting for new calendar systems need to update legacy_testdata.

We could either eat this cost until 1.3 (probably 5-6 times), or change the tutorials to not use that constructor. I think there are not that many.

@Manishearth @robertbastian thoughts?

**Comment by Manishearth** [comment]
Yeah, I would change the tutorials for now

**Comment by sffc** [comment]
I'm fine changing the tutorials back to (Any)DateTimeFormatter in 1.3 when we can use compiled_data
