### ISSUE TITLE
Linebreak after number followed by comma in segmenter

### ISSUE THREAD

**Issue by laurmaedje** [unicode-org/icu4x#3811]
I'm using icu4x for linebreaking paragraphs in Typst. We've now hit the [issue](https://github.com/typst/typst/issues/1794) that there are sometimes leading spaces in a line.  Typst strips whitespace from the end of a line, but keeps all whitespace at the beginning of a line. Hence, if it takes the breakpoint directly after the comma, there is a leading space.

Given the text `1, b`, icu4x's segmenter reports a linebreak opportunity directly after the comma _and_ one after the space. This only happens if a number precedes the comma, not for letters. Is there a good reason for this behaviour? I also tried [xi-unicode](https://docs.rs/xi-unicode/latest/xi_unicode/) and [foliojs/linebreak](https://github.com/foliojs/linebreak) and both do not report this linebreak.

Here is a demonstration.

```rust
fn main() {
    linebreaks("a, b");
    linebreaks("1, b");
}

fn linebreaks(text: &str) {
    println!("Linebreak opportunities of {text:?} are:");
    let provider = icu_testdata::unstable();
    let segmenter = icu_segmenter::LineSegmenter::try_new_auto_unstable(&provider).unwrap();
    for offset in segmenter.segment_str(text) {
        println!("  {:?}", &text[..offset]);
    }
}
```

This gives the following output:
```
Linebreak opportunities of "a, b" are:
  ""
  "a, "
  "a, b"
Linebreak opportunities of "1, b" are:
  ""
  "1,"
  "1, "
  "1, b"
```

**Comment by aethanyc** [comment]
cc @makotokato Any ideas?

**Comment by makotokato** [comment]
This seems to be that we should add more rule for NU x IS (LB24) then SP (LB7).
