### ISSUE TITLE
Fix FormattableMonth for leap months and FormattableYear for shared eras

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3821]
Currently FormattableMonth is

```rust
pub struct FormattableMonth {
    pub ordinal: u32,
    pub code: MonthCode,
}
```

This is problematic because

1. There is not a clear use case for having both `ordinal` and `code`. We can derive the month number from `code`.
2. `code` in this context is an identifier used for data lookup, but this is not the same as month identity. `M06` and `M06L` for example (Adar and Adar II) are the same month identity but have different display names.

I suggested that we could make `FormattableMonth` be opaque and add getters for the things we need.

---

`FormattableYear`, meanwhile, contains an era code. When we merge islamic down to a single key, we need to consider how this interoperates.

**Comment by sffc** [comment]
Related: https://github.com/unicode-org/icu4x/issues/3869

**Comment by sffc** [comment]
We really should also add extended year since it is required by Temporal and since there is a UTS 35 placeholder for it

**Comment by sffc** [comment]
Discuss with:

- @sffc 
- @Manishearth 
- (@echeran)

**Comment by Manishearth** [comment]
We should redesign these methods to be Month/Year _by default_ with the formattable ones being separate methods

**Comment by Manishearth** [comment]
We're talking about ICU4X here, not Temporal.

**Comment by Manishearth** [comment]
Let's keep discussion on the other issue.

**Comment by Manishearth** [comment]
Conclusion: We plan to split this into Month/FormattableMonth and Year/FormattableYear, with Month/Year returning values roughly matching Temporal's needs, and FormattableMonth/FormattableYear returning values matching `icu_datetime`'s needs

**Comment by Manishearth** [comment]
I think what needs to be done pre-1.5 is designing these types and potentially adding _private_ APIs for them (or suitably named public APIs).

In 2.0 we then move the names around.

**Comment by Manishearth** [comment]
Things needed by Temporal to describe the year/month:

 - Year: era, eraYear, (extended) year. There is no cyclic year or related_iso.
 - Month: (ordinal) month, month code

We could add each of these as separate getters if we liked, or have a single trait method that produces all year and all month info.


Things needed by datetime format:

 - Year: era, eraYear OR cyclic year + related_iso
 - Month: month code, month _number and leapiness_ (derivable from code). It's unclear to me if ordinal month is ever needed (@sffc @zbraniecki ?)

**Comment by sffc** [comment]
I think it's fine to use month number (as opposed to ordinal month) when we need a numeric month while formatting. CLDR has never been very clear/precise about this. They avoid the problem in Hebrew by not having any patterns with numeric month. We need ordinal month in Temporal because it exhibits certain desirable properties like being monotonically increasing.

**Comment by sffc** [comment]
Also note my comment from last summer:

> We really should also add extended year since it is required by Temporal and since there is a UTS 35 placeholder for it

**Comment by Manishearth** [comment]
Ah okay!

**Comment by sffc** [comment]
As part of your design, remember to consider how to split "month/era codes for data lookup" from "month/era codes for user-facing Temporal". For example, `M06L` should be used for formatting but not for Temporal.

**Comment by sffc** [comment]
Is fixing era codes in scope of this issue, too? I don't think we are handling them correctly. For every era, there is a globally unique era code and calendar-scoped aliases.

https://github.com/unicode-org/cldr/pull/2665

**Comment by Manishearth** [comment]
I think we already fixed those? But I'd say that's separate.

I'd also think changing to Linear is separate.

**Comment by Manishearth** [comment]
I'm going to wait for 1.5 for this, it's not worth creating temporary neo types.

**Comment by Manishearth** [comment]
working on this

**Comment by Manishearth** [comment]
question: do we want years with cycles to have eras?
@sffc: nah, it's fine to say they don't.

Proposal: 

 - EraYear gets two era fields: formatting_era and temporal_era
 - followup: we potentially change formatting_era to be a smaller type (TinyStr4). may involve truncation in datagen.
 - We get rid of `formattable_year()`
 - `FormattableYear` becomes the new YearInfo.
 - EraYear and Cyclic get EraYearInfo and CyclicYearInfo sub-structs instead. we tweak the ctors to take in structs.
 - potentially fix the temporal era code in  #5509.

We consider this issue to include the fixing of the formatting era type and switching over to the temporal era code, but #5509 doesn't need to do that to land

signed off: @Manishearth @sffc

**Comment by Manishearth** [comment]
@sffc I think given that we ended up with a single `YearInfo` type, perhaps we should go with a single MonthInfo type as well? Fields would be `standard_code` and `formatting_code`. `ordinal` is removed.

**Comment by sffc** [comment]
Well I still think we need `ordinal`, right? It is the arithmetic month in Temporal. But yes, single struct with two month code fields LGTM.

**Comment by Manishearth** [comment]
Ah. Should we call it `arithmetic_month`? Though `ordinal` seems fine to me.

I'm going to rename it to MonthInfo since it's no longer about FormattableMonth.

**Comment by sffc** [comment]
How about `extended_month` to parallel `extended_year`?

**Comment by sffc** [comment]
If you show people a struct with 3 fields:

- `extended_month`
- `standard_month`
- `formatting_month`

people are like, WTF, which one do I use? But I guess docs can clear that up.

**Comment by Manishearth** [comment]
I'd say `ordinal`, `standard_code`, `formatting_code` and write good docs.

**Comment by sffc** [comment]
The one people should generally be using though is `standard_code`, but it is really tempting to reach for `ordinal`. So I feel like we should prefix all three.

**Comment by Manishearth** [comment]
Cool. https://github.com/unicode-org/icu4x/pull/5536 has `ordinal`, `standard_code`, and `formatting_code`. The codes differ only for Hebrew.

We could expose MonthCode methods on MonthInfo if people want convenience, thoughts? `.month_number()` and `.is_leap()` seems useful.
