### ISSUE TITLE
Revisit requirements for non_exhaustive

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#383]
Let's discuss again the style guide for non_exhaustive.

@zbraniecki said:

> Hmm, I think I'm confused about your approach to non_exhaustive. You seem to say that you are certain that all public errors should have it. Why? If we modify that enum we'll have a breaking release, and I don't think it's any different from changing other public APIs.
>
> If we add it on public errors then we lose the chance to let user know that their error handling should be updated to handle new set of errors that may be returned by the public APIs.

@sffc said:

> The whole point of non_exhaustive is to avoid breaking changes when adding fields to structs and enums. The way I see it is, after we release version 1.0.0, the bar for us to release 2.0.0 should be extremely high. Certainly no more than once a year, but hopefully even less frequently than that, like once every 3 years. I am strongly of the opinion that breaking changes are very costly to the ecosystem and we should go out of our way to avoid them.
>
> However, your point about informing users of new error types is interesting.

**Comment by sffc** [comment]
2020-11-12: Error enums should be non_exhaustive. Follow up on a case-by-case basis after #170 is in.

**Comment by Manishearth** [comment]
While working on #170  I realized that the best default to have is probably that _structs_ are exhaustive by default (since if they have fully pub fields, they probably should be constructible), but enums probably should be non-exhaustive by default

**Comment by Manishearth** [comment]
So, real-world results: I started applying the two lints in https://github.com/unicode-org/icu4x/pull/1789, and there are a couple categories of things I can see:

 - Error enums. Always should be `#[non_exhaustive]`
 - Provider enums. Can be `#[non_exhaustive]`
 - Provider _structs_. Should be `#[allow(clippy::exhaustive_structs)]`
 - Options enums: _can_ be `#[non_exhaustive]`. Should they?
 - Options structs: If they are `#[non_exhaustive]`, they cannot be constructed as easily. How do we feel about this?
 - Misc structs/enums from the crate: depends on the situation

I've tagged @sffc @gregtatum @nordzilla @zbraniecki for review in that PR, and would appreciate feedback on what does and doesn't make sense here, so we can come up with a more concrete set of guidelines.

**Comment by sffc** [comment]
> * Error enums. Always should be `#[non_exhaustive]`

Yes.

> * Provider enums. Can be `#[non_exhaustive]`

What is an example of this one?

> * Provider _structs_. Should be `#[allow(clippy::exhaustive_structs)]`

They should be exhaustive because of Postcard.

> * Options enums: _can_ be `#[non_exhaustive]`. Should they?

These should definitely be non-exhaustive. Having the ability to add new options in dot releases is one of the original motivating factors for opening this issue.

> * Options structs: If they are `#[non_exhaustive]`, they cannot be constructed as easily. How do we feel about this?

These should definitely be non-exhaustive. Having the ability to add new options in dot releases is one of the original motivating factors for opening this issue. The structs should implement `Default` which can be used to construct them.

The call site is not that bad:

```rust
let options = FooOptions::default();
options.bar = "baz";
Foo::try_new(options);
```

There is quite a bit of discussion about the ergonomics issues (e.g. https://github.com/rust-lang/rust/issues/70564). I would like to do the right thing from an API standpoint, and let the RFC process play out to improve the ergonomics later. We should eventually be able to write:

```rust
Foo::try_new(FooOptions {
    bar: "baz",
    ..Default::default()
});
```

But that's the same number of lines of code as what you can do now. So I think it's a perfectly acceptable middle state.

> * Misc structs/enums from the crate: depends on the situation

One special category I suggested you add is that newtypes should be exhaustive.

**Comment by Manishearth** [comment]
I think we've settled on requirements here

**Comment by sffc** [comment]
Can we document the requirements in style_guide.md?
