### ISSUE TITLE
Unblock Datagen 1.3 by releasing Elsa or reverting to an older version of Elsa

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3831]
Datagen depends on a git hash of Elsa because the test `test_fallback_options` uses an unreleased API. We have a few choices:

1. Release Elsa and update ICU4X's Cargo.toml to remove the git hash
    - Pro: We can use the new Elsa APIs
    - Con: The next Elsa release is not completely trivial because it seems it was discovered that some other newly added APIs are unsound (not the one we're using): https://github.com/Manishearth/elsa/issues/48
2. Change ICU4X to not use the new Elsa APIs (use a `RwLock<HashMap>` instead)
    - Pro: No external dependency
    - Con: Less pretty code
3. Depend on the git hash in dev-dependencies only
    - Pro: Unblocks the release with no code changes
    - Con: Multiple versions of Elsa in tree

@Manishearth @robertbastian

**Comment by Manishearth** [comment]
I'm planning on releasing I just have a backlog of things to do on elsa

**Comment by Manishearth** [comment]
> newly added APIs are unsound 

No, it's existing APIs, but it changes the model of the type and raises questions of how to best support other APIs, including the one we're using (though the one we're using can be made to work regardless, it's just potentially more work)

**Comment by Manishearth** [comment]
Elsa 1.9.0 published
