### ISSUE TITLE
Support favor-script variant of likely subtags algorithm

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3859]
UTS 35 has the following aside:

> A variant of this favors the script over the region, thus using {language, language_script, language_region} in the above. If that variant is used, then the result in this example would be zh_Hant instead of zh_TW.

https://www.unicode.org/reports/tr35/tr35.html#Likely_Subtags

@dminor, the author of the code, said:

> I remember reading that aside, and I'm almost certain I didn't implement it. Would we add it as an option in the API?

The option is used in the new CLDR data-driven tests. It also came up recently in ICU4X locale fallbacking when we encountered the surprising behavior of yue-Hans "minimizing" to yue-CN.

**Comment by sffc** [comment]
Suggestion: `LocaleExpander::minimize_with_options`

**Comment by zbraniecki** [comment]
Suggestion:

```rust
let bag = LocaleExpanderOptionsBag {
  prioritize: LocaleExpanderSubtagPriority::REGION
};
let lc = LocaleExpander::new(bag);
```

**Comment by sffc** [comment]
I prefer that the bag goes into the terminal function and not the constructor because:

1. This is an algorithmic change, not a data loading change; a developer could reasonably want to create a single LocaleExpander that supports both minimize modes, just like a LocaleExpander supports minimize and maximize in the same object.
2. Adding an options bag is a breaking change to the constructor.

**Comment by zbraniecki** [comment]
convinced

**Comment by sffc** [comment]
I believe this does not require a data change, so it should be a good first issue all in code.
