### ISSUE TITLE
Should we add new experimental crates to testdata?

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#3917]
We decided to keep testdata alive for the 1.x track. New data in existing crates is being added, such as the new calendar systems, but we haven't added any of the new experimental crates.

**Comment by sffc** [comment]
Conclusion: No.

LGTM: @sffc @Manishearth @robertbastian @zbraniecki @younies

**Comment by sffc** [comment]
Rob: should we add new keys for old crates?

- @sffc - I think probably yes, because e.g. DateTimeFormater should continue to work.

Conclusion: Yes.

LGTM: (@Manishearth) @sffc @robertbastian
