### ISSUE TITLE
Loading cache data for lunar calendars

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3933]
@Manishearth - This is 1.3 blocking because the API of a calendar that has no data versus one that does is different. We could theoretically remove constructors from these types for 1.3 and only do things through AnyCalendar. But then these APIs are functionally useless outside of AnyCalendar.

Parts:
 - Common:
   - [x] https://github.com/unicode-org/icu4x/pull/4051
   - [x] Prepare calendars for caching on ArithmeticDate https://github.com/unicode-org/icu4x/pull/4407
 - [x] Chinese / Dangi
   - [x] Add caching on ArithmeticDate https://github.com/unicode-org/icu4x/pull/4411 
   - [x] Optimize data https://github.com/unicode-org/icu4x/pull/4465
   - [x] Add precomputed data loading https://github.com/unicode-org/icu4x/pull/4468
 - [x] Hebrew
   - [x] Add optimized Four Gates-based code https://github.com/unicode-org/icu4x/pull/4500
   - [x] Cache Keviyah on ArithmeticDate https://github.com/unicode-org/icu4x/pull/4504
   - [x] Consider adding a `new()` and deprecating `new_calculating()` (and the `try_new...with_calendar()`, if we are definitely not precomputing (otherwise add precomputing) https://github.com/unicode-org/icu4x/pull/4532
 - [x]  Islamic
    - [x] Write optimized YearInfo code per-calendar (at least UAQ and observational), with a shared YearInfo type
    - [x] Use in cache on ArithmeticDate
    - [x] Add precomputed data

**Comment by Manishearth** [comment]
There's a PR open for Chinese (https://github.com/unicode-org/icu4x/pulls), but islamic/hebrew also need similar work done.

**Comment by sffc** [comment]
Discussion for the name of the constructor that does not load data:

- `Chinese::new_without_data()`
- `Chinese::new_calculating()`
- `Chinese::new_without_calculated_data()`
- `Chinese::new_runtime_calculating()`
- `Chinese::new_always_calculating()`

- @robertbastian - I prefer short
- @Manishearth - I don't prefer short

Conclusion: `new_always_calculating()` for the no-data constructor. `new()` is the constructor with compiled data.

Next steps:

- The following calendars need work: Chinese, Dangi, all Islamic, _maybe_ Hebrew
- Make the following changes:
    - Change these calendars to have `new_always_calculating()` constructor
    - Make sure they are not `Copy`

It would be nice to have Chinese ready with the pre-calculated caches in 1.3 but does not need to block.

LGTM: @Manishearth @sffc @robertbastian

**Comment by Manishearth** [comment]
#4051 solves this for the milestone, kicking the can to 1.4

**Comment by Manishearth** [comment]
The plan is:

 - CalendarArithmetic takes in a `&PrecompiledData` type parameter on all of its methods. Most calendars use `()`
 - ArithmeticDate contains a `YearInfo` field which also defaults to `()`. Date mutations must update it.
 - The PrecompiledData is stored on the Calendar object, whereas the YearInfo, as a field of the ArithmeticDate, is stored on the Date. The calendar passes in PrecompiledData where necessary
    - Note: this is different from the current code; which stores both caches on the Date! This design is incorrect and duplicates the data.
  - Methods which can rely on YearInfo will do so. Methods which cannot must hit the precompiled data store to obtain year info.

One thing I'm not sure about is if YearInfo should ever differ from what is stored in precompiled data. Currently the YearInfo equivalent in tree for chinese is:

```rust
pub(crate) struct ChineseBasedCache {
    pub(crate) new_year: RataDie,
    pub(crate) next_new_year: RataDie,
    pub(crate) leap_month: Option<NonZeroU8>,
}
```

whereas the precompiled cache is:

```rust
pub(crate) struct ChineseBasedCompiledData {
    pub(crate) new_year: RataDie,
    /// last_day_of_month[12] = last_day_of_month[11] in non-leap years
    /// These days are 1-indexed: so the last day of month for a 30-day 一月 is 30
    /// The array itself is zero-indexed, be careful passing it self.0.month!
    last_day_of_month: [u16; 13],
    ///
    pub(crate) leap_month: Option<NonZeroU8>,
}
```

(This packs down to three bytes in `PackedChineseBasedCompiledData`)

If we are going to store such data live, we might as well store `PackedChineseBasedCompiledData` everywhere, which simplifies the architecture down to "load `PackedChineseBasedCompiledData` into `YearInfo`, if you can't load from precompiled data then compute on your own". In the long run this may mean we don't need to pass in `PrecompiledData` everywhere, though in the short run I'd like to grant us that freedom.

However, if we make that call now, we can avoid having to pass in the compiled data for everything other than the `until()` and `offset_days()` which is nice.

**Comment by Manishearth** [comment]
ugh, found some gnarly stuff that will not be easy to optimize


https://github.com/unicode-org/icu4x/blob/c755786f6482daf0fb277ffdad001a53950082b3/components/calendar/src/chinese.rs#L311

This needs the number of days in the _previous_ year. We might just also cache that but it's suboptimal, it's only needed for the rather rare case of week-of-year formatting, but it needs to be computed mandatorily when formatting

**Comment by Manishearth** [comment]
@sffc We need to make a decision based on the [benchmarking results](https://github.com/unicode-org/icu4x/pull/4504#issuecomment-1874721841):


>  Consider adding a new() and deprecating new_calculating() (and the try_new...with_calendar(), if we are definitely not precomputing (otherwise add precomputing)


For background, currently `Hebrew` must be constructed with [`new_always_calculating()`](https://unicode-org.github.io/icu4x/rustdoc/icu/calendar/hebrew/struct.Hebrew.html#method.new_always_calculating)

Proposal: We commit to never precomputing, add `::new()`, make `Hebrew` constructable as a singleton struct, and deprecate the old APIs. For Hebrew only. 

Approval:

 - [ ] @sffc
 - [x] @Manishearth 
 - [ ] (optional) @zbraniecki 
 - [ ] (optional) @hsivonen

**Comment by Manishearth** [comment]
All dates (in range, which is a range of ~i32 I think: check the code)

Prior versions of the Hebrew calendar used slightly different four gates tables, Adjler documents them all, but the book does not handle that either, it implements the modern set of calculations.

**Comment by Manishearth** [comment]
I've started working on the islamic ones. My current data model is to store month length booleans and then use the remaining 4 bits to store a new years offset from the mean synodic new year (`year * 12 * MEAN_SYNODIC_MONTH`). It's unlikely that that number will be super large.
