### ISSUE TITLE
Exposed API for Temporal operation CalendarDateInLeapYear

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#3963]
For Temporal compat, ICU4X should implement https://tc39.es/proposal-temporal/#sec-temporal-calendardateinleapyear on its calendars.

**Comment by sffc** [comment]
We should already have this, but we need to test it and document it and add it if missing.

**Comment by nekevss** [comment]
`CalendarArithmetic` has an `is_leap_year` method but the trait and its methods are private.

**Comment by CanadaHonk** [comment]
Looking into working on this. Do we want to just expose `calendar_arithmetic` as above?

**Comment by Manishearth** [comment]
No, we should expose a `year_is_leap` on the [`Calendar`](https://unicode-org.github.io/icu4x/docs/icu/calendar/trait.Calendar.html) trait that takes in a DateInner; and then expose `.year_is_leap()` or something on `Date`. `calendar_arithmetic` must stay internal.


You can call the method on `calendar_arithmetic` for implementation.

**Comment by sffc** [comment]
In Temporal, the function is called `inLeapYear` on both PlainDate and Calendar:

https://tc39.es/proposal-temporal/#sec-get-temporal.plaindate.prototype.inleapyear

I think the functions should be named:

- `is_leap_year` for (internal) functions that take a year integer
- `is_in_leap_year` for functions that take a Date or DateInner

LGTM: @robertbastian @sffc @Manishearth
