### ISSUE TITLE
Provide list of available named time zones

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#3970]
Temporal requires the operation [AvailableNamedTimeZoneIdentifiers](https://tc39.es/ecma262/#sec-availablenamedtimezoneidentifiers), which enumerates the non-primary and primary (IANA) named time zones and also gives the primary name for each one.

For Temporal compat, ICU4X should provide this list.

**Comment by hsivonen** [comment]
Unclear how well this is covered by #2909.

**Comment by sffc** [comment]
@sffc to reply here with a design and then mark as good first issue.
