### ISSUE TITLE
Unify `true` handling in Unicode and T extensions

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#403]
Spinning it off of #402 for larger discussion before we dive into PRs again.

@FrankYFTang said:
> And the context is within the "U extension key values" and the value of "type".
> But what we are talking about is NOT inside "U extension" but rather in "T extension" and the argument is about the absent of "tvalue" could be implied as a "true" but not the absent of "type" can be implied as "true" or not. These are TWO different context- the "type" inside U Extension vs the "tvalue" inside T Extension.

Ok, so can we separate Unicode from T extensions from the perspective of treating `true` in parsing/serialization?

<table>
	<thead>
		<tr>
			<th></th>
			<th></th>
			<th colspan="2">Unicode</th>
			<th colspan="2">Transform</th>
		</tr>
		<tr>
			<th>Example</th>
			<th></th>
                        <th><code>und-u-kn</code></th>
                        <th><code>und-u-kn-true</code></th>
                        <th><code>und-t-m0</code></th>
                        <th><code>und-t-m0-true</code></th>
		</tr>
		<tr>
			<th rowspan="2">Expected</th>
			<th>Parse</th>
			<th>✓</th>
			<th>✓</th>
			<th>✗</th>
			<th>✓</th>
		</tr>
		<tr>
			<th>Serialize</th>
			<th><code>und-u-kn</code></th>
			<th><code>und-u-kn</code></th>
			<th></th>
			<th><code>und-t-m0-true</code></th>
		</tr>
		<tr>
                        <th rowspan="2">ICU4X</th>
			<th>Parse</th>
			<th>✓</th>
			<th>✓</th>
			<th>✗</th>
			<th>✓</th>
		</tr>
		<tr>
			<th>Serialize</th>
			<th><code>und-u-kn-</code></th>
			<th><code>und-u-kn-</code></th>
			<th></th>
			<th><code>und-t-m0-</code></th>
		</tr>
	</thead>
</table>

If this is true, then I suggest the following fixes to ICU4X:

* Fix serialization of unicode extension with implicit `true` (`und-u-kn`, `und-u-kn-true`, `und-u-kn-nu-thai`, `und-u-ca-calendar-kn`)
* Fix serialization of transform extension keyword to explicitly serialize `true` (we can still store it as `None` internally) (`und-t-m0`, `und-t-m0-true`, `und-t-m0-true-n0-mixed`, `und-t-m0-true-l0-mixed`)

@FrankYFTang does it look like you'd expect it to?

**Comment by FrankYFTang** [comment]
yea, you need to handle -u- and -t- differently
