### ISSUE TITLE
Stabilize LocaleDirectionality

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#4043]
- [x] https://docs.google.com/document/d/1gKZCaiTG2eeyxrIKUF2tf6PIsaPCIBaUVRXD-JDh6dI/edit?pli=1&disco=AAAA5ZIsOe8

**Comment by sffc** [comment]
@markusicu The feedback for LocaleDirectionality has been addressed. OK to ship?

**Comment by markusicu** [comment]
lgtm tnx

**Comment by robertbastian** [comment]
Duplicate of #3722
