### ISSUE TITLE
Release ICU4X 1.3

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#4065]
## Pre-release checklist

This is a checklist of things that should be done in the weeks leading to the release.

* [x] Verify that the milestone and checklist are complete
* [x] Verify with component owners that they're ready for release
* [x] Take a bird-eye view at:
  * [x] READMEs
  * [x] Documentation
  * [x] Coverage
  * [x] Performance / Memory / Size benchmarks
  * [x] Cargo.toml files
    * [x] All dependencies from the workspace should use `workspace = true` rather than their version number or path 
    * [x] Cargo.toml files need to specify versions for each non-workspace entry in `dependencies`, or use `workspace = true`.
    * [x] Ensure that any new packages have version number `0.0.0`, this will making bumping during the release easier.
    * [x] Ensure that the Cargo.toml file includes a set of fields consistent with other ICU4X packages.
        * These should mostly use workspace inheritance
* [x] Run `cargo +nightly fmt -- --config=format_code_in_doc_comments=true --config=doc_comment_code_block_width=80` to prettify our docs
* [x] Run `cargo update` for each `Cargo.lock` file to update our CI to freshest dependencies
* [x] Go through `ffi/diplomat/tests/missing_apis.txt` and verify that it is empty. If it is not, component owners should either add FFI APIs, add `rust_link` annotations, or allowlist the relevant APIs as having been punted to the future
* [x] Verify that `ffi/diplomat` depends on a released (not Git) version of Diplomat. Get it published (ask manishearth or sffc) otherwise.
* [x] Start work on a changelog (see below)
* [x] Prepare a PR to update tutorials using the upcoming release. The PR should pass `cargo make test-tutorials-local`, but can fail `cargo make test-tutorials-cratesio` prior to release

## Release steps

Once the release checklist is complete, the assigned release driver will perform the following steps, in order:

* Go through the prerelease checklist again, ensuring that no problems were reintroduced in the PRs that landed since the opening of the checklist. (Things like doc prettification will likely need to be rerun!)
* Release utils (see section below). Get the version bumps reviewed and checked in before releasing. (https://github.com/unicode-org/icu4x/issues/4066)
* Update ICU4X package versions as needed. Most of this can be done by updating `workspace.package` in the root `Cargo.toml` and the `workspace.dependencies` entries there. Some `icu_*` crates do not follow the ICU4X versioning scheme like `icu_codepointtrie_builder` or experimental crates.
* Temporarily add `icu_testdata` back to the workspace
  * To build, run `cargo make testdata-legacy-gen` to generate the gitignored data
* Get this reviewed and checked in before continuing
* Publish each `icu_*` crate
  * Use `cargo workspaces publish --from-git` to automatically publish the crates in the correct order if you would like
  * Add `icu4x-release` group as owners to each new component you're publishing
    * `cargo owner -a github:unicode-org:icu4x-release`
* Merge the tutorials PR. `cargo make test-tuturials-cratesio` should now pass
  * If there are any errors, please fix them before advertising the release
* [Tag the Release](https://github.com/unicode-org/icu4x/releases)
* Land the changelog (see below)
* Announce the release to public
  * Send an email to [icu4x-announce](https://groups.google.com/u/0/a/unicode.org/g/icu4x-announce)
  * Submit to This Week In Rust

**Comment by sffc** [comment]
The task "birds-eye view at benchmarks" caused me to file https://github.com/unicode-org/icu4x/issues/4067

**Comment by sffc** [comment]
FFI issues and PR:

- https://github.com/unicode-org/icu4x/issues/4070
- https://github.com/unicode-org/icu4x/issues/4071
- https://github.com/unicode-org/icu4x/pull/4072

**Comment by sffc** [comment]
I get the following errors when trying to publish `components/locid`:

```
$ cargo publish
    Updating crates.io index
warning: license-file `../../LICENSE` appears to be a path outside of the package, but there is already a file named `LICENSE` in the root of the package. The archived crate will contain the copy in the root of the package. Update the license-file to point to the path relative to the root of the package to remove this warning.
   Packaging icu_locid v1.3.0 (/home/sffc/projects/icu4x/components/locid)
    Updating crates.io index
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for the requirement `icu = "~1.3.0"`
  candidate versions found which didn't match: 1.2.0, 1.1.0, 1.0.0, ...
  location searched: crates.io index
  required by package `icu_locid v1.3.0 (/home/sffc/projects/icu4x/components/locid)`
  perhaps a crate was updated and forgotten to be re-vendored?
```

I can solve the warning by changing the license-file back to a per-component one but I don't know if that's a good or bad change. I might put up a PR for this anyway and let someone approve or reject it.

The second one is because `{ workspace = true }` seems to imply the version number rather than `path` when publishing. The way to work around this problem is to just always use paths. I am putting up a PR changing all the `workspace = true` to path imports in dev dependencies.

**Comment by sffc** [comment]
I released the first version of many new crates (the data crates); I went through and ran `cargo owner -a github:unicode-org:icu4x-release` for them

**Comment by sffc** [comment]
In other words, these two need to be bumped:

https://github.com/unicode-org/icu4x/blob/main/ffi/ecma402/Cargo.toml

https://github.com/unicode-org/icu4x/blob/main/experimental/harfbuzz/Cargo.toml

**Comment by Manishearth** [comment]
Once a release is fine
