### ISSUE TITLE
Upgrade to CLDR 38

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#409]
@srl295 has done work to improve the structure CLDR 38 JSON.  We will need to change ICU4X to use the new JSON distribution mechanism before we can upgrade to CLDR 38.

CC @zbraniecki @filmil

**Comment by srl295** [comment]
Or request to change the mechanism

**Comment by sffc** [comment]
Upstream ticket: https://unicode-org.atlassian.net/browse/CLDR-14258

@srl295 What is the status of my suggestion to have a way to download a zip file *cldr-json-modern-38.0.0.zip* or *cldr-json-full-38.0.0.zip*?

**Comment by sffc** [comment]
@srl295 suggested downloading the tar.gz files directly from npmjs.org:

```
$ npm info cldr-core@38.0.0

cldr-core@38.0.0 | Unicode-DFS-2016 | deps: none | versions: 21
http://cldr.unicode.org

dist
.tarball: https://registry.npmjs.org/cldr-core/-/cldr-core-38.0.0.tgz
.shasum: f54a5dfd222c79a050f1fe8e87ad9764f16fb840
.integrity: sha512-WkjA4zo5rLT/BWTZAxHJ0lJXwI33gCYucEz1+CpoI8Wu+rr5IrC57wyNXyrNNMdxfDE5RsWi/JCQ9qnG8sHTiw==
.unpackedSize: 1.3 MB

maintainers:
- jcemmons <emmo@us.ibm.com>
- srl295 <srl295@gmail.com>

dist-tags:
beta: 38.0.0-BETA2  latest: 38.0.0      

published 4 days ago by srl295 <srl295@gmail.com>
```
