### ISSUE TITLE
We should support likelysubtags transforms that *change* subtags

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#4130]
We currently error if likelySubtags.xml has a transform that changes the subtag, e.g. `sh -> sr-Latn-RS`

https://github.com/unicode-org/icu4x/blob/663f527def20cf1ac2692a1b220adaec42ecd91d/provider/datagen/src/transform/cldr/locale_canonicalizer/likely_subtags.rs#L196-L197

There are valid reasons to have something like this, specifically when refining a macrolanguage, for example `ku-IR` to [`kmr-Arab-IR`](https://en.wikipedia.org/wiki/Kurmanji)

We should at least warn instead of erroring, but in the long run our locale expansion data model should probably support this.

cc @sffc

**Comment by sffc** [comment]
Not convinced we should support this. We already have the aliases table used by LocaleCanonicalizer which is intended to convert aliases, macroregions, etc.

**Comment by sffc** [comment]
CC @zbraniecki

**Comment by Manishearth** [comment]
In that case, ought we be converting this into an aliases entry?

Note that `ku-IR` is `kmr` by default, but `ku` is not (I _think_ `ku` by default means Sorani Kurdish)

**Comment by Manishearth** [comment]
cc @markusicu who brought up the example in the first place

**Comment by sffc** [comment]
The aliases are in a different file

https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-core/supplemental/aliases.json

"kmr" is in there.

**Comment by sffc** [comment]
Discuss with:

- @zbraniecki 
- @markusicu 
- @sffc 

Optional:

- @Manishearth

**Comment by sffc** [comment]
@markusicu suggests bringing this to the CLDR Design meeting. @sffc has added it to the agenda.

- @sffc - It seems like macrolangauge resolution should be a separate step.
- @Manishearth - Yeah, like `zh` vs `cmn`. This is a case where you may not want macrolangauge resolution (`zh-CN` to `cmn`).

**Comment by markusicu** [comment]
Discussed in the CLDR/ICU design meeting. Outcome:
> OK (and good) to add constraint on the data file, that prevents each target field from being different from the source field except for the documented cases: und, Zzzz, ZZ, empty, macroregion. This would be in the LDML spec, and in a CLDR unit test.

This needs to be confirmed by the CLDR-TC.

Also, the [LDML spec](https://www.unicode.org/reports/tr35/#Likely_Subtags)’s “Add Likely Subtags” first canonicalizes the input language tag. This is where sh should be mapped to sr-Latn, and then likelySubtags can map sr-Latn to sr-Latn-RS.

**Comment by markusicu** [comment]
More discussion: The likely subtags algorithm does not say that it does full canonicalization. It replaces “deprecated subtags with their canonical values” -- and apparently **only** deprecated ones. However, the "sh" alias is not "deprecated": `<languageAlias type="sh" replacement="sr_Latn" reason="legacy"/>` @macchiati will look into this more, and see whether the "deprecated" spec text predates the reason tags, and whether the likelySubtags algorithm was meant to do full canonicalization.

FYI @FrankYFTang

New CLDR ticket from this discussion: CLDR-17251

**Comment by sffc** [comment]
@Manishearth Given the comment from Markus above, is there any action needed on this issue?

**Comment by Manishearth** [comment]
Nope, unless the macroregion thing needs code changes.
