### ISSUE TITLE
Use proper file download library in ICU4X

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#414]
Right now ICU4X uses a mechanism I cobbled together to download and cache CLDR JSON data.  We should look for a common solution to this problem on crates.io so that we don't have to maintain file downloader code in ICU4X.

**Comment by gregtatum** [comment]
I'm interested in this, but I'd like to finish #107 and start #272 first. If someone else wants to take it before then that's fine.

**Comment by nordzilla** [comment]
I just wanted to highlight a poor experience that I had with the current file download system, as motivation to add this functionality. 

I apparently had a partially downloaded CLDR archive stored in my cache. This caused unintended behavior (deleting files) when trying to generate new test data.

The eventual fix was for me to delete the cached archive to force a re-download. In addition to using a more standard tool for this, I think it would also be nice to run some sort of checksum on the downloaded archive to ensure that the data was downloaded correctly and completely.

**Comment by sffc** [comment]
FYI, the code for this (which should be replaced) is here:

https://github.com/unicode-org/icu4x/blob/master/components/provider_cldr/src/download/io_util.rs

**Comment by sffc** [comment]
@nordzilla @gregtatum Any interest in taking this backlog issue for the April cleanup?

**Comment by gregtatum** [comment]
I'm probably at capacity already for April.

**Comment by sffc** [comment]
I'm going to do this by not actually downloading the full CLDR JSON zip file.  Instead, I'll download each file one at a time.  Then we don't have to touch the system cache directory at all, which seems good.

The file listing is available via the GitHub API:

https://api.github.com/repos/unicode-org/cldr-json/contents/cldr-json/cldr-cal-buddhist-full/main?ref=39.0.0

**Comment by sffc** [comment]
I got the new downloader working in #704, but I'd like to discuss before I delete the old one.

**Comment by sffc** [comment]
2021-05-07: Remove the old flaky download utility (+1 from @Manishearth , @nordzilla , @mihnita ).  Open new issue to introduce a new, better download utility for 1.0.

**Comment by sffc** [comment]
Sorry, not quite fixed yet. I still need to remove the old tool.
