### ISSUE TITLE
Unclear what "ExtraneousLocale" error means

### ISSUE THREAD

**Issue by sophie-h** [unicode-org/icu4x#4165]
My collator works with all languages but `vi`:

```rust
Collator::try_new_with_buffer_provider(&provider, &icu_locid::locale!("vi").into(), CollatorOptions::new())
```

I get the following message

```rust
Data(DataError { kind: ExtraneousLocale, key: Some(DataKey{collator/dia@1}), str_context: None, silent: false })
```

I can't figure out what this error means. Since it's an [provider error](https://docs.rs/icu_provider/1.3.2/icu_provider/enum.DataErrorKind.html#variant.ExtraneousLocale), is it an error in the data?

I got the data via `DatagenProvider::new_latest_tested()`.

**Comment by sffc** [comment]
Hmm, something's wrong here.

`ExtraneousLocale` is an error to signify a singleton key that was loaded with something other than the root locale.

`CollationDiacriticsV1Marker` is labeled as a singleton key in 1.3:

```rust
#[icu_provider::data_struct(marker(
    CollationDiacriticsV1Marker,
    "collator/dia@1",
    extension_key = "co",
    fallback_by = "collation",
    fallback_supplement = "collation",
    singleton,
))]
// ...
pub struct CollationDiacriticsV1<'data>
```

but the rest of the configurations, as well as the way the key is loaded, suggest that it should not be singleton:

```rust
        let tailored_diacritics = metadata.tailored_diacritics();
        let diacritics: DataPayload<CollationDiacriticsV1Marker> = provider
            .load(if tailored_diacritics {
                req
            } else {
                Default::default()
            })?
            .take_payload()?;
```

Is it wrong that it is labeled as a singleton key?

@hsivonen @robertbastian

**Comment by sffc** [comment]
We should add a test that singleton keys don't have data in datagen that is non-singleton.

**Comment by sffc** [comment]
Filed two follow-up issues for holes in our testing infrastructure that let something like this leak through.

I also suspect that the upcoming Unicode Conformance test could have caught this since it has broader locale coverage.

**Comment by sffc** [comment]
I double-checked the other collator keys labaled as singleton and verified that they are correctly being loaded as singleton, so this problem is isolated only to the "collator/dia@1" data key.

**Comment by sffc** [comment]
`icu_collator` version 1.3.3 is released.

https://docs.rs/icu_collator/1.3.3/icu_collator/index.html

https://github.com/unicode-org/icu4x/releases/tag/ind%2Ficu_collator%401.3.3

**Comment by sophie-h** [comment]
Thanks a lot!
