### ISSUE TITLE
Add test for all locales that have additional data in Collator

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4167]
We should add a test for the 'vi' locale and any other locales that load additional data from other keys.

Follow-up to #4165 / #4166

**Comment by ashu26jha** [comment]
In languages like `Vietnamese`, the diacritics are important in determing the sorting order (something like `CollationDiacriticsV1Marker` ) so loading additional data may help accuracy and might change the order.

To fix this, I could use something like (pseducode)

```
let local_provider = MultiForkByKeyProvider::new(vec![]);

Collator::try_new_with_buffer_provider(
    &local_provider, 
    LOCALE.into(), 
    CollatorOptions::new()
);
```

Wheather I am going in the correct direction or not, can you elaborate on this issue?

**Comment by sffc** [comment]
We have some tests here already: https://github.com/unicode-org/icu4x/blob/main/components/collator/tests/tests.rs

We should add some more tests there. This issue is to focus on the locales that load non-root data. You can see which locales do this by looking in the baked data files:

https://github.com/unicode-org/icu4x/tree/main/provider/baked/collator/data/macros

For example, in collator_dia_v1.rs.data, there is: `static KEYS: [&str; 2usize] = ["und", "vi"];` which means that `vi` is the only locale in this case that uses non-root data. Ideally you can find a pair of strings that have different ordering in `und` versus `vi` due to this difference. This helps prove that the `vi` data supplement is being loaded correctly.

It would be good to have at least one test per data supplement. Some of these might already be covered, but we know `vi` is not covered due to #4165.

**Comment by ashu26jha** [comment]
> Ideally you can find a pair of strings that have different ordering in `und` versus `vi` due to this difference.

Now I get it, test cases should like this: 
```
assert_eq!(collator.compare("à", "á"), Ordering::Less);       // For "vi"
assert_eq!(collator.compare("à", "á"), Ordering::Greater);    // For "und"
```

**Comment by sffc** [comment]
@ashu26jha Do you consider this issue complete?

**Comment by ashu26jha** [comment]
I personally feel not to close this one as there are few TODOs at the end of the file which needs to be completed. For example writing the test for `Tibetan`, `"sr and sr-Latn"` etc. 

Since #4633 was my first PR, I wanted to keep it short and easy for review ✌🏼
