### ISSUE TITLE
Add datagen assertion that singleton keys don't have additional supported locales

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4168]
The "collator/dia@1" data key was marked as singleton in 1.3.0-1.3.2, but it contained non-singleton data. I'm not sure how this happened but it seems like we should have an assertion of some sort to prevent this from happening again.

Follow-up to #4165 / #4166

@robertbastian

**Comment by robertbastian** [comment]
Hmm I thought we're already checking this here: https://github.com/unicode-org/icu4x/blob/main/provider/datagen/src/transform/mod.rs#L32-L33

**Comment by robertbastian** [comment]
Ah this gets defeated by https://github.com/unicode-org/icu4x/blob/main/provider/datagen/src/transform/icuexport/collator/mod.rs#L142-L144

**Comment by robertbastian** [comment]
There's in general no way to assert that `supported_locales` is correct, and that was the issue here. If `supported_locales` had returned `["und", "vi"]`, then this would have produced an error.
