### ISSUE TITLE
Add Locale support for likely subtags

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#417]
We should add support for likely subtags [1] and minimizing/maximizing language ids.

[1] https://raw.githubusercontent.com/unicode-cldr/cldr-core/master/supplemental/likelySubtags.json

**Comment by dminor** [comment]
I'm planning to work on this.

**Comment by zbraniecki** [comment]
This fits into ICU4X 0.2 roadmap (#239) and brings parity to ECMA-402 `maximize/minimize` - https://tc39.es/ecma402/#sec-Intl.Locale.prototype.maximize

For prior art I suggest you use `unic-locale` which has:
 - https://github.com/zbraniecki/unic-locale/blob/master/unic-langid-impl/src/lib.rs#L362
 - https://github.com/zbraniecki/unic-locale/blob/master/unic-langid-impl/src/likelysubtags/mod.rs
 - https://github.com/zbraniecki/unic-locale/blob/master/unic-langid-impl/src/likelysubtags/tables.rs

We will not be doing the inline tables directly in the component, but the table structure and size optimizations done using TinyStr may be useful for ICU4X Provider tables.

Two architectural choices we can make is:
* Put it behind the flag. Locale is useful without data so I'd like to I suggest that by default we exclude it, and if someone wants the functionality they use `feature flag`.
* Decide on whether it modifies in place or returns a new maximized/minimized version

@sffc - other considerations?

**Comment by sffc** [comment]
I see this as being fairly closely related to #218, in the sense that they will both be adding a locale data dependency to ICU4X Locale.

Presumably this is only for language/script/region, at least at first?  Then I guess we should add the minimize/maximize functions to LanguageIdentifier.

The functions should take a `&DataProvider` argument.  They will become async.

**Comment by zbraniecki** [comment]
I like that idea! It feels a bit weird to have to carry DataProvider to supply likelySubtags tables for each call of maximize/minimize, but the alternative would have to be that we pull that data in the constructor...

Which also might be an option?

I could imagine this working like that:

```rust
let options = style::Bag {
    date: Some(style::Date::Medium),
    time: Some(style::Time::Short),
    likelySubtags: true, // default `false`
    ..Default::default()
}.into();

let dtf = DateTimeFormat::try_new(locales, &options)?;
```

This way you'd indicate in the constructor that you'll want to use the minimize/maximize.

@sffc - what do you think of such API design vs. the one you proposed? (we could support both as well!)

**Comment by sffc** [comment]
In most classes we are designing, you provide the data provider to the constructor.  Locale is special because we have established a use case that doesn't require data.  Therefore, I feel it makes the most sense to keep the data provider only in the methods that require it.

It's up to the call site of .minimize/.maximize to figure out what data provider to include.  I think that's actually *better* than the place where the locale is constructed, which may or may not know whether or not the Locale should be equipped with the likely subtags data.

**Comment by zbraniecki** [comment]
Hmm, one trade-off is that then data provider call is *per-call*, rather than per construction.

We can cache the table on the instance but that adds a bit complexity, and, well, cache, and cache invalidation is one of the three hardest problems in computer science :)

Are you in favor of that?

**Comment by sffc** [comment]
> Hmm, one trade-off is that then data provider call is _per-call_, rather than per construction.

Yeah.  I think that's better.  Provide the data at the call site of .maximize()/.minimize().  I assume people generally only ever call that function one time during the lifetime of a Locale.

> We can cache the table on the instance but that adds a bit complexity, and, well, cache, and cache invalidation is one of the three hardest problems in computer science :)
> 
> Are you in favor of that?

We absolutely should not cache the data provider.  Saving a Cow of the data struct is kosher, and it is what formatters do.

**Comment by sffc** [comment]
Another thing: I think it is undesirable to have Locale carry around a data table that it may or may not ever need, because it increases the memory usage of a Locale instance.  I would like to keep Locale instances having as little memory usage as possible, because they could be kept in large quantities and used as hash map keys, etc.

**Comment by zbraniecki** [comment]
Thanks! I think I agree with everything, but I have some brainstorm material for:

>  Neither of these things apply to Locale.

This is what I'm not sure about. I can see scenarios like locale management where you *will* want to maximize 100 locales in a hot loop.
Can we do something to avoid loading the same data from the provider 100 times? Or do we think that it'll be fast enough because Provider will cache the ready-to-return result? Or do we think that it's ok to pay that price and not architect for that?

You said earlier that `Saving a Cow of the data struct is kosher`, which means that you'd only use the provided DataProvider once, and the next time ignore it, because you have it in the instance? Can you invalidate that cache if you want to?

That may tap into my earlier question about new instance vs. modify in place. If I call `maximize` and get a new instance, will the new instance clone the `Cow` of data, or will I need to fetch the data again if I call `minimize` on it? Or do we want to modify in place?

To reiterate - I'm convinced by your argument - optional data loading in the constructor is undesirable from API design perspective. I'm now exploring if we can/want to do something about data loading in hot loops, and that may be a non issue if returning data from DataProvider is fast in "warm" fetch.

**Comment by zbraniecki** [comment]
Re-reading your comment:

> Another thing: I think it is undesirable to have Locale carry around a data table that it may or may not ever need, because it increases the memory usage of a Locale instance.

My proposal for passing `likelySubtagsNeeded` in Options Bag was intended to prevent that scenario. You'll pass it *only* if you know you'll want to use maximize/minimize. It's not a "maybe" case.
It's just an explicit "this locale is to be created in such a way that allows for that".

I'm not bringing back the argument for it, just correcting my position on why I proposed it.
From that perspective, the questions form my last comment are more relevant - do we care about calling DataProvider per call or do we want do something to make many calls to `maximize` cheap?

We could even separate inner/outer in such a way:

```rust
struct InnerLocale {
    likelySubags: Option<Data>
}

struct Locale {
    inner: Rc<InnerLocale>
}
```

It's a common concept used in many async scenarios in Rust and it would allow all `Locale` instances to share the data if we think it's worth the hassle.
Alternatively, we could say that DataProvider is fast when it's warmed up, and we don't care about calling to DataProvider per `maximize`.

**Comment by sffc** [comment]
> I can see scenarios like locale management where you will want to maximize 100 locales in a hot loop.

Yeah, but they are 100 different locale objects that need to load the data 100 different times, no matter whether it is in the constructor or in the maximize function.

> Can we do something to avoid loading the same data from the provider 100 times? Or do we think that it'll be fast enough because Provider will cache the ready-to-return result? Or do we think that it's ok to pay that price and not architect for that?

A caching mechanism should generally be present on the data provider layer, making this fairly efficient, assuming all those locales request the same data key.

Another model, likely the *most* efficient, would be to make a LocaleCanonicalizer class with a data provider provided during construction time, and you pass locales to a function on that one instance of LocaleCanonicalizer in a loop.

**Comment by zbraniecki** [comment]
> Yeah, but they are 100 different locale objects that need to load the data 100 different times, no matter whether it is in the constructor or in the maximize function.

Yep, that's why I threw the `InnerLocale` into the mix.

> Another model, likely the most efficient, would be to make a LocaleCanonicalizer class with a data provider provided during construction time, and you pass locales to a function on that one instance of LocaleCanonicalizer in a loop. We could still have .maximize(); it would just wrap (create & destroy) a LocaleCanonicalizer.

I haven't seen such an approach, but first impression is that it's architecturally addressing all the needs. Do you think it's worth exploring or should we leave it as a potential avenue to optimize if we ever need to?

**Comment by dminor** [comment]
Thank you for the conversation so far! I have a few questions I was hoping I could get some input on:

The load API / DataRequest struct method uses a langid, so it seems like the most natural thing is to let the provider implementation search the likely subtags data for the matching id and return a single entry, rather than returning all of the entries and letting the minimize/maximize functions handle the searching. Does that make sense?

Looking at Shane's suggestion that we would add minimize/maximize methods to the Locale (or LanguageIdentifier?) that take DataProvider as an argument, it looks like that would introduce a cyclic dependency between the provider package and the locid package, since provider already depends on locid.

The idea of using a LocaleCanonicalizer class might be one way of breaking this dependency, but is there another way? I haven't had to deal with cyclic dependencies in Rust yet, so quite possibly I'm missing something.

**Comment by sffc** [comment]
The data provider should not perform business logic, except for what can be performed via offline processing. For example, the data request could be for "langid/likelysubtags@1/en" to return likely subtags data for all of English, and on disk, every language would be a JSON file. You could also make the path specific to a language-region, depending on the nature of the likely subtags data.

Good catch about the cyclic dependency. Some ideas:

1. Use a helper class LocaleCanonicalizer
2. Move LanguageIdentifier to its own crate, and keep data loading in the Locale crate
3. When implementing #243, make a new langid type for DataProvider that doesn't depend on locid

For the time being, I think you should implement option (1), and we will revisit before checking it in.

**Comment by dminor** [comment]
Thank you!

With the likely subtags data, there are only ~1850 entries in total, and many languages have only a single entry, so my intuition is that it would be more efficient to read all of the data at once rather than potentially access a bunch of tiny json files.

Assuming you agree, the problem is that it looks like there is no way with the current API to not specify a language when reading data. I thought to perhaps use "und" as a way of asking for everything, but there are a number of entries for und in the data, so that could potentially be confusing.

Could we maybe instead make the DataEntry optional in the DataRequest to support cases like this where there's a small amount of data and we'd like to read it all at once?

**Comment by sffc** [comment]
For now use "und" for locale-agnostic data.  I'll tweak this in #243 and #196 to remove the requirement for a language identifier in the data path.

Is there a lot of overlap in the data files if you split them by language?  For example, if many languages use an identical set of likely subtags, then we don't have to store them all separately.

However, if you make a LocaleCanonicalizer class, then it makes sense to put all the likely subtags data into one entry.  It only makes sense to split them if we are feeding a .maximize() function where we know the locale at the call site.

**Comment by dminor** [comment]
Thanks!

I don't think there's a lot of overlap if split by language, but we might be able to split them up based upon which subtags are in the key, like in Zibi's example here https://github.com/zbraniecki/unic-locale/blob/master/unic-langid-impl/src/likelysubtags/tables.rs.
