### ISSUE TITLE
Time zones and data provider

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#418]

**Comment by zbraniecki** [comment]
Types of timezones: https://github.com/FrankYFTang/proposal-intl-extend-timezonename#copy-from-httpsgithubcomtc39ecma402issues

**Comment by sffc** [comment]
2020-12-10 discussion:

- @sffc and @zbraniecki agree to use separate data keys for each time zone style and width (each row of the table in @zbraniecki's post above)
- @zbraniecki wants to specify how to perform fallbacking between time zone widths
- @sffc suggests thinking carefully about how to identify time zones in input data and in the data bundles; this should be based on prior art.  Consider whether to use "America/Chicago" (IANA) or "uschi" (CLDR locode).

**Comment by mihnita** [comment]
The short format (GMT+0800) is localizable:
```
[7] "GMT {0}"
[109] "GMT{0}"
[1] "GMT{0}‎\u200E"
[1] "KLG {0}"
[1] "MAG{0}"
[5] "UTC{0}"
[1] "WAT{0}"
[1] "[GMT]{0}"
[2] "{0} GMT"
[1] "{0} گرینویچ"
[1] "Гринуич{0}"
[1] "غرينتش{0}"
[1] "জি এম টি {0}"
[1] "ജിഎംടി {0}"
[1] "ග්‍රිමවේ{0}"
[1] "ཇི་ཨེམ་ཏི་{0}"
[1] "ጂ ኤም ቲ{0}"
[1] "ម៉ោង​សកល {0}"
[1] "ᱡᱤᱮᱢᱴᱤ{0}"
[1] "𞤑𞤖𞤘{0}"
```

**Comment by sffc** [comment]
Assigning this to @nordzilla: this issue tracks design discussions around the ICU4X locale data model for time zones.
