### ISSUE TITLE
Bikeshed: What should neo datetime placeholder markers be called

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#4186]
Part of https://github.com/unicode-org/icu4x/issues/3865

From https://github.com/unicode-org/icu4x/pull/4185

We have an opportunity to reduce data size for calendars that don't need, say, day symbols data (or numeric month formatting data). For generic and AnyCalendar formatting to work, however, we need to be able to abstract over calendars that both have and don't have this data alike. Ideally we can do something like `type DaySymbols = ()`, however this causes trouble  when we attempt to abstract over this with traits since you can't easily do "or" bounds with traits (here we need "`Yokeable = LinearSymbolsV1` OR `Self = ()`").

We should have an always-empty key for this, like `PlaceholderDaySymbolsV1`, which we never attempt to load but exists to satisfy the trait bound.

We should figure out what to call it.

(In general I'd like to avoid the term "dummy", it's often [considered non-inclusive](https://developers.google.com/style/word-list#dummy-variable))

**Comment by sffc** [comment]
Discuss with:

- @echeran 
- @younies 
- @sffc 
- @Manishearth

**Comment by Manishearth** [comment]
Approach:
 - Have `PlaceholderDaySymbolsV1 => LinearSymbolsV1` marker type, name TBD
 - In DTF data loading skip loading data when you encounter `CldrCalendar` assoc types that are placeholder. Either use `type_id` or something else.

Name bikeshed:

- `PlaceholderDaySymbolsV1`
 - `EmptyDaySymbolsV1`
 - `EmptyMarker<Yokeable>`

Decision: `EmptyMarker<Yokeable>`

```rust
impl<Y: Yokeable> KeyedDataMarker for EmptyMarker<Y> {
    const KEY: DataKey = data_key!("_empty", singleton);
}

// on most providers
impl<Y: Yokeable> DataProvider<EmptyMarker<Y>> for Foo {
    debug_assert!(false);
    return DataError::MissingDataKey.with_key(EmptyMarker<Y>::KEY);
}


// Check for the EmptyMarker before calling .load()
// this should be a convenience method on EmptyMarker
if core::any::TypeId::of::<M>() == core::any::TypeId::of::<EmptyMarker<M::Yokeable>>() {
    // skip loading
}
```

Discussion:
 - rob: should not need a new error variant, since it's not something to catch and handle
 - manish: also want same behavior for blob.
 - manish: ultimately should never be called (and documented as such)
 - sffc: debug assert in AsDeserializingBufferProvider?
 - manish: yes 

Agreed: @manishearth @robertbastian @sffc

**Comment by sffc** [comment]
I need this for skeleta, so I am taking it now

**Comment by sffc** [comment]
Since the key fails to load, instead of EmptyMarker, wdyt of NeverMarker?

**Comment by Manishearth** [comment]
works!
