### ISSUE TITLE
Semver still broken with 1.3.2 ?

### ISSUE THREAD

**Issue by paul-hansen** [unicode-org/icu4x#4191]
I was trying to use [yarn-slinger](https://github.com/yarn-slinger/yarn-slinger/issues/157) as a git dependency and I get this error:

```
error[E0308]: mismatched types
   --> /home/paul/.cargo/git/checkouts/yarn-slinger-8221464b2261577f/67ce061/crates/runtime/src/pluralization/icu/plurals/ordinal_v1/uk.rs.data:1:159
    |
1   | ...: Rule (unsafe { :: zerovec :: VarZeroVec :: from_bytes_unchecked (b"\x02\0\0\0\0\0\r\0\xC0\n\0\0\0\x03\0\0\0\x03\0\0\0\x80d\0\0\0\r\0\0\0\r\0\0\0") } ,)) , many : None , }
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `VarZeroVec<'_, RelationULE>`, found `VarZeroVec<'_, _, _>`
    |
    = note: `VarZeroVec<'_, _, _>` and `zerovec::varzerovec::vec::VarZeroVec<'_, RelationULE>` have similar names, but are actually distinct types
note: `VarZeroVec<'_, _, _>` is defined in crate `zerovec`
   --> /home/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zerovec-0.9.6/src/varzerovec/vec.rs:148:1
    |
148 | pub enum VarZeroVec<'a, T: ?Sized, F = Index16> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `zerovec::varzerovec::vec::VarZeroVec<'_, RelationULE>` is defined in crate `zerovec`
   --> /home/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zerovec-0.10.0/src/varzerovec/vec.rs:148:1
    |
148 | pub enum VarZeroVec<'a, T: ?Sized, F = Index16> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `zerovec` are being used?
```
I reported this issue here: https://github.com/yarn-slinger/yarn-slinger/issues/157 but it looks like it's caused by this library, probably an unresolved part of https://github.com/unicode-org/icu4x/discussions/4093 which was not fixed in the 1.3.2 patch.

# Reproduction steps
1. `git clone https://github.com/yarn-slinger/yarn-slinger.git --recursive`
2. `cd yarn-slinger`
3. `cargo run --example`
4. Observe it works
5. `rm Cargo.lock`
6. `cargo run --example`
7. Observe error

Note that we delete the lock file to mimic when this library is used as a dependency since dependency lock files are ignored.

# Things I've tried
Since yarn-slinger depends on icu_* crates using `version = "1"` and should have auto updated to the 1.3.2 patch, I tried updating the zerovec dependency of yarn-slinger to 0.10 to remove the duplicate dependency but I still get a ton of errors like this:
```
error[E0433]: failed to resolve: could not find `provider` in `fallback`
 --> crates/runtime/src/pluralization/icu/mod.rs:2:2816
  |
2 | ...r < :: icu_provider_adapters :: fallback :: provider :: LocaleFallbackLikelySubtagsV1Marker > for $ provider { fn load (& self , req : Da...
  |                                                ^^^^^^^^ could not find `provider` in `fallback`
  |
 ::: crates/runtime/src/pluralization/generated.rs:9:1
  |
9 | impl_data_provider!(UnstableProvider);
  | ------------------------------------- in this macro invocation
  |
  = note: this error originates in the macro `impl_data_provider` (in Nightly builds, run with -Z macro-backtrace for more info)i
```

Any help is appreciated!

**Comment by paul-hansen** [comment]
https://docs.rs/icu_provider_adapters/1.2.0/icu_provider_adapters/fallback/index.html
https://docs.rs/icu_provider_adapters/1.3.2/icu_provider_adapters/fallback/index.html

Those releases should be semver compatible right? Looks like there were structs that were moved into a different crate? Should 1.3.2 just be yanked and released as a 2.0?

**Comment by sffc** [comment]
Replied in the downstream issue.

**Comment by paul-hansen** [comment]
Appreciate the help!

Question though, this exists in 1.2.0 : 
https://docs.rs/icu_provider_adapters/1.2.0/icu_provider_adapters/fallback/provider/struct.LocaleFallbackLikelySubtagsV1.html
But in 1.3.2 it doesn't:
https://docs.rs/icu_provider_adapters/1.3.0/icu_provider_adapters/fallback/provider/struct.LocaleFallbackLikelySubtagsV1.html
Isn't that a violation of semver? I don't see anything documented as being "unstable" there.

**Comment by sffc** [comment]
All `provider` modules are unstable and they should be marked as such. For example:

https://docs.rs/icu_collator/1.2.0/icu_collator/provider/index.html

There is not an automated check that all `provider` modules got the unstable tag, but we had multiple people manually crawl the docs before putting out 1.0. If this particular `provider` module was not marked then that is certainly an error in the documentation.

**Comment by sffc** [comment]
What this comes down to is that baked data for 1.2 does not compile in 1.3 and baked data for 1.3 does not compile in 1.2. Everything inside the provider modules is unstable and is (intended to be) well documented as such. If you care about stability then just don't use those APIs; we have others that you can use (especially with the advent of compiled data constructors in 1.3).

**Comment by paul-hansen** [comment]
Ah, I didn't see that since I was in the icu_provider_adapters crate. Appreciate your explanation and patience! 
I'm probably coming at this backwards, I should probably just work through your documentation/examples first if I want to help solve this.

**Comment by sffc** [comment]
(`icu_provider_adapters` follows semver, but not `icu_provider_adapters::fallback::provider`)

**Comment by paul-hansen** [comment]
Maybe a warning here could be good then too: https://docs.rs/icu_provider_adapters/1.2.0/icu_provider_adapters/fallback/provider/index.html

Again I'm probably working this backwards though, if I was the one that set this up originally I'd probably have seen the warnings in the other places before I got there.

**Comment by paul-hansen** [comment]
In summary, because yarn-slinger used an unstable feature I have these options:

1. Update yarn-slinger to use the new version and regenerate (I had trouble getting this to work, probably need to read more docs)
2. Pin the 1.2 versions in my Cargo.lock file like yarn-slinger's lock file has them so my app is compatible with it's generated code.

I think this has been answered so I'll close this for now. Feel free to reopen if you think something is outstanding though. Thanks!
