### ISSUE TITLE
Change bakeddata files in the icu4x repo to have an extension compatible with GitHub file filters

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4209]
Currently they have the extension `.data.rs`. However, one of the main use cases for the file extension is filtering in the GitHub pull request review pane. I _frequently_ freeze my browser tab when opening PRs that change a lot of bakeddata files, which delays reviews, sometimes significantly (e.g. if my browser freezes near the end of the day and I decide to wait until the next work day to try again). GitHub only knows how to filter by individual extension, so it only sees `.rs`.

Can we change these to use an extension that is filterable? Suggestions:

- `.rs.data`
- `.datars`
- `.dtrs`
- `.bake`
- `.bakers` (hmm, this would have also been a good crate name, though i like "databake")
- `.databake`
- `.rs.inc`

CC @Manishearth @robertbastian

**Comment by Manishearth** [comment]
The main reason we used `.data.rs` was to get appropriate syntax highlighting, but we can set this in `.gitattributes` too. I think `.rs.data` is fine

**Comment by robertbastian** [comment]
https://github.com/orgs/community/discussions/44763

https://github.com/orgs/community/discussions/54785

https://github.com/orgs/community/discussions/30686

https://github.com/orgs/community/discussions/70009

**Comment by robertbastian** [comment]
(I'm fine with the extension as a workaround)

**Comment by sffc** [comment]
Yes, I asked @Manishearth who wasn't super sanguine on the timeline for a feature request like this. I changed the issue title to emphasize that this change is all about being more compatible with GitHub which is our tooling of choice.
