### ISSUE TITLE
Migrate blob data to ZeroTrie

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4216]
https://github.com/unicode-org/icu4x/pull/4207 is adding a ZeroTrie variant of BlobDataProvider. We should consider moving most or all postcard data to this variant. However, if datagen makes the new variant by default, it won't work in older versions of ICU4X.

Discuss with:

- @robertbastian 
- @Manishearth

**Comment by Manishearth** [comment]
> it won't work in older versions of ICU4X.

I'm okay with this as long as there is a path to generating it in compat mode.

**Comment by sffc** [comment]
On the CLI:

- `--format blob2`

On the API:

- `BlobExporter::new_v2_with_sink(...)` using `Box<dyn Write>` but leave a 2.0 issue for changing the name or signature of this method
- Mark the old function as deprecated in order to inform users that there is a better function available now. Monitor the situation and leave the door open to reversing the deprecation.

LGTM: @sffc @Manishearth @robertbastian

**Comment by sffc** [comment]
Currently BlobV2 uses `ZeroTrieSimpleAscii`. I could instead make it use `ZeroTrie`. However, I lean toward keeping it `ZeroTrieSimpleAscii` because:

1. A single well-defined format
2. We can add more variants in the future via BlobV3, which will have a lot of code sharing with BlobV2
3. The only alternative ZeroTrie is the one with perfect hash, but my benchmarks previously showed no compelling performance difference for small to medium ASCII. The difference is most noticeable for arbitrary binary data with more than an alphabet's worth of branches per node.

OK?
