### ISSUE TITLE
How should datagen deal with CLDR invariants?

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#4226]
When working on https://github.com/unicode-org/icu4x/issues/3865 I've come across a lot of cases where ICU4X makes an assumption about CLDR data (e.g. "chinese calendars must have monthPatterns" or "gregorian must have two eras"). We currently panic here.

There are also cases where we work with assumptions about CLDR data that are expected to be eventually invalidated. For example, I'm going to be assuming that CLDR only has the numeric overrides  `d=hanidays`, `hanidec`, `hebr`, `M=romanlow`, `y=jpanyear` for datetime stuff. In the future it may add more, but I'd like ICU4X developers to know when these invariants are invalidated.

What are the lines we should draw? Should we use debug assertions for this? Have a "fail more" CI mode? Or are we okay with users being exposed to these assertions when they update CLDR? I know we don't guarantee new-CLDR-old-datagen anyway.

Discuss with:

 - @Manishearth 
 - @sffc 
 - @robertbastian 
 - ??

**Comment by Manishearth** [comment]
Relatedly, it's kinda annoying that `expect()` and friends can't do string formatting, it may be useful to have an `expect!()` macro for use in datagen.

**Comment by sffc** [comment]
> I know we don't guarantee new-CLDR-old-datagen anyway.

Yeah, we can really only care about old-CLDR-new-datagen. CLDR changes structure enough that there's no way we can support new-CLDR-old-datagen.

A nice thing about assertions is that it's easy to locate them in the code. Datagen has such a gigantic number of invariants that it is in many ways helpful for developers and users to be able to pinpoint exactly where they occur in code.

With debug assertions you need to GIGO in non-debug mode. We do this in component crates for reasons we've discussed at length in the past, but in datagen we shouldn't need to do that.

Where I'd draw the line is:

1. Errors that can happen during normal execution of datagen (such as file-not-found, invalid key name, or permissions issues): return an error result
2. Invariants that are true in all locales in all current and past CLDR versions that we support but which may break in future CLDR versions:
    1. If they affect code flow (e.g., unwrapping an Option field): panic
    2. If you can easily continue (e.g., checking that a string is equal to some other string): debug_assert

Are there other classes of error cases to consider?

**Comment by Manishearth** [comment]
Yeah that makes sense and is roughly what I expected.

I'm actually going to close this issue; it should have been marked more as a question rather than a discussion, unless people really do disagree on this.

**Comment by robertbastian** [comment]
lgtm
