### ISSUE TITLE
Document sub-component crate examples as part of the larger crate

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#424]
I think it would be best to remove obvious use declarations from appearing in documentation examples. This will reduce the amount of space, clutter, and boilerplate information in the documentation, and will add to the uniformity of our docs throughout the project. 

For instance, consider the current documentation for `icu::locid::subtags::Region`

https://unicode-org.github.io/icu4x-docs/doc/icu/locid/subtags/struct.Region.html

Each example for `Region` includes the line `use icu_locid::subtags::Region;`

```rust
/// ```
/// use icu_locid::subtags::Region;
/// 
/// let region: Region = "DE".parse()
///     .expect("Failed to parse a region subtag.");
/// ```
```

This produces documentation that contains the use declaration in the example itself.

![image](https://user-images.githubusercontent.com/58569820/102648282-1872d280-411c-11eb-8f90-289bb6327042.png)

The declaration must still be present in order to compile the documentation tests, but we can hide the obvious declaration from appearing in the documentation by adding a `#` in front of it: 

```rust
/// ```
/// # use icu_locid::subtags::Region;
/// let region: Region = "DE".parse()
///     .expect("Failed to parse a region subtag.");
/// ```
```

This will produce a much cleaner example:

![image](https://user-images.githubusercontent.com/58569820/102648624-ac449e80-411c-11eb-8d95-41e9ff86d044.png)

In general, I think it's good to show use declarations for top-level, comprehensive, or multi-module examples, and for non-obvious dependencies; but I think that it would save a lot of space/clutter to hide the obvious dependency on the item(s) for which the documentation exists.

**Comment by nordzilla** [comment]
I'd actually like to re-open this for discussion, but perhaps in a different light. 

I've been looking more at the standard library docs, and in a lot of cases, they do have explicit `use` declarations for every example.

See the documentation for [`HashMap`](https://doc.rust-lang.org/std/collections/struct.HashMap.html)

So I'm thinking it would be fine to leave the `use` declarations in, even if it is more verbose. I think it's important to be congruent with the standard library documentation in this way. 

But there is a potential problem with the `use` declarations themselves. They're always local to the component crate.

How often do we expect people to use individual component crates as dependencies vs. the `icu` crate itself?

That is, something like:

> ```toml
> [dependencies]
> icu_datetime = "0.1.0"
> ```
> 
> paired with
> 
> ```rust
> use icu_datetime::*
> ```

vs.

> ```toml
> [dependencies]
> icu = "0.1.0"
> ```
> 
> paired with
> 
> ```rust
> use icu::datetime::*
> ```

I think it’s unfortunate that someone who pulls up the documentation for the `icu` crate and then navigates to the `datetime` component will see `use` declarations in examples that are `icu_datetime` instead of `icu::datetime`. 

I'm not sure if there is a good way to resolve this issue. There might be some sort of conditional flag we could use when running rustdoc that would be able to tell if the documentation was generated from the `icu` crate root vs. the individual component crate root.

Ideally if someone is looking at the documentation for _only_ the `icu_datetime` crate they should see 
```rust
use icu_datetime::*
```

And if someone is looking at the documentation for the `icu` crate and then they navigate to the `datetime` module, they probably should see 
```rust
use icu::datetime::*
```

@Manishearth are you aware of a clean solution to this problem? 

I'm particularly interested in ways to ease the barrier of entry for newcomers and I could see this being frustrating to people who look at the documentation for `icu` and see the wrong `use` declarations in the examples.

**Comment by zbraniecki** [comment]
Ah! Thank you for bringing it up! I am actually struggling with that for a long time now!

It is fairly common for us to have a component that is intended to be fully sufficient standalone, and also as a part of some meta component. I've experienced it in `unic_langid`, `fluent` and other places.

I'd love to find a clean solution to the `use icu_datetime::DateTime` vs `use icu::datetime::DateTime`!

With the recent advancements to rustdoc it seems like it miiight be possible to autodetect where the `DateTime` is coming from and autogenerate the correct `use` line for it for docs, but maybe there's a better solution that is already available?

**Comment by Manishearth** [comment]
I would just use `icu::datetime` unconditionally, and add it as a dev-dependency.

This makes less sense for standalone components,  but while `icu_datetime` is supposed to _work_ standalone, it's okay for it to document itself as a part of `icu`.

There is no clean solution. Doc comments _are_  sugar for `#[doc = ""]` attributes (per line) so if you can set different env vars when documenting these crates you can do the horrendous solution of using `cfg_attr` with manual doc comments. But this doesn't solve the docs.rs problem.

**Comment by sffc** [comment]
2021-02-04: Use meta crate in all doc examples. Depend on metacrate as a dev dependency; include it with no default fatures.
