### ISSUE TITLE
Impl Databake for maps/sets

### ISSUE THREAD

**Issue by adamchalmers** [unicode-org/icu4x#4266]
Hi! The databake crate seems really helpful. One quick question, I notice that Bake is implemented for a lot of stdlib types, mostly strings, numbers, smart pointers and vec/slice/tuple. I notice there's no implementation for sets or maps (either tree- or hash-based).

I imagine there's some reason why Bake isn't implemented for those types. Or maybe it's just that nobody's gotten around to it yet. If there's no reason making this difficult, I think it should be implemented for those types. But I assume there's something going on that I'm not aware of which makes it difficult.

**Comment by adamchalmers** [comment]
@jessfraz

**Comment by adamchalmers** [comment]
Apparently I was overthinking it, and the team just didn't have a need for Bake impls on these collection types. So I'm adding them!

**Comment by adamchalmers** [comment]
Makes sense. I actually only want HashMap impl for my specific project, but it does seem like we should support more collections if possible.

My usecase actually has nothing to do with performance, I just want an easy way to output my Rust types from a macro. But maybe we could just add docs about the underlying algorithmic complexity.

**Comment by robertbastian** [comment]
@adamchalmers we're planning to do a release ~tomorrow, if you want hashmap to be included I suggest you open a PR soon.

**Comment by adamchalmers** [comment]
> @adamchalmers we're planning to do a release ~tomorrow, if you want hashmap to be included I suggest you open a PR soon.

Not gonna make it in by tomorrow, don't wait on me! I'm happy to use my fork if I need to :)
