### ISSUE TITLE
Document Dart tool dependencies

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#4326]
CI tells me to run `cargo make diplomat-gen` and that command fails with: "Trying to run `dart format` ... failure"

`rg dart -t md` does not find documentation for what I need to install.

ICU4X should have documentation for what Dart tooling needs to be installed, considering that `cargo make diplomat-gen` is a prerequisite for landing pretty much any PR that affects API surface.

**Comment by robertbastian** [comment]
Duplicate of #4291
