### ISSUE TITLE
Internal bikeshedding for date symbol variable names

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4328]
We have "field symbol", which is like "formattable month" (`M`), and "field length", which is like "numeric" or "abbreviated", which together create a "field pattern item" (`MMM`).

What do we call the thing that gets interpolated into the field pattern item? Currently the code re-uses the word "symbol" for this, like `DateSymbolsV1`. However, we should consider using a different name.

We could go with `Value` (or `PlaceholderValue` or `FieldValue`) as discussed in #4026. Note that this value is specifically for the field, and it is not the value being formatted, which we currently call "input".

Would be good to fix this before we ship neo date symbols.

CC @echeran @Manishearth

**Comment by Manishearth** [comment]
To me "symbols" are the things that get interpolated, but that could just be me. So personally I'd change "field symbol" to something else.

It does make more "sense" for the pattern code to be a "symbol" though.

**Comment by sffc** [comment]
Another word would be `Names`, like `MonthNames` rather than `MonthSymbols`.

**Comment by Manishearth** [comment]
I like that

**Comment by sffc** [comment]
@zbraniecki Do you agree with the proposed naming?

- "symbols" refers to datetime field symbols, such as `M`
- "names" refers to the placeholder values, such as "January" and "Jan."

**Comment by zbraniecki** [comment]
I'm ok with that. `DisplayNames` is also returning `January`, `Jan` etc.

**Comment by sffc** [comment]
I think this is done but I should audit.
