### ISSUE TITLE
Add functions to get ICU4X, CLDR, and Unicode versions

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4342]
Currently clients of ICU4X do not have a way to programmaticaly get the version numbers from the library. To get the ICU4X version, they can query the `cargo metadata`. To get the CLDR version, they are mostly out of luck; currently the only function for this is `icu_testdata::versions::cldr()` which is deprecated since `icu_testdata` is deprecated.

I'd like to have a function somewhere that makes these version numbers easier to fetch.

I imagine @robertbastian or @Manishearth may have an opinion.

CC @sven-oly

**Comment by Manishearth** [comment]
I think we should do this, probably in `icu_locid` or `icu_provider` or the metacrate.

Or maybe it's time for an `icu_util` crate idk

**Comment by sffc** [comment]
It could go into the same crate where we're planning to put `LocaleFallbacker` which is currently slated to be `icu_locid_transform` (#3931) but I'm not opposed to just calling it `icu_utils`, being super duper strict with what we allow to land in that abomination of a crate, and putting it in the rearview mirror

**Comment by sffc** [comment]
Although the purpose of that crate is to hold common dependencies required for compiled data, so I think maybe we should stick with that mindset. The version number functions for CLDR and Unicode still fit.

The ICU4X version number function could go into the metacrate. If you need the version number from a component crate, you are a power user and can get it from `cargo metadata`

**Comment by robertbastian** [comment]
> To get the CLDR version, they are mostly out of luck; currently the only function for this is icu_testdata::versions::cldr() which is deprecated since icu_testdata is deprecated.

`icu_datagen::DatagenProvider::LATEST_TESTED_CLDR_TAG`, `icu_datagen::DatagenProvider::LATEST_TESTED_ICUEXPORT_TAG`, `icu_datagen::DatagenProvider::LATEST_TESTED_SEGMENTER_LSTM_TAG`

Those give the source versions for compiled data. For custom data we should use something like the supported locales functionality we're already discussing, as that's also datagen metadata.

**Comment by robertbastian** [comment]
> Is there a mapping from icu_datagen version to compiled data version?

Don't quite understand the question? CLDR versions? They're always the same for a given ICU4X release.

**Comment by sffc** [comment]
So if you have `~1.4` of `icu`, then you can get the cldr version from your choosing of `icu_datagen` or `icu_testdata`. Would be nice to not depend on those heavy crates.

**Comment by robertbastian** [comment]
> One issue with putting it on BakedProvider is that it's internal unstable API.

We can expose the unstable API through a stable API. See my PR.

**Comment by robertbastian** [comment]
Resolved after discussion in https://github.com/unicode-org/icu4x/pull/4399#issuecomment-1845922423
