### ISSUE TITLE
Implement `IterableDataProvider` for `BlobDataProvider`

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#4344]
We can significantly speed up datagen by using a precomputed `BlobDataProvider` as the exporting provider, instead of `DatagenProvider`, for example for Dart tree shaking.

However, while `BlobSchemaV1` is iterable, `BlobSchemaV2` is not as far as I can tell.

**Comment by sffc** [comment]
Ok if you put the impl behind a `datagen` feature.

ZeroTrie supports iteration. https://unicode-org.github.io/icu4x/docs/zerotrie/struct.ZeroTrieSimpleAscii.html#method.iter

**Comment by robertbastian** [comment]
Fixed by https://github.com/unicode-org/icu4x/pull/4347
