### ISSUE TITLE
Change CodePointInversionListBuilder::add_u32 to add32 and check for others

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4354]
In https://github.com/unicode-org/icu4x/issues/2413 we decided to use the `foo(char)` and `foo32(u32)` as our naming convention for function overloads that take a u32 instead of a char.

In #2460 we adopted this convention across most of the code base. However, it seems we did not change `CodePointInversionListBuilder::add_u32`, which I think should be `add32`.

I think we should fix this in 2.0 and also scrub for any other instances we might have missed.

OK?

@robertbastian @Manishearth @echeran

**Comment by sffc** [comment]
Also we should make sure this is in the style guide.

**Comment by Manishearth** [comment]
+1

**Comment by robertbastian** [comment]
We should add `add32` now and deprecate `add_u32`. Having a deprecation period before removal is nicer for clients, and it lets us fix this today. Removing all deprecated items in 2.0 is trivial.
