### ISSUE TITLE
[locale] Consider using a parsing iterator for comparing

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#44]
At the moment `PartialEq<&str>` relies on `to_string` of the `LanguageIdentifier`, but as we can see from benchmarks, parsing is much faster than serializing.
Therefore it might be nice to do the reverse - start parsing the `&str` and compare subtags as we go.
The nice thing about this is that if we encounter mismatching tags early on, we can stop parsing.

**Comment by sffc** [comment]
Marking as backlog.
