### ISSUE TITLE
Add error case to TransformResult

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4409]
UTS 35 specifies an error case in the likely subtags algorithm. It says that the error case can be returned in a way conventional in the programming language. I propose adding it to the TransformResult enum:

```
#[allow(clippy::exhaustive_enums)]
pub enum TransformResult {
    /// The canonicalization operation modified the locale.
    Modified,
    /// The canonicalization operation did not modify the locale.
    Unmodified,
    // NEW ENTRY:
    /// The canonicalization operation failed to run to completion.
    /// The locale was not modified.
    Failed,
}
```

Unfortunately the enum is marked as `exhaustive`, so we need to wait until 2.0 to do this.

OK?

- [ ] @zbraniecki

**Comment by zbraniecki** [comment]
Reading https://www.unicode.org/reports/tr35/#Inheritance_vs_Related algo indicates that the "raise an error" happens on missing match only, and I feel that `FAILED` communicates some internal error, which is not the case.

Can we call it "NO_MATCH"?

**Comment by sffc** [comment]
Naming the variant `NoMatch` works for me.

**Comment by sffc** [comment]
Another path here would be to make the maximize function return a `Result` whose `Err` variant we use to signal that the language was not found.

Do we think it's useful for Rust programmers to get an "unused return value" warning?

The problem with `NoMatch` is that it means that the locale might not contain all of its subtags, so code using `.unwrap()` on a subtag might no longer work.

**Comment by zbraniecki** [comment]
My mental model, which may be diverging from TR35 intention, is that maximize is a best effort operation that does not guarantee that all subtags are populated.

In other words, `und` can be extended to `aa-Bbbb-CC` or may be extended to `aa-CC`. Both are valid, which means that the consumer has no reason to expect that after maximization all subtags are populated (clearly, variant isn't in most/all cases!).

I think therefore that the difference between scenario (a) "I took your input and found an extended output that I'm returning" and (b) "I took your input, haven't found any match, so returning your input" is not observable, and I'm not sure if there's a value in signaling a difference in return type.

In both cases, I imagine that there may be a separate operation that takes any LI and populates missing LSR (but not V, right?) turning `und` to `und-Zzzz-ZZ` and `en-US` to `en-Zzzz-US`.

If we think it's a hot path, we could make it an option on maximize.

The longer I think about it, the less convinced I am that the new return variant is useful.

**Comment by zbraniecki** [comment]
> I think therefore that the difference between scenario (a) "I took your input and found an extended output that I'm returning" and (b) "I took your input, haven't found any match, so returning your input" is not observable, and I'm not sure if there's a value in signaling a difference in return type.

I misspoke. I see a difference in language matching and that's why we return Modified/Unmodified, to avoid a loop in case maximize didn't return any difference without having to compare pre-post.

What I don't see a value of is difference between unmodified because it's maximized from because we have no data to maximize.

**Comment by sffc** [comment]
My mental model was that `maximize()` always returns a nonempty script and region subtag, but I am happy with the mental model you propose.

I changed #3874 to document this behavior and give examples.

Is this a breaking change? Because currently clients can `.unwrap()` the script and region subtag, and now they can't.

**Comment by zbraniecki** [comment]
> Is this a breaking change? Because currently clients can .unwrap() the script and region subtag, and now they can't.

That's a good question. I would like to suggest that this is not a breaking change, you're fixing a bug.
