### ISSUE TITLE
Unexpected word boundary with WB4 and WB6/WB7 rules

### ISSUE THREAD

**Issue by anba** [unicode-org/icu4x#4417]
Word segmentation over the string `"a.\xADb"` returns unexpected word breaks: The returned word segments are `"a"`, `".\xAD"`, and `"b"`. But I think [WB4](https://www.unicode.org/reports/tr29/#WB4) should have prevented the word break, right? Compared to that, `"a.b"` and `"a\xAD.b"` are both correctly classified as a single word.

CC: @aethanyc and @makotokato

**Comment by sffc** [comment]
@eggrobin

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/4550 fixes some of the issues here but not all of them, see https://github.com/unicode-org/icu4x/pull/4550#issuecomment-1908267095

**Comment by robertbastian** [comment]
Tracking remaining changes in #5015
