### ISSUE TITLE
Reduce stack size of DecimalSymbolsV1

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4437]
Currency DecimalSymbolsV1 is 192 bytes. We should consider reducing that size since it is retained in a lot of other types, so we get a high ROI by reducing it. Here's a sandbox where I got it down to 56 bytes without sacrificing much:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5900f3431d428cb8b11695b6ca9dbeea

Other representations may be possible as well.

**Comment by Manishearth** [comment]
One downside of this would be that the Pixel Watch code, which directly constructs a DecimalSymbolsV1, would have to resort to manually constructing a VarZeroVec, which we try not to make a runtime problem.

**Comment by sffc** [comment]
Here's a 112-byte version with no VarZeroVecs

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=317921850e317c266ded75b8432422a3

**Comment by sffc** [comment]
DecimalSymbolsV3 is probably just about the same performance-wise as DecimalSymbolsV1. VarZeroVecs add runtime cost for lookup.

**Comment by sffc** [comment]
- @Manishearth - We should look at postcard size, too. And measure performance. But initially version 2 seems good.

**Comment by Manishearth** [comment]
@sffc your design here would be optimized by the new MultiFieldsULE thing too, if we added ArrayVarULE
