### ISSUE TITLE
Consider making Locale wrap LanguageIdentifier as a field

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#447]
This came up in the context of the LocaleCanonicalizer that I'm working on in https://github.com/unicode-org/icu4x/pull/423. It would be nice to apply likely subtags to LanguageIdentifiers as well as Locales, but because there is currently no relationship between the two types, there is not a good way of doing so.

One suggestion was to make LanguageIdentifier a field of Locale. The likely subtags alogrithms could then work on LanguageIdentifiers, either standalone instances or ones that are a field of Locale.

There are other possibilities as well. Since this could end up being a large change, I thought it made sense to break this out into a separate issue rather than leaving the conversation in the LocaleCanonicalizer pull request.

**Comment by sffc** [comment]
I think it would be nice to `impl AsRef<LanguageIdentifier> for Locale`, and this can be done easily if the LanguageIdentifier is a field of the Locale.

**Comment by sffc** [comment]
2021-01-15: Consider implementing Deref to allow `locale.language` to work.  Otherwise we would need to do `locale.li.language` or a new method like `locale.language()`.
