### ISSUE TITLE
Writeable: how to parameterize fmt::Write?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#449]
The definition of Writeable is currently

```rust
// Option 1 (status quo)
pub trait Writeable {
    fn write_to(&self, sink: &mut dyn fmt::Write) -> fmt::Result;
    fn write_len(&self) -> usize;
}
```

This impl forces the `fmt::Write` to be a trait object.  I've learned since writing this definition that it is [slightly](https://github.com/unicode-org/icu4x/pull/431#issuecomment-750780808) faster if the compiler can skip the dynamic dispatch and call the method directly.

Here are some other options:

```rust
// Option 2
pub trait Writeable {
    fn write_to<W: fmt::Write + ?Sized>(&self, sink: &mut W) -> fmt::Result;
    fn write_len(&self) -> usize;
}

// Option 3
pub trait Writeable<W: fmt::Write + ?Sized> {
    fn write_to(&self, sink: &mut W) -> fmt::Result;
    fn write_len(&self) -> usize;
}

// Option 4
pub trait Writeable {
    type W: fmt::Write + ?Sized;
    fn write_to(&self, sink: &mut W) -> fmt::Result;
    fn write_len(&self) -> usize;
}

// Option 5
pub trait Writeable {
    fn write_to(&self, sink: &mut dyn fmt::Write) -> fmt::Result;
    fn write_to_object<W: fmt::Write + ?Sized>(&self, sink: &mut W) -> fmt::Result where Self: Sized;
    fn write_len(&self) -> usize;
}
```

Option 2 seems to make sense, but it prevents the Writeable from being itself used as a trait object.  Option 3 may work, and the trait object version would be `Writeable<dyn fmt::Write>`.  I don't really understand when to use associated types, so I don't know if Option 4 is appropriate or not.

Thoughts?  @Manishearth @zbraniecki

**Comment by Manishearth** [comment]
What if we add `write_to` and `write_to_string`, where the former is generic? The point of `Writeable` is to write to strings, everything else can be done through `Display`, no? Do we actually need a separate `write_to` for _calling_ purposes?

**Comment by sffc** [comment]
We already have writeable_to_string. I didn't include it above because impls don't implement it.

Auto allocating the string is only half (actually right about half) of the perf improvement. The other half is that fmt::Write is much lighter weight and therefore faster than Formatter as used in Display. I posted my benchmark results on this forum somewhere and can dig them up if needed. So yes, write_to is useful on its own merits.

**Comment by sffc** [comment]
Is there a way in Rust to use option 2 but force `W` to be a specific type, in this case `dyn fmt::Write`, when the object is made into a trait object?

So, if you use `a.write_to(b)` when `a` is Sized, then `b` is ingested as `&impl fmt::Write`, but if you use `a.write_to(b)` when `a` is a trait object, then `b` is ingested as a `&dyn fmt::Write`.

**Comment by Manishearth** [comment]
Nah, that's not possible, you need two methods
