### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#45]
I find having a continuous code coverage to be very useful in finding missing spots in test coverage.

I only ever used `coveralls`, but it works quite well. Here's an example for [`fluent-rs`](https://coveralls.io/github/projectfluent/fluent-rs?branch=master).

I think we should set up some CI+codecov, either via github actions, travis or any other solution. `tarpaulin`, which is a crate I'm using, also supports `codecov`.

**Comment by zbraniecki** [comment]
On a related note - this github action may be useful to track bloat and dependency bloat - https://github.com/orf/cargo-bloat-action/

**Comment by sffc** [comment]
Between coveralls and codecov, is there a difference to their robustness of code coverage?  For example, if you have a line like,

```
if (a || b) {
```

Are either of these tools sophisticated enough to recognize that there are actually 4 different code paths at play there?  (If a is true, if b is true, if both a and b are true, if both a and b are false)

**Comment by zbraniecki** [comment]
> Are either of these tools sophisticated enough to recognize that there are actually 4 different code paths at play there? 

coveralls vs codecov are not analyzing anything. They just show data over time.

There may be difference between `tarpaulin` vs `grcov` - in this PR I use grcov. I don't know if there is a difference in coverage quality.

**Comment by zbraniecki** [comment]
I think this is now completed thanks to @echeran !

**Comment by sffc** [comment]
@echeran Can you link the PRs that fixed this issue?
