### ISSUE TITLE
Use auxiliary keys instead of fixed locales for segmenter

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#4511]
Segmenter locales are not locales in the sense that they participate in fallback, or that they are even exposed to the user. Instead of using hardcoded locales to look up segmenter payloads, we should use auxiliary keys.

**Comment by sffc** [comment]
Please propose:

1. What are the aux keys exactly?
2. How do they fall back between each other?

Note: adding aux keys is nice because then we can introduce fallback between different models, but then we need to define how that fallback works.

**Comment by robertbastian** [comment]
This would basically remove these mappings: https://github.com/unicode-org/icu4x/blob/9491b6358f0e59776cc3a1fe2efb2115a5c02506/provider/datagen/src/transform/segmenter/dictionary.rs#L19-L39, https://github.com/unicode-org/icu4x/blob/9491b6358f0e59776cc3a1fe2efb2115a5c02506/provider/datagen/src/transform/segmenter/lstm.rs#L184-L202, and we'd use aux keys instead.

We would have these combinations
* `DictionaryForWordOnlyAutoV1Marker`, aux key `cjdict`
* `DictionaryForWordLineExtendedV1Marker`, aux keys `khmerdict, `laodict`, `burmesedict`, `thaidict`
* `LstmForWordLineAutoV1Marker`, aux keys `Burmese_codepoints_exclusive_model4_heavy`, `Khmer_codepoints_exclusive_model4_heavy`, `Lao_codepoints_exclusive_model4_heavy`, `Thai_codepoints_exclusive_model4_heavy`

If we support more models in the future, the segmenter constructor might do its own fallback between these.

**Comment by sffc** [comment]
We could shorten `Burmese_codepoints_exclusive_model4_heavy` as follows:

1. `Burmese` should probably be either `my` (if langauge-specific) or `Mymr` (if script-specific)
2. `codepoints` is probably okay to write as `cp`
3. `exclusive` should be inferred by the key. The other mode is inclusive of Latin text, which the segmenter doesn't expect with this key. So I would say to drop this.
4. `model4` is probably good to keep as-is
5. `heavy` can probably be dropped. We should only have heavy-trained models. Light-trained models could be called `dev` or something.

**Comment by sffc** [comment]
@robertbastian said:

> I'd prefer not to maintain a mapping. Can we change the source repo to use more concise names, or declare short names for each model?

I do think it's ICU4X's job to choose the names that make the most sense for the specific context in which those names are being used. But, if this gets us unblocked, I'm not opposed to adding a short name upstream, similar to how we get short names for properties from icuexportdata.

**Comment by robertbastian** [comment]
In that case I think we should stick with the upstream names. Neither the size of the keys nor the time it takes the binary search over them are significant in the context of segmentation data/runtime.

**Comment by sffc** [comment]
There has never been time put into figuring out what good names would be. These model names were invented by @SahandFarhoodi and I don't think they were intended to be publicly facing names.

**Comment by sffc** [comment]
> In that case I think we should stick with the upstream names. Neither the size of the keys nor the time it takes the binary search over them are significant in the context of segmentation data/runtime.

In terms of specific issues, the names are not BCP47-compatible, and I think we should try to keep our key attributes being BCP47-compatible.

**Comment by SahandFarhoodi** [comment]
Sorry for my late response. 
Yes, I just chose those names to be able to distinguish between multiple experiments we were doing at the time, they were not supposed to be public-facing names. Shane, I agree with your suggestions for shortening names, just one additional thing is that you can also drop codepoints maybe? It was initially there because we had other models that were trained on grapheme and grapheme clusters, but I think you are going to use those models anywhere anyway (correct me if I'm wrong).

**Comment by robertbastian** [comment]
Discussion:

* Keep model names, as an extra mapping in any location is not worth the trouble
  * *Potentially* remove the `_heavy` suffix, because all models are heavy
* During data loading, use prefix matching on marker attributes, i.e. `Lao_` to load the first Lao model that appears in the data
  * This needs prefix matching support in `load(DataRequest)`, we can add a `match_attribute_prefix` flag to `DataRequestMetadata` (trivial for binary search, `ZeroTrieCursor::probe`)
* Users can then pass any of model names from the `lstm_word_segmentation` repo to datagen, and they will work 

LGTM: @robertbastian @sffc
