### ISSUE TITLE
Bikeshedding Needed for extract_convertibility Method in converter.rs

### ISSUE THREAD

**Issue by younies** [unicode-org/icu4x#4512]
We need to discuss and decide on the name of the extract_convertibility method in the converter.rs file. This method is currently extracting the convertibility from the given units in the form of CLDR identifiers.
```rust
impl ConverterFactory {
  /// Extract the convertibility from the given units in the form of CLDR identifiers.
  pub fn extract_convertibility(
      &self,
      unit1: &MeasureUnit,
      unit2: &MeasureUnit,
  ) -> Result<Convertibility, ConversionError> {
      // method implementation
  }
  
  pub fn converter(&self, unit1: &MeasureUnit, unit2: &MeasureUnit2) -> Converter { ... }
}
```

**Comment by robertbastian** [comment]
```rust
pub enum DimensionEquivalency {
  Equivalent, // i.e. length and length
  Reciprocal, // i.e. length/time and time/length
  Unrelated,
}

pub enum UnitConvertibility {
    Convertible, // i.e. meter and foot
    InverseConvertible, // i.e. mpg and l/100km
    NotConvertible, // i.e. meter and square meter
}

```
- robertbastian: why do we need this type? does the caller of the API actually need to distinguish between `Convertible` and `InverseConvertible`?
- younies@: google project A uses `are_convertible`
- robertbastian@: so it's just a boolean instead of three values
- younies@: we can return `Option<Converter>` instead of having this enum

```rust
impl ConverterFactory { 
    pub fn converter(&self, unit1: &MeasureUnit, unit2: &MeasureUnit2) -> Option<Converter> { ... }
}

impl Converter {
    pub fn convert(&self, ...) -> ... { ... }
    // potential future extensions:
    pub fn is_inverse(&self) -> bool { ... }
    pub fn info(&self) -> ConversionInfo { ... }
}

ConversionInfo {
    offset: Ratio<BigInt>, 
    rate: Ratio<BigInt>,
    is_reciprocal: bool,
}
```

lgtm: @younies, @robertbastian
?: @sffc

**Comment by sffc** [comment]
How about naming the struct on what is is instead what it is used for, like `DimensionRegistry`

```rust
impl DimensionRegistry { 
    pub fn converter_for(&self, unit1: &MeasureUnit, unit2: &MeasureUnit2) -> Option<Converter> { ... }
}
```

On `Converter`, seems `info` is sufficient here, right? We don't need to add `is_inverse` and bikeshed the name of it.

**Comment by younies** [comment]
We do not use `is_reciprocal` anymore because we are having three converters right now.
