### ISSUE TITLE
Improve parsing efficiency for PPUCD Provider

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#454]
PPUCD Provider provides the functionality for parsing the [PPUCD file](http://site.icu-project.org/design/props/ppucd) and returning the data (inversion lists) that back the `UnicodeSet`s for each binary and enumerated Unicode property.

Beyond parsing the PPUCD file and applying the cascade of information that it defines, there is also a transformation involving switching the dimension of the "grouping" of code point <-> property information. The PPUCD file is organized around the code point as the most granular unit of grouping for the Unicode property key-value information. The `UnicodeSet`s, however, are defined as code point range(s) per Unicode property.

Current implementations in PRs #242, #439 and #448 are slow and inefficient because they pull in the entire PPUCD file's information for all code points into memory before performing the transformation. However, we can improve the speed by scanning linearly and handling only one block range and one code point range at a time. PPUCD documentation confirms the specification that this assumption is based on -- `cp` lines for code points that override a block must be defined after the `blk` line it overrides but before the next `blk` line.

This issue can represent the sub-task of optimization in the overall UnicodeSet L3a task started in PR #242 to allow for changes in logical correctness and code organization/integration (ex: rebasing after the latest refactoring of data provder) so that they can implemented first.

**Comment by echeran** [comment]
Also, get advice on whether to use a Vec or a HashMap to store the `UnicodeProperty` items within `UnicodeProperties`.

* [in favor of Vec over HashMap in a diff discussion](https://github.com/unicode-org/icu4x/pull/242#discussion_r552292147)
* [in favor of HashMap](https://github.com/unicode-org/icu4x/pull/242#discussion_r553238328)

**Comment by echeran** [comment]
Also, figure out how to [remove Hash and Eq traits from UnicodeSet](https://github.com/unicode-org/icu4x/pull/242#discussion_r561593256). We care about code size for UnicodeSet, and don't care so much about runtime for PPUCD Provider, which is primarily used in an offline manner.

**Comment by echeran** [comment]
Also, use [a `TinyString` for the `name` field of `UnicodeProperty` ](https://github.com/unicode-org/icu4x/pull/448#discussion_r562987915) instead of `str`.

**Comment by echeran** [comment]
Also, apply changes in comments in [Zibi's review of the binary props PR](https://github.com/unicode-org/icu4x/pull/242#pullrequestreview-577501506), esp code cleanup (ex: replacing `.unwrap()` with `Result` + `?`)

**Comment by echeran** [comment]
From Markus:
* binary properties in PPUCD defined like `property;Binary;;alnum` are defined in ICU based on [the Regex spec UTS 18](https://www.unicode.org/reports/tr18/#Compatibility_Properties)
* the enumerated properties `lccc` and `tccc` are created by ICU for convenience to give a shortcut for the `ccc` property's values for the lead and trailing characters of the decomposition mapping
* there are (or will be) also other properties in PPUCD that come from other places besides UCD

Also:
* rename the getters using the long form alias of the property name
* also, prefix getters with `get_` and suffix them with `_property`
* change the string value associated with the resource keys to be the long form alias; the actual identifier of the resource key constant is not important if it is entirely internal
* `ccc` is different from the other enumerated properties -- [see ValueAliases.txt headers](https://www.unicode.org/Public/UCD/latest/ucd/PropertyValueAliases.txt)
 * "# In the case of Canonical_Combining_Class (ccc), there are 4 fields: 
    # The second field is numeric, the third is the short name, and the fourth is the long name."
* can use [code point trie](https://sites.google.com/site/icusite/design/struct/utrie) to store properties of code points
  * each range is associated with a value
* can use an inversion map
  * the PPUCD Python script implements this
  * the ICU4J UnicodeMap implements this too (but ICU4C doesn't do this yet)
* still want to have a structure to look up property values given a code point and a [enumerated] property name
  * code point trie and inversion map are 2 different data structure alternatives to implement this functionality
* for enum properties: more often than looking up a set for a pair of enum property and property value, you would rather find the property value given a enum property and code point

**Comment by sffc** [comment]
I was using ppucd today for the first time.  You weren't joking when you said it was slow!  Right now it runs on the order of minutes against the full ppucd.txt data file.  I'm looking forward to when you improve the speed, hopefully down to the order of seconds.  Have you profiled what's making it so slow?

While you're at it, I noticed that the test "test_enum_props_getters" is quite slow as well.  Try to make it faster, on the order of milliseconds instead of seconds.

**Comment by sffc** [comment]
ppucd.txt is a big file.  But the I/O to read 2 MB into memory is less than a second.  So the slowness must be coming from the work to actually process the file.

Rust is a very fast language.  The 325 seconds it took to parse the file means that well over 325 billion operations had to be performed (assuming ~1 GHz).  That just doesn't make sense!  The file is only 40,000 lines long.  Even if you square that, you're only at one or two billion operations, and it doesn't make sense that there would be anything in ppucd that's quadratic.  I would expect it to be a linear-time operation.

So I hope that we can go back to first principles and figure out what algorithm is slow, and fix it to drastically improve the performance.

**Comment by sffc** [comment]
Another thought: it would be useful to add logging messages while parsing ppucd.txt.  To do this, include the `log` crate as an optional dependency and then use `log::debug!()` and similar.  We do this already in some parts of ICU4X.

**Comment by sffc** [comment]
Just one more comment here.  Instead of spending time improving the efficiency of ppucd parsing in Rust, we could decide to cut our losses and import pre-computed UnicodeSets from ICU, like we're planning to do with CodePointTries (#578, #508).  In some ways, that would be a more elegant solution, because all Unicode properties come in one nice package from ICU, rather than having the binary properties computed on the Rust side and the enumerated properties computed on the C++ side.

**Comment by echeran** [comment]
This issue should be obsolete by the different approach to reading Unicode property data as UnicodeSets described in #662
