### ISSUE TITLE
Making an all-in-one experimental crate

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4551]
Context: see #4543, etc.

- @robertbastian - We made it cfg(test) because there was no functionality, only data structs
- @sffc - The client, Blayne, needs data to plumb into an existing framework. They added data stucts to an unreleased crate and want to be able to leverage that in datagen.
- @robertbastian - can they not just fork datagen if they want to do weird stuff? 
- @manishearth - i agree with rob, the use case feels rather narrow and strange, i would be open to supporting it for normal stuff but not with exceedingly strange hacks
- @robertbastian - we planned to use the cfg(test) stuff for a short time around the release window. we will release these crates with the next release, so I think we should remove it
- @manishearth - i agree, i do not think we should have actual functionality in datagen under cfg(test) except as a temporary "i'm still landing PRs" case
- @manishearth - i don't see the problem with declaring that we will release these crates as experimental next release (not to mention the cargo hack i suggested that lets us avoid publishing this)
- @robertbastian - the names for icu_dimension and icu_units have been discussed and decided now, so they are releasable
- @robertbastian - this is a very weird request that we don't have to solve in the general case
- @sffc - The general problem is that crates can exist as path dependencies without being released; we have had problems releasing crates before we had decided on their name and what content they hold. However, we still should be able to use those crates for our development purposes. (Note: I'd like to even allow bakeddata.)
- @manishearth - yeah no_main isn't guaranteed for test
- @sffc - no_main for test is on stable and it works on stable.
- @manishearth - my preference is to just say that icu_dimension gets released as experimental next time. i really don't understand having cfg(test) functionality in the medium term in datagen. I think it's fine to have around for a period of a couple weeks when stuff lands but that's not what's happening here, and it has *already* caused frustrating issues for me
- @Manishearth - i don't think we need a solution to the self-inflicted problem of "there is actual functionality in datagen hidden behind cfg(test)". we shouldn't do that
- @robertbastian - I don't understand what problem this solves. Having the binary available with cfg(test) is not something we need. If you want to run testdata with more locales, tweak the script, if you want to run it with release data, tweak the script, it's easier than using the CLI
- @younies - I think it is important to allow a dev to make a change end-to-end in a pre-experimental crate
- @younies - Making a specific change to code is a high bar. It should be a well paved path. It should be easy for developers to access full testdata or bakeddata.
- @robertbastian - There are only 2 lines of code to change in make_testdata.rs
- @sffc - Mutating code is a high bar. I think it is important for the solution to be things that can be run on the CLI without touching code.
- @robertbastian - Figuring out the correct binary incantation for baked data is complicated, and doing it for just your component so it doesn't take 20 minutes is even more complicated
- @Manishearth - Can we release the crate that hasn't been named yet, like `icu_namefire_dimension`
- @robertbastian - Can we have the crate behind a feature and comment it out before release
- @sffc - I think it should be a high bar for us to deviate from the repo being in a releasable state without code changes
- @Manishearth I am concerned about the abuse of `cfg(test)`. In general, we should not do this because the problem will recur again. One way around this is to rename `icu_dimension` to something else distinct (`icu_temporary_crate1`), and that would avoid confusion and naming conflicts.
- @robertbastian - Then we don't need to comment it out for release? That is more public messiness
- @Manishearth The messiness is on the crate names and not the modules.
- @robertbastian I'd rather continue to `cfg(test` rather than bring our own stuff to the public.
- @sffc I'm okay with @Manishearth's proposal. It allows us to use `icu_bakeddata`
- @robertbastian I have a better way to run `bakeddata`, which is to move the script into datagen as a test, and that helps because the baked data step is slow.
- @Manishearth - Blayne's use case is a little strange but seems legitimate. But if this is a legitimate case, using cfg(test), then people probably want to be able to do this on release. Having it exposed only on git and not on release is a problem.
- @robertbastian If we have datagen-only crates, then we don't need a crate for them. All the code can live in `datagen`.
- @Manishearth Not opposed.
- @sffc I'm open to that. We have had issues of naming a crate that we regret later. One option is having a crate named `icu_experimental` that is a kitchen sink of everything that hasn't been moved into a proper crate.
- @Manishearth I agree with the option of putting the code in `icu_datagen`, I agree with the option of coming up with naming scheme. I am okay with the option of putting everything in an `icu_experimental` crate.
- @robertbastian Maybe a different name than `icu_experimental` since it sounds like a framework.
- @robertbastian - I think a single experimental crate has advantages because we don't end up with 15 abandoned crates. The disadvantage is that we have a mess of dependencies. But it's experimental so we don't need to worry about dependencies too much yet.
- @sffc I agree. We should avoid the mess of abandoned crates.
- @echeran +1

Question 1: single evergreen experimental crate or multiple pre-experimental crates that could be retired?

Decision: single evergreen crate

LGTM: @sffc @robertbastian @echeran @younies

Question 2: name for evergreen crate

Discussion:

- @sffc For crate names: "nursery" sounds good and I've seen that terminology used before.
- @robertbastian - rust-lang used to do a lot of things in nursery
- @echeran I like `experimental`. It used to mean the same thing across many programming languages' API docs. Nursery and incubator have similar meanings originally for growing early stage things (kids, plants; eggs).
- @robertbastian: icu_unstable is my preference, because 
- @sffc - "experimental" is stronger than "unstable" in our usage of the term. We have `try_new_unstable` for example.
- @echeran - You have experimental features and components, but once you create the API and the API is subject to change then you can say unstable.
- @robertbastian - Most of our crates are nouns
- @sffc - `icu_development` sounds like it might contain development tooling
- @robertbastian - "nursery" indicates that the componetns are intended to graduate
- @sffc - "experimental" is the term we already use for our feature flags
- @sffc - I see the flow as the following: new stuff gets added directly to the evergreen experimental crate. Once we decide on the crate structure and names, we make the crate and figure out dependencies, but the crate can still be "experimental" (pre-1.0). Then, once it gets through the i18n review process and is feature-complete, we release it as stable.
- @robertbastian - That's usually very late, so I don't think these crates will necessarily be released as experimental before stabilizing
- @sffc - To clarify, my understanding is that this new experimental evergreen crate should be for components, not for utils
- @younies - "development" sounds like it is something under development, whereas "experimental" sounds like something that may or may not be finalized. Maybe we could even have both names.
- @sffc - ICU4C uses the language "technology preview" for this
- @younies - "nursery" sounds like something in a hospital. Unclear to non-native speakers.

Voting:

1. `icu_experimental`
2. `icu_nursery`
3. `icu_incubator`
4. `icu_development`
5. `icu_alpha`
6. `icu_unstable`
7. `icu_preview`
8. `icu_nightly`
9. `icu_labs`
10. `icu_prototype`
11. `icu_draft`

**Comment by sffc** [comment]
Vote here: https://docs.google.com/document/d/1xOVOQNbpA9GAjpJsH4XkXderj3BSK1jkVbl7BsPODZU/edit

**Comment by sffc** [comment]
It just occurred to me that we are already hospital themed. The "nursery" is the incubator for the "ICU". 😏

**Comment by sffc** [comment]
OK, the votes are in, and the two choices which float to the top are `icu_experimental` and `icu_nursery`. Among those, `icu_experimental` is the clear winner with 4 out of 6 first-choice votes.

Next action on this ticket is to create the `icu_experimental` crate and move all unreleased code into that crate, but only when there are no big outstanding pull requests into unpublished crates to reduce churn.

**Comment by robertbastian** [comment]
I'll start merging the inactive crates
