### ISSUE TITLE
How to actually convert system locale to ICU locale(s)?

### ISSUE THREAD

**Issue by VorpalBlade** [unicode-org/icu4x#4580]
Hi,

I'm looking into options for localising one of my Rust command line program, and I'm a bit confused about icu4x: How do you actually get from a system locale to the proper ICU4X settings? E.g. consider something like this mixed POSIX locale (what I actually use):

```
$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=sv_SE.UTF-8
LC_NAME=sv_SE.UTF-8
LC_ADDRESS=sv_SE.UTF-8
LC_TELEPHONE=sv_SE.UTF-8
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION=sv_SE.UTF-8
LC_ALL=
```

In which ICU crate is the logic to resolve this (and whatever Windows and Mac OS uses, I'm not familiar with programming on those platforms) to the proper locale to use in ICU4X for each feature?

(The reason I use a mixed locale like this, and also many other people I know do, is that message translations tend to be poor and translated error messages ungooglable. But I still want Swedish dates, 24 hour dates, decimal comma, etc)

In addition, what part of ICU4X handles message translation? Looking at the module list in https://docs.rs/icu/latest/icu/ I don't see anything for that. E.g. something like gettext would provide traditionally. Or is that out of scope of this project?

**Comment by sffc** [comment]
Issue to track adding OS locale bindings to ICU4X: https://github.com/unicode-org/icu4x/issues/3990

Closing as a duplicate.
