### ISSUE TITLE
Struct extensions::unicode::Unicode shouldn't implement Ord

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4609]
The tuple ordering of extensions::unicode::Unicode is not equal to its string ordering. I added a `total_cmp` function to this type in https://github.com/unicode-org/icu4x/pull/4608, and in 2.0 we should remove the derived impl.

**Comment by Harsh1s** [comment]
Hi, I'd love to work on this issue. Can you assign this to me?

**Comment by sffc** [comment]
Hi @Harsh1s! Thanks for your interest but this isn't a good first issue because it is a breaking change that can't land until we start preparing the 2.0 release.

**Comment by Harsh1s** [comment]
> Hi @Harsh1s! Thanks for your interest but this isn't a good first issue because it is a breaking change that can't land until we start preparing the 2.0 release.

Oh, no problem then! Is there any other issue I could work on? I'm quite interested in the project, and would love to make any sort of contribution.

**Comment by Harsh1s** [comment]
Thanks for the help, hope I can make good contribution to the project!
