### ISSUE TITLE
 Improve compiled data FFI constructors

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#4639]
At the moment we're using a runtime branch over the provider enum.

**Comment by sffc** [comment]
Conclusion:

- have each type have two constructors: `create` and `create_with_provider`
- `DataProvider(Box<dyn BufferProvider>)`, the other variants are useless
- `enable_locale_fallback` can either load from itself or be fed a LocaleFallbacker (potentially with compiled data), similar to in Rust

LGTM: @sffc @robertbastian

**Comment by robertbastian** [comment]
See also #3790

**Comment by sffc** [comment]
With the `#[methodversion]` attribute in #3790, we can now make these be simply

- Rust: `ListFormatter::create()`, `ListFormatter::create_with_provider(DataProvider)`
- ABI: `icu4x_list_ListFormatter_create_mv1`, `icu4x_list_ListFormatter_create_with_provider_mv1(DataProvider)`
- C++: we are allowed to break across major versions. within a minor version we can still use overloads.
- JS/Dart: `ListFormatter()`, `ListFormatter.withProvider(DataProvider)`

LGTM: @sffc @robertbastian

**Comment by sffc** [comment]
@robertbastian What is to do here?

**Comment by robertbastian** [comment]
This has to be implemented completely

**Comment by Manishearth** [comment]
> * `DataProvider(Box<dyn BufferProvider>)`, the other variants are useless

Does this mean DataProvider should only be enabled when buffer_provider is enabled?

Also, should we still allow the Empty and Destroyed variants? The Destroyed variant is used for locale fallback.

**Comment by Manishearth** [comment]
The only use case I see of `Empty` is wanting to use a type that optionally loads data; in which case we should just have a `no_data` ctor. I'm removing `Empty`.

**Comment by Manishearth** [comment]
My plan is to upgrade the API without removing any DataProvider variants, and then remove variants in a followup. Variant removal should be possible to do automatically by find-and-replacing on the macro.

**Comment by Manishearth** [comment]
Short discussion with Shane about `ffi::DataProvider`:

 - We can remove `Compiled`, `Empty`. Keep around `Buffer` and `Destroyed`
 - Gate it on `buffer_provider` for now
 - In the future if we decide to add mixed forks/etc we can ungate it and add variants.
