### ISSUE TITLE
icu_properties release at some point?

### ISSUE THREAD

**Issue by cmyr** [unicode-org/icu4x#4681]
Not urgent-urgent, but I would like to be able to use `icu_properties` including #4612 and #4603 at some point.

For the time being I'm happy to handle this via the `patch` section of cargo.toml, but if I can delete that I will be happy.

Thanks!

**Comment by sffc** [comment]
This will get released as part of version 1.5, which is coming as soon as all the issues in the milestone are complete: https://github.com/unicode-org/icu4x/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.5+Blocking+%E2%9F%A8P1%E2%9F%A9%22

**Comment by cmyr** [comment]
that works for me, thanks!

**Comment by rsheeter** [comment]
@sffc can you give us an estimate of the timeline for that? - I understand it might not be clear but your guess will surely be better than mine.

**Comment by sffc** [comment]
Realistically sometime between mid April and mid May.

If you are time-bound we have a process for patch releases.
