### ISSUE TITLE
Bridge the gap between `icu::properties::Script` and `icu::locale::subtags::Script`

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#4705]
Currently we for example define locale directionality on the locid type, so clients that have a properties script cannot use this API. Example: https://github.com/googlefonts/fontc/blob/9466281d982d49a2b7b19845e5f13d720c1682d4/fontbe/src/features/properties.rs#L65

**Comment by sffc** [comment]
There are a few differences, the most well known one being that `Hani` is a property script with `Hans` and `Hant` the corresponding subtag scripts.

Probably worth adding a conversion anyway, though, with the caveats listed.

**Comment by sffc** [comment]
CC our SAH and PAG fellows, @Manishearth @eggrobin @markusicu

**Comment by Manishearth** [comment]
I think "conversion with caveats" might be fine. Yes, they represent different things.

**Comment by markusicu** [comment]
Conversion is probably fine, but in the end they are just script codes, so it also makes sense to define the full set once and have Unicode APIs use a subset of the values.

The ones in the UCD are a subset of the full set.

And only the ones in the UCD have Unicode-defined long value names (identifiers).

**Comment by robertbastian** [comment]
> There are a few differences, the most well known one being that Hani is a property script with Hans and Hant the corresponding subtag scripts.

The Wikipedia page for [ISO 15924](https://en.wikipedia.org/wiki/ISO_15924#Hani) says that `Hani` is an ISO 15924 code, and therefore a valid subtag.

**Comment by robertbastian** [comment]
Our name lookups are already fallible, so they could just return `None` on non-UCD scripts.

**Comment by robertbastian** [comment]
Is [this table](https://en.wikipedia.org/wiki/Script_(Unicode)#List_of_scripts_in_Unicode) available in data, or do we need to crate it from the spec/Wikipedia?

**Comment by eggrobin** [comment]
See https://unicode.org/iso15924/iso15924.txt, linked from https://unicode.org/iso15924/codelists.html.

The PVA column is from https://www.unicode.org/Public/UCD/latest/ucd/PropertyValueAliases.txt.

**Comment by markusicu** [comment]
Also https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
look for `Type: script`

which becomes this in CLDR:
https://github.com/unicode-org/cldr/blob/main/common/validity/script.xml

Note that the CLDR list includes one or more private use script subtags:
- https://www.unicode.org/reports/tr35/#unicode_script_subtag_validity
- https://www.unicode.org/reports/tr35/#Private_Use_Codes

Qaag is current but yucky... Don't include Qaai which has become an alias for Zinh

**Comment by sffc** [comment]
- @sffc - We already have a table for mapping the script numeric ID to the string ID. It's called the enum to TinyStr4 name mapper.
- @robertbastian - Can we make the `properties::Script` type use the TinyStr4-underlying repr internally?
- @sffc - That would require loading the table all the time, as well as an indirection to load things from the table. It seems unnecessary. Not all clients need or want the TinyStr4 representation.
- @robertbastian - I don't think we should make clients convert between the two script types on their end. We should choose a single representation. The only value I see in exposing the u16s is interaction with ICU4C, which I'm not even sure is a use case
- @sffc - It's a rough corner of the API, but I think we should err on the side of modularity. We can make the conversion functions be nicer to use.
- @echeran - LocaleDirectionality spans two crates, which is weird.
- @sffc - Both of these "script" types are context-specific. Are these even things we want to promote to be the canonical representation of a _script_?
- @zbraniecki - The `icu_locid` representation is definitely designed as a script subtag.
- @robertbastian - Unless we include the whole IANA registry it's always going to be open. Also properties only ever return scripts, it's currently an open enum already.
- @sffc - My position is still that what we have now is the most modular, efficient solution. We shouldn't deviate from that. We can make nice conversion functions, even `From` and `Into` gated on `#[cfg(feature = compiled_data)]`. But I don't think we should force all users to use the slower, bigger code path. I don't think the motivation is compelling enough for that.

```
propnames/to/short/linear4/sc@1, und, 802B, 55c3455e15d1d2ae
```

- @robertbastian - My original proposal was to use the tinystr representation in the data structs themselves, this way there is no conversion cost. It will make the CPT slightly bigger, but this could be offset by conversion code size even.
- @sffc - _Maybe_ that would work.. it would change the value size from 2 to 4, which overall is less data than the additional lookup table. However, we lose the ability to return the ICU4C enumerated integers, which I believe is something that we should support so we can be a drop-in replacement.
- @robertbastian - I think that can be modularily added, ICU4C compatibility is not universally required
- @sffc - It would be easiest and most self-consistent to just keep all of the properties APIs returning integers.


No conclusion yet.

**Comment by Manishearth** [comment]
Separately from the discussion of performance, I do think these are _two different kinds of things_ and I would overall prefer us to have an explicit separation of types even if it may be annoying.

**Comment by sffc** [comment]
I would argue that the concept of a "script" is different than either a Script Subtag or a Script Property.

A principled approach would be to introduce a new `Script` type with a private inner representation. The type can have conversions to and from both `subtags::Script` and `properties::Script`. This new type would also have a function to get the script directionality.

However, I'm not convinced at this time that we have a clear need for that type, nor do I have an idea where such a type would live. Therefore, I tend to think that we should keep the two types context-specific and just focus on the conversion between them.

**Comment by Manishearth** [comment]
I generally agree. I'm not really sure I can see any way a third type would make sense, but I think having the split is somewhat valuable, provided it's easy to convert.

**Comment by sffc** [comment]
@robertbastian to leave a comment suggesting what else to be done and then add to meeting agenda

**Comment by robertbastian** [comment]
- @sffc As I posted on the thread: "I want these conversions to exist. I'm not sure about putting them in a From impl (which is not super discoverable) and furthermore making the From impl gated on a non-obvious feature."
- @robertbastian It'll tell you if you need to enable a feature, no?
- @Manishearth The trait resolver might not figure that out
- @Manishearth We could just generate this; why do we need data?
- @robertbastian - then we'd duplicate the data. using properties without compiled_data is not a very common use case
- @sffc I think making the function data-driven is fine and maintainable
- @Manishearth Or we could use data when available, and generate the code if compiled_data is not enabled
- @robertbastian I don't like that. It causes drift
- @manishearth I feel like that wouldn't be a big deal. But yes, it's annoying. I'm also fine with a gated From impl.
- @sffc Generating multiple versions of this functions seems like a complex solution for a uncommon problem
- @sffc I'd prefer making these functions instead of From impls due to discoverability. If we insist on making them From impls for ergonomics, then we should add docs on the type.
- @manishearth why not just doc the From impl
- @sffc IME that doesn't show up always.
- @Manishearth It's borderline being something to document on the type anyway, so putting it on the type is fine.
- @sffc And why not implement it as a function?
- @robertbastian I've seen code that is bound on `From<Script>` for example.
- @Manishearth In my experience I look first for `From` impls.

Conclusion: implement `From`, and make sure that the impl being gated on the feature is well documented and discoverable on the docs page
