### ISSUE TITLE
Should we have a fallible Writeable?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4741]
Our `.format` functions are generally low-cost, pushing all business logic to the stage when we have a `sink` available. Unfortunately, this means that these code paths cannot have any errors. Currently we convert the `DateTimeError` to a `core::fmt::Error`, but this is wrong because it makes `ToString` panic.

We could implement a trait such as

```rust
pub trait WriteableWithError {
    type Error;
    pub fn write_to_with_error(&self, sink) -> Result<(), Self::Error>
}
```

(or an enum between core::fmt::Error and Self::Error)

**Comment by robertbastian** [comment]
This will be a pain for components like list formatter that take Writeables as inputs. I like the current model because you can pass around Writeables and don't have to deal with errors from other domains, figure out what a good replacement value would be, etc. Once you create the Writeable it will work.

**Comment by sffc** [comment]
Letting clients choose how to handle their errors seems beneficial. The `WriteableWithError` can have functions like

- `as_panicky()` returning a `Writeable` that either panics or returns `core::fmt::Error`s. This can go on the trait and be default-impl'd.
- `validate()` returning a `Result<Writeable>` that checks the error condition. This would be specific to the concrete type implementing `WriteableWithError`.

**Comment by sffc** [comment]
I guess we could also do this only in the datetime crate without making a trait, and we can make it into a trait later.

**Comment by robertbastian** [comment]
I don't think we should ever panic implicitly through `core::fmt:Error`, that is violating the trait interface. So you might as well pass around a `Result<Writeable, Error>` if you want to unwrap later.

**Comment by sffc** [comment]
This comes up again in the named placeholder pattern. The map of placeholder keys to values may or may not have all of the required placeholders. Checking it in the constructor takes time and we still need unwraps or GIGO in the interpolate function.

**Comment by sffc** [comment]
Writing down some more thoughts:

- FallibleWriteable can have two default-implemented functions `.lossy()` and `.panicky()` that return wrappers referencing `&self` and perform one of the two behaviors
- The error associated type should implement `Writeable` and that impl is used in lossy mode
- The type implementing FallibleWriteable could also implement Writeable and use a debug-assert-or-lossy implementation. Not sure if this should be the default implementation or not.
- To support both lossy and panicky modes, I think we need a `.write_to_with_error_handler` function which causes two different behaviors to be used, one that returns early and the other that recovers and continues writing.

**Comment by sffc** [comment]
See https://github.com/unicode-org/icu4x/pull/4772 for an implementation of this.

**Comment by robertbastian** [comment]
I'd like to reconsider this statement: 

> Our .format functions are generally low-cost, pushing all business logic to the stage when we have a sink available.

We could very well do this the other way around. It might even be more natural, as once constructed a `FormattedDateTime` can be cheaply written multiple times. I don't really see a reason for deferring the logic until write-time.

**Comment by sffc** [comment]
The GIGO case can be written as follows since Rust 1.76 (a few characters shorter):

```rust
let _ = dtf.format(...).try_write_to(...)?
    .inspect_err(|e| debug_assert!(false, "{e:?}"));

```

https://doc.rust-lang.org/std/result/enum.Result.html#method.inspect_err

**Comment by sffc** [comment]
An issue I encountered while implementing this regarding `try_writeable_length_hint` and `try_write_cmp_bytes`: we agreed on the signatures above. However, I'm not sure we considered all of the implications. Should we

1. Keep the signatures approved above
2. Change the names to be without `try_` since they don't return a Result (this would be the same name as the Writeable functions, which is _probably_ fine since these aren't often called in user code)
3. Make the functions return `Result` which must return the same type of `Result` as `try_write_to` (both Ok or both Err for the same TryWriteable). Sub-option 3a, keep `writeable_length_hint` with a default impl. Sub-option 3b, remove the default impl of `writeable_length_hint`.
4. Make the functions return `Result` which can be less strict (okay for it to return `Ok`, but if it returns `Err`, then `write_to` must also return `Err`)
5. Change the signature to something different especially for `writeable_length_hint`, such as `-> Option<Result<LengthHint, Self::Error>>`

Note on point 4: the default impl of `writeable_length_hint` is `LengthHint::undefined()`. If we keep the default impl in TryWriteable to be `Ok(LengthHint::undefined())`, then the invariant in point 3 is broken.

Another note: it might be useful to detect early when a Writeable is in a failure state. It seems consistent with the design of Writeable for us to bail early if `writeable_length_hint` returns an error, rather than having that function conceal the error and only find out later when we call `write_to`.

@robertbastian @Manishearth

**Comment by robertbastian** [comment]
In favour of 2. I think it's an advantage that they would be the same names as on `Writeable`, types that implement both `Writeable` and `TryWriteable` seem weird.

**Comment by robertbastian** [comment]
Wait, why does `write_cmp_bytes` have a `write_` prefix? The other methods that start with `write_` do writing, it should have a `writeable_` prefix like or no prefix at all.

**Comment by sffc** [comment]
We haven't released `write_cmp_bytes` yet, so there could still be time to bikeshed this.

**Comment by robertbastian** [comment]
Why would it be `write_length_hint`? I can see `length_hint`, and `writeable_length_hint` to avoid conflicts with other `length_hints` from different traits, but the trait is `Writeable`, not `Write`.

**Comment by sffc** [comment]
Because all the other functions are called `write_`. I don't see a strong reason that `write_` needs to be only used when it is the active verb. It can also just be Writeable's method prefix.

**Comment by robertbastian** [comment]
We have voted on this: https://docs.google.com/document/d/1zm_pQsrO7kTBjHbtmoQiriFNedUyd1_AjJ2Um3u_kD4/edit?pli=1

**Comment by sffc** [comment]
aha, we did already vote... ok
