### ISSUE TITLE
Google Summer of Code: Good First Issues for ICU4X

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4760]
Always good to do:

- Write FFIs for things listed in https://github.com/unicode-org/icu4x/blob/main/ffi/capi/tests/missing_apis.txt
- Identify components that are lacking good benchmarks and add Criterion benches for them

If interested in ICU4X development:

- https://github.com/unicode-org/icu4x/issues/4167
- https://github.com/unicode-org/icu4x/issues/2588
- https://github.com/unicode-org/icu4x/issues/2445
- https://github.com/unicode-org/icu4x/issues/1946
- https://github.com/unicode-org/icu4x/issues/1665

Slightly harder starter issues for ICU4X:

- https://github.com/unicode-org/icu4x/issues/3004
- https://github.com/unicode-org/icu4x/issues/2118
- https://github.com/unicode-org/icu4x/issues/1258
- https://github.com/unicode-org/icu4x/issues/763
- https://github.com/unicode-org/icu4x/issues/746

If interested in Segmentation:

- https://github.com/unicode-org/icu4x/issues/4446
- https://github.com/unicode-org/icu4x/issues/3612

**Comment by 0saurabh0** [comment]
Aren't we supposed to work on this [repo](https://github.com/unicode-org/lstm_word_segmentation) for the ML segmentation project?

**Comment by sffc** [comment]
Yes, this issue is for ICU4X issues. Please refer to that repo for the ML segmentation project.

**Comment by sffc** [comment]
Closing because this is not actually an issue. We can re-open it next year!
