### ISSUE TITLE
`LineBreakStrictness::Anywhere` gives the wrong breakpoints for Arabic in `icu_segmenter`

### ISSUE THREAD

**Issue by asibahi** [unicode-org/icu4x#4771]
Hello.

I am aware this is probably a unicode spec issue, rather than a rust library issue, but I thought I would point it out regardless.

This is the minimal application I was using to test this behavior:

```rust
use icu_segmenter::{LineBreakOptions, LineBreakStrictness, LineSegmenter};
fn main() {
    let test = "الخيل والليل";

    let mut options = LineBreakOptions::default();
    options.strictness = LineBreakStrictness::Anywhere;

    let segmenter = LineSegmenter::new_auto_with_options(options);

    let breakpoints = segmenter.segment_str(test);

    for bp in breakpoints {
        println!("{bp}:  {}", &test[bp..]);
    }
}
```

This gives the following output:

```
0:  الخيل والليل
2:  لخيل والليل
4:  خيل والليل
6:  يل والليل
8:  ل والليل
10:   والليل
11:  والليل
13:  الليل
15:  لليل
17:  ليل
19:  يل
21:  ل
23:
 ```

as you can tell, it is breaking after every single letter, without respect to the letters' connections. However, as I am sure you are aware, the letters' connections are *not* optional. 

The output I expected is the following:

```
0:  الخيل والليل
2:  لخيل والليل
10:   والليل
11:  والليل
13:  الليل
15:  لليل
23:
 ```

Putting the break points across the visual boundaries of the letters. This is not the current orthodoxy, but any looser breaks than that and you'd be rendering the text illegible and unnatural.

Note: This is how old written manuscripts break their words.

**Comment by sffc** [comment]
@eggrobin

**Comment by eggrobin** [comment]
> I am aware this is probably a unicode spec issue, rather than a rust library issue

If it is an issue, it is a spec issue.
If it were a Unicode spec issue, I could perhaps help; but it is not a Unicode spec issue, it is a W3C spec issue.
See https://drafts.csswg.org/css-text-3/#valdef-line-break-anywhere. LineBreakStrictness::Strict comes straight from the Unicode Line Breaking Algorithm, but Normal and Loose are tailorings defined by CSS, and Anywhere is a set of rules defined by CSS and unrelated to the Unicode Line Breaking Algorithm (specifically, it would not be a conformant tailoring of the Unicode Line Breaking Algorithm, since it does not apply some of the non-tailorable rules).

**Comment by asibahi** [comment]
Thanks for the prompt replies.

Aside from manually adding spaces after separated letters, is there a setting I can use to get this behavior?

**Comment by eggrobin** [comment]
> Aside from manually adding spaces after separated letters, is there a setting I can use to get this behavior?

If you want to manually override the behaviour of the line breaking algorithm, you should use the character U+2060 WORD JOINER to suppress break opportunities, and U+200B ZERO WIDTH SPACE to add break opportunities; see the descriptions of Line_Break classes [ZW](https://www.unicode.org/reports/tr14/#ZW) and [WJ](https://www.unicode.org/reports/tr14/#WJ) in Unicode Standard Annex #&zwnj;14, “Unicode Line Breaking Algorithm”.

If you want to automatically insert U+200B where Arabic letters would be separated, you could write an algorithm to do so based on the Joining_Type property. See sub [“Joining Types”](https://www.unicode.org/versions/latest/ch09.pdf#G34453) in Section 9.2, “Arabic”, of _The Unicode Standard_.

**Comment by asibahi** [comment]
so, the way to do it is only manually. Which makes it indeed a spec issue :). Arabic words should never break in these positions the same way Korean syllables should not break mid-syllable.

Thanks for the help. I much appreciate it.

**Comment by sffc** [comment]
Thanks @eggrobin for the responses. Closing as out of scope.

**Comment by robertbastian** [comment]
I think this is actually an issue, see https://github.com/unicode-org/icu4x/issues/7932. We should use grapheme clustering for `::Anywhere`.

**Comment by asibahi** [comment]
> I think this is actually an issue, see [#7932](https://github.com/unicode-org/icu4x/issues/7932). We should use grapheme clustering for `::Anywhere`.

The individual Arabic letters are, as far as I understand it, considered separate graohemes, or that would make editing hell. Grapheme clustering in Arabic only considers vowel marks.

**Comment by robertbastian** [comment]
Well, not breaking around vowel marks would be an improvement already. CSS says

> A UA must use the extended grapheme cluster (not legacy grapheme cluster), as defined in UAX29, as the basis for its typographic character unit.

So using extended grapheme clustering brings us into compliance with the spec.

> However, the UA should tailor the definitions as required by typographic tradition since the default rules are not always appropriate or ideal—​and is expected to tailor them differently depending on the operation as needed.

This one is more complicated, but also optional. Do you know what browsers do here?

**Comment by sffc** [comment]
I checked Safari, Firefox, and Chrome. They all appear to break at the (extended) grapheme cluster boundaries. However, Chrome and Firefox preserves the Arabic rendering across lines (the last character on a line is still rendered as a joining character even if its joining character was moved to the next line); Safari re-renders them.

**Comment by robertbastian** [comment]
> Safari re-renders them

That seems to violate the spec: https://drafts.csswg.org/css-text-3/#word-break-shaping.
