### ISSUE TITLE
[Feature Request] Yoke: `get_mut`

### ISSUE THREAD

**Issue by Ddystopia** [unicode-org/icu4x#4773]
Hello, I really liked the idea of yoke. It has a lot of applications even beyond zero copy deserialization. For example, it allows kind of self referential structs - data can be yoked to some backing buffer, like vec, while having other structure. My use case some computation is required to get right references - some `split_at`, paddings etc. If there wasn't a need for a mutation of bytes inside buffer, yoke would've been a great choice. But use case requires to store mutable references, which is not feasible by current api. 

Is there a possibility of adding such a features? I can give a try to implement it too.

**Comment by sffc** [comment]
Such a function would be unsafe. Use with_mut instead. 

https://docs.rs/yoke/latest/yoke/struct.Yoke.html#method.with_mut

**Comment by Ddystopia** [comment]
I was unclear in what I was asking. Yes, `with_mut` would work as I would get mutable reference to the yokable, but `Yoke::attach_to_cart` gives `Deref::Output` so I can't store a mutable referece to the cart and then use it inside `with_mut`. 
Consider that code:
```rust
use yoke::{Yoke, Yokeable};

struct Foo {
    inner: Yoke<Mutator<'static>, Vec<u8>>,
}

#[derive(Yokeable)]
struct Mutator<'a> {
    inner: &'a mut [u8; 2],
}

impl Mutator<'_> {
    fn mutate(&mut self) {
        self.inner[0] = 99;
    }
}

fn main() {
    let mut foo = Foo {
        inner: Yoke::attach_to_cart(vec![77, 88], |buf| Mutator {
            inner: buf.try_into().unwrap(),
        }),
    };

    foo.inner.with_mut(|mutator| {
        mutator.mutate();
    });
}
```

**Comment by sffc** [comment]
The design of Yoke is that

```rust
#[derive(Yokeable)]
struct Mutator<'a> {
    inner: &'a mut [u8; 2],
}
```

should instead be

```rust
#[derive(Yokeable)]
struct Mutator<'a> {
    inner: Cow<'a, [u8; 2]>,
}
```

If you need to mutate the data, you mutate it in the yokeable, not in the cart.
