### ISSUE TITLE
Unexpected grapheme boundary with regional indicators (GB12)

### ISSUE THREAD

**Issue by anba** [unicode-org/icu4x#4780]
```rs
use icu::segmenter::GraphemeClusterSegmenter;

fn main() {
    let segmenter = GraphemeClusterSegmenter::new();
    let text = "🇺🇸🏴󠁧󠁢󠁥󠁮󠁧󠁿";

    segmenter
        .segment_str(text)
        .for_each(|i| println!("{}", i));
}
```

Reports the following break points:
``` 
0
4
8
36
```

which means "🇺🇸" is split into two graphemes, which should be disallowed per [GB12](https://www.unicode.org/reports/tr29/#GB12). 

CC: @aethanyc and @makotokato

---

Original bug report: <https://bugzilla.mozilla.org/show_bug.cgi?id=1890007>

**Comment by aethanyc** [comment]
This is fixed by #4536. Let me add the example as a test.
