### ISSUE TITLE
Move performance benchmark artifacts into /benchmark/perf instead of /dev

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#483]
This is a follow-up to #107. Now that there are multiple benchmarks, we should update the organization.

https://github.com/echeran/icu4x/blob/03b3486395ee1caa8970cc972c46c2ec40cd8ec7/.github/workflows/build-test.yml#L142

**Comment by sffc** [comment]
Punt to post-0.2 cleanup (April)
