### ISSUE TITLE
create Map interface for TupleVecMap

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#484]
There are a few instances in ICU4X PR code where HashMaps were converted to some linear data structure of tuples for optimization reasons. (IIRC, I think the optimization was for both time and space reasons, esp when the number of entries is small -- hashing takes time, and it requires allocating larger structures on the heap). ([ex1](https://github.com/unicode-org/icu4x/pull/242#discussion_r552292147), [ex2](https://github.com/unicode-org/icu4x/pull/242#discussion_r553238328)).

When using a vector of tuples, lookups need to use binary search. Instead, it would be nice to preserve the simpler Map abstraction over the backing data structure (vector of tuples) and perhaps reduce boilerplate code, too.

**Comment by sffc** [comment]
The other reason that we favored tuple_vec_map is because of code size.  Hashbrown (the library backing std hash_map) carries a lot of weight into the ICU4X binary, but a map interface on top of a Vec via binary_search is extremely small code.

**Comment by sffc** [comment]
I looked around and didn't find any existing crates that do exactly this.  There are some that are similar, like [`dict`](https://docs.rs/dict/0.1.5/dict/), but the idea here is that you store the actual key in the map, not the hash of the key.  Our assumption is that the key is small and has a fast comparison operation (like TinyStr).

**Comment by sffc** [comment]
Features that this data structure should have:

- `insert(k, v)`
    - O(n) in the general case, but could be amortized constant time if the key is at the end of the list
    - Use HashMap semantics for duplicate keys (update the value and return the old one)
- `remove(k)`
    - O(n) with same caveat as above
- `contains_key(k)`, `get(k)`, `get_mut(k)`, `entry(k)`
    - O(log n)
- `keys()`, `values()`, `iter()`
    - Returns iterator visiting keys/values/pairs
- Construct from iterator of key-value pairs
    - O(n^2) in the general case, but could be O(n) if the items are sorted
- Serde serialize and deserialize
    - How should we represent it?

How should we represent this structure in JSON?  It could be a map, or it could be a list of pairs.  Could we serialize/deserialize into both forms?

**Comment by sffc** [comment]
Also look at https://docs.rs/vec_map/0.6.0/vec_map/struct.VecMap.html.

**Comment by Manishearth** [comment]
It seems like std's `BTreeMap` is actually what we want here? BTreeMap uses `Ord` (no hashing), and the Rust implementation has a `B=6`, which means each node holds 11 entries. In other words, for `n <= 12`, it is for all intents and purposes, a `TupleVecMap`.

You can test this out ([playpen](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f25badde335bda9d5cf06d6574264022)):

```rust
use std::collections::BTreeMap;

fn main() {
    let mut map = BTreeMap::new();
    map.insert(1, true);
    map.insert(11, true);
    map.insert(3, true);
    map.insert(2, true);
    map.insert(4, true);
    map.insert(7, true);
    map.insert(5, true);
    map.insert(11, true);
    map.insert(6, true);
    map.insert(9, true);
    map.insert(8, true);
    map.insert(10, true);
    // map.insert(12, true);
    
    for i in 1..12 {
        println!("{:p}", &map[&i]);
    }
}
```

This will print out an adjacent list of pointers, until you insert the 12th element, at which point it gets split into two allocations.

A _slight_ wrinkle with `BTreeMap` is that `TinyStr` will use `str`'s `Ord` impl, but we can very easily write a wrapper that can take `TinyStrs` and use the underlying integer `Ord`.

Does this sound good? `BTreeMap` is a fair amount of code, but it will have the perf characteristics we want, and will be code we don't have to maintain.

**Comment by zbraniecki** [comment]
My only concern is how much of the binary size win from avoiding HashMap we'd lose by pulling in BTreeMap vs implementing a thin wrapper?

**Comment by Manishearth** [comment]
I suspect we don't win much on binary size, but we get a better perf win (since BTreeMaps can handle bigger inputs without starting to hit worst-case scenarios)

**Comment by zbraniecki** [comment]
Right, but the main point of using tuple-vec-map was to avoid pulling in code that will blow up binary size.

**Comment by Manishearth** [comment]
Ah, if binary size is the main goal, then yeah, I can write this. But if perf is the main goal we should just use BTreeMap
