### ISSUE TITLE
Improve FractionalSecond

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#485]
#445 introduced a placeholder for fractional seconds.  It should be improved by:

- [x] Enforce range limits on the values
- [X] Fully support in pattern formatting
- [x] Add to MockDateTime FromStr
- [X] Add to day period resolution logic (https://github.com/unicode-org/icu4x/pull/445#discussion_r570612228)

Things to keep in mind:

- Most formats for fractional seconds appear as `"s.SSS"`; however, the number of fractional seconds should be programmer-defined.
- See #565 for a previous attempt.

**Comment by JamesHinshelwood** [comment]
Hi, I would like to try tackling this issue if that is okay?

**Comment by sffc** [comment]
@JamesHinshelwood Sure!  I assigned the issue to you.

**Comment by sffc** [comment]
Before getting started, take a look at CONTRIBUTING.md:

https://github.com/unicode-org/icu4x/blob/master/CONTRIBUTING.md

I look forward to your contribution!  Let me know if you need any more help getting started.

CC @nordzilla @zbraniecki who have worked on this part of the code extensively and can help answer questions.

**Comment by dminor** [comment]
https://github.com/unicode-org/icu4x/pull/1801 partially addressed this. I'm working on a followup to address formatting and day period resolution.

**Comment by sffc** [comment]
Temporarily re-opening to resolve https://github.com/unicode-org/icu4x/pull/1813#discussion_r860139979

**Comment by dminor** [comment]
> Temporarily re-opening to resolve [#1813 (comment)](https://github.com/unicode-org/icu4x/pull/1813#discussion_r860139979)

I think it makes sense to handle millisecond support in a separate issue rather than blocking this one on it.

**Comment by sffc** [comment]
> > Temporarily re-opening to resolve [#1813 (comment)](https://github.com/unicode-org/icu4x/pull/1813#discussion_r860139979)
> 
> I think it makes sense to handle millisecond support in a separate issue rather than blocking this one on it.

That's fine; would you mind opening such an issue?

**Comment by sffc** [comment]
I filed https://github.com/unicode-org/icu4x/issues/1834
