### ISSUE TITLE
FixedDecimal `*ed` methods should be infallible

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4857]
This function is misleading:

```
pub fn concatenated_end(self, other: FixedDecimal) -> Result<Self, FixedDecimal>
```

In the error case, it returns `other`, but it still throws away `self`. It should probably return a tuple containing both FixedDecimals. It makes it tempting to write code such as `mantissa.concatenated_end(fraction).unwrap_or_else(|fd| fd)`, which is wrong because it promotes `fraction` when it should probably keep `mantissa` and throw away `fraction`.

I think we should delete this function since it is only sugar over `concatenate_end`, which is harder to use incorrectly.

**Comment by robertbastian** [comment]
For the datetime use case, I think it would be useful to have a `FixedDecimal` constructor that accepts `usize, usize` as the integer and fractional parts. Then we avoid this infallibility altogether.

**Comment by sffc** [comment]
> For the datetime use case, I think it would be useful to have a `FixedDecimal` constructor that accepts `usize, usize` as the integer and fractional parts. Then we avoid this infallibility altogether.

I don't think it solves the overlap issue.

**Comment by robertbastian** [comment]
I think it does. It would use `IntIterator::from(integer).chain(IntIterator::from(fractional))` and then shift the resulting `FixedDecimal` by `fractional.log10()`.

**Comment by sffc** [comment]
Hmm, that's quite clever. How does it handle these cases though?

- Seconds = 123, Nanoseconds = 20 (needs to know that there are leading zeros: easy enough)
- Seconds = 123, Nanoseconds = 4444444444 (same problem as we currently have: overlapping fields)

**Comment by sffc** [comment]
I wouldn't be opposed to implementing a `plus` operator that just performs a sum.
