### ISSUE TITLE
Experiment with putting most of potential_passthrough_impl in an cold function

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#4858]
`potential_passthrough_impl` starts with the remark
```
// This methods looks badly branchy, but most characters
// take the first return.
```

Experiment with delegating the rest of the function after the first check to a second function marked cold.

**Comment by sffc** [comment]
@hsivonen This looks like internal cleanup, correct? If it impacts data struct stability, we could do it sooner.

**Comment by hsivonen** [comment]
#5813 makes this moot.
