### ISSUE TITLE
Implement year-week calculations for formatting

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#488]
#445 introduced a placeholder structure for year-week calculations (week numbering within a year).  This logic is required for full UTS 35 compliance.  This issue is to track implementation of these calculations.

Suggested task list:

- [ ] Review UTS 35 for information on week calculations (week of month and week of year)
- [ ] Implement week calculations
- [ ] Add week formats as a new key in the datetime data provider
- [ ] Implement the formatting glue code to format the calculated week of month and week of year

**Comment by gregtatum** [comment]
As a follow-up to #480, this will need to handle adding the plural rules to skeletons. At the time of this writing, this would mean turning the second entry of the `SkeletonTupleV1` from a single pattern, to an enum of either a pattern, or a TupleVecMap of multiple patterns keyed by the plural form.

**Comment by Manishearth** [comment]
(@sapriyag is tracking 20%er work, adding her as an assignee. Unfortunately GH still doesn't let us assign non-org members to issues)
