### ISSUE TITLE
Remove DynamicDataProvider and expand methods into ExportableProvider

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#4881]
I'm pretty sure that we're not using DynamicDataProvider anywhere except in the bounds of ExportableProvider.

We should merge DynamicDataProvider and IterableDynamicDataProvider into ExportableProvider in 2.0.

**Comment by robertbastian** [comment]
I see `DynamicDataProvider` as a core provider type, it's the equivalent to `DataProvider` where the key is only known at runtime. In fact, `AnyProvider` and `BufferProvider` should be instantiations of `DynamicDataProvider` for `AnyMarker` and `BufferMarker`.

**Comment by robertbastian** [comment]
`DynamicDataProvider` currently unifies code between `BufferProvider` aka `DynamicDataProvider<BufferMarker>`, and `ExportableProvider`, aka `DynamicDataProvider<ExportMarker>`. Ideally it would also do this for `AnyMarker`, but this doesn't currently work with yoke.
