### ISSUE TITLE
Add Temporal CalendarDateDayOfYear to FFI

### ISSUE THREAD

**Issue by anba** [unicode-org/icu4x#4891]
Implementing [CalendarDateDayOfYear](https://tc39.es/proposal-temporal/#sec-temporal-calendardatedayofyear) is easier when [Date::day_of_year_info](https://docs.rs/icu/latest/icu/calendar/struct.Date.html#method.day_of_year_info) is available through the FFI.

**Comment by sffc** [comment]
Absolutely. There is a comment in allowlist.rs that says:

```rust
        // This is formatting internals, we do not expect people
        // to implement custom formatters over FFI
        "icu::calendar::Date::day_of_year_info",
```

but this doesn't take into consideration that this is the standard way to get the day of year in FFI. We should add that API regardless of whether we put the rest of `DayOfYearInfo` in FFI.
