### ISSUE TITLE
Option for am/pm format ?

### ISSUE THREAD

**Issue by wiiznokes** [unicode-org/icu4x#4935]
I would like to use this crate in the cosmic desktop environment, and there is a settings to choose between am/pm format and 24h.
It seems that this settings is not exposed as an option thought `DateTimeFormatterOptions`.

Is it planned ?

**Comment by robertbastian** [comment]
https://docs.rs/icu/latest/icu/datetime/options/preferences/enum.HourCycle.html

**Comment by wiiznokes** [comment]
Howsome! i confused with https://docs.rs/icu/latest/icu/datetime/fields/enum.DayPeriod.html#variant.AmPm

**Comment by sffc** [comment]
We respect the -u-hc Locale parameter, too.
