### ISSUE TITLE
Support for single types without context

### ISSUE THREAD

**Issue by wiiznokes** [unicode-org/icu4x#4937]
I need to translate the weekday in my app, but i can't use a specific date. It would be nice to leverage the already existing translation of icu for this.

Sorry if this it out of scope

**Comment by sffc** [comment]
In 1.x you can use https://unicode-org.github.io/icu4x/rustdoc/icu/datetime/options/components/struct.Bag.html#structfield.weekday

In 2.x you will be able to use https://unicode-org.github.io/icu4x/rustdoc/icu/datetime/neo_skeleton/enum.NeoDayComponents.html#variant.Weekday

**Comment by wiiznokes** [comment]
Yes but to translate this bag, i need to use the [format](https://unicode-org.github.io/icu4x/rustdoc/icu/datetime/struct.DateFormatter.html#method.format) function which take a specific date.

Or maybe i missing smtg
