### ISSUE TITLE
Feature-gate UTF8 and UTF16 normalization

### ISSUE THREAD

**Issue by kirawi** [unicode-org/icu4x#4988]
It reduces dependencies and compilation time.

**Comment by sffc** [comment]
It would remove `utf8_iter` and `utf16_iter`.

These are small dependencies that we use fairly widely  in icu4x.

**Comment by robertbastian** [comment]
`utf8_iter` can be removed at 1.79 MSRV because it gets added to the standard library: https://doc.rust-lang.org/std/primitive.slice.html#method.utf8_chunks

**Comment by hsivonen** [comment]
> `utf8_iter` can be removed at 1.79 MSRV because it gets added to the standard library: https://doc.rust-lang.org/std/primitive.slice.html#method.utf8_chunks

That's not the same thing. utf8_iter provides an API that's so close to `chars()` on `str` that macros that work on either.

**Comment by Manishearth** [comment]
Some points brought up in discussion:

 - `utf8_chunks` is not an acceptable replacement: it doesn't hav ereverse iteration or Results
 - We're okay with adding default features as a non-breaking change.
 - The codepaths here are _not_ shared: `str` iteration uses a more optimized path.
 - These crates are used in normalizer, collator, segmenter
 - These crates have unsafe

**Comment by Manishearth** [comment]
Litmus test: if the primary way of using the crate, or one of the primary ways of using the crate, uses APIs that don't pull in a dep, we may wish to consider feature gating, *especially* if it is unsafe. This is a per-crate call, not a global call: ixdtf may unconditionally use utf8_iter, but normalizer still can gate. This is not a per-*depenendency* decision.


Decision: Feature gating ill formed utf8 and utf16 in normalizer is something we can do. This is not something we *must* do (@manishearth will probably do it at some point). Let's call the features: utf8_iter, utf16_iter unless someone can come up with better names. We could consider a similar approach for other crates, but for now we agree to do it for icu_normalizer.

Agreed: @manishearth @sffc @hsivonen @nekevss

**Comment by hsivonen** [comment]
Making UTF-16 support optional makes not only utf16_iter optional but also write16.
