### ISSUE TITLE
Fallback option for South East Asian line breaking?

### ISSUE THREAD

**Issue by Jules-Bertholet** [unicode-org/icu4x#5023]
[`LineSegmenter`](https://docs.rs/icu_segmenter/latest/icu_segmenter/struct.LineSegmenter.html) currently offers the choice of the LSTM machine learning data or a word list for handling complex South East Asian Scripts. However, there is no obvious way to get the fallback behavior of treating all SA characters as AL (as suggested by [UAX 14](https://www.unicode.org/reports/tr14/#SA)). Would it be possible to provide this with `LineSegmenter::new_no_sea()` or similar?

**Comment by sffc** [comment]
Duplicate of https://github.com/unicode-org/icu4x/issues/3612?

**Comment by Jules-Bertholet** [comment]
Ah yes, that issue should probably have the word "line" in it somewhere so it shows up in search
