### ISSUE TITLE
Panic while formatting date in beta and nightly compilers

### ISSUE THREAD

**Issue by Nerixyz** [unicode-org/icu4x#5039]
The following code panics while handling a panic in beta and nightly versions of Rust:

**main.rs**:

```rust
use std::str::FromStr;

use icu_calendar::Date;
use icu_datetime::{options::length, DateFormatter};
use icu_locid::Locale;

fn main() {
    let locale = Locale::from_str("en-u-ca-japanese").unwrap();
    let formatter = DateFormatter::try_new_with_length(&locale.into(), length::Date::Full).unwrap();
    let date = Date::try_new_iso_date(2020, 5, 30).unwrap().to_any();
    dbg!(formatter.format_to_string(&date).unwrap());
}
```

**cargo.toml**
```rust
[package]
name = "bar"
version = "0.1.0"
edition = "2021"

[dependencies]
icu_datetime = { version = "1.5.1", features = ["std"] }
icu_calendar = { version = "1.5.1", features = ["std"] }
icu_locid = { version = "1.5.0", features = ["std"] }
```

**output**:

```text
panicked at library\core\src\fmt\mod.rs:2431:38:
thread panicked while processing panic. aborting.
error: process didn't exit successfully: `target\debug\bar.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```
([library\core\src\fmt\mod.rs:2431:38](https://github.com/rust-lang/rust/blob/0c960618b56f662d933e8b864cd9632a99174e87/library/core/src/fmt/mod.rs#L2431))

It's not really easy to debug, but it seems like the original panic is because of [this debug_assert failing](https://github.com/unicode-org/icu4x/blob/8a229de164a02cd059d7709441b3677871fd6aef/components/datetime/src/format/datetime.rs#L137) and the next panic seems to happen while trying to format [`icu_calendar::Era`](https://github.com/unicode-org/icu4x/blob/8a229de164a02cd059d7709441b3677871fd6aef/components/calendar/src/types.rs#L26-L28) - so the original error was probably [`DateTimeWriteError::MissingEraSymbol`](https://github.com/unicode-org/icu4x/blob/8a229de164a02cd059d7709441b3677871fd6aef/components/datetime/src/format/datetime.rs#L298-L300). In release mode, this causes invalid UTF-8 to be written, because the era is wrong (from debugging I noticed it seems to be garbage - at least until the next nul).

---

[`test_japanese`](https://github.com/unicode-org/icu4x/blob/8a229de164a02cd059d7709441b3677871fd6aef/components/datetime/tests/datetime.rs#L782-L785) panics on nightly as well (when changing the toolchain in `rust-toolchain.toml` to nightly).

---

Update: It seems like rustc decided to swap the order of the tuple elements inside [`dates_to_eras`](https://github.com/unicode-org/icu4x/blob/90727cc0cb8f75194939323f8805f9c320f71d86/components/calendar/src/provider.rs#L124), so it thinks the string comes first, but that one [doesn't contain valid UTF-8](https://github.com/unicode-org/icu4x/blob/90727cc0cb8f75194939323f8805f9c320f71d86/provider/data/calendar/data/macros/calendar_japanese_v1.rs.data#L14C268-L14C298).

**Comment by Manishearth** [comment]
I'm surprised this wasn't caught by our CI

The test I've been using to check this is

```
use icu::calendar::{AnyCalendar, DateTime, Time};
use icu::datetime::{options::length, DateTimeFormatter};
use icu::locale::locale;
use writeable::Writeable;

fn main() {
    let locale = locale!("en-u-ca-japanese").into(); // English with the Japanese calendar

    let calendar = AnyCalendar::new_for_locale(&locale);

    let iso = DateTime::try_new_iso_datetime(2020, 10, 5, 13, 33, 15).unwrap();
    let datetime = iso.to_calendar(calendar);
    let options = length::Bag::from_date_time_style(length::Date::Full, length::Time::Short);

    let dtf = DateTimeFormatter::try_new(&locale, options.into())
        .expect("Failed to create DateTimeFormatter instance.");
    let manual_value = dtf
        .format(&datetime)
        .expect("Calendars should match");
    let s = manual_value.write_to_string();
    println!("{:?}", s);

    assert_eq!(s, "Monday, October 5, 2 Reiwa, 1:33 PM")
}
```

**Comment by Manishearth** [comment]
> [`test_japanese`](https://github.com/unicode-org/icu4x/blob/8a229de164a02cd059d7709441b3677871fd6aef/components/datetime/tests/datetime.rs#L782-L785) panics on nightly as well (when changing the toolchain in `rust-toolchain.toml` to nightly).

@robertbastian would you be able to verify why the nightly CI didn't catch this?

**Comment by Manishearth** [comment]
```
[cargo-make] INFO - Running Task: set-ci-toolchain
forced-toolchain environment not required 
```


in both scheduled CI jobs https://github.com/unicode-org/icu4x/actions/runs/9501131062/job/26185924275 , https://github.com/unicode-org/icu4x/actions/runs/9501092498/job/26185787376

I know we tweaked how the nightly toolchain got set a bunch of times, I suspect we broke it?

**Comment by Manishearth** [comment]
June 27


- - Filing rustsec issues triggers linting for clients. The nature of the issue in zerovec is of the same nature as other rustsec type issues.
- @sffc - I agree, it's the right thing to do and shows that we are good stewards
- - OK

LGTM: @sffc, @robertbastian , @Manishearth

**Comment by robertbastian** [comment]
Tracking rustsec

**Comment by robertbastian** [comment]
https://github.com/rustsec/advisory-db/pull/1990
