### ISSUE TITLE
Rename "master" to "main" 

### ISSUE THREAD

**Issue by alolita** [unicode-org/icu4x#505]
Hi ICU4x maintainers, Please rename "master" to "main" for https://github.com/unicode-org/icu4x/tree/master in accordance with GitHub's recommendation to promote inclusivity on our project. It should take no more than 5 minutes. Here are some guidelines - see: https://github.com/github/renaming#renaming-existing-branches Thanks!

**Comment by gregtatum** [comment]
This will need to be coordinated with the GitHub Actions, as they reference the master branch on deciding what to run.
