### ISSUE TITLE
Consider moving CLDR transformers into component crates?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#511]
Right now we have all the transformers in `icu_provider_cldr::transform`.  Should we consider moving those into the component crates instead?

Pros:

- Code for each component is in one place
- Easier for users of a component to plug in CLDR JSON

Cons:

- The transformer requires a lot of dependencies, which could be mitigated by having a feature flag, but it is still a lot more stuff to add to Cargo.toml
- Future changes to CLDR structure require changes globally instead of inside one crate
- Less general for future sources of data that are not CLDR
- Less-centralized transformer code could lead to divergent implementations

I favor keeping things the way they are and would like to close this issue.

**Comment by dminor** [comment]
Personally, I like the status quo and would prefer keeping everything together in the provider_cldr crate. The point about divergent implementations is a good one, and having everything together made it a lot easier for me as a newcomer to handle the likely subtags data.

**Comment by zbraniecki** [comment]
I'm in favor of keeping status quo.

**Comment by sffc** [comment]
Great; I will close the issue then.
