### ISSUE TITLE
`cargo install icu4x-datagen` fails

### ISSUE THREAD

**Issue by lynn** [unicode-org/icu4x#5166]
I'm trying to follow [this tutorial](https://github.com/unicode-org/icu4x/blob/main/tutorials/data_management_interactive.md), but the `cargo install icu4x-datagen` command fails.

```console
$ cargo install icu4x-datagen
    Updating crates.io index
error: there is nothing to install in `icu4x-datagen v0.0.1`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency to a Cargo project with `cargo add`.
```

Looking at the latest change to that file, 5f8de9c5af959ef3436f964f083eff60dfd1916a, I learned that I actually had to run `cargo install icu_datagen` to get the `icu4x-datagen` binary, at least as of right now.

**Comment by lynn** [comment]
I also had to replace `--markers` with `--keys` in the subsequent commands.

Maybe the tutorial should include an invocation of `icu4x-datagen --version` (I see `icu4x-datagen 1.5.0`).

**Comment by robertbastian** [comment]
The tutorial refers to code at head, which hasn't been released. Please follow the tutorials in the [`release/1.5`](https://github.com/unicode-org/icu4x/tree/release/1.5) branch for now.
