### ISSUE TITLE
Mismatched icu_capi local and upstream bindings

### ISSUE THREAD

**Issue by jiyuntu-google** [unicode-org/icu4x#5175]
My package depended on icu_capi v1.5.1, so I set it as a dependency in my `Cargo.toml` and built the code. Then I found that the c/cpp headers in `$(cargo metadata --format-version 1 | jq '.packages[] | select(.name == "icu_capi").manifest_path' | xargs dirname)/bindings` were very different from the upstream code. Attached are files I got locally. Are they expected to be different from upstream?
[datetime.rs.txt](https://github.com/user-attachments/files/16096679/datetime.rs.txt)
[diplomat_runtime.h.txt](https://github.com/user-attachments/files/16096641/diplomat_runtime.txt)
[ICU4XFixedDecimalFormatter.h.txt](https://github.com/user-attachments/files/16096645/ICU4XFixedDecimalFormatter.txt)

**Comment by robertbastian** [comment]
Yes this is expected, the repo is currently making breaking changes which we'll release as ICU4X 2.0 this summer.
