### ISSUE TITLE
Align Locale::is_empty, LanguageIdentifier::is_empty, and DataLocale::is_und

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#5199]
Follow-up to https://github.com/unicode-org/icu4x/pull/5176#discussion_r1665956407

We have three similar functions which don't have consistent naming. We should bikeshed and implement in 2.0.

**Comment by sffc** [comment]
Some choices:

1. `is_default`
2. `is_empty`
3. `is_und`

- @robertbastian: `is_und` is nice because we document that fallback stops at the `und` locale, not at the default or empty locale. You call `locale.is_und()` to check if the iterator is done.
- @sffc: `is_und` is slightly ambiguous because `und-CA` contains the `und` subtag.
- @robertbastian: `is_empty` is not great because it's not a collection, like `Option` or `Vec` that contains something
- @sffc: `is_default` could work because all the fields are set to their default values, like `None`.
- @robertbastian: we have `::UND` constants, not `::EMPTY` constants (although we do implement the `Default` trait)

Recommendation:

1. Rename the stated functions to `is_default`
2. Add `pub const fn const_default()` functions to Locale, LanguageIdentifier, and remove `::UND`
3. Document that fallback stops at "the default locale" instead of the "`und` locale"

LGTM: @sffc @robertbastian 

Do you agree @zbraniecki?

**Comment by zbraniecki** [comment]
Aligned on `is_default()`. I suggest we shadow `default()` for our const constructor. I don't see a value in separating `const_default()` and `default()`.
My mental model is that customer would never be confused or try to distinguish between which default they're calling.
