### ISSUE TITLE
icu_compactdecimal 1.3 and 1.4 do not build with latest fixed_decimal

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#5200]
fixed_decimal 0.5.6 changed `CompactDecimal::exponent` to return u8 instead of i16

https://docs.rs/fixed_decimal/0.5.5/fixed_decimal/struct.CompactDecimal.html

https://docs.rs/fixed_decimal/0.5.6/fixed_decimal/struct.CompactDecimal.html

I think this is a positive change, but it breaks `icu_compactdecimal` versions 1.3 and 1.4.

I think I prefer fixing this by releasing `icu_compactdecimal` 1.3.x and 1.4.x with a `<= 0.5.5` version bound on fixed_decimal.

**Comment by sffc** [comment]
Ok? @Manishearth

**Comment by sffc** [comment]
I guess I could also release `icu_compactdecimal` 1.3.x and 1.4.x with a code change to use the new u8 functions.

**Comment by Manishearth** [comment]
Yes, I would do that instead, but really it feels like this means we should yank-and-break fixed_decimal

**Comment by sffc** [comment]
I want to turn the fewest cranks possible, and the fewest cranks is releasing `icu_compactdecimal` with a small patch that fixes the issue.

Yanking `fixed_decimal` due to the breakage is much more invasive:

- We release `fixed_decimal@0.6.0`
- All `icu_*` crates at 1.5 that have a dep on `fixed_decimal` need to be patch-released to use the new `fixed_decimal`
- Then we yank `fixed_decimal@0.5.6`
- `icu_compactdecimal@1.5.0` assumes the u8 functions, so we'd have to yank `icu_compactdecimal@1.5.0`, too
- And then hope that we thought of everything

**Comment by Manishearth** [comment]
Ah, this is 1.4 being broken. 

Yeah, okay, let's release `<=` revisions.

**Comment by Manishearth** [comment]
We may also need to yank older `icu_compactdecimal`? This is the kind of bound that may confuse cargo's resolver; i.e. `cargo update` may choose to update `fixed_decimal` but not `icu_compactdecimal`, which will be broken.

**Comment by sffc** [comment]
The issue is only observable when a client depends on `~1.3` or `~1.4` (as is the case in Unicode Conformance where we saw this).

**Comment by sffc** [comment]
With options 2 and 3, I don't propose yanking anything.

**Comment by sffc** [comment]
Done: https://crates.io/crates/icu_compactdecimal/0.2.4

Turns out I only needed to release 0.2.4 because both 1.3 and 1.4 depend on 0.2.x. (In 1.5 it was moved to icu_experimental)

**Comment by sffc** [comment]
@Manishearth to review my pushes to https://github.com/unicode-org/icu4x/tree/release/1.4 and then close this issue.

**Comment by Manishearth** [comment]
Pushes lgtm

**Comment by robertbastian** [comment]
Technically 0.5.6 was a breaking change. The impact to `icu_compactdecimal` has been mitigated, but we might have broken clients. We cannot actually do a major bump, because `FixedDecimal` is part of the `icu` API through `FixedDecimalFormatter::format`, as well as through `icu_capi`. So I think we might want to revert the change.
