### ISSUE TITLE
Combine icu4x-gen-testdata and icu4x-cldr-export

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#525]
We have two separate binaries that do similar things, and they continue to converge closer and closer in functionality.  Now that we have cargo-make to perform build-time command line argument manipulation, I think we should combine the two tools in order to reduce code duplication.

**Comment by gregtatum** [comment]
I would like to request as part of this work to create the following CLI commands that can be run from the root folder. I find it takes me awhile to find the right place to run these while working on the testdata.

`cargo gen-testdata json`
`cargo gen-testdata bincode`
