### ISSUE TITLE
`icu_capi` builds a lib instead of a staticlib

### ISSUE THREAD

**Issue by ajtribick** [unicode-org/icu4x#5265]
I was trying to get icu4x to work with CMake and [Corrosion](https://github.com/corrosion-rs/corrosion). This would end up looking like:

```cmake
include(FetchContent)

FetchContent_Declare(
    Corrosion
    GIT_REPOSITORY https://github.com/corrosion-rs/corrosion.git
    GIT_TAG v0.5)

FetchContent_Declare(
    icu4x
    GIT_REPOSITORY https://github.com/unicode-org/icu4x
    GIT_TAG icu@1.5.0)

FetchContent_MakeAvailable(Corrosion)
FetchContent_MakeAvailable(icu4x)

corrosion_import_crate(
    MANIFEST_PATH "${icu4x_SOURCE_DIR}/Cargo.toml"
    CRATES icu_capi)

set_target_properties(
    icu_capi
    PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${icu4x_SOURCE_DIR}/ffi/capi/bindings/cpp")
```

Unfortunately this fails at `corrosion_import_crate` because icu_capi does not specify `crate-type` in its Cargo.toml file, so it ends up building a `lib` rather than a `staticlib`. This also means that Corrosion cannot see the crate as importable into CMake.

This can be fixed by adding the relevant section to the Cargo.toml:

```toml
[lib]
crate-type = ["staticlib"]
```

**Comment by robertbastian** [comment]
> This can be fixed by adding the relevant section to the Cargo.toml:

It cannot unfortunately. Take a look at our tutorial which explains how to build the `staticlib`: https://github.com/unicode-org/icu4x/blob/main/tutorials/cpp.md#:~:text=You%20can%20now%20build%20a%20staticlib%20with%20the%20following%20command%3A

**Comment by robertbastian** [comment]
We used to have a crate `icu_capi_staticlib` that wraps `icu_capi` and sets the type to `staticlib`, we believe the solution in the tutorial is sufficient, if it's not for your use case please let us know.
