### ISSUE TITLE
Compute binary prop ResourceKey subcategory string like for enum props

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#536]
The latest changes in #448 have changed the way that the Tinystr16 for the ResourceKey's subcategory string is constructed for Unicode enumerated properties. Instead of concatenating the Unicode property's name and value alias strings, the numerical values of the corresponding Rust enums (aka enums' determinants) are combined instead, and this avoids the 16-char limit of Tinystr16. (Note: The subcategory string is used as the identifier for the `UnicodeProperty` that is returned from the DataProvider.)

This PR represents making a similar change for Unicode binary properties. That entails creating a Rust enum, a conversion function to go from Unicode alias string (which PPUCD parser will see) to the string identifier, and updating the static ResourceKey definitions accordingly.

**Comment by sffc** [comment]
Blocked on #537
