### ISSUE TITLE
Specify Rust enum values (discriminants) for all Unicode properties

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#537]
In ICU, the enum values for `ccc` / `Canonical_Combining_Class` (and the derived, ICU-internal properties `lccc` and `tccc`) are used directly for collation purposes.  PR #448 sets the Rust enum discriminants for those properties to match ICU's. This PR represents updating the discriminant value for the Rust enums for all of the Unicode properties to match the ICU values.

**Comment by sffc** [comment]
2021-03-18:

- @Manishearth: We should make tests to ensure that we are compatible with ICU4C
- @sffc: We need these for stability because (1) they are used in data provider keys, and (2) for FFI. It only makes sense to re-use the discriminant values from ICU4C instead of starting over.
