### ISSUE TITLE
Consider design around equality rules in PluralRules

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#540]
In https://github.com/unicode-org/icu/pull/1632, I wrote code to change the algorithm for the selection of compact notation plural forms. The problem is that we used to use the algorithm

1. Compute the plural form (from the 6 standard plurals)
2. If the data has an entry for that form, use it
3. Otherwise, fall back to other

But this algorithm doesn't accommodate itself well to the =0 and =1 "equality rules" (don't know exactly what to call them). The new algorithm I implemented basically adds two steps at the beginning:

1. If not an integer, skip to step 3
2. If there is a matching equality rule, use it
3. Compute the plural form (from the 6 standard plurals)
4. If the data has an entry for that form, use it
5. Otherwise, fall back to other

The reason I opened this issue is that this selection algorithm should live inside PluralRules or some other centralized location. Right now, PluralRules gives you the plural form and leaves it up to the caller to resolve it against their data. Instead, maybe PluralRules should take a number plus a map from plural form (include equality rules) to string, and return the best match string.

**Comment by aphillips** [comment]
I dunno. I thought plural rules currently implemented only the top algorithm---given a number, which rule keyword should fire---but doesn't pretend to be an implementation of a plural formatter. The equality rules (ICU calls these "explicit values" in documentation) are important, of course, but the selection algorithm depends on the the rules for the third step in your bottom algorithm, but not rules don't depend on understanding the plural structure being operated on (saving the complexity of parsing all the explicit values and setting them on the plural rules object). Does that make sense?

**Comment by sffc** [comment]
That makes sense.  I guess what I'm suggesting is that the plural selection algorithm should be built into the core library somewhere, and perhaps we should make it as visible and easy-to-use as the plural rules algorithm.  If we don't provide plural selection, then people will be prone to make mistakes like

```javascript
let pluralForm = number.getPluralForm();  // zero, one, two, few, many, or other
let result = data[pluralForm];
if (!result) {
    result = data["other"];
}
```

Put another way: what is the use case of returning the naked plural form?  The next step in the code, in my experience, is almost always going to be selecting a value based on that plural form.  If that's the main use case, then maybe we should build that into PluralRules.

**Comment by sffc** [comment]
2021-04-29:

- @mihnita: We could have a low-level API as well, but I feel strongly about the selection-style algorithm as being the most useful API. Without it, we're forcing users to do selection by hand. If a library forces all users to do something to get correct results, then that should be part of the libary.
- @zbraniecki: We should hash out equality rules more in MFv2.

Conclusion: Revisit before 1.0.

**Comment by sffc** [comment]
It's been 11 months since this was last discussed. We are now approaching 1.0. I'm adding back the "discuss" label so that we can revisit this and decide what to do for 1.0.

**Comment by sffc** [comment]
Revisit again in June 2022.

**Comment by sffc** [comment]
Discussion:

- @zbraniecki - I think the current API is sufficient for MF2.0
- @sffc - It seems like PluralRules is not useful on its own; a selection algorithm must be used.
- @zbraniecki - There may be multiple choices for selection algorithms.
- @sffc - It's a little bit unusual that the output of PluralRules cannot be used directly; it needs to feed into something else.
- @zbraniecki - I think we're moving in a direction where ICU will feed into more and more components.
- @zbraniecki - We could re-name `select`.
- @sffc - How about `category_for`.

LGTM: @robertbastian, @Manishearth
