### ISSUE TITLE
Should feature icu_provider/export be named icu_provider/datagen

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#5505]
We have the feature "datagen" everywhere.

I think icu_provider/export is basically the same meaning: it exports impls related to data generation.

Should we change the name of the feature?

@robertbastian @Manishearth

**Comment by robertbastian** [comment]
It's called export on `icu_provider`, `icu_provider_fs`, `icu_provider_blob`, `icu_provider_baked`, because it gates `ExportMarker`, `ExportableProvider`, `BlobExporter`, `FsExporter`, `BakedExporter`.

See https://github.com/unicode-org/icu4x/pull/5125 which was approved by you.
