### ISSUE TITLE
Remove the initial 0 length from VarZeroVec's representation

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#5516]
VZV's representation is `[length] [indices..]` where the `indices` array is the indices of each element in the data segment. Index 0 is always 0, we don't need to store this and can remove it.

See also: https://github.com/unicode-org/icu4x/issues/5240 and https://github.com/unicode-org/icu4x/issues/5378

**Comment by Manishearth** [comment]
Fixing this is a good warm up for figuring out how much work is involved in fixing https://github.com/unicode-org/icu4x/issues/5378

**Comment by sffc** [comment]
@Manishearth is currently working on a PR.
