### ISSUE TITLE
Move data provider code around in the repo

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#555]
Here are my latest thoughts on where things should go.

- `/components/provider` --> `/utils/provider`
- `/components/provider_*` --> `/providers/*`
- `/resources/testdata` --> `/providers/testdata`

Reasoning:

1. The number of providers is going to keep growing (static, web, cache, ...), so it makes sense to make a top-level directory for them
2. Many providers are not intended to be used at runtime, and segregating them may make it easier to reason about that
3. I put the main `icu_provider` crate under `utils` because it is not a provider in and of itself

**Comment by zbraniecki** [comment]
I'd suggest also to get `ffi` related modules to top-level directory like `ffi/capi` and `ffi/ecma_402`.
