### ISSUE TITLE
Document Rust features

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#556]
In PR #480 I had a lot of feedback around feature usage. It would be good to document the ideas behind how each of these work, and have a central document explaining them. The features need to be coordinated across the modules, and it would be good to have shared knowledge around them.

In particular I had a lot of confusion around `serialize_none`, in that I was assuming incorrectly that it meant "no serialization" while it really means "serialize the Option::None type". [There is also some discussion](https://github.com/unicode-org/icu4x/pull/480#discussion_r593451380) on the meaning of `serde` and `provider_serde`.

A quick scan of the code turns up these features:

### Used across components

provider_serde
serde
bench
serialize_none
erased
erased-serde
benchmark_memory

### Probably component specific

provider_fs/export
provider_fs/export-bin
testdata/metadata
testdata/icu4x-gen-testdata

**Comment by sffc** [comment]
provider_serde - Documented in #650 
serde - Documented in #650
bench - Documented in #650
serialize_none - Removed in #613 
erased - No longer exists
erased-serde - No longer exists
benchmark_memory - Documented in #631
provider_fs/export - Documented in #650 
provider_fs/export-bin - Documented in #650 
testdata/metadata - Documented in #650 
testdata/icu4x-gen-testdata - Documented in #650
