### ISSUE TITLE
Dart CI broken

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#5570]
Dart CI has been broken for a couple days

https://github.com/unicode-org/icu4x/actions/runs/10975088543/job/30474331089

```
  Failed to load "test/icu_test.dart":
  lib/src/lib.g.dart:180:7: Error: Couldn't find constructor 'ResourceIdentifier'.
  @meta.ResourceIdentifier('diplomat_alloc')
        ^^^^^^^^^^^^^^^^^^
  lib/src/lib.g.dart:185:7: Error: Couldn't find constructor 'ResourceIdentifier'.
  @meta.ResourceIdentifier('diplomat_free')
        ^^^^^^^^^^^^^^^^^^
  lib/src/lib.g.dart:811:7: Error: Couldn't find constructor 'ResourceIdentifier'.
  @meta.ResourceIdentifier('diplomat_buffer_write_create')
        ^^^^^^^^^^^^^^^^^^
  lib/src/lib.g.dart:816:7: Error: Couldn't find constructor 'ResourceIdentifier'.
  @meta.ResourceIdentifier('diplomat_buffer_write_len')
```

We pin Dart in CI, so I'm not sure why this is happening

https://github.com/unicode-org/icu4x/blob/886220f6d9f7f574d75580ca35ddaa4fae657ad2/.github/workflows/build-test.yml#L325C14-L325C29

**Comment by Manishearth** [comment]
https://pub.dev/packages/meta/changelog

> Renamed @ResourceIdentifier to @RecordUse.

**Comment by Manishearth** [comment]
@robertbastian should we be locking this package in ICU4X (since we use an unstable feature)? Or should we be not locking it in diplomat so we get updates early?

**Comment by mosuem** [comment]
We should have pinned meta to `1.15.0`, instead of automatically getting newer minor releases with the `^` syntax.

**Comment by mosuem** [comment]
Also, the we do need to record the symbol name. So we should introduce something like
```
import 'package:meta/meta.dart';

@meta.RecordUse()
class RecordSymbolName {
  final String symbol;

  const RecordSymbolName(this.symbol);
}

...


@RecordSymbolName('_icu4x_BidiInfo_destroy_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'icu4x_BidiInfo_destroy_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_BidiInfo_destroy_mv1(ffi.Pointer<ffi.Void> self);

```
This way, any instance of `RecordSymbolName` is recorded with it's fields, in this case only one field `symbol`.

But I don't know where to contribute this - probably diplomat? @robertbastian

**Comment by robertbastian** [comment]
The `symbol` field is already present on the `fii.Native` annotation - is there any way to avoid specifying it twice?

I don't think this should live in Diplomat, this is Dart FFI infrastructure.

**Comment by mosuem** [comment]
> The symbol field is already present on the fii.Native annotation - is there any way to avoid specifying it twice?

The symbol in the native annotation specifies the name of the symbol in the native library, the symbol in `RecordSymbolName` is what we want to record. `meta.RecordUse` is agnostic of what the user wants to record. So the answer is no, and that is by design.

There is an open question as to whether we want to add the `RecordUse` annotation to all `ffi.Native` calls by default, but this is future work.

> I don't think this should live in Diplomat, this is Dart FFI infrastructure.

I don't think I understand, so `class RecordSymbolName` should be added manually to `lib.g.dart`? But these files are generated by diplomat, or are they not?

**Comment by mosuem** [comment]
Ah, I see. It should not - users, in this case `package:icu4x`, can decide what they want recorded. We probably want something like `RecordSymbolName`. Other users might want different things - so it should definitely live in `package:icu4x`.

We could discuss if this is a general enough use case to warrant publishing it to other packages, but I don't think it's worth it. Doing it this way allows us to add other, more icu-specific information to be recorded as well in the future, such as the key (`icu_list` or `icu_datetime`).

**Comment by Manishearth** [comment]
We could have some generic way for Diplomat to accept additional metadata like this via attribute.
