### ISSUE TITLE
Prefer String over Cow<'static, str> in CLDR JSON structs

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#558]
In the review for #480 @sffc [stated](https://github.com/unicode-org/icu4x/pull/480#discussion_r593534335):

> Since the CLDR JSON is only ever created from serde::from_reader, these strings will never be static. Therefore, I think we should start using plain String in CLDR JSON structs (only in CLDR JSON, not in ICU4X JSON!)

I agree with this analysis, but would prefer it to be a follow-up to handle the entire file to use this practice, and document the reasoning for it.

**Comment by sffc** [comment]
My recommendation: CLDR JSON structs should be optimized for simplicity and code readability. Performance decisions should be focused on the ICU4X DataProvider structs. This means that in CLDR JSON structs, we can do these things that we can't do in ICU4X structs:

- HashMap or BTreeMap
- String
- More third-party libraries/plugins like itertools

Decision 2021-03-18: Go with this recommendation.
