### ISSUE TITLE
`BasicEmoji` is not a property

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#5588]
Currently, "Basic Emoji" is modeled as a property, but it's not really a property because it's not a binary or enum classification for a code point. Instead, it is defined as a set, and because properties induce sets, this works, but isn't really logically sound. "Basic Emoji" is also the only "property" that induces a `UnicodeSetData` instead of a `CodePoint[Set/Map]Data`.

Instead, let's call it what it is: an Emoji set. There are in fact 7 Emoji sets defined in TR51: https://unicode.org/reports/tr51/#Emoji_Sets, which we might want to support in the future.

**Comment by sffc** [comment]
If the 7 emoji sets are the only users of this type, I'm fine calling it EmojiSetData

**Comment by sffc** [comment]
Names for things (discussed with @sffc @Manishearth @robertbastian)

- struct EmojiSetData
- struct EmojiSetDataBorrowed
- trait EmojiSet
- struct BasicEmoji; impl EmojiSet for BasicEmoji

**Comment by Manishearth** [comment]
Noting that UTR 23 documents ["properties of strings"](https://www.unicode.org/reports/tr23/#PropertyStringsDefinitions), so it _is_ a property, but since BinaryStringProperty is ambiguous EmojiSet seems fine.
