### ISSUE TITLE
capi: Separate data loading from ICU4X APIs

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#560]
Followup of https://github.com/unicode-org/icu4x/pull/552

See https://github.com/unicode-org/icu4x/blob/68d6b2bdcfbf36c7d25848a71009a2159ea3d780/docs/research/wrapper_layer.md

We should improve our APIs to expose lower level "you do the data loading for me" APIs such that they can be exposed at the FFI level.

This is _technically_ possible already by writing one-off data providers that are capable of _only_ providing the data you have already loaded, but this is more of a hack.

There are two steps to this:

 - Add lower level construction APIs for `PluralRules`, etc which take in their required data objects
 - Expose these to the C API

**Comment by sffc** [comment]
Related: #663

**Comment by Manishearth** [comment]
This is currently blocked on all of the DataPayload refactorings (https://github.com/unicode-org/icu4x/issues/667)

**Comment by Manishearth** [comment]
Given the plans for async data providers we don't need to do this anymore
