### ISSUE TITLE
Do something with legacy skeleton datetime APIs

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#5611]
Currently they are behind the `feature = "datagen"` flag in icu_datetime. What should we do with them?

1. Leave as-is, potentially with a bit of documentation. Question: does `feature = "datagen"` mean unstable?
2. Move to icu::datetime::provider
3. Move to icu_provider_source, the only client
4. Make a new crate for it
5. Other suggestions?

@zbraniecki @robertbastian @Manishearth

**Comment by robertbastian** [comment]
I'd prefer 3 or 2. I think we should get rid of all the markers, so there's probably not much of an advantage of 2.

**Comment by Manishearth** [comment]
I agree, 3 or 2, preference for 3

**Comment by zbraniecki** [comment]
I prefer 2.

**Comment by Manishearth** [comment]
3, but 2 is also fine.

**Comment by sffc** [comment]
Given the code's fairly deep integration with other types that live in `icu_datetime`, I think I share a preference for 2.

**Comment by Manishearth** [comment]
That's a good argument in favor of 2, I like that. Seems like we're in consensus on 2?

**Comment by sffc** [comment]
I did option 2 in https://github.com/unicode-org/icu4x/pull/5744
