### ISSUE TITLE
Tracking issue: CLDR-14571 Add bcp47 data to CLDR JSON

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#562]
***This is the ICU4X tracking issue for https://unicode-org.atlassian.net/browse/CLDR-14571.***

I would like to access the data under bcp47, especially bcp47/timezone.xml, through CLDR JSON.

Suggested structure:

- Add a new directory under "cldr-core", parallel to "supplemental", called "bcp47"
- Add a file inside called "timezone.json"
- JSON structure such as:

```
{
  "keyword": {
    "tz": {
      "description": "Time zone key",
      "alias": "timezone",
      "type": {
        "adalv": {
          "description": "Andorra",
          "alias": "Europe/Andorra"
        },
        "aedxb": {
          "description": "Dubai, United Arab Emirates",
          "alias": "Asia/Dubai"
        },
...
```

**Comment by sffc** [comment]
@kipcole9 maintains the following JSON file:

https://github.com/elixir-cldr/cldr/blob/cldr39/priv/cldr/timezones.json

**Comment by sffc** [comment]
CC @nordzilla

**Comment by nordzilla** [comment]
@sffc would iit be more helpful to have the `key` be the IANA-like name, and the alias be the BCP-47 name?

e.g.

```
{
  "keyword": {
    "tz": {
      "description": "Time zone key",
      "alias": "timezone",
      "type": {
        "Europe/Andorra": {
          "description": "Andorra",
          "alias": "adalv"
        },
        "Asia/Dubai"": {
          "description": "Dubai, United Arab Emirates",
          "alias": "aedxb"
        },
...
```

I imagine my use case will be oriented more toward looking up the BCP-47 name from the IANA name, rather than the reverse of that.

**Comment by sffc** [comment]
That would be more useful, yes, but I think we should try to track the XML as closely as possible, and XML has the BCP-47 first.  We can always invert the map once we read it from CLDR-JSON.

**Comment by sffc** [comment]
The data has now been generated:

https://github.com/unicode-org/cldr-json/tree/wip-alpha3/cldr-json/cldr-bcp47/bcp47
