### ISSUE TITLE
Conditionally support zero-copy deserialization in ErasedDataProvider

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#563]
In #552, we decided to use ErasedDataProvider as the primary method of delivering data across FFI.  Currently, ErasedDataProvider requires structs to implement `Any`, which means they can't support zero-copy deserialization except for the static lifetime.

The only method that really *requires* `Any` is [`receive_erased`](https://unicode-org.github.io/icu4x-docs/doc/icu_provider/erased/trait.ErasedDataReceiver.html#tymethod.receive_erased).  We can figure out somewhere else for that method to live so that it doesn't unconditionally require the data struct to be `Any`.

CC @Manishearth

**Comment by sffc** [comment]
I think we can take the `ErasedDataReceiver` trait and split it in two pieces, one that requires `Any` and one that does not.  The version of the trait that does not require `Any` can be the one used by `ErasedDataProvider`, and then we support zero-copy deserialization.

**Comment by Manishearth** [comment]
That makes sense

**Comment by Manishearth** [comment]
Overall I'm a bit wary of doing too much zero-copy stuff over FFI, it's really hard to get zero-copy right in C/++ so these APIs may be of little value to expose.

**Comment by sffc** [comment]
#564

The refactor reduced the total number of lines.  It's something I've been wanting to do for a while actually.

The model for zero-copy deserialization over FFI is that you create a DataProvider on top that pre-loads a bunch of strings, and then just make sure that the DataProvider lives longer than any objects that are using data from it.  It shouldn't be terribly complicated, at least not until we introduce other variables like caches and async data.
