### ISSUE TITLE
Informal icu_calendar rereview

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#5632]
We changed a bunch of icu_calendar for 2.0, and still have some changes planned (https://github.com/unicode-org/icu4x/issues/4889)

Now is a good time to have another look at the API shape and do any necessary cleanups.

**Comment by Manishearth** [comment]
Thoughts:

 - Should the individual calendar modules all be organized under `icu_calendar::calendars::*`? They feel cluttered right now. We could reexport individual calendars into this module.
 - `WeekCalculator` could do with more docs
 - We're probably getting rid of DateTime, IsoHour, IsoMinute, IsoSecond, NanoSecond
 - We should change MonthInfo to use a FormattableEra code that can be numeric rather than an era code.

**Comment by Manishearth** [comment]
@sffc thoughts on the first bullet point?

**Comment by sffc** [comment]
Hmm, the word "calendar" is already in the crate name, but I agree it would be nice to put the calendars in their own namespace separate from Date and other types/traits.

Maybe `icu_calendar::cal::Buddhist`? (better than `icu_calendar::buddhist::Buddhist`)

**Comment by sffc** [comment]
> We're probably getting rid of DateTime, IsoHour, IsoMinute, IsoSecond, NanoSecond

We can get rid of DateTime, but we need Time, IsoHour, ... _somewhere_ because icu_datetime uses them

**Comment by Manishearth** [comment]
`icu_calendar::cal::{Buddhist, etc}` works for me.

I will also have the individual calendar modules live there, because the BuddhistDateInner (etc) types need to live _somewhere_

**Comment by sffc** [comment]
Thought: `icu_calendar::cal::Buddhist` and `icu_calendar::cal::scaffolding::BuddhistDateInner` (as exports only; actual types live in a file named `buddhist.rs`)

**Comment by Manishearth** [comment]
`scaffolding` wfm.

I think `any_calendar` should live at the top level though, as it does now.

**Comment by sffc** [comment]
I named it `scaffold` in #5690 since the style guide is to omit suffixes
