### ISSUE TITLE
Support short localized GMT format and GMT format with seconds

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#5638]
https://unicode.org/reports/tr35/tr35-dates.html#Using_Time_Zone_Names says:

> **Localized GMT format:** A constant, specific offset from GMT (or UTC), which may be in a translated form. There are two styles for this. The first is used when there is an explicit non-zero offset from GMT; this style is specified by the <gmtFormat> element and <hourFormat> element. The long format always uses 2-digit hours field and minutes field, with optional 2-digit seconds field. The short format is intended for the shortest representation and uses hour fields without leading zero, with optional 2-digit minutes and seconds fields. The digits used for hours, minutes and seconds fields in this format are the locale's default decimal digits:
>
> - "GMT+03:30" (long)
> - "GMT+3:30" (short)
> - "UTC-03.00" (long)
> - "UTC-3" (short)
> - "Гринуич+03:30" (long)

However, currently we only support the "long" format, and we don't support offsets with hours only (the spec doesn't say how to do that: presumably use FixedDecimalFormatter directly??) or hours, minutes, and seconds (although there are no examples of this in the spec, and the data has only hours and minutes).

2.0 to check if we need to add data to TimeZoneEssentialsV1. Otherwise, 2.x priority because ECMAScript will need this.

CC @robertbastian

**Comment by robertbastian** [comment]
I already have code for this.

**Comment by robertbastian** [comment]
> seconds (although there are no examples of this in the spec, and the data has only hours and minutes).

No timezone that I know of has a sub-minute UTC offset, so the "optional seconds" are never required (they're not in the pattern anyway).

> we don't support offsets with hours only (the spec doesn't say how to do that: presumably use FixedDecimalFormatter directly??)

My solution is to ignore everything between the hours and minutes field of the pattern. We need to use the pattern because it contains the +/- signs.

**Comment by sffc** [comment]
> > seconds (although there are no examples of this in the spec, and the data has only hours and minutes).
> 
> No timezone that I know of has a sub-minute UTC offset, so the "optional seconds" are never required (they're not in the pattern anyway).

But you can construct one and they are in Temporal

**Comment by robertbastian** [comment]
> (They were routinely used before trains were invented)

No time zone has ever been defined with a sub-minute offset to UTC. The local times that were used before international standardisation have a sub-minute offset to UTC, but they were defined as "the time at my observatory". All of this stopped being used *well before* the UNIX epoch (i.e. in late 19th/early 20th century), and while the TZDB shoehorns these time zones into UTC offsets, we have in multiple places made the decision that correctness before 1970 is not a goal of ICU4X.

> But you can construct one and they are in Temporal

Well, again, the patterns in CLDR don't include seconds. ISO patterns support seconds, localized formats don't.

**Comment by anba** [comment]
[Africa/Monrovia](https://github.com/eggert/tz/blob/e6258faabc7f896411492bcea35521cec651ac77/africa#L440-L443) has sub-minute offsets after 1970. (Not sure if that case is relevant here, though.)

**Comment by sffc** [comment]
How to reproduce sub-minute offset formatting in Chrome:

```javascript
new Intl.DateTimeFormat("en-US", {
  timeZone: "Europe/Amsterdam",
  dateStyle: "full",
  timeStyle: "full"
}).format(new Date(1800, 0, 1))
```

**Comment by robertbastian** [comment]
* Inconsistent with duration formatter (i.e. `.` separator in Serbian duration, but `:` in time zones)
* No seconds support
* Patterns control padding, however the spec prescribes padding already (2 digits for long and 0 for short)

**Comment by robertbastian** [comment]
Also for CLDR discussion, from #5656:
* Add strings for "Unknown Timezone" and "GMT+?"
