### ISSUE TITLE
What belongs in Cargo.toml include?

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#569]
Question (I'm mainly just curous): Why are benches included in the published artifact? I see this is done in the other Cargo.toml files as well. It seems like they wouldn't be needed in the published files, unless I'm missing something.

_Originally posted by @gregtatum in https://github.com/unicode-org/icu4x/pull/541#r597784547_

**Comment by sffc** [comment]
2021-03-25: @Manishearth made a case for including tests and examples, and was a bit fuzzy on benchmarks.  @Manishearth will go through the Cargo.toml files and make sure they are consistent for the 0.2 release on what is included in the artefacts.

**Comment by gregtatum** [comment]
Here are some guidelines for the way that Firefox includes vendored crates, which may be good to keep in mind:

https://firefox-source-docs.mozilla.org/build/buildsystem/rust.html#third-party-crate-dependencies

> Third-party dependencies for in-tree Rust crates are vendored into the [third_party/rust](https://searchfox.org/mozilla-central/source/third_party/rust) directory of mozilla-central. This means that a copy of each third-party crate’s code is committed into mozilla-central. As a result, building Firefox does not involve downloading any third-party crates.

> Third-party crate tests aren’t run, which means that large test fixtures will bloat mozilla-central. Consider working with upstream to mark those test fixtures with [package] exclude = ... as described [here](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields).

**Comment by Manishearth** [comment]
Posted https://github.com/unicode-org/icu4x/pull/635

**Comment by zbraniecki** [comment]
Are we sure we want to ship tests? Tests can be large, especially with fixtures. What's the value of shipping tests in the package?

**Comment by Manishearth** [comment]
So I've gotten repeated feedback from _packagers_ that they like to have working `cargo test`, even if it's just a subset, so that they can verify that packaging worked correctly. This is also true for other use cases where crates are vendored (e.g. monorepo-based workflows).  This feedback doesn't apply to benches.

If a crate is particularly large due to some tests we can individually work on excluding just those tests. But let's wait for someone to complain.

**Comment by zbraniecki** [comment]
I had feedback from Gecko devs that fluent-rs test dir is large. But yeah, let's handle it when we get that feedback.
