### ISSUE TITLE
Make scope more explicit in the charter

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#57]
The charter currently says:

> OmnICU will provide an ECMA-402-compatible API surface in the target client-side platforms

and:

> **What if clients need a feature that is not in ECMA-402?**
> Clients of OmnICU may need features beyond those recommended by ECMA-402. The subcommittee is not ruling out the option of adding additional features in the same style as ECMA-402 to cover additional client needs. The details for how to determine what features belong in OmnICU that aren't already in ECMA-402 will be discussed at a future time.

The caption in ecosystem.md says:

> This document tracks the crates that already exist in the ecosystem that cover functionality that we may wish to cover in OmnICU.

I added the word "may" in #41.

I think it's important that we be more explicit about the use cases that ICU4X is supporting.  This will guide our discussions, such as https://github.com/unicode-org/icu4x/pull/43#discussion_r413329507, when deciding whether a certain API or functional unit belongs in ICU4X.

We could start by making an explicit list of use cases that warrant APIs and functional units not covered by 402, and adding that list to the charter.  It might be best to do this on a case-by-case basis: if proposing a feature not explicitly sanctioned by the charter, then propose a change to the charter adding the corresponding use case to the charter, such that we can agree on that change in the subcommittee meeting.

@zbraniecki

**Comment by zbraniecki** [comment]
My initial position is that we should aim to support a set of needs required to make ICU4X a sufficient API for internationalization of a slim list of high-value products.
My list for that was:

* ECMA402 - basically all Stage 4 first, likely Stage 3/2 soon after or where it makes sense (for example for NumberFormat we could already include NF rev. 3 proposal)
* Gecko - needs listed in [ecosystem.md](https://github.com/unicode-org/icu4x/blob/master/docs/ecosystem.md)
* Fuschia - I expected Fuschia to review the list from `ecosystem.md` and add what's missing.

Gecko is strictly speaking a superset of ECMA402, but it also has needs related to layout, font management, language negotiation etc.
I would expect Fuschia needs to overlap with Gecko quite well and adding constrains mostly on cpu/memory, data providers etc. but I was open to more APIs being added.

**Comment by hsivonen** [comment]
> My initial position is that we should aim to support a set of needs required to make ICU4X a sufficient API for internationalization of a slim list of high-value products.

That should probably be qualified/clarified to operations that use the Unicode Database or CLDR. We already discussed that encoding conversions are out of scope. Gecko uses [encoding_rs](https://github.com/hsivonen/encoding_rs) and [chardetng](https://github.com/hsivonen/chardetng), which thematically overlap with ICU4C features but don't depend on either the Unicode Database or CLDR, so they don't need to be part of the ICU4X crate constellation.

**Comment by sffc** [comment]
First step: #59

**Comment by sffc** [comment]
With #59 checked in, reassigning this issue to @zbraniecki to curate the list of covered use cases.
