### ISSUE TITLE
Clarify, document, and enforce string types in data structs

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#571]
@gregtatum said in https://github.com/unicode-org/icu4x/pull/541/files#r597812794:

> We're only testing a subset of locale data available in the CLDR. This leads to some observations:
> 
> 1. The CLDR could currently contain data that breaks the assumption of what can be represented by a certain size. I think this is somewhat unlikely, but for the available formats work [I wrote a script to programmatically verify assumptions](https://gist.github.com/gregtatum/775379b393da798c7be172f31f954f3d#file-skeleton-variants-js).
>
> 2. Future CLDR data could contain data that breaks this assumption. I'm less concerned about this as we could bump the version and fix the problem. I don't think we have an automated solution to categorically detect any case of this happening. However, it would happen when some user manually generates the data. This risk seems somewhat low, and something we could fix on the fly.

We should consider having a standard way to recommend whether a field in a data struct is best as a `TinyStr`, `SmallStr`, or `Cow<str>`, in accordance with the style guide.

We should also at least document why we reached a decision on which string type to use.  @gregtatum also said:

> Suggestion: It would be nice to document the decision here on representing this and others with 8 bytes.

**Comment by gregtatum** [comment]
Another question I don't know the answer to, is what happens when TinyStr is too long in data providers?

**Comment by sffc** [comment]
> Another question I don't know the answer to, is what happens when TinyStr is too long in data providers?

If the ASCII strings are fixed length, choose between TinyStr4, TinyStr8, and TinyStr16.  If they are variable length, then you get into an interesting discussion of whether to use TinyStrAuto or fall back on Cow<str> or TinyString.

**Comment by sffc** [comment]
Blocked on #667

**Comment by sffc** [comment]
The enforcement should be handled by the new `#[icu_provider::data_struct]` annotation.

Action items remaining on this issue:

- [ ] Ensure the style guide is up to date
- [ ] Scrub ICU4X of remaining references to SmallStr and other obsolete mechanisms
