### ISSUE TITLE
Generate Priority Fallback logic for Preferences based on the marker INFO

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#5764]
> Ideally this should be generated as well. The way to do this would be to add the
> marker as a macro argument and branch on
> `<$marker>::INFO.fallback_config.priority`

_Originally posted by @robertbastian in https://github.com/unicode-org/icu4x/pull/5729#discussion_r1819608381_

**Comment by robertbastian** [comment]
I have code for this in https://github.com/unicode-org/icu4x/pull/5573/commits/f3f165756b6376128f080282155263505e9d7b50
