### ISSUE TITLE
# Example vs #Examples

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#580]
I noticed that our documentation remains fairly inconsistent in how we name the docstring section containing examples:

```
mozilla@mozilla:~/projects/icu4x (pattern_util)$ rg '# Example$' ./|wc -l
85
mozilla@mozilla:~/projects/icu4x (pattern_util)$ rg '# Examples' ./|wc -l
171
```

Looking at the stdlib all cases of the section that I can find are named `Examples`, and this is also what my intuition guides me toward - this is an examples section, not an example section.
The fact that in most cases we'll have just one example is what I believe causes the mistake, but doesn't justify it.

I'd love to suggest this to be consistently resolved in time for 0.2 and I'd like to ask contributors who are done with 0.2 to consider taking it to help us polish the docs.

**Comment by zbraniecki** [comment]
Actually - https://doc.rust-lang.org/core/num/struct.ParseFloatError.html

:(

**Comment by sffc** [comment]
I have a mild preference for singular "Example".  If there are multiple examples, then give them each their own header: "Example 1: Demonstrate Foo", "Example 2: Demonstrate Bar"

**Comment by sffc** [comment]
While we're on this subject, I wanted to ask about conventions for heading sizes.  `#` is an H1, and there should generally be only one H1 per page.  It looks like cargo-doc solves this problem by putting all the docs in a `<section>`, which according to the HTML standard is allowed to restart header counting.  I just wanted to verify if `#` is indeed the correct heading level to use.

**Comment by gregtatum** [comment]
I'm a bit concerned on making a decision on this and then enforcing it. This is a style nit that doesn't really affect the usage of the product. As far as I know, this isn't lintable with our existing tools. If there were a lint for it, I wouldn't mind, but I'd prefer not to give human feedback on maintaining this distinction.

**Comment by sffc** [comment]
Conclusion: Migrate to the `# Examples` heading, and allow crate authors to choose whether to add additional captions describing each example within that section.
