### ISSUE TITLE
How to get month names from specific locale

### ISSUE THREAD

**Issue by keepitupkitty** [unicode-org/icu4x#5801]
Hello, I am working on my project that involves date handling, I want to extract names of months from specific locale I use rust and I can't figure out if there's something like getShortMonths like it's in C++ icu

**Comment by sffc** [comment]
In the upcoming ICU4X 2.0, use the semantic skeleton API

https://unicode-org.github.io/icu4x/rustdoc/icu/datetime/fieldset/struct.M.html

```rust
use icu::calendar::Date;
use icu::calendar::Gregorian;
use icu::datetime::FixedCalendarDateTimeFormatter;
use icu::datetime::fieldset::M;
use icu::locale::locale;
use writeable::assert_try_writeable_eq;

let fmt = FixedCalendarDateTimeFormatter::<Gregorian, M>::try_new(
    &locale!("en").into(),
   M::long(),
)
.unwrap();
let dt = Date::try_new_gregorian(2024, 5, 17).unwrap();

assert_try_writeable_eq!(
    fmt.format(&dt),
   "May"
);
```

It looks like it didn't quite make it into the 1.5 snapshot, but 2.0-beta should be released this month.

If you need it in 1.5, use the old experimental skeleton API (removed in 2.0).

https://docs.rs/icu/latest/icu/datetime/options/components/index.html

**Comment by keepitupkitty** [comment]
Thank you!!
