### ISSUE TITLE
Add support for timezones to components::Bag

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#583]
Components bag #481 and time zones #533 are being worked on in parallel. After both initial implementations land, we need to make sure that time zones work with the components bag. Right now the support is being stubbed out with `TODO` statements.

**Comment by sffc** [comment]
@gregtatum: Please choose a milestone for this issue and assign it to that milestone. For example, do you plan to work on this in April, in May for 0.3, in June, or later?

**Comment by gregtatum** [comment]
This will require appendItems support for time zones. See bug #586.

**Comment by gregtatum** [comment]
Resolved with #845.
