### ISSUE TITLE
Modify patterns from a skeleton match to have the correct width

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#584]
https://unicode.org/reports/tr35/tr35-dates.html#Matching_Skeletons

>  * 2.6.2.1 Matching Skeletons
>    - TODO - Modify the resulting pattern to have fields of the same length. For example requesting
>      a skeleton "yMMMMd" can have a best match of ["yMMMd", "d MMM y"]. This pattern should
>      then be modified to use the requested length to produce a pattern "d MMMM y".
>      However, fields should not be changed from numeric to text.

This is a follow-up to #481. It blocks #272.

**Comment by gregtatum** [comment]
It looks like skeleton expansion has an implicit assumption in the data that the width expansion will happen for weekdays. There are almost no skeletons with multiple `E` symbols. I found a few exceptions, but they had custom skeletons to match against.

In Serbian there are only `E` symbols.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1588648/113428124-d5bbca00-939b-11eb-912c-51ced8e1d46a.png">

In Thai a few patterns have multiple `EEEE` fields, but they have a matching skeleton, so they would take priority:

`"GyMMMEEEEd": "EEEEที่ d MMM G y"`

**Comment by gregtatum** [comment]
2020-04-02: Most likely this behavior is a "compression algorithm" used by the CLDR behavior. There is some risk that it will produce garbage data. There is some investigation needed for what the proper behavior is, especially in regards to how ICU4C handles this.

Weekday clearly needs to be handled with the width expansion here.
It's unclear if this applies to every field, or just certain fields like months.
It may be possible to "expand the compression" on the CLDR processing side, and then re-compress in some other way on the ICU4X data provider side.

**Comment by sffc** [comment]
@gregtatum: Please choose a milestone for this issue and assign it to that milestone.  For example, do you plan to work on this in April, in May for 0.3, in June, or later?
