### ISSUE TITLE
Multiple versions of ICU4X in lockfile via `url` crate

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#5871]
Currently we have the `url` crate in our dependency tree via `icu_provider_source`, which causes us to pull in multiple copies of `icu4x`:

```
icu_provider_source v2.0.0-beta1 (/usr/local/google/home/sffc/projects/icu4x/provider/source)
├── calendrical_calculations v0.1.2 
...
├── icu v2.0.0-beta1 (icu4x/components/icu)
│   ├── icu_normalizer v2.0.0-beta1 (icu4x/components/normalizer) (*)
...
├── ureq v2.10.1
│   ├── url v2.5.4
│   │   ├── idna v1.0.3
│   │   │   ├── idna_adapter v1.2.0
│   │   │   │   ├── icu_normalizer v1.5.0
```

@Manishearth @hsivonen

**Comment by sffc** [comment]
Note that this is also in our main Cargo.lock file.

```
[[package]]
name = "idna_adapter"
version = "1.2.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "daca1df1c957320b2cf139ac61e7bd64fed304c5040df000a745aa1de3b4ef71"
dependencies = [
 "icu_normalizer 1.5.0",
 "icu_properties 1.5.1",
]
```

**Comment by hsivonen** [comment]
[ICU4X already is optional for `url`.](https://docs.rs/crate/idna_adapter/latest)

We could have a `cargo make` target that runs `cargo update; cargo update -p idna_adapter --precise 1.1.0` (or even `cargo update; cargo update -p idna_adapter --precise 1.0.0` if we only connect by host names that are known to be ASCII).

(Additionally, we only have this problem during the time window when `icu_normalizer` in the ICU4X repo is not API-compatible and semver-compatible with published `icu_normalizer`.)

**Comment by hsivonen** [comment]
Also, is this really a problem? Is building a non-ICU4X normalizer as part of building ICU4X better than building an older release of `icu_normalizer`? (Anyway, if we connect to known-ASCII hostnames only, we can do `cargo update; cargo update -p idna_adapter --precise 1.0.0` and not depend on any normalizer for this step.)

**Comment by hsivonen** [comment]
And one option is to use a git patch for `idna_adapter` in ICU4X's Cargo.toml: https://github.com/hsivonen/idna_adapter/commit/76e6d7a197e5c12e92edf4e038f6110ade35e5da

(I thought @robertbastian already did this but with a different revision of `idna_adapter` previously, so I'm suprisised that this issue got filed.)

**Comment by sffc** [comment]
> Also, is this really a problem?

It's not really a problem I guess; it was just surprising to me to find icu4x 1.5 in the dependencies of icu4x 2.0.

Patching the lockfile seems like an okay idea, or we could leave it.

**Comment by Manishearth** [comment]
ICU4X is still large, I'd rather have the smaller legacy dep, atleast until the adapter gets updated to 2.0.

**Comment by Manishearth** [comment]
> Anyway, if we connect to known-ASCII hostnames only, we can do cargo update; cargo update -p idna_adapter --precise 1.0.0 and not depend on any normalizer for this step

Yep. Open to that.

**Comment by sffc** [comment]
```
$ cargo update -p idna_adapter --precise 1.0.0
warning: ignoring `resolver` config table without `-Zmsrv-policy`
    Updating crates.io index
    Removing icu_collections v1.5.0
    Removing icu_locid v1.5.0
    Removing icu_locid_transform v1.5.0
    Removing icu_locid_transform_data v1.5.0
    Removing icu_normalizer v1.5.0
    Removing icu_normalizer_data v1.5.0
    Removing icu_properties v1.5.1
    Removing icu_properties_data v1.5.0
    Removing icu_provider v1.5.0
    Removing icu_provider_macros v1.5.0
 Downgrading idna_adapter v1.2.0 -> v1.0.0
    Removing litemap v0.7.3
    Removing tinystr v0.7.6
    Removing writeable v0.5.5
    Removing yoke v0.7.5
    Removing yoke-derive v0.7.5
    Removing zerofrom v0.1.4
    Removing zerofrom-derive v0.1.4
    Removing zerovec v0.10.4
    Removing zerovec-derive v0.10.3
```
