### ISSUE TITLE
Reduce number of enumerated binary properties

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#588]
We currently have 610 UnicodeSets that are returned by the uniset crate.  It's highly likely that we can cut out a significant chunk of them that have no use in regular expressions.  For example, we could omit all of the LEAD_CANONICAL_COMBINING_CLASS keys.  @echeran will investigate.

**Comment by sffc** [comment]
Dependency of #662

**Comment by sffc** [comment]
Ask: Figure out which binary properties are actually needed for regex.

**Comment by echeran** [comment]
(For some insight on catalog properties, see see notes in #589)

**Comment by sffc** [comment]
@iainireland posted this reference: https://tc39.es/ecma262/#table-binary-unicode-properties

**Comment by markusicu** [comment]
I understand that you want to provide at least the properties needed for ES regex, but it's not obvious to me that ICU4X should limit itself to those. Various developers might well need Bidi_Class or Numeric_Value etc.

ICU4X will omit data for properties that are not used, right?

**Comment by sffc** [comment]
I propose that we have APIs that:

1. Expose all *binary* properties as UnicodeSet.
2. Expose all *enumerated* properties as CodePointTrie.
3. Expose a UnicodeSet for each enumerated property value included in ECMA-262 (each value of General Category, Script, and Script Extensions).

I only propose that we do not have an API to return UnicodeSet for arbitrary enumerated property values.  For example, we do not need an API for "give me the set of all characters that have Canonical_Combining_Class=CCC22", and we should not create such APIs.  We could support more than the ECMA-262 list, but should have justification (use cases) that any additions are useful as a UnicodeSet as opposed to just CodePointTrie.
