### ISSUE TITLE
Use FixedDecimalFormat in DateTimeFormat

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#597]
In format.rs, there is a temporary function `format_number`.  This should be changed such that FixedDecimalFormat is used instead, providing locale-sensitive formatting of numbers.

**Comment by sffc** [comment]
To discuss: how should DTF load the data required by FDF, especially when we go async?

**Comment by sffc** [comment]
- @sffc: We should be able to make a DataProvider load_multi function.
- @Manishearth: load_two, load_three, ... would be better.
- @sffc: Could nested formatters send keys to parent formatters via a callback?

Conclusion: Move forward on the FDF integration. @sffc will come back later this quarter or early next quarter with more concrete recommendations on how to optimize the data loading for nested formatters.

**Comment by dminor** [comment]
I'm going to pick this up for ICU4X 1.0
