### ISSUE TITLE
Automatically run all examples in memory benchmark

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#611]
There is currently an includelist of examples in `build-test.yml`.  This list requires manual maintenance and is already stale.  However, it should be fairly easy to automatically run the memory benchmarks on all examples.

First, build all examples from the workspace root:

```bash
$ cargo build --all-features --examples
```

Then, get a list of all examples:

```bash
$ cargo run --example
error: "--example" takes one argument.
Available examples:
    code_line_diff
    elevator_floors
    filter_langids
    language_names_hash_map
    language_names_lite_map
    litemap_rkyv
    litemap_serde
    permyriad
    syntatically_canonicalize_locales
    tui
    unicode_bmp_blocks_selector
    unread_emails
    work_log
    writeable_message
```

Alternatively, if the above command output is not sufficiently stable, we can `ls target/debug/examples` with some filtering.

Once you have an example name, you can run it directly from the workspace root:

```bash
$ cargo run --all-features --example code_line_diff
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/examples/code_line_diff`
Feature
Added/Removed: -৫০/+৭২
Added/Removed: ০/+৩,৭৫০
Added/Removed: -১,২০১/০
Added/Removed: -৯,৮৭৬/+৫,৪৩২
Added/Removed: -৫০,০০,০০০/+৩০,০০,০০০
dhat: Total:     13,553 bytes in 51 blocks
dhat: At t-gmax: 8,973 bytes in 6 blocks
dhat: At t-end:  1,112 bytes in 3 blocks
dhat: The data in dhat-heap.json is viewable with dhat/dh_view.html
```

This should be very easy to automate using Duckscript in Makefile.toml.  We can put the automation there instead of *build-test.yml* so that users can reproduce the memory benchmarks locally.

CC @gregtatum

**Comment by gregtatum** [comment]
I believe `cargo_metadata` could also get at this information.

**Comment by sffc** [comment]
Here's another way to get the list that I stumbled upon yesterday:

```duckscript
cargo_output = exec cargo build --examples --message-format=json
trimmed_stdout = trim ${cargo_output.stdout}
json_messages = split ${trimmed_stdout} "\n"
for json_message in ${json_messages}
    json_obj = json_parse ${json_message}
    is_compiler_artifact = eq ${json_obj.reason} "compiler-artifact"
    is_example = eq ${json_obj.target.kind[0]} "example"
    if ${is_compiler_artifact} and ${is_example}
        echo "Running" ${json_obj.target.name}
        # Executable path is available in ${json_obj.executable}
    end
end
```

https://github.com/sffc/omnicu/blob/75a828e2a0167bff372a6547e66ea36d7ffb76e8/Makefile.toml#L303

**Comment by sffc** [comment]
@gregtatum Do you think you could take a look at this?

**Comment by gregtatum** [comment]
Sure, I've gotten a few things in my backlog, so if anyone else wants to take it before I get to it they can.

**Comment by sffc** [comment]
@gnrunge Can you take a look at this? I think it is fairly well scoped.

**Comment by gnrunge** [comment]
Will have more breathing room after ICU integration (April 20), will put on schedule G if possible.
