### ISSUE TITLE
Refactor Makefile.toml into smaller files

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#612]
Makefile.toml is currently a grab-bag of a lot of different build tasks, and it keeps growing.  It would be better if we could refactor separate parts of it into separate files that get included into the main file.

I believe that this would also enable us to use Duckscript functions, allowing us to reduce code duplication.

This could involve a new top-level directory named `build_scripts` or similar.

**Comment by dminor** [comment]
We should move README.tpl at the same time, in case people confuse it with an actual readme.

**Comment by sffc** [comment]
@dminor : `tools/scripts` ?

2021-05-07: GO with `tools/scripts`.

**Comment by sffc** [comment]
As part of this, I'd like to *fully* unify the tests run on CI with the ones in Makefile.toml.  We have taken great steps toward unifying them, but we still have the problem where a different subset of tests runs on CI versus what runs in Makefile.toml.

**Comment by sffc** [comment]
Splitting the Duckscript functions into https://github.com/unicode-org/icu4x/issues/785
