### ISSUE TITLE
Crate naming case convention

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#62]
I've seen both kebab case and snake case used in crate names.

Which convention do we want to adopt?

- `icu-locale`
- `icu_locale`

**Comment by Manishearth** [comment]
I typically find kebab-case to be more normal for crate names. It looks slightly nicer and it gets autoconverted to snake in rust code. Crates using snake are typically from the time when this autoconversion didn't occur.

**Comment by zbraniecki** [comment]
If I remember correctly, we talked about this on a weekly call and per Manish suggestion, settled on `icu-locale`. @Manishearth - can you confirm?

**Comment by Manishearth** [comment]
I think so yeah

**Comment by sffc** [comment]
I'm fine with adopting the kebab convention.  Can we document that decision, e.g., in the Rust Style Guide?

**Comment by Manishearth** [comment]
being discussed in https://github.com/unicode-org/icu4x/pull/48#discussion_r411554680

**Comment by sffc** [comment]
I believe this was fixed by #48.
