### ISSUE TITLE
ICU4X data structs don't actually borrow any data

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#632]
I discovered that even though we religiously use `Cow<'s, str>` and similar in our data structs, we are not actually benefiting from zero-copy deserialization, because the default implementation of `Deserialize` for `Cow<'s, str>` is to always use `Owned` data.  See a discussion here: https://github.com/serde-rs/serde/issues/1497

We need our structs to support zero-copy deserialization.  This requires adding `#[serde(borrow)]` to opt in where possible, keeping the following issues in mind: https://github.com/serde-rs/serde/issues/2016, https://github.com/serde-rs/serde/issues/723.

Unfortunately, if we make this change, it means that we will no longer be able to read from an `std::io::Read` when deserializing.  We must always load the buffer and then point into the buffer.  This *might* be an okay constraint for ICU4X, but I want to make sure we are explicit about it.

If we want to retain the ability to deserialize into a `'static`, we could add functions that flatten the lifetime on the data struct after we deserialize it from a borrowed buffer.

CC @Manishearth

**Comment by zbraniecki** [comment]
https://docs.serde.rs/serde_json/fn.from_reader.html

```
Note that counter to intuition, this function is usually slower than reading a file completely into memory and then applying from_str or from_slice on it. See issue #160.
```

The `ToOwned` is relatively easy for flat structs like `Vec<Cow>>` it becomes challenging for nested structs like `AST`.
In Fluent Rs I worked it around by making it generic over Slice and Slice is implemented for `String` or Cow`:
 - https://github.com/projectfluent/fluent-rs/blob/master/fluent-syntax/src/ast/mod.rs#L116
 - https://github.com/projectfluent/fluent-rs/blob/master/fluent-syntax/src/parser/slice.rs

**Comment by sffc** [comment]
2021-04-15: We are okay with the constraint that deserializers operating on `std::io::Read` will not work.  @Manishearth is investigating some of the upstream bugs.  I will work on the changes to ensure that we can achieve zero-copy deserialization on all of the existing data structs.

**Comment by sffc** [comment]
Closing this as a duplicate of #667
