### ISSUE TITLE
Add zero-copy string list data structure

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#637]
Splitting from #78

We should add a data structure for lists of strings that supports zero-copy deserialization.

Some requirements and nice-to-haves:

- Like UVec and Cow, it should have variants for Owned and Borrowed
- Should not support mutation; if you want to mutate, convert to a Vec<String> first
- Should be extensible to external string pools that own the string data (e.g., storing shared strings across locales)
- Should support not only strings but also other variable-length fields

A rough outline of this type would be

```rust
// Not exactly sure about this trait
trait AsVarULE {
    type Error;
    type Owned;
    fn validate_bytes(&[u8]) -> Result<(), Error>;
    fn from_validated_bytes(&[u8]) -> &Self;
    fn to_owned(&self) -> Owned;
}

/// I = width of index (1 for u8, 2 for u16, ...)
/// L = width of length (1 for u8, 2 for u16, ...)
struct ZeroCopyVarVec<'a, T, const I: usize, const L: usize>
where
    T: VarULE
{
    /// A list of indices into data_table and the length of the items in data_table
    index_table: &'a [(PlainOldULE<I>, PlainOldULE<L>)],
    // TODO: Is there a way to cast the data bytes to a special type, a la UVec?
    data_table: &'a [u8],
}

enum UVarVecInternal<'a, T>
where
    T: VarULE
{
    Owned(Vec<T>),
    Borrowed(ZeroCopyVarVec<'a, T>),
    // future variant: string pool
}

pub struct UVarVec<'a, T>
where
    T: VarULE
{
    internal: UVarVecInternal<'a, T>,
}
```

**Comment by Manishearth** [comment]
Current WIP at https://github.com/sffc/omnicu/compare/uvec...Manishearth:varzero?expand=1
