### ISSUE TITLE
Where to put crate-specific testing utils

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#657]
Follow-up to https://github.com/unicode-org/icu4x/pull/647#discussion_r614437789

Frequently it is useful to have functions or test data that you want to make accessible to integration tests and benchmarks.  Where should we put that data?  We could put it in public modules of the crate, but that clutters the API.  Hiding it behind `#[cfg(debug_assertions)]` isn't good because it makes the benchmarks and examples fail to compile in release mode.

**Comment by Manishearth** [comment]
We should use `#[cfg(test)]` on modules with testing code. Benches may need `#[cfg(or(test, bench))]`, unsure.

If we want examples to have access to the data we would have to do something like

```
#[path = "../src/samples.rs"]
mod samples;
```

**Comment by sffc** [comment]
We should scrub to make sure all testing utils are properly labeled according to @Manishearth's suggestion above across all of ICU4X.
