### ISSUE TITLE
Read Unicode property UnicodeSet data from ICU4C

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#662]
Instead of continuing to parse the PPUCD file directly and fix logic / perf issues (ex: #454), we want to replace that approach with directly reading UnicodeSet data for Unicode properties directly from ICU4C.

This will match the work for reading CodePointTrie data (#132) (as described in dupe issue #508).

**Comment by sffc** [comment]
Possible duplicate of #578
