### ISSUE TITLE
Add tutorial for building ICU4X data

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#664]
We have documentation scattered around a bit.  We should update the data_provider.md tutorial to document the full lifecycle of ICU4X data with a focus on clients of ICU4X.

Blocked on #78

**Comment by sffc** [comment]
The data build process for client Rust crates can be the following, based on discussion with @robertbastian:

1. build.rs invokes datagen with a list of keys and locales
2. An integration test verifies that the extracted keys are consistent with the keys that were passed to datagen

We may want to move toward a datagen.toml file that contains the list of keys, locales, CLDR version, etc., so that:

1. It can be read from both build.rs and the integration test
2. To better separate code (build.rs) and data (datagen arguments)

**Comment by robertbastian** [comment]
Fixed by #2678
