### ISSUE TITLE
Add borrowed-only versions of data structs in ZeroVec

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#676]
Part of https://github.com/unicode-org/icu4x/issues/1082

Depends on https://github.com/unicode-org/icu4x/issues/1078

zerovec is capable of supporting no_std, including no heap allocations.  To achieve this, we should make public versions of ZeroVec, VarZeroVec, and ZeroMap that are borrow-only.

Some caveats:

- Can we make ICU4X data structs no_std at the same time?
- How to avoid code duplication?

CC @Manishearth

**Comment by Manishearth** [comment]
Things I may work on, as an inverted dependency tree:

 - Support infinite nesting in VZV (VZVOwned) https://github.com/unicode-org/icu4x/pull/1065
    - make VZVOwned/Borrowed public
        - Add ZeroMapBorrowed (needed by staticdataprovider), fixes this issue
    - restrcuture AsVarULE to move as_unaligned (needed by zibi)
        - custom derive for AsVarULE and friends (not currently needed, probably won't work on just yet)
    - improve VZV's mutation ops

**Comment by Manishearth** [comment]
Some things to make requirements of the VarULE and ULE trait

- no padding bytes, all bytes are initialized (allows us to treat them as `u8` slices safely)
- equality is byte equality

**Comment by sffc** [comment]
> * no padding bytes, all bytes are initialized (allows us to treat them as `u8` slices safely)

+1

> * equality is byte equality (should AsVarULE require Eq?)

Yes, and we should also require that the parser reject any input that is not in canonical form.  For example, "1.00e3" and "10.0e2" are semantically equal, but only the former is in canonical form.

With these new constraints, can people implement ULE/VarULE without any unsafe code?  (Maybe except for a single "unsafe" on the trait impl to assert that all the constraints are satisfied.)

**Comment by Manishearth** [comment]
> With these new constraints, can people implement ULE/VarULE without any unsafe code? (Maybe except for a single "unsafe" on the trait impl to assert that all the constraints are satisfied.)

No because they both expose `unsafe fn` as well. I don't think this is a useful metric to optimize for.

**Comment by Manishearth** [comment]
Another potential improvement might be to get rid of AsVarULE entirely and have people directly use ULE types

**Comment by sffc** [comment]
Related: type structure for ZeroMap.  Removing AsVarULE requires making changes to the ZeroMap traits.  (Follow-up to https://github.com/unicode-org/icu4x/pull/1057#discussion_r709821567)

**Comment by Manishearth** [comment]
I moved the list of work items to https://github.com/unicode-org/icu4x/issues/1082. "Get rid of AsVarULE" is https://github.com/unicode-org/icu4x/issues/615

**Comment by Manishearth** [comment]
As a part of this we should make `make_mut()` public on `ZeroVec` (and perhaps rename both to `to_mut()`)
