### ISSUE TITLE
0.2 missing documentation

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#681]
I  audited the state of our documentation and collected views that I consider sub-standard quality:

| Done | component                | node                               | task                                           | reference |
|------|--------------------------|------------------------------------|------------------------------------------------|-----------|
|      | icu_decimal              | [FixedDecimalFormat](https://unicode-org.github.io/icu4x-docs/doc/icu_decimal/struct.FixedDecimalFormat.html)                  | add example                                    |  [DateTimeFormat](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/datetime/struct.DateTimeFormat.html)  |
|      | icu_decimal              | [format](https://unicode-org.github.io/icu4x-docs/doc/icu_decimal/format/index.html)                             | add example (do we need this exposed?)  |   |
|      | icu_decimal              | [format::FormattedFixedDecimal](https://unicode-org.github.io/icu4x-docs/doc/icu_decimal/format/struct.FormattedFixedDecimal.html)      | add example                                    |  [FormattedDateTime](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/struct.FormattedDateTime.html)          |
|      | icu_decimal              | [error](https://unicode-org.github.io/icu4x-docs/doc/icu_decimal/error/index.html)                              | add example (do we need this exposed?)                                    |   [DateTimeError](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/enum.DateTimeFormatError.html)        |
|      | icu_decimal              | [options::FixedDecimalFormatOptions](https://unicode-org.github.io/icu4x-docs/doc/icu_decimal/options/struct.FixedDecimalFormatOptions.html) | add examples                                   |   [icu_datetime::options](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/options/index.html)        |
|      | icu_decimal              | [provider](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/provider/index.html)                           | document                                       |           |
|      | icu_datetime             | [date](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/date/index.html)                               | document                                       |           |
|      | icu_datetime             | [datetime](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/datetime/index.html)                           | module doc/example                             |           |
|      | icu_datetime             | [mock](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/mock/index.html)                               | module doc/example                             |           |
|      | icu_datetime             | [options::components](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/options/components/index.html)                | Add headline                                   |           |
|      | icu_datetime             | [options::components](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/options/components/index.html#enums)                | document Enum                                  |           |
|      | icu_datetime             | [options::preferences](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/options/preferences/index.html)               | add note that it doesn't work with lenghts yet |           |
|      | icu_datetime             | [provider](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/provider/index.html)                           | document                                       |           |
|      | icu_datetime             | [skeleton](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/skeleton/index.html)                           | examples                                       |           |
|      | icu_datetime             | [skeleton::SkeletonError](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/skeleton/enum.SkeletonError.html)            | document                                       |           |
|      | icu_datetime             | [skeleton::{functions}](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/skeleton/index.html#functions)              | document                                       |           |
|      | icu_datetime             | [zoned_datetime](https://unicode-org.github.io/icu4x-docs/doc/icu_datetime/zoned_datetime/index.html)                     | module doc                                     |           |
|      | icu_locid                | [icu::locid::macros](https://unicode-org.github.io/icu4x-docs/doc/icu/locid/macros/index.html)                 | document                                       |           |
|      | icu_locale_canonicalizer | [main](https://unicode-org.github.io/icu4x-docs/doc/icu/index.html)                               | add to `icu`                                   |           |
|      | icu_locale_canonicalizer | [main](https://unicode-org.github.io/icu4x-docs/doc/icu_locale_canonicalizer/index.html)                               | document + example                             |           |
|      | icu_plurals              | [provider](https://unicode-org.github.io/icu4x-docs/doc/icu_plurals/provider/index.html)                           | document                                       |           |
|      | icu_uniset               | [enum props](https://unicode-org.github.io/icu4x-docs/doc/icu_uniset/enum_props/index.html)                         | document                                       |           |
|      | icu_uniset               | [provider](https://unicode-org.github.io/icu4x-docs/doc/icu_uniset/provider/index.html)                           | document                                       |           |
|      | icu_uniset               | [UnicodeSetSpanCondition](https://unicode-org.github.io/icu4x-docs/doc/icu_uniset/enum.UnicodeSetSpanCondition.html)            | document                                       |           |
|      | icu_provider_fs          | [manifest](https://unicode-org.github.io/icu4x-docs/doc/icu_provider_fs/manifest/index.html)                           | document                                       |           |
|      | fixed_decimal            | [decimal](https://unicode-org.github.io/icu4x-docs/doc/fixed_decimal/decimal/index.html)                            | document + example                             |           |
|      | litemap                  | [main](https://unicode-org.github.io/icu4x-docs/doc/litemap/index.html)                               | example                                        |           |
|      | litemap                  | [LiteMap](https://unicode-org.github.io/icu4x-docs/doc/litemap/struct.LiteMap.html)                            | methods examples                               | [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html)          |
|      | writeable                | [writeable::Writeable](https://unicode-org.github.io/icu4x-docs/doc/writeable/trait.Writeable.html)               | example                                        |  [fmt::Display](https://doc.rust-lang.org/std/fmt/trait.Display.html)         |
|      | zerovec                  | [samples](https://unicode-org.github.io/icu4x-docs/doc/zerovec/samples/index.html)                            | should we hide it from doc?                       |           |
|      | zerovec                  | [VecZeroVec](https://unicode-org.github.io/icu4x-docs/doc/zerovec/enum.VarZeroVecError.html)                         | module doc                                     |           |

All those pages are reachable from top directories and can be landing pages indexable by search engines. They all look empty, or confusing, or miss an example that would explain what one can do with the API.

While it is often possible to reach a more full documentation within couple clicks, I believe we should aim to minimize cases where one has to, and in those, at least state "For docs and examples, see LINK".

Often a headline of a doc is a single line in the upper level list of modules/structs/enums etc. It's worth verifying that the headline works in both contexts.

I'd like to discuss the option of blocking 0.2 on this issue.

p.s. I collected several examples of analogous docs that I believe to be comprehensive, and with useful examples. Let me now if you think it's worth for me to add them in more places.

**Comment by sffc** [comment]
> FixedDecimalFormat

The docs say: "See the crate-level documentation for examples."  Do you suggest we add additional examples?  I see two problems with that:

1. I don't like duplicating examples that are basically the same.  Don't Repeat Yourself.
2. More examples means slower `cargo test` times.  icu_locid has, in my opinion, far *too many* examples, and it takes a long time for `cargo test` to finish on my team.

> zerovec | samples | should we hide it from doc?

Discussion backlog issue for this: #657

> I'd like to discuss the option of blocking 0.2 on this issue.

At that rate, we may as well drop 0.3 and just hold 0.2 for EOQ.  I would rather release 0.2 while it's still April, and consider 0.3 our cleanup release.

**Comment by zbraniecki** [comment]
> I guess the more general question is, then, must we give examples for every type, given that this just leads in many cases to duplicated examples, with the problems stated above?

The usual hygiene question is - must we expose a module if it only exposes a single type? Can we export just the type?

> The docs say: "See the crate-level documentation for examples." Do you suggest we add additional examples?

Or link the sentence at least. I'd prefer an example, because if I land on this page, I prefer to see an example than to have to click to go to see one.

> I don't like duplicating examples that are basically the same. Don't Repeat Yourself.

DRY is great for code. It's not great for people. The primary target of docs are people, not code.

> More examples means slower cargo test times. icu_locid has, in my opinion, far too many examples, and it takes a long time for cargo test to finish on my PC.

We could selectively disable some tests from the default cargo test` (must like we do with `bench` feature for extensive benchmarks). My concern about this is that you evaluate docs from their impact on engineering cycle, while I think their main value comes from their onboarding and DX value.

When you work on code, how often you read HashMap docs, or Rc docs, of Pin. Do you imagine engineers working on those saying "let's not document [pin](https://doc.rust-lang.org/std/pin/index.html) module, it's just [one struct](https://doc.rust-lang.org/std/pin/struct.Pin.html), we can document that"?
Do you think "[HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html) has too many examples, it must cut into cargo test` times"?

I think most consumers of docs use them and enjoy them and praise the quality and standard of Rust documentation ecosystem precisely because `stdlib` has incredibly high standard with examples by every single module, structure, enum variant and error type. I understand we're not stdlib, but I wouldn't want us to lower that standard for wrong reasons.

**Comment by sffc** [comment]
To be clear, I agree with the majority of your suggestions in the OP.

**Comment by sffc** [comment]
One more thing to throw out there: I think we should spend time to document the data structs in every component, such as what I did in [FixedDecimalFormat](https://unicode-org.github.io/icu4x-docs/doc/icu_decimal/provider/index.html), including all the fields.

**Comment by zbraniecki** [comment]
`locale_canonicalizer` also lacks README.md - this is particularly noticable since this is what people see in crates.io. See https://crates.io/crates/writeable vs https://crates.io/crates/fixed_decimal (we're fixing writeable in 0.2!)

**Comment by dminor** [comment]
I'm adding better docs for locale canonicalizer in https://github.com/unicode-org/icu4x/pull/688

**Comment by sffc** [comment]
2021-04-29:

- @sffc: Module-level docs can show thorough examples. Putting less-good docs in each individual struct or method could be counterproductive if users get deep links to those structs and methods.
- @gregtatum: should we separate coding from documentation? Because it could slow down development velocity, and one might not fully understand the code they are writing until they've finished the whole thing.
- @sffc: We should lean more heavily on experimental for features that are not complete. We have an experimental directory for new components, and we could perhaps use an experimental feature for new work in existing components.
- @zbraniecki: We should try to balance development velocity with landing incomplete code.
- @dminor: Isn't the whole project experimental until we reach 1.0?
- @sffc: The APIs are experimental and subject to change, but we shouldn't lower our bar for things like documentation, tests, and benches.
- @nordzilla: We should focus on this kind of quality for future work. We don't want to get to 1.0 with a big backlog of quality issues.
