### ISSUE TITLE
Build cargo docs in PR

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#685]
It would be helpful to reviewers if cargo doc could be built for every PR so that it can be reviewed for quality.

**Comment by sffc** [comment]
2021-04-29:

- @echeran: How does this work? We wouldn't want to clobber the main icu4x-docs branch.
- @Manishearth: Netlify does this kind of thing. Could you teach Netlify to do cargo doc?
- @sffc: Or Heroku or Google Cloud something.

**Comment by gregtatum** [comment]
Here's netlify:
https://docs.netlify.com/configure-builds/manage-dependencies/#rust

Also, GitHub actions allows you to specify uploading artifacts, which could contain the docs, but they may be download-only, and not be clickable to view.

**Comment by sffc** [comment]
It appears that GHA [does not support browsable HTML artifacts](https://github.community/t/need-clarification-on-github-actions/16027), but competitors like [CircleCI](https://circleci.com/docs/2.0/code-coverage/) appear to have this capability.  So we could consider CircleCI for this specific use case.

**Comment by sffc** [comment]
Another option... since we have GCP at our disposal, we could use Google Cloud Build to upload the artifacts to Google Cloud Storage, with a configurable lifetime like 30 days.  Data stored on Google Cloud Storage can be viewed as static HTML.

https://cloud.google.com/build/docs/building/store-build-artifacts
https://cloud.google.com/storage/docs/hosting-static-website-http

**Comment by sffc** [comment]
I set up Google Cloud Build on a test repo, and got it to upload cargo docs to GCS on a PR (https://github.com/sffc/ci_test/pull/2) to:

http://sffc-chromium-ci-test-bucket.storage.googleapis.com/pr/2/743a56e/ci_test/index.html

The only point of friction is that I can't find a way to post that link on GitHub itself.  All you see is a generic summary that says "Build 9a8c5d48-0b5e-435d-993b-546150d5fa45 successful ... View more details on Google Cloud Build".  You can do the extra click, and if you're signed in, you can see the URL.  However, I also set it up so that the URL is predictable: it has the PR number and the short sha of the commit.

**Comment by sffc** [comment]
I found an [official tutorial](https://cloud.google.com/run/docs/tutorials/configure-deployment-previews) about uploading deployment previews on GitHub pull requests, and it suggests creating a secondary status with a link to the docs.  We can do that, but I was hoping for a more elegant solution.
