### ISSUE TITLE
Document common commands that are available for each component

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#70]
Spinning this off from #43.

Rust provides a number of commands that help universally work with each component. @nciric suggested to drop just listing those commands in README.md which I did, but I think it could be nice to have them documented.

Those commands are:

```
cargo test
cargo bench
cargo doc --open
cargo build --release
cargo fmt
cargo clippy
```

**Comment by nciric** [comment]
I think we should have documentation/build_test.md (or whatever) that tells people how to ... well ... build and test our project.
Filip has #69 that points to all docs from Readme through index so I think we can plumb it through that.

**Comment by nciric** [comment]
Now that I know more about Rust, I am not sure we need this document, it's all well laid out in [the official docs](https://doc.rust-lang.org/cargo/commands/index.html).

I'll close the issue - feel free to open it if you feel strongly.
