### ISSUE TITLE
Figure out how to document FFI

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#702]
FFI introduces a large surface of APIs, both in Rust and in C/C++.  All of these surfaces should be just as well documented as core ICU4X Rust.  However, we don't want to cause too much work maintaining duplicated documentation.

Some questions to answer:

- How to map from core Rust API to Rust FFI to C to C++?
- How to copy the Markdown
- What documentation system for C/C++? Doxygen?  ReadTheDocs?
- How to handle examples; can we auto-generate them somehow, like APIs?

CC @Manishearth

**Comment by Manishearth** [comment]
So for the C API my intent was that the `capi` rustdoc documentation would be sufficient.

For C++ and such I imagine we'll need to duplicate a lot of the docs or at least cross reference them, unless we can write tooling which is basically the plugin part of `diplomat` for generating these.

**Comment by Manishearth** [comment]
Here's what our existing docs look like: https://unicode-org.github.io/icu4x-docs/doc/icu_capi/pluralrules/index.html

**Comment by sffc** [comment]
Discussion: we could sue ReadTheDocs and part of Diplomat would involve a plugin to generate ReadTheDocs for the target language.
