### ISSUE TITLE
Add uax14_rs as an experiment crate

### ISSUE THREAD

**Issue by aethanyc** [unicode-org/icu4x#707]
The issue is to discuss integrating https://github.com/makotokato/uax14_rs into icu4x as the first step toward #109. We may import it under `experiment/`, and improve it later.

Summary on uax14_rs status
---------------------
This may answer some of the questions in [this comment](https://github.com/unicode-org/icu4x/issues/109#issuecomment-832235347).

1. uax14_rs has implemented [spec_test.rs](https://github.com/makotokato/uax14_rs/blob/master/tests/spec_test.rs) that passes https://www.unicode.org/Public/UCD/latest/ucd/auxiliary/LineBreakTest.txt.
2. uax14_rs use [`generate_properties.py`](https://github.com/makotokato/uax14_rs/blob/master/tools/generate_properties.py) to generate line break properties and UAX14 rules tables, and use them to drive the finite state machine. See next section for its performance.

Performance comparison of line breaking implementations 
---------------
The line break benchmark is in https://github.com/zbraniecki/intl-measurements

The test is simple: read the data into a UTF-16 string, and pass to the line breaker. Measure the total time to iterate all the line break opportunities. Numbers are from [here](https://github.com/zbraniecki/intl-measurements/pull/7#issuecomment-831430959) and [here](https://github.com/zbraniecki/intl-measurements/pull/8#issue-630922163), running on Intel Core i5-9600K 6-Core 3.7 GHz, 32 GB RAM.

Lang / Impl | [uax14_rs](https://github.com/makotokato/uax14_rs) | icu4c (66) | [rust_icu](https://github.com/google/rust_icu)
--- | --- | --- | ---
English | 844ms | 1246ms | 1195ms
Chinese | 151ms | 389ms | 353ms
Thai [1] | 1687ms | 712ms |  716ms

[1] For Thai, uax14_rs uses  `experimental/segmenter_lstm/`; rust_icu and icu4c use dictionary.

Possible future work after the integration
-------------------
1. Use CodePointTrie to map codepoint to line break value. 
2. Use Rust instead of python to generate UAX14 line break rules into tables. 
3. Use `DataProvider` to plugin the rule table.
4. Improve documentation and tests.

Other thought? 

@makotokato Feel free to comment if I misinterpret anything, or add any potential future work you envision.

cc @jfkthame @zbraniecki

**Comment by zbraniecki** [comment]
Thank you Ting-Yu for driving that and being persistent to enable the evaluation and research!

My hope is that we can either reimplement the dictionary model for SAE or improve performance of ML model or possibly both.

@FrankYFTang - do the numbers look convincing for you that the runtime approach proposed here is performant enough to warrant divergence from ICU4X constrains?

**Comment by FrankYFTang** [comment]
LGTM
