### ISSUE TITLE
[locale] Add a second component owner/peer

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#72]
Locale component is currently owned by me and I get a lot of Rust specific help from Manish who has been my reviewer for this codebase.

Per today's conversation, it would be good to have a second person to co-own the component with me from the implementation/API etc. point of view.

I don't think it's blocking or urgent, but I'd like to file this issue so that we make sure to get the proper ownership coverage per component as we move.

**Comment by nciric** [comment]
Is there an official way of adding owners per crate? Or is just author in
toml file?

чет, 30. апр 2020. у 18:27 Zibi Braniecki <notifications@github.com> је
написао/ла:

**Comment by zbraniecki** [comment]
Once we start releasing on crates.io, we can list two owners there.

My suggestion is that we should have two owners (individual) and we should have some shared icu4x account that also has admin privs on crates.io.

**Comment by Manishearth** [comment]
No need, you can add github teams as owners on crates.io. It's something like `cargo owner -a github:unicode-org/teamname`

**Comment by nciric** [comment]
Should we put this decision in bylaws, or create crate-ownership.md doc?

**Comment by sffc** [comment]
Eventually I'd like to work toward OWNERS files in the component tree (follow-up: #72), but for now, I would just make a new .md file under docs/.
