### ISSUE TITLE
Add .take() function to Yoke

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#731]
In Yoke, if `Y` does not have any lifetime parameters (or if it is fully owned), then we should be able to add a `.take()` function to Yoke that returns the struct and drops the cart (which should either be empty or unused by the struct).

The use case is that we have code that tries to take ownership of fields within a data struct, while dropping the other fields (see datetime.rs).  I hope that this code may be obsoleted by #257, but this type of operation seems like it should be possible.

My first thought was to make the function constrained on `Y: 'static`, but this won't work since `Y` lies about being `'static` in the normal use case.

**Comment by Manishearth** [comment]
This isn't possible to do safely; we cannot distinguish between fully owned and borrowed values at compile time in Yoke, and while it's possible at runtime it would require an additional unsafe trait.

A thing that _might_ be possible is a method that lenses the Yoke to a subset of the borrowing type. This is really tricky to get right, though, we're already doing some really tricky stuff with `make_mut` and this has more complexities.

Another thing that might be possible is a method that behaves like `make_mut` but gives you an owned value, and we have an `IntoOwned` trait that is able to do a moveable ownership switch. This is again tricky to get right.

I'd prefer we just avoid this requirement, I don't think it's worth it. We should add an IntoOwned custom derive though.

**Comment by Manishearth** [comment]
Another thing you can do here is nest Yokes: you can always "lens" a Yoke by putting it inside another Yoke. It's probably not worth doing that though.

**Comment by Manishearth** [comment]
We could potentially have an `OwnedYokeable` trait that essentially is implemented in tandem with `Yokeable<Output=Self>`

**Comment by Manishearth** [comment]
> The use case is that we have code that tries to take ownership of fields within a data struct, while dropping the other fields (see datetime.rs). I hope that this code may be obsoleted by #257, but this type of operation seems like it should be possible.


Is this issue still necessary since we now (soon will) have lensing/projection (https://github.com/unicode-org/icu4x/pull/847)?
