### ISSUE TITLE
Implement working Clone and PartialEq on DataPayload and Yoke

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#753]
Currently, the `Clone` impl is present for `Yoke` and `DataPayload`, but it does not work when one tries to use it.  The error looks like this:

```
note: the following trait bounds were not satisfied:
      `<hello_world::HelloWorldV1<'static> as Yokeable<'a>>::Output: Clone`
```

This seems to be caused by https://github.com/rust-lang/rust/issues/85636.  However, the workaround mentioned there does not work for `Clone`, since the Clone impl for a reference copies the reference instead of cloning the struct that the reference points to.

`PartialEq` is a related but separate issue.  I have the following impl, but it doesn't compile:

```rust
impl<'d, 's, M> PartialEq for DataPayload<'d, 's, M>
where
    M: DataMarker<'s>,
    for<'a> &'a <M::Yokeable as Yokeable<'a>>::Output: PartialEq,
{
    fn eq(&self, other: &Self) -> bool {
        self.get().eq(other)
    }
}
```

Error message:

```
error[E0308]: mismatched types
   --> provider/core/src/data_provider.rs:165:23
    |
165 |         self.get().eq(other)
    |                       ^^^^^ expected reference, found struct `data_provider::DataPayload`
    |
    = note: expected reference `&&<<M as marker::DataMarker<'s>>::Yokeable as Yokeable<'_>>::Output`
               found reference `&data_provider::DataPayload<'d, 's, M>`
```

I played around with different variations of `&` and `*` on the arguments to get them to match up, to no success.  My guess is that the compiler is just confused about the lifetimes, since the lifetime of `.get()` is different than the lifetime of `other`.

CC @Manishearth

**Comment by Manishearth** [comment]
I think we fixed this with yoke_trait_hack, yes? Can this issue be closed?

**Comment by sffc** [comment]
It's implemented for Yoke, but we still need to it for DataPayload I think
