### ISSUE TITLE
Experiment with ICU4x in Gecko and SpiderMonkey

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#754]
We're planning to experiment with ICU4x in Gecko in June. Our goals are to do some correctness testing using test262, some performance comparisons against ICU4C and to provide feedback on the ICU4x FFI.

This is the corresponding Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1713136. I'm filing this issue so we have a way of tracking this work on the ICU4x side as well.

We're not planning to land a lot of code as part of this, but hopefully some of what we develop can be tidied up and used after the experimentation is complete.

**Comment by dminor** [comment]
We fixed https://github.com/unicode-org/icu4x/pull/738 as part of this.

**Comment by dminor** [comment]
We landed some expansions to the C locale in https://github.com/unicode-org/icu4x/pull/764 and uncovered some problems with licensing packaging in: https://github.com/unicode-org/icu4x/issues/771.

**Comment by dminor** [comment]
Erik filed https://github.com/unicode-org/icu4x/issues/778 and https://github.com/unicode-org/icu4x/issues/779.

**Comment by nordzilla** [comment]
Filed #794

**Comment by dminor** [comment]
Filed #805

**Comment by dminor** [comment]
Erik found https://github.com/unicode-org/icu4x/issues/807.

**Comment by dminor** [comment]
Found likely subtags bugs: #817 #818 #823

**Comment by dminor** [comment]
Follow on to Locale FFI extensions to add them to C++ API: https://github.com/unicode-org/icu4x/issues/824.

**Comment by dminor** [comment]
The work that this issue tracked has been completed.
