### ISSUE TITLE
Use Rust instead of Python to generate UAX14 line break tables

### ISSUE THREAD

**Issue by aethanyc** [unicode-org/icu4x#758]
Currently, segmenter uses [generate_properties.py](https://github.com/unicode-org/icu4x/blob/main/experimental/segmenter/tools/generate_properties.py) to generate `rule_table.rs` and `lb_define.rs`, and we have to run the script manually to generate the table.

We may consider generate them by using Rust, and integrate the step into the build process.

**Comment by u-03c9** [comment]
Hi, can I try do this task ?

**Comment by aethanyc** [comment]
Since the binary format for UAX14 and UAX29 rules will be similar, per discussion with @makotokato, we decide to do this after we have a prototype of UAX29. At that time, we'll know more about what the binary format will look like.

**Comment by aethanyc** [comment]
Duplicate of #1372 since #1372 has more information to move forward.
