### ISSUE TITLE
Add custom derive macro for data structs

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#761]
I have temporary macros, `icu_provider::unsafe_impl_data_marker_with_lifetime` and `icu_provider::impl_data_marker_no_lifetime`, that implement much of the data struct boilerplate required for the zero-copy yoke migration.  These should be replaced with safe custom derives instead.

**Comment by sffc** [comment]
CC @shadaj @Manishearth

**Comment by Manishearth** [comment]
Followup: https://github.com/unicode-org/icu4x/issues/844
