### ISSUE TITLE
Split likely subtags from LocaleCanonicalizer into their own type LocaleExpander

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#767]
In the review of #747, there was feedback that some users might only want to use likely subtags operations and not canonicalization and that we should provide a feature to make canonicalization optional to avoid having to package and load data that will not be used.

**Comment by dminor** [comment]
This seems like a reasonable approach to me and much better than adding a feature.

**Comment by zbraniecki** [comment]
Suggestion: `LocaleExpander`
