### ISSUE TITLE
C/C++: Encoding of string arguments

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#769]
I want to discuss **type signatures** for our C and C++ API functions in ICU4X.  Please note that this is distinct from the general discussion of string encodings across the FFI boundary, which is discussed in detail in [string_representation.md](https://github.com/unicode-org/icu4x/blob/main/docs/design/string_representation.md).

Since these APIs are Rust wrappers, we want string arguments to always be guaranteed as UTF-8 encoded.  C++ does not guarantee the encoding of `char*` strings, but C++20 introduces a new type `char8_t*` which carries additional information that the string is UTF-8 encoded.  However, `char8_t*` is not fully backwards compatible with C++17 (info: [P1423R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r3.html)), and it also has not yet made it into the C standard.

One suggested migration path, noted [here](https://stackoverflow.com/a/57504236/1407170), is to create two versions of each C++ function: one that takes `char*` and the other `char8_t*`.  However, it's not clear how to make this work with C functions, which can't be overloaded.

Separately from the type signatures, we should probably take steps to ensure that string literals in our C/C++ test files are compiled as UTF-8.  Right now they are raw string literals, which means they get compiled using the system's character encoding.  We can use `u8""` string literals, but that introduce some complications noted above with regard to C++20 compatibility.

**Comment by dminor** [comment]
I think it's important that our C FFI should compile as C, not C++, which would rule out using char8_t until it makes it into the C standard.

I suggest we make validation that input is UTF-8 something controlled by a feature. Then people who are really, really sure their input is valid UTF-8 can disable checks, or only enable them for debug builds.

For the C++ FFI, I think we could use C++ version checks in the header file to make char8_t available for C++20 callers. Ideally, we could then automatically disable the UTF-8 input validation feature for people using the C++20 interfaces, since we know it isn't necessary.

**Comment by markusicu** [comment]
`char` vs. `char8_t` indicates an intent about the encoding, but there is no guarantee either way. And for a library that is documented to only ever expect UTF-8 in byte-type string inputs, the distinction is meaningless.

Thus, in C APIs just use `char`. In C++, you could conditionally (C++20 & up) have inline `char8_t` overloads, hiding casts inside the library.

As Dan says, validation could be a mode; or you could have parallel _unsafe functions that don't validate and are thus faster. That leaves the speed vs. safety trade-off to the caller.

**Comment by sffc** [comment]
Do you have suggestions on how to handle our unit tests?  Right now we have plain `char*` static string literals (`""`), which could cause tests to fail on non-UTF-8 platforms.  Should we change our unit tests to use `u8""` string literals instead?

**Comment by markusicu** [comment]
> Do you have suggestions on how to handle our unit tests? Right now we have plain `char*` static string literals (`""`), which could cause tests to fail on non-UTF-8 platforms. Should we change our unit tests to use `u8""` string literals instead?

Well, for testing a C API where you can't overload, either you require that the library & tests are built with a compiler that is implicitly or explicitly set to use UTF-8 for the default charset, or you do what ICU4C does and use u8 with a cast.

This is why I argued (unsuccessfully) in the C++ WG against adding the distinct char8_t type.

Example:
https://github.com/unicode-org/icu/blob/main/icu4c/source/test/intltest/strcase.cpp#L1356
```
    length = CaseMap::utf8ToUpper("el", U_OMIT_UNCHANGED_TEXT,
                                  reinterpret_cast<const char*>(u8"Πατάτα"), 6 * 2,
                                  dest, UPRV_LENGTHOF(dest), &edits, errorCode);
```
(This is testing a C++ function, but there is no char8_t overload for this function. There is an overload with a simpler overall signature taking a StringPiece and a ByteSink (and there are char8_t overloads in those classes), but this function still needs to be tested.)

**Comment by sffc** [comment]
Response from Tom Honermann:

https://groups.google.com/u/2/a/unicode.org/g/icu4x-core/c/BlonY-S35Ao

**Comment by sffc** [comment]
2021-06-24:

- See additional replies from Tom Honermann above.
- @markusicu suggests sticking with `char*` for C API and overloads for C++ APIs. Consider accepting string_view and u8string_view (C++20 only).

**Comment by dminor** [comment]
@sffc Just to make sure, the decision is to go ahead with `char` and we're keeping this issue open to make any changes necessary to the unit tests?

**Comment by sffc** [comment]
The issue remains open in order to implement this:

> * @markusicu suggests sticking with `char*` for C API and overloads for C++ APIs. Consider accepting string_view and u8string_view (C++20 only).  See also https://en.cppreference.com/w/cpp/string/basic_string_view

**Comment by sffc** [comment]
Action item: Document the decision and the motivation behind it.
