### ISSUE TITLE
LICENSE file not packaged with individual crates

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#771]
In our Cargo.toml files we have a `license-file` with a relative path back to the root LICENSE file. This means that LICENSE is not actually packaged with the individual crates, which breaks tooling that expects to be able read the LICENSE file, like the `vendor_rust.py` script used to vendor crates into Firefox.

Assuming we can't use `license` in Cargo.toml to `OR` together the different licenses we're using, I think that we'll have to include a copy of the LICENSE file with each component that we package as a separate crate.

**Comment by sffc** [comment]
2021-06-10:

- @Manishearth - We should put this as a tidy task like generate-readmes
