### ISSUE TITLE
Add SingleFileDataProvider

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#776]
Currently we have FsDataProvider which requires a file tree, and StaticDataProvider which works by loading the entire file tree into static memory (for WASM tests, not production).

Ideally we have a production-worthy data provider that works like FsDataProvider but loads off of a single bincoded string/file provided at construction, so e.g. WASM users can fetch it off of the network as necessary. `StaticDataProvider` can then be tweaked to just use this directly with the bincode file being `include_bytes!`d

This will need to first build a `DataExporter` that can output a single bincoded file.

cc @sffc

**Comment by sffc** [comment]
CLosely related: #78

**Comment by sffc** [comment]
This was done in #835 but for static only. Follow-up for non-static: #848
