### ISSUE TITLE
Add PluralRules Categories functionality

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#778]
ICU4X currently has no functionality to return an enumeration of keywords that are supported by a PluralRules object for a given locale and `Cardinal`/`Ordinal` setting. 

The equivalent call that we currently use in SpiderMonkey is `uplrules_getKeywords()`
https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/upluralrules_8h.html#a5f8a89ec2b58323e9f96ac0bf2c13ab5

**Comment by sffc** [comment]
2021-06-10:

- @Manishearth - We don't have vectors over FFI yet. You should start with the Rust side though. But on FFI, there are two ways to do this: (1) return an iterator, similar to what we do for strings (Writeable), or (2) return a custom type that wraps Vec and makes it possible to read from Vec on the other side.
- @sffc - Should we be concerned about no_std with this API?  Returning an enumeration might be better.  Or an enum set?
- @Manishearth - Or an array of bools.
