### ISSUE TITLE
Expose PluralOperands::from_str() over C++ FFI

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#797]
#794 exposed the `PluralOperands::from_str()` function over the `capi` FFI. We should do the equivalent for the C++ FFI.

**Comment by nordzilla** [comment]
# Good First Issue

## Recommended Knowledge
* Some experience with Rust, C, and C++
* Familiar with the concept of  Foreign Function Interface ([FFI](https://en.wikipedia.org/wiki/Foreign_function_interface))

## Background
We want ICU4X's functionality to be usable by many different programming languages through (FFI). To start, we have a C API ([ffi/capi](https://github.com/unicode-org/icu4x/tree/main/ffi/capi)) that exposes some of our existing functionality through C. 

We would like to wrap these C API calls in some native C++ types ([ffi/cpp](https://github.com/unicode-org/icu4x/tree/main/ffi/cpp)) to create a library that feels natural to use with C++ style and idioms. 

## Where To Start

* Familiarize yourself with the `PluralOperands` Rust struct and its members in [components/plurals/src/operands.rs](https://github.com/unicode-org/icu4x/blob/main/components/plurals/src/operands.rs).

* Familiarize yourself with the `PluralOperands::from_str()` Rust function in [components/plurals/src/operands.rs](https://github.com/unicode-org/icu4x/blob/main/components/plurals/src/operands.rs). You don't need to know all of the details of the algorithm, but understand how it takes a string, and returns a `PluralOperands` object. 

* In the C API, we need to create an ICU4XPluralOperands type that will be exposed over the FFI boundary. See that on the Rust side in [ffi/capi/src/pluralrules.rs](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/src/pluralrules.rs)

* Since creating an `ICU4XPluralOperands` from a string is a fallible operation, what we actually return is a `ICU4XCreatePluralOperandsResult` object. See that in the same file [ffi/capi/src/pluralrules.rs](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/src/pluralrules.rs).

* Now, see the `icu4x_plural_operands_create()` implementation on the Rust side of the FFI boundary in [ffi/capi/src/pluralrules.rs](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/src/pluralrules.rs).

* Next, see how we have equivalent types for `ICU4XPluralOperands`, `ICU4XCreatePluralOperandsResult` and `icu4x_plural_operands_create()` on the C side of the FFI boundary in [ffi/capi/include/pluralrules.h](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/include/pluralrules.h)

* Finally, see how `icu4x_plural_operands_create()` is used in [ffi/capi/examples/pluralrules/test.c](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/examples/pluralrules/test.c)

## What You Need To Do

As mentioned, we want to create wrappers around our exposed C API that feel like using native C++. Look at the [ffi/cpp/include/pluralrules.hpp](https://github.com/unicode-org/icu4x/blob/main/ffi/cpp/include/pluralrules.hpp) file and how it wraps the functionality that is exposed in [ffi/capi/include/pluralrules.h](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/include/pluralrules.h).

Now that we have a C API for `icu4x_plural_operands_create()` we need to:
> In [ffi/cpp/include/pluralrules.hpp](https://github.com/unicode-org/icu4x/blob/main/ffi/cpp/include/pluralrules.hpp)
* Change the `using` declaration for `PluralOperands` to be an actual C++ struct so that we can add a `Create()` method to it.

* Add a `Create()` method to the `PluralOperands` type that optionally returns a `PluralOperands` if the call to `icu4x_plural_operands_create()` is successful. See `PluralRules::Create()` in the same file for a similar example.

> In [ffi/cpp/examples/pluralrules/test.cpp](https://github.com/unicode-org/icu4x/blob/main/ffi/cpp/examples/pluralrules/test.cpp)
* Expand the test to cover the new `PluralOperands::Create()` functionality.

**Comment by sffc** [comment]
We have this function on FFI.

https://unicode-org.github.io/icu4x/cppdoc/classICU4XPluralOperands.html#a872c55e00edf48a479fadf44302c7f88
