### ISSUE TITLE
Expose PluralRules::categories() over C++ FFI

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#798]
#779 exposed the `PluralRules::categories()` function over the `capi` FFI. We should do the equivalent for the C++ FFI.

**Comment by nordzilla** [comment]
# Good First Issue

## Recommended Knowledge
* Some experience with Rust, C, and C++
* Familiar with the concept of  Foreign Function Interface ([FFI](https://en.wikipedia.org/wiki/Foreign_function_interface))

## Background
We want ICU4X's functionality to be usable by many different programming languages through (FFI). To start, we have a C API ([ffi/capi](https://github.com/unicode-org/icu4x/tree/main/ffi/capi)) that exposes some of our existing functionality through C. 

We would like to wrap these C API calls in some native C++ types ([ffi/cpp](https://github.com/unicode-org/icu4x/tree/main/ffi/cpp)) to create a library that feels natural to use with C++ style and idioms. 

## Where To Start

* Read up about [Language Plural Rules](https://www.unicode.org/reports/tr35/tr35-29.html#Language_Plural_Rules). We are dealing specifically with returning which `PluralCategories` have rules for a particular `PluralRules` object for a given language identifier.

* Familiarize yourself with the `PluralRules::categories()` Rust function in [components/plurals/src/lib.rs](https://github.com/unicode-org/icu4x/blob/main/components/plurals/src/lib.rs), which returns an iterator over the supported categories for a particular `PluralRules` object.

* In the C API, rather than an iterator, we are returning a struct of booleans for each category, representing whether there are rules for each. See the `ICU4XPluralCategories` struct in [ffi/capi/src/pluralrules.rs
](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/src/pluralrules.rs)

* Next, view the Rust implementation of the `icu4x_plural_rules_categories()` function in [ffi/capi/src/pluralrules.rs
](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/src/pluralrules.rs) that gets exposed across the FFI boundary.

* Now see the C header for the same function `icu4x_plural_rules_categories()`, and the C typedef for the same struct `ICU4XPluralCategories` on the other side of the FFI boundary in [ffi/capi/include/pluralrules.h](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/include/pluralrules.h)

* Finally, see how `icu4x_plural_rules_categories()` is invoked and used in [ffi/capi/examples/pluralrules/test.c](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/examples/pluralrules/test.c)

## What You Need To Do

As mentioned, we want to create wrappers around our exposed C API that feel like using native C++. Look at the [ffi/cpp/include/pluralrules.hpp](https://github.com/unicode-org/icu4x/blob/main/ffi/cpp/include/pluralrules.hpp) file and how it wraps the functionality that is exposed in [ffi/capi/include/pluralrules.h](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/include/pluralrules.h).

Now that we have a C API for `icu4x_plural_rules_categories()` we need to:
> In [ffi/capi/include/pluralrules.h](https://github.com/unicode-org/icu4x/blob/main/ffi/capi/include/pluralrules.h)
* Add an equivalent C++ struct to that of `ICU4XPluralCategories` from the C API, similar to how we add a new C++ enum class for `PluralRuleType` that mirrors `ICU4XPluralRuleType` on the C side.

* Add a `Categories()` member function to the `PluralRules` class that invokes the `icu4x_plural_rules_categories()`  function and returns the native C++ type.

> In [ffi/cpp/examples/pluralrules/test.cpp](https://github.com/unicode-org/icu4x/blob/main/ffi/cpp/examples/pluralrules/test.cpp)
* Expand the test to cover the new `Categories()` functionality. 

You can see which language identifiers support which categories for `Cardinal` [here](https://github.com/unicode-org/cldr-json/blob/master/cldr-json/cldr-core/supplemental/plurals.json), and for `Ordinal` [here](https://github.com/unicode-org/cldr-json/blob/master/cldr-json/cldr-core/supplemental/ordinals.json) in the CLDR data. It looks like our test is using the Arabic language identifier `"ar"`.

**Comment by sffc** [comment]
@Manishearth We have the enum on FFI. Should we return an iterator / vector, too?

**Comment by Manishearth** [comment]
No strong feeling, leaning towards no. It's a convenience function and the perf cost isn't worth it over FFI.

https://unicode-org.github.io/icu4x/rustdoc/icu_capi/pluralrules/ffi/struct.ICU4XPluralCategories.html

A thing I'd love in the long run is the ability to use diplomat attrs to inject extra code.

**Comment by sffc** [comment]
Actually I think we have it, here:

```rust
        /// Get all of the categories needed in the current locale
        #[diplomat::rust_link(icu::plurals::PluralRules::categories, FnInStruct)]
        pub fn categories(&self) -> ICU4XPluralCategories {
            ICU4XPluralCategories::from_iter(self.0.categories())
        }
```

https://github.com/unicode-org/icu4x/blob/ef3da315952d1513b6a02ff05e81d64bd86a47a7/ffi/capi/src/pluralrules.rs#L84C1-L88C10

**Comment by Manishearth** [comment]
Right, that's what I linked above. It just doesn't have an iterator.

**Comment by sffc** [comment]
The function has the `#[diplomat::rust_link(icu::plurals::PluralRules::categories, FnInStruct)]` on it, which means we made a conscious choice previously to make this the canonical FFI.
