### ISSUE TITLE
Set up continous integration

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#81]
The way I run CI for my projects is via Travis.
I have an account there, connected my project to it and set up a [`.travis.yml` file](https://github.com/projectfluent/fluent-rs/blob/master/.travis.yml).

Here's the view of `fluent-rs` CI: https://travis-ci.org/github/projectfluent/fluent-rs

I'm not sure what other options exist beyond Travis and if we want to use it. @echeran ?

**Comment by sffc** [comment]
I've heard (don't exactly remember where) that for a free CI solution, GitHub Actions is compatible with Travis and should be used for newer projects.

For a paid solution, we can do anything that GCP supports.

**Comment by sffc** [comment]
Explanation of labels:

"R-needs-more-info" is a resolution for closed issues. Maybe we should have a similar label for open issues, like "discuss".

For the type, I think "T-core" is most appropriate here, since CI is a core feature of the project.

**Comment by zbraniecki** [comment]
I've never used github actions, but would be open to! @echeran do you want to try setting this up?

**Comment by echeran** [comment]
Yeah, let's try out Travis for starters.  It seems like an easy and prevalent solution for open source, and may integrate with fancier things like Coveralls like you were mentioning.  We can iterate from there.

**Comment by sffc** [comment]
Here's where Node.js moved from Travis to GitHub Actions:

https://github.com/nodejs/node/pull/32450

A quick Google search finds a number of other people jumping on this bandwagon:

https://www.google.com/search?q=travis+vs+github+actions

The original motivation is that Travis CI was acquired, and there was speculation that the new owners intend to "milk" Travis CI and discontinue feature development.  Here is a discussion on this subject and the new owner's official response to that speculation:

https://travis-ci.community/t/after-idera-future-development-and-support-plans/2474

**Comment by sffc** [comment]
To be clear, I have no strong opinion between Travis CI and GitHub Actions.  I like Travis CI and would be happy if we used it.  I'm just providing some context of a trend I've seen.

@srl295

**Comment by srl295** [comment]
I have nothing _against_ travis. (i.e. no reason not to use it.) In fact, it's what I use extensively internally, and I did a lot of the tooling for setting up icu and cldr's travis config. The travis-ci.org can get backed up and take a while to start queues, but I think that's a lot better than it used to be.

Github actions have some advantages, I think:
- better integration (unsurprisingly) in the UI
- I like the separate workflow concept: parallel things can be in separate action files, not all in one .travis.yml
- modularity, being able to import from other actions.  This means fewer helper-scripts checked into the main repo and/or waiting for core support for something.

OTOH if, say, fluent-rs is already using travis, there may be some advantage to getting up and running copying what's already been setup. 

https://github.com/projectfluent/fluent-rs/blob/master/.travis.yml looks nicely done. **So I'd say: I'd lean towards actions, but in the end go for expediency. If @zbraniecki is implementing and wants to use travis, no reason not to**

one thing to consider is how the monorepo structure will look with the build. Just have a list of components and build them? Have a parallel build? I don't know what build times look like here.

**Comment by echeran** [comment]
Hmm, in that case, maybe this is a good opportunity to try out Github Actions, seeing that the fluent-rs Travis config exists as a good backup option in the worst case.  I can try this out on my personal fork.

In the meantime, do we need CI set up for the main ICU4X right now?  If so, we can use the Travis setup for expediency to have something going for now.  Otherwise, we can wait a little.

**Comment by nciric** [comment]
This is a good writeup (Travis to Actions) -
https://markphelps.me/2019/09/migrating-from-travis-to-github-actions/

уто, 12. мај 2020. у 11:45 Elango <notifications@github.com> је написао/ла:

**Comment by zbraniecki** [comment]
Yeah, I'm down to try github actions. Let me try to set them up today for my personal fork and if that works, I'll file a PR here.

**Comment by zbraniecki** [comment]
> one thing to consider is how the monorepo structure will look with the build. 

For travis I just have one file per monorepo, see https://github.com/zbraniecki/unic-locale/blob/master/.travis.yml

**Comment by echeran** [comment]
@zbraniecki take a look at my WIP in #83 as a starting point for your exploration, lmk what you think
