### ISSUE TITLE
Incorrect likely subtags maximization of und-Latn-AQ

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#817]
This testcase in Firefox [1] maximizes `und-AQ` twice. The first call results in `und-latn-AQ` but the second call results in `en-latn-AQ`. Calling maximize() twice should not change the result (otherwise it would not be maximized!), so there must be a bug in our handling of maximizing `und` languages.

To work on this bug:
* Code is found in https://github.com/unicode-org/icu4x/blob/b56441cc06ca09210d7859e7628f06ac7bb7336c/components/locale_canonicalizer/src/locale_canonicalizer.rs#L458
* Unit tests are present here: https://github.com/unicode-org/icu4x/blob/main/components/locale_canonicalizer/tests/fixtures/maximize.json
* The algorithm is defined here: https://www.unicode.org/reports/tr35/#Likely_Subtags

[1] https://searchfox.org/mozilla-central/rev/c114db74a92cf15096dfda02255e125949b0e070/js/src/tests/non262/Intl/Locale/likely-subtags.js#5

**Comment by pandusonu2** [comment]
I would like to try working on this issue.

Commenting to avoid multiple people working on the same issue

**Comment by pandusonu2** [comment]
Want to confirm before making the changes.

I think the main point of difference occurred during the following optimization change: https://github.com/unicode-org/icu4x/commit/efba26f9e066c514a2f1bfce9a8020e7e0a2b653#diff-eab169624c9a686e5bfb7f68700e2ffa5bdd801323bfd2e41309687b61941d61

The order to check is 
languages_scripts_regions
languages_regions
languages_scripts
languages
und_scripts

Acc to the algorithm defined in unicode.org

The current code does the following:
language_region
language_script
language
und_script_region
und_script
und_region

In the case mentioned, it initially undergoes und_region, but on the second maximize undergoes a und_script_region check which is wrong.

The fix:
Delete the additional check conditions.

**Comment by zbraniecki** [comment]
Thank you for the analysis! @dminor do you have thoughts on this? I'm inclined to wait till I see the code but it seems reasonable to me.

**Comment by dminor** [comment]
Before deleting anything, I'd suggest playing with the order of the checks.

If I recall correctly, und_script_region is an optimization of language_script_region where we know the language is undefined. If that is correct, we should be checking it first. Similarly, und_region is likely a specialization of languages_region where we know the language is undefined, so we should check it when we check language_region.

**Comment by pandusonu2** [comment]
@dminor May I also assume this is the definitive guide as to what is the expected output for each expected I/O: https://unicode-org.github.io/cldr-staging/charts/38/supplemental/likely_subtags.html

It would be great if you can redirect me to an online checker to see if the output the service is giving matches with the expected output of each input.

**Comment by dminor** [comment]
I don't think the guide you linked is definitive, I think it is intended to provide examples of the operation. They include old numeric region codes, so you would have to canonicalize the input prior to running it through maximize.

I think it is safe to assume that Chrome and Firefox have correct implementations, so if you need to check expected output, you could do so from developer tools:

```
let a = new Intl.Locale("und");
>>> Intl.Locale { baseName: "und", numeric: false, language: "und" }
a.maximize();
>>> Intl.Locale { baseName: "en-Latn-US", numeric: false, language: "en", script: "Latn", region: "US" }
```

We have some test cases in ICU4X: https://github.com/unicode-org/icu4x/blob/main/components/locale_canonicalizer/tests/fixtures/maximize.json. I'd suggest starting there and expanded it as necessary.
