### ISSUE TITLE
Likely subtags minimization of `und` should be `en`.

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#818]
According to test262, the likely subtags minimize operation applied to `und` should result in `en`.

To work on this bug:
* Code is found in: https://github.com/unicode-org/icu4x/blob/b56441cc06ca09210d7859e7628f06ac7bb7336c/components/locale_canonicalizer/src/locale_canonicalizer.rs#L491
* Unit tests are present here: https://github.com/unicode-org/icu4x/blob/main/components/locale_canonicalizer/tests/fixtures/minimize.json
* The algorithm is defined here: https://www.unicode.org/reports/tr35/#Likely_Subtags

[1] https://github.com/tc39/test262/blob/main/test/intl402/Locale/prototype/minimize/removing-likely-subtags-first-adds-likely-subtags.js#L23

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please guide me what needs to be done as i am new here. Thanks

**Comment by dminor** [comment]
Hi, thanks for offering to help! I'm not sure I can give much guidance beyond what I wrote down above. I think there's an algorithmic error in our implementation, so I'd suggest adding a failing test case, and comparing what is happening in our code to the description in https://www.unicode.org/reports/tr35/#Likely_Subtags.

**Comment by sffc** [comment]
@samchen61661 is interested in working on this.
