### ISSUE TITLE
Add projection functions to Yoke

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#829]
There are several use cases where we need to project a Yoke from one Yokeable type to another Yokeable type but keeping the same Cart; i.e., map `Yoke<A, C>` to `Yoke<B, C>`.

A few examples of use cases:

1. `Yoke<ZeroMap<'static, Foo, Bar>, C>` to `Yoke<Bar, C>` (getting a value from a map)
2. `Yoke<&'static [u8], C>` to `Yoke<T, C>` (applying a deserializer to a slice)
3. `Yoke<T, C>` to `Yoke<Q, C>` where `Q` is a field of `T` (selecting more specific data)

I can envision these operations being chained and performed by different data providers.  For example, the single-file data provider can return `DataPayload<BytesMarker>`, which a deserialization provider converts to a `DataPayload<LargerDataStructMarker>`, which a data filtering provider converts to a `DataPayload<SmallerDataStructMarker>`.

CC @Manishearth

**Comment by Manishearth** [comment]
I _think_ this can be done safely in a generic fashion but I'm not 100% sure and I need to think about it to figure out the correct bounds.

**Comment by Manishearth** [comment]
This'll also make it easier to clone Yokes!
