### ISSUE TITLE
Add smarter locale filtering in DataExporter

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#834]
ICU4C's data build tool has a fairly smart algorithm when figuring out which locales to include based on an allowlist: all children and parents.  For example, including "en-001" results in all parents ("en", "root") and children ("en-GB", "en-ZA", ...) being included.

We should implement this as well in ICU4X.  It should be done in the LanguageIdentifierFilter trait in icu_provider.

This depends on the resolution to #173, since the locale fallback chain will need to be computed by this filter.

**Comment by sffc** [comment]
This does not need to block 1.0 because this is something we can add incrementally.

**Comment by Manishearth** [comment]
A major component of this would be https://github.com/unicode-org/icu4x/issues/2683
