### ISSUE TITLE
Implement range iterator for UnicodeSet

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#836]
We should expose an iterator over `UnicodeSet` ranges for consumers who implement regex-related code. For those users, they will want to iterate over the inversion list ranges often enough that it would be worth expose a convenience function that provides Rust Iterator interface.

**Comment by echeran** [comment]
Two ways of representing the range are using `std::ops::Range<u32>` or `(u32, u32)`. I vaguely remember a discussion about this from a while ago... I think `Range` is idiomatic in Rust but creates a dependency on `std` that makes it harder for a language-agnostic FFI to target other languages.

I'm leaning towards `(u32, u32)` for FFI reasons, but if there could be a way to have an FFI annotation in Diplomat that allows skipping auto-generating bindings for a function (like `#[serde(skip)]` does for struct fields during serialization), then maybe we can instead / in addition have the `Range<u32>` version.

**Comment by sffc** [comment]
Another option would be a `(char, char)` inclusive range.

But I think we should use either `std::ops::Range<u32>` or `std::ops::RangeInclusive<u32>`.

For FFI, we can use some other type, but for the Rust API, we should use the thing that's idiomatic for Rust.

**Comment by Manishearth** [comment]
I'd use `Range`, the design of Diplomat and our FFI is that everything is wrappable; so this would be similarly wrapped.

The goal of diplomat is not to make every rust datastructure FFI-compat, it's to make it easy to write FFI wrappers.

**Comment by echeran** [comment]
> Another option would be a `(char, char)` inclusive range.

Oh, right. I see why you had to specify the caveat "inclusive range" -- I found this [blog post](https://ridiculousfish.com/blog/posts/least-favorite-rust-type.html) that explains the footgun of `Range<char>` (and coincidentally enough, framed against the scenario of implementing a regex engine...)

> But I think we should use either `std::ops::Range<u32>` or `std::ops::RangeInclusive<u32>`.

For now, going with `Range` as Manish suggested.

**Comment by markusicu** [comment]
That “My Least Favorite Rust Type” about `Range` is pretty damning...

Note that in ICU we almost always use `end` for an *inclusive* end but `limit` for an *exclusive* end. And on the UnicodeSet API we do work with user-friendly, inclusive `end` values while of course the inversion list implementation works with more implementation-friendly `limit`s.

FYI ICU4C/J UnicodeSet range iteration:
- getRangeCount()/getRangeStart(i)/getRangeEnd(i)
- separate class UnicodeSetIterator has nextRange()/codepoint/codepointEnd
  - too bad about the non-titlecasing of the "point"
- Java only: the newer ranges() returns an `Iterable<UnicodeSet.EntryRange>`

**Comment by sffc** [comment]
Digression: I disagree with most of the points in the blog post.  As soon as you construct a mental model around the concept that Range is specifically *not* `Copy` and should be treated as an object, not a primitive type, most of the design decisions Rust makes are intuitive.

**Comment by sffc** [comment]
Also, although `RangeInclusive<char>` is valid syntax, Rust disables most methods on that type, since it is not well defined to iterate over such a range, since there are holes (e.g. surrogates).  When I first discovered that, I was frustrated, but now I think that is quite clever, because it prevents you from making mistakes.

**Comment by markusicu** [comment]
If `char` cannot hold surrogate code points, then iteration over `char` should skip from U+D7FF to U+E000.

An API that supports “Unicode code points” should work for surrogates, though. https://www.unicode.org/glossary/#code_point

**Comment by markusicu** [comment]
By the way, in ICU4C we use *signed* `UChar32` = `int32_t` for code points, because it is very convenient to use/return `U_SENTINEL` = -1 for "no code point", and cheaply & easily test `< 0` for that.

In Java, all we have is `int` anyway, and with our choice in C++ it is easy to port code.

**Comment by echeran** [comment]
Yeah, I didn't mean to bring attention to the corner case arguments that the blog post was coming up, they seemed somewhat contrived. Just the point about {`char` vs. `u32`} x {`Range` vs. `RangeInclusive`} seemed relevant.

Based on the distinction of ICU ranges using an `end` bound (inclusive of value) rather than a `limit` bound (exclusive of value), it seems like we should use `RangeInclusive`, not `Range`.

I also prefer the `u32` type rather than the `char` type for the `iter_ranges` / `get_range` / `get_range_start` / `get_range_end` functions since it bypasses concerns of Rust-specific caveats about surrogate code points when providing the data from the underlying inversion list, which is `Vec<u32>`. @iainireland  -- what do you think? Implicit in that statement is an assumption that your use cases for regex implementations would be simpler to think in terms of `u32` than Rust `char`. Is that a fair assumption?

(I do recognize that the existing [contains_range()](https://unicode-org.github.io/icu4x-docs/doc/icu_uniset/struct.UnicodeSet.html#method.contains_range) function takes a range in terms of `char`, not `u32`. But that is a query/predicate method. The only other method that returns data using the `char` type is `iter_chars()`, which has to call `.filter_map(char::from_u32)` to go from the inversion list's `u32` to the narrower type `char`.)

I made changes in the PR based on what I think matches this discussion most closely, but PTAL.

**Comment by echeran** [comment]
Also, I think the `Iterator<RangeInclusive<u32>>` return type on `iter_ranges()` should be able to provide a clear, idiomatic counterpart to the ICU's `UnicodeSetIterator`'s operations.

**Comment by iainireland** [comment]
Oops, missed this originally. 

Irregexp uses `uint32_t` internally to represent characters. (It used to be `int32_t`, but it was [changed](https://github.com/v8/v8/commit/f6874c73bd4e7603a7dcb5a5461bcbe683483c94#diff-5f434b85d3af38e9b21bfbf9e2797cec64f0cbc49658c47e5e2b80f1544b45d7) to avoid comparisons between signed and unsigned types.) I think it is reasonable to use `u32` here.
