### ISSUE TITLE
Add CI for linting

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#84]
Things we should cover in a linting CI:

1. Code format is consistent with `cargo fmt`
2. Copyright headers are correct

**Comment by sffc** [comment]
@echeran @zbraniecki

**Comment by zbraniecki** [comment]
Yep! Later we can consider `clippy`. Clippy has false-positives, so it requires some one-off cases to turn it off, but it generally helps avoid mistakes that cost perf/mem and the hints are ~90% useful in my experience.

**Comment by echeran** [comment]
How exactly should the copyright headers check go?  Check that every file has copyright headers?  Check that we're not adding code with copyright headers?

**Comment by sffc** [comment]
@hsivonen What is the correct strategy for license headers in code files in ICU4X?

**Comment by sffc** [comment]
Ping @hsivonen about copyright headers
