### ISSUE TITLE
Add string -> property enum functions

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#842]
### Background

For implementing a regexp parser, it is useful to take the string tokens used in escapes like `\p{Whitespace}` or `\p{gc=Letter}` and turn them into a form that works with the APIs for UnicodeSet.

(Note: we wouldn't want an all-in-one API that takes strings like "Whitespace" or "gc"+"Letter" and attempts to return a UnicodeSet directly since, for example, it doesn't leave room for validating the corresponding Unicode properties against an allow list.)

ICU has [`getPropertyEnum`](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/uchar_8h.html#a3ccdd12983f379830fb61de20069df01) that takes a String and returns a Unicode property enum, which is suitable for all properties (ex: including binary and enumerated. ICU also has [`getPropertyValueEnum`](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/uchar_8h.html#a8b997c4d6d97eb8e0581b96d1ef5e2a3), which for the given property enum, converts the property value string to the int value represented by that property value.

### Caveat

It is useful to convert C-style enums (which are aliases to integers) into the namespaced Rust enums because, for example, Rust enums can support compiler checking of exhaustive branch coverage in matches. However, for getting and validating the property value enums, the ICU-style API that returns an `int32_t` is convenient since it is only function that returns a single return type. A hypothetical scenario that returns Rust enums might look like `get_general_category_value_enum(prop_val_name: &str) -> GeneralCategory` for General_Category, and it would have to be duplicated per property because each per-property enum is a distinct type.

#### Option 1 - all-in-one

Ex: `fn get_unicode_set(prop_name: &str, prop_value: Option<&str>) -> UnisetResult`

As mentioned above, this all-in-one function might be easiest for a specific use case (ex: regexp parsing), but even in that scenario, isn't decoupled to allow things like allow-list validation

#### Option 2 - ICU-style

Ex: `fn get_property_enum(prop_name: &str) -> Option<UnicodeProperty>`
and `fn get_property_enum_val(prop: UnicodeProperty, prop_val_name: &str) -> Option<u32>`

Looking up the property value enum is given as an integer, but there is only one function to deal with. There could be int -> Rust enum converters to support validation, and it would help to consolidate the Rust enums for enumerated and binary properties into one enum. Maybe it would be useful to pull it out into a separate component to be shared across UnicodeSet and CodePointTrie components?

#### Option 3 - ICU-style but with modification

Ex: `fn get_property_enum_val(prop_name: &str, prop_value: &str) -> Option<(u32, u32)>`
and `fn get_property_enum(prop_name: &str) -> Option<u32>`

This option is similar to Option 2, but tries to offer a lookup of the property name and property value strings in a single pass rather than a 2-step pass, but requires the UnicodeProperty from the property name to also be given back as an int rather than a Rust enum.

**Comment by echeran** [comment]
@markusicu @iainireland

**Comment by echeran** [comment]
Also, for future reference, [loose matching](http://unicode.org/reports/tr44/#Matching_Symbolic) when matching property name/value strings during parsing would not be necessary because it is not included in the [relevant TC39 proposal](https://github.com/tc39/proposal-regexp-unicode-property-escapes#why-not-support-loose-matching)

**Comment by sffc** [comment]
Something for consideration: we want a solution that works well with dead code elimination.  An API that takes a string and resolves to any property means that dead code elimination can't help us eliminate properties.  Consider whether we could design something that allows the client to put a match statement in the client code to cover the properties they know they need to support.

**Comment by sffc** [comment]
Also worth noting that this feature request is a subset of L3b: https://github.com/unicode-org/icu4x/issues/168

**Comment by sffc** [comment]
@iainireland to document the specific needs of SpiderMonkey. Then we need to design exactly what this looks like in terms of dead code elimination.

**Comment by echeran** [comment]
This previous comment from @markusicu seems relevant here, too: https://github.com/unicode-org/icu4x/pull/698#issuecomment-840899732

**Comment by iainireland** [comment]
As I understand it, the goal of dead code elimination is to enable dead data elimination. I see two broad strategies for dead data elimination:

1. Require the user of this API to populate their own data provider with only the properties they need. In the case of irregexp, this would be the [set of binary properties documented here](https://tc39.es/ecma262/multipage/text-processing.html#table-binary-unicode-properties), `General_Category`, `Script`, and `Script_Extension`. This circumvents the problem by pushing it to the user (although we could simplify it by writing a datagen tool that takes a list of properties and emits the desired blob of data.)
2. Restrict the data based on which accessors (like `get_ascii_hex_digit_property`) are called. This means that any fully generic API (e.g. `fn get_unicode_set(prop_name: &str, prop_value: Option<&str>) -> UnisetResult` above) would make every property reachable, so there would instead need to be something like `get_unicode_set_for_ecma_regexp(...)` which internally would call only the property accessors that are supported by the JS standard. (My understanding is that this could be on either the Rust or the C++ side.) Alternatively, we could push the task of parsing property names to the caller.

The downside of the first approach is that it requires extra build steps from the user. 

The downsides of the second approach are that it requires every user with a different set of supported properties to write their own `get_unicode_set_for_foo` with largely identical boilerplate, and that it depends on infrastructure that doesn't exist yet.

Would a plan along these lines work?
1. Provide a DefaultDataPropertyProvider (name open to bikeshedding) that includes all data and is pruned via dead code elimination.
2. Hard-code `get_ascii_hex_digit_property` and friends to use the DefaultDataPropertyProvider.
3. Provide `get_unicode_set(provider: ..., prop_name: &str, prop_value: &str) -> UnisetResult`. This can either be used by passing in DefaultDataPropertyProvider, in which case every property will be bundled, or by passing in a custom provider (which irregexp can create by hand/datagen). This lets the user pick the tradeoff between convenience and data size.

**Comment by markusicu** [comment]
ICU does not have option 2, only options 1 and 3 (where you need to call two functions to resolve both the property enum and the value enum).

For modularization, there should be per-property functions like getGeneralCategory(codePoint)->enum GeneralCategory. People who know that property they need don't get any unnecessary code & data.

There should be separate functions for mapping names<->enums. ICU has one data file for this, for all of the properties it recognizes; it's about 20kB.

If that's not modular enough, you could offer one function for propertyName<->propertyEnum, and separate functions for getGeneralCategoryValueEnum(valueName) and getGeneralCategoryValueName(valueEnum), backed by per-property mapping data.

All-in-one functions can be useful, and can be in a higher-level piece of code that is easily stripped out for people who don't need them. ICU needs its all-in-one functions in the UnicodeSet pattern parser, and they are handy for tools and testing.

Ultimately, a regex implementation will depend on "all" of these, or anyway on those for the properties they support. ES regex supports only a small set of enumerated properties. ES regex also uses string name matching, while Unicode recommends loose matching (as you wrote earlier). I suggest that ES-regex-specific name<->enum mappings and wrapper code should live in the regex package/module, not in ICU4X.

**Comment by sffc** [comment]
A solution that is fairly ergonomic and works with dead code elimination would be to create something such as:

```rust
/// Object that maps from strings to property enums and/or UnicodeSets
struct UnicodePropertySelector {
    key_map: BytesTrie,
    value_map: BytesTrie,
}

/// Metadata for unicode properties used to build a UnicodePropertySelector.
struct UnicodePropertyMetadata<'a> {
    resource_key: ResourceKey,
    aliases: &'a [str],
}

impl UnicodePropertySelector {
    pub fn new_from_items(items: &[UnicodePropertyMetadata]) -> Self {
        // Build up the two BytesTries from the list of metadata
    }
}
```

Example call site:

```rust
let selector = UnicodePropertySelector::new_from_items(&[
    uniset::props::meta::WHITESPACE,
    uniset::props::meta::ALPHANUM,
    // ...
]);
```

This allows the call site to give the list of properties that they want while still using ICU4X to do most of the hard work.

***Please note:*** The above code has a lot of questions that need to be resolved and design that needs to be done.  This would be a good project for someone.

**Comment by iainireland** [comment]
In the short term, I've written [a prototype of a crate](https://github.com/iainireland/icu4x-js-regexp) that uses ICU4X to build its own StaticDataProvider with exactly the properties that JS supports. It will hopefully give us time to design a complete long-term solution.

**Comment by sffc** [comment]
> In the short term, I've written [a prototype of a crate](https://github.com/iainireland/icu4x-js-regexp) that uses ICU4X to build its own StaticDataProvider with exactly the properties that JS supports. It will hopefully give us time to design a complete long-term solution.

The prototype crate looks quite good!  Looking forward to seeing you pull parts of it into PRs against ICU4X.

**Comment by sffc** [comment]
@iainireland I moved this to the 0.6 milestone. Do you intent to work on it?

**Comment by sffc** [comment]
@iainireland Thoughts on this? Do you intend to land anything in ICU4X?

**Comment by sffc** [comment]
This is fixed by https://github.com/unicode-org/icu4x/pull/3169
