### ISSUE TITLE
Support ZeroMaps in Yokeable custom derive

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#844]
Followup from https://github.com/unicode-org/icu4x/issues/761

`#[derive(Yokeable)]` will not be able to work on types including `ZeroMap` since the compiler does not know that `ZeroMap` is covariant. A different derive implementation will be necessary to handles these.

**Comment by sffc** [comment]
@Manishearth to document what is needed here. @nordzilla potentially interested in helping implement.

**Comment by Manishearth** [comment]
The relevant part of the current implementation is https://github.com/unicode-org/icu4x/blob/cce8f224c263fb579d3f5ff02e6589e3aa9d9717/utils/yoke/derive/src/lib.rs#L61-L102 , where we implement `derive(Yokeable)` for structs with a single lifetime.

it currently generates this impl: https://github.com/unicode-org/icu4x/blob/cce8f224c263fb579d3f5ff02e6589e3aa9d9717/utils/yoke/derive/src/lib.rs#L78-L100


The only safety requirement of implementing `Yokeable` on a type is that the lifetime is _covariant_, which means that `Foo<'b>` can be cast to `Foo<'a>` if `'b` is longer than `'a`. `#[derive(Yokeable)]` is able to assert this by generating this function definition: https://github.com/unicode-org/icu4x/blob/cce8f224c263fb579d3f5ff02e6589e3aa9d9717/utils/yoke/derive/src/lib.rs#L80-L82

where it casts a `Foo<'static>` to a `Foo<'a>`, which is only legal if `'a` is covariant in `Foo<'a>`.

The tricky thing is that `ZeroMap<'a>` uses enough generics that the compiler isn't sure of that variance, and thus it does not allow `transform` and `transform_owned` to compile.

We still want most cases to just use the simple covariance test, but we could include a `#[yoke(cannot_prove_covariance)]` attribute to enable this other mode (see how `cloning_zcf` works to understand how attributes can be read).

In such cases we should instead be generating transmutes for `transform` and `transform_owned`, and _somehow_ asserting that all fields with lifetimes also implement `Yokeable`, correctly. One way to do that is to generate some [static assertions](https://docs.rs/static_assertions/1.1.0/static_assertions/macro.assert_type_eq_all.html) for all these fields, asserting that `<Field<'static> as Yokeable<'a>>::Output == Field<'a>`. Another way is to make `transform_owned()` actually rebuild the type bit by bit, calling `Yokeable::transform_owned()` on all of the subfields-with-lifetimes. This can be done with `synstructure`, see how the ZeroCopyFrom derive uses synstructure to call ZCF on each of the fields: https://github.com/unicode-org/icu4x/blob/cce8f224c263fb579d3f5ff02e6589e3aa9d9717/utils/yoke/derive/src/lib.rs#L169-L180 (we won't need any of the lifetime-replacement, most likely). I prefer the latter approach.
