### ISSUE TITLE
Add benches for ZeroMap

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#853]
Follow-up from #652

Action items:

- [ ] Review how [ZeroVec](https://unicode-org.github.io/icu4x-docs/doc/zerovec/index.html) and [ZeroMap](https://unicode-org.github.io/icu4x-docs/doc/zerovec/map/index.html) work
- [ ] Learn Criterion: https://bheisler.github.io/criterion.rs/book/index.html
- [ ] Review the current benchmarks for ZeroVec: https://github.com/unicode-org/icu4x/tree/main/utils/zerovec/benches
- [ ] Add benchmarks for ZeroMap in Criterion
- [ ] Add similar benchmarks to LiteMap
- [ ] Optional: Add benchmarks for ZeroMap/LiteMap in IAI

@andrewnguyen

**Comment by Manishearth** [comment]
We should probably write the same benches for `litemap` too.

**Comment by Manishearth** [comment]
@andrewnguyen is interested in working on this

**Comment by Manishearth** [comment]
(Andrew isn't planning on fixing this anymore)

**Comment by Manishearth** [comment]
Alan plans to work on this

**Comment by poulsbo** [comment]
It's not clear to me what these benches are doing. I've put together a basic `ZeroMap` benchmark, and I can add more, but it would help to know our aim here.

I see with `ZeroVec` we quote benchmark numbers against `Vec<T>`, proving the speed of building/deserializing the thing, with comparable speeds for operations such as binary search, as expected. Do we want something similar here? We're binary searching the keys; do we want some numbers showing "serialization is a win, but you pay at lookup time"?

**Comment by Manishearth** [comment]
@poulsbo it's worth comparing against HashMap and also potentially LiteMap. We absolutely expect that lookup is more expensive, the question to answer is "how much more expensive" :)

utils/litemap already has a couple benchmarks to copy. 

The _main_ operations we care about are read operations, but benchmarking some write operations can be good too. Note that borrowed ZeroMaps will switch internal implementations if you try writing to them, it would be interesting to capture the performance impact of that.

**Comment by sffc** [comment]
> it would help to know our aim here.

I would like to have results to allow us to expand [this table](https://docs.rs/zerovec/0.3.0/zerovec/#performance) to include ZeroMap.
