### ISSUE TITLE
Migrate remaining data structs to fully borrowed

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#856]
Some data structs are capable of zero-copy deserialization.  We should migrate all data structs to be this way.  This means removing `#[yoke(cloning_zcf)]` where possible (from #847).

Separate issues to track each component:

- https://github.com/unicode-org/icu4x/issues/1661
- DateTimeFormat (see #876)
- PluralRules (see #615)
- UnicodeSet (see #855)
- LocaleCanonicalizer (see #1034)
- Calendar (see #1393)
- LSTM (see #1426)

Before closing this issue, the code should be audited to ensure there are no remaining instances of `#[yoke(cloning_zcf)]`, and then this meta-issue can be closed.

**Comment by Manishearth** [comment]
For some structs this will be dependent on https://github.com/unicode-org/icu4x/issues/844

**Comment by sffc** [comment]
ICU4X 0.4 is shipped.  This got done in some crates but not others.  Punting to 0.5.

**Comment by robertbastian** [comment]
In addition to the issues above there are also `#[yoke(cloning_zcf)]`s on `UnicodeSet` (fixing in #1604) and in `experimental/segmenter_lstm`. Should we file an issue for the latter?

**Comment by Manishearth** [comment]
We can also just add it as a list entry there without filing an issue, either works

**Comment by sffc** [comment]
Segmenter LSTM data is tracked by #905.  That issue is assigned to Ting-yu and scheduled for Sprint C.

**Comment by robertbastian** [comment]
Should be #1426 actually

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/1676

**Comment by Manishearth** [comment]
Here's the current list of non-zc keys:

```
    "datetime/skeletons@1",
    "list/and@1",
    "list/or@1",
    "list/unit@1",
    "locale_canonicalizer/aliases@1",
    "locale_canonicalizer/likelysubtags@1",
```

The first one is rather tricky, I plan to file an issue about it. The next three are experimental, the last two are https://github.com/unicode-org/icu4x/issues/1034 and need LocaleStr

**Comment by Manishearth** [comment]
list_formatter: https://github.com/unicode-org/icu4x/pull/1680

**Comment by robertbastian** [comment]
Actually https://github.com/unicode-org/icu4x/issues/1678 is the leaf, I think we can close #876 as well, we're not tracking anything there either.

**Comment by sffc** [comment]
#876 should stay open until the skeletons / components bag is actually zero-copy (no ZeroFrom hacks).
