### ISSUE TITLE
icu4x_fs_data_provider_create returns success when accessing bincode data without bincode feature enabled

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#861]
The `success.result` value is `true` when accessing bincode data even if the `bincode` feature not enabled. Using the provider in this state results in undefined behaviour.

The `success.value` is `false` when given a bogus path, so some errors are being handled properly.

Filing this as an FFI bug, but maybe an error is not being propagated elsewhere in the code.

**Comment by Manishearth** [comment]
I'm unable to reproduce this: I tweaked the example to have a `const char* path = "../../../../provider/testdata/testdata.bincode";`, and it faithfully errored "unable to create FsDataProvider"

**Comment by dminor** [comment]
Looking at the code for FsDataProvider::try_new [1], I don't see anything that will fail if the manifest.json file says the format is bincode, and we've compiled without bincode support. I would expect `try_new` to fail in this case.

It appears it will only fail if it is handed a bad path, which would be why it appeared to be working as expected when you tested above, it will try to access the manifest file at `./../../../provider/testdata/testdata.bincode/manifest.json`, and that manifest file does not exist.

[1] https://github.com/unicode-org/icu4x/blob/main/provider/fs/src/fs_data_provider.rs#L49-L59

**Comment by Manishearth** [comment]
@dminor Alright, so how should I get the kind of data y'all are looking at?

**Comment by sffc** [comment]
The error occurs in the `.load_payload()` function, not in `.try_new()`:

https://github.com/unicode-org/icu4x/blob/aca8858ffa29cf0721647d59e52863c059b45b3c/provider/fs/src/deserializer.rs#L114

I agree it would be nicer in `.try_new()`, but the error is handled, so we shouldn't be crashing.

**Comment by sffc** [comment]
In other words, the FFI function that should be failing is `icu4x_fixed_decimal_format_create`.

**Comment by dminor** [comment]
> @dminor Alright, so how should I get the kind of data y'all are looking at?

Roughly the same as the third example here: https://github.com/unicode-org/icu4x/tree/main/tools/datagen#examples

```cargo run --bin icu4x-datagen -- --cldr-tag 39.0.0 --all-keys --all-locales --out /tmp/icu4x_data --syntax bincode```

**Comment by dminor** [comment]
> The error occurs in the `.load_payload()` function, not in `.try_new()`:
> 
> https://github.com/unicode-org/icu4x/blob/aca8858ffa29cf0721647d59e52863c059b45b3c/provider/fs/src/deserializer.rs#L114
> 
> I agree it would be nicer in `.try_new()`, but the error is handled, so we shouldn't be crashing.

I'm sure we left out a return code check somewhere across the FFI in Gecko, and that is why it is crashing. I think it would still be nicer to error out as early as possible, but I can see the argument that this wouldn't be a problem if we're using the C++ FFI and checking return values is enforced.

**Comment by sffc** [comment]
I filed #866 to re-work how we handle the *manifest.json* file and fail early if a required feature is not enabled.

**Comment by Manishearth** [comment]
@dminor Yep, confirmed that when I run our example with that data I get (the expected) error:

```
[14:28:42] मanishearth@manishearth-glaptop ~/dev/icu4x/ffi/capi/examples/fixeddecimal ^_^ 
$ make
gcc test.c ../../../../target/debug/libicu_capi.a -ldl -lpthread -lm -g
./a.out
Failed to create FixedDecimalFormat
[14:29:58] मanishearth@manishearth-glaptop ~/dev/icu4x/ffi/cpp/examples/fixeddecimal ^_^ 
$ make
g++ -std=c++17 test.cpp ../../../../target/debug/libicu_capi.a -ldl -lpthread -lm -g
./a.out
terminate called after throwing an instance of 'std::bad_optional_access'
  what():  bad optional access
```

It sounds like `icu4x_fixed_decimal_format_create` needs an error check on your side. Hopefully Diplomat+cpp will exist soon and y'all will be able to use that API then.

**Comment by Manishearth** [comment]
So, on the plus side, the Rust code is not inherently unsound in any way (which I was really afraid of, since it would point to some bug in `yoke` or our other very limited `unsafe` dependencies). But we need to get better at error reporting.

**Comment by dminor** [comment]
Thanks! I think this will be covered by #866.
