### ISSUE TITLE
C++ FFI should allow use of externally defined ICU4XWriteable implementations

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#872]
I'm guessing this is already the plan, but we should allow callers of the C++ FFI to define their own ICU4XWriteable implementations instead of relying on the internal ones. We'd use this in Gecko for instance to pass in an existing buffer and hopefully avoid copies. So for something like https://github.com/unicode-org/icu4x/blob/09d5aef92cd37de4e51c53e0b1eb03abb1ce8543/ffi/cpp/include/decimal.hpp#L60-L69 I'd expect we'd have an overload that also takes a FixedDecimal and an ICU4XWriteable. Or maybe just the overloaded version, and have callers be explicit about what kind of ICU4XWriteable they want to use.

@Manishearth what do you think?

**Comment by Manishearth** [comment]
Yes, this is the plan, Writeable is already designed to allow this pluggability. _right now_ the FFI is returning strings however I think in the long run we want to generate _both_ a `FormatToString` and a `Format()` where `Format` operates on a general `Writeable` (could be templated for ease of use). Feel free to add a `Format()` operating on a writeable directly if you need one

cc @shadaj

**Comment by Manishearth** [comment]
Basically, this is explicitly a part of the design, you should add it when needed.
