### ISSUE TITLE
Import ICU4C enumerated properties data into ICU4X

### ISSUE THREAD

**Issue by iainireland** [unicode-org/icu4x#883]
Using the upropdump tool (unicode-org/icu#1741), ICU4C can emit data for Unicode properties as a .toml file. Issue #882 tracks the import of binary properties. We should also import enumerated properties.

**Comment by sffc** [comment]
Is this issue intended to cover binary enumerated properties (key/value as a UnicodeSet), actual enumerated properties (as a CodePointTrie), or both?

**Comment by iainireland** [comment]
I haven't written a patch yet. It's intended to cover at least binary enumerated properties. If it makes sense to split that up from CodePointTrie-style enumerated properties, we can open a separate issue.
