### ISSUE TITLE
Monitor and benchmark ICU4X data size?

### ISSUE THREAD

**Issue by gnrunge** [unicode-org/icu4x#913]
Is it worthwhile benchmarking/monitoring the ICU4X data size? Pros and cons.
Con: The data is what it is, and sending alerts when the size increases may be an unwelcome distraction most of the time.
Pro: It can make it easier to find out and explain when the data size increases and why.

**Comment by sffc** [comment]
I think it would make sense to add a dashboard for this.  As you say, data size is what it is, and we will have tools in place to help strip out what you don't need, but it would be useful nonetheless to track the "worst case" data size over time.

The easiest way to do this would be to track the size of the file "provider/testdata/data/testdata.postcard"

**Comment by gnrunge** [comment]
File "provider/testdata/data/testdata.postcard" is stored in the repository. How does it get build?
I assume cargo builds the file whenever necessary and then the file will be part of the PR.

In this case the benchmark will just measure the size of the file and send it to the dashboard.

**Comment by gnrunge** [comment]
https://github.com/unicode-org/icu4x/issues/913

**Comment by gnrunge** [comment]
https://github.com/unicode-org/icu4x/pull/1051

**Comment by sffc** [comment]
> File "provider/testdata/data/testdata.postcard" is stored in the repository. How does it get build?
> I assume cargo builds the file whenever necessary and then the file will be part of the PR.
> 
> In this case the benchmark will just measure the size of the file and send it to the dashboard.

CI ensures that the data file is kept up-to-date with the "testdata-check" command:

https://github.com/unicode-org/icu4x/blob/f19a64b4662d56c2588a592685e87c1e799c7f2a/tools/scripts/data.toml#L80
