### ISSUE TITLE
Write ICU4X-developer-oriented tutorial on DataProvider

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#917]
We should have a tutorial oriented toward ICU4X developers to help onboard people on creating a new data struct.  The tutorial should cover:

- Overview of the lifecycle of data in ICU4X
- How to write a good data struct definition
- How to write a transformer
- How to plug the transformer into the ICU4X infrastructure

CC @zbraniecki 

See #905

**Comment by aethanyc** [comment]
I'm interested to read this tutorial.
