### ISSUE TITLE
Perform normalization performance evaluation between Rust and ICU

### ISSUE THREAD

**Issue by zbraniecki** [unicode-org/icu4x#93]
The proposed experiment will allow us to get a basic idea on performance of normalization libraries between ICU and the Rust normalization crate.

I will use the https://github.com/zbraniecki/intl-measurements/ harness building two example apps that will use microtiming intervals to measure time used by both apps.
On top of that I'll plug the Rust test into Criterion for more detailed measurements.

If the results will warrant further testing, it may be then useful to write basic FFI for ICU4C to plug it into Criterion.

**Comment by zbraniecki** [comment]
This is related to #40 and #66

**Comment by zbraniecki** [comment]
The current procedure plan is:

* Build sample set
  * Vietnamise
    * Select a page from Vietnamise Wikipedia
    * Synthesize it to NFC (?)
    * ?
  * Korean
    * Select a page from Korean Wikipedia
    * ?
  * Perform the normalization operation on each document once

**Comment by zbraniecki** [comment]
Question marks represent things I'm unsure of:
* How to "synthesize a document to NFC"?
* Is there any other step or is the result text the input for our test?
* What to do with the Korean text?
* What operation should I perform from ICU and what from Rust normalization crate?

@hsivonen , @Manishearth , @sffc , @nciric - feedback and help?

**Comment by Manishearth** [comment]
I think we should just get text examples, and:

 - benchmark conversion to NFC
 - benchmark conversion to NFD
 - benchmark conversion of NFC form to NFD
 - benchmark conversion of NFD form to NFC

for everything. For everything but Vietnamese the text is probably already in nfc form.

The Rust crate has extension `nfc()` and `nfd()` methods which are character iterators: https://docs.rs/unicode-normalization/0.1.12/unicode_normalization/trait.UnicodeNormalization.html

**Comment by macchiati** [comment]
Let me elaborate what I said before: for perf testing we should use
representative data. That means ideally a representative sample for each of
the top world languages, then weight the resulting durations by the
percentage of text in that language (approximately,
*https://w3techs.com/technologies/history_overview/content_language/ms/y
<https://w3techs.com/technologies/history_overview/content_language/ms/y>*).

Anyway, a test with Vietnamese text, in the format used on the web, would
be interesting, but we have to keep in mind that the majority of text will
already be in NFC, so the speed with text that is already normalized will
be crucial.

Caveats of course since there are some diminishing returns on the effort to
collect that data. And other domains may vary, eg texting.

So you should also test English, and a few other languages on the top of
that list, as proxies for the whole list.

On Thu, May 14, 2020, 20:19 Zibi Braniecki <notifications@github.com> wrote:

> Question marks represent things I'm unsure of:
>
>    - How to "synthesize a document to NFC"?
>
> Not sure what that means either.

>
>    - Is there any other step or is the result text the input for our test?
>    - What to do with the Korean text?
>
> Less than 1%, so other languages would be better.

>
>    - What operation should I perform from ICU and what from Rust
>    normalization crate?
>
> I'd recommend

Convert to NFC
Test if NFC

**Comment by zbraniecki** [comment]
Thank you all!

Updated the plan to list languages and 4 benchmarks. Lmk if that sounds good.

**Comment by hsivonen** [comment]
> Select a Wikipedia page of a substantial length

FWIW, for encoding_rs, I chose the page for Mars, the planet (for [the reasons documented](https://github.com/hsivonen/encoding_bench#selection-of-test-data)). (Get plain-text versions from the [encoding_bench repo](https://github.com/hsivonen/encoding_bench/tree/master/src/wikipedia), [links to Wikipedia revisions](https://github.com/hsivonen/encoding_bench/blob/master/src/wikipedia/sources.txt), [license](https://github.com/hsivonen/encoding_bench/blob/master/LICENSE-CC-BY-SA) (not suited for checking into the ICU4X repo; also note the Czech version has GFDL portions).)

> For each document

For Vietnamese, please also generate a starting point that corresponds to the keyboard layout, which is neither NFC nor NFD. To get this form, first normalize to NFC and then apply the [`detone`](https://crates.io/crates/detone) crate with `orthographic` set to `true`.

> How to "synthesize a document to NFC"?

I suggest using the `unic_normal` crate. testdet has a [bit of code](https://github.com/hsivonen/testdet/blob/3f2629c9814290603e995be3184e79b4c349b5a7/src/main.rs#L701-L703) that generates as-if-from-keyboard Vietnamese using `unic_normal` and `detone`.

**Comment by hsivonen** [comment]
> Is there any other step or is the result text the input for our test?

I think the inputs are:

* Original data normalized to NFC (bench normalization to NFC, which should be no-op, and normalization to NFD)
* Original data normalized to NFD (bench normalization to NFD, which should be no-op, and normalization to NFC)
* Additionally for Vienamese only: Original data normalized to NFC followed by orthographic decomposition (bench normalization to NFC and NFD)

> What operation should I perform from ICU and what from Rust normalization crate?

For `unic_normal` you'd do `input.chars().nfc().collect::<String>()`, which has fundamentally different allocation behavior from ICU4C. You could also bench `input.chars().nfc().count()` to estimate the allocation and memory write cost. For ICU4C, the relevant function seems to be [`unorm2_normalize`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/unorm2_8h.html#a0a596802db767da410b4b04cb75cbc53), which writes to a caller-allocated buffer.

**Comment by hsivonen** [comment]
Sadly, there doesn't appear to be enough API surface to test the two engines in a commeasurable way in terms of allocation behavior.

**Comment by hsivonen** [comment]
On the Rust side, if you set the capacity of the `String` ahead of time and then extend it from an iterator, the allocation behavior matches ICU4C, and then UTF-8 vs. UTF-16 remains as the difference.

**Comment by hsivonen** [comment]
Using [`std::char::decode_utf16`](https://doc.rust-lang.org/std/char/fn.decode_utf16.html) to get the iterator over `char` in the Rust case would address the UTF-8 vs. UTF-16 difference on the input side.

**Comment by hsivonen** [comment]
On the output side, AFAICT, you'd need a bit of custom code around [`encode_utf16`](https://doc.rust-lang.org/std/primitive.char.html#method.encode_utf16) to write an iterator over `char` into a UTF-16 buffer.

**Comment by macchiati** [comment]
I don't think normalizing from NFD to NFC is a high use case. I'd recommend
(where "wild" is representative of what's on the web):

   - wild => NFC
   - wild => NFD
   - isNFC(wild)
   - isNFD(wild)

I'm a bit leery of simulating what we *think* Vietnamese might be on the
web at this point in time. However, vi is only 1.4%  of the total weight,
so as long as we weight it appropriately.

Mark

**Comment by macchiati** [comment]
Btw, nice page talking about why to pick Wikipedia Mars...

**Comment by zbraniecki** [comment]
With help from @hsivonen and @Manishearth I completed the initial test harness for normalization crate.

# Explainer

Due to differences between UTF-8 vs UTF-16 handling and its impact on the nature of the operation, both C and Rust code are measured within Rust crate, both in an [example binary](https://github.com/zbraniecki/intl-measurements/tree/master/unic/normalize/src) and a criterion [benchmark](https://github.com/zbraniecki/intl-measurements/tree/master/unic/normalize/benches). For the sake of sanity, I also verified on a very small subset that [a C++ app ](https://github.com/zbraniecki/intl-measurements/blob/master/icu/normalize.cpp) will give comparable numbers for ICU.

The criterion benchmark is more stable, but a single run of the binary in `--release` mode gives comparable results, so while below I'm presenting numbers from criterion, the `cargo run --release` on that crate should give comparable results.

For the performance review I used Henri's [encoding testsuite](https://github.com/hsivonen/encoding_bench/tree/master/src/wikipedia) which uses [wikipedia articles for given set of locales](https://hsivonen.fi/encoding_rs/#workloads).

As for locales, I used the following set: `"ar", "de", "en", "ko", "ru", "vi"`.

For the sake of completeness I compared UTF-16 operations on NFC and NFD and for `vi` Henri added an `orthographic` scenario for both.

Notice: I did not validate the output of any of the methods. I exclusively compared the performance of the calls based on the given input.

# Results

| Locale | Operation | Source | Encoding | C++ | Rust | Diff |
| --------: | ------------: | ---------: | -------------| -----: | -----: | ----: |
| ar | NFC | NFC | UTF-16 | 27.224 us | 365.91 us | (x13.0) |
| ar | NFC | NFC | UTF-8 | | 321.13 us | |
| ar | NFD | NFC | UTF-16 | 42.021 us | 234.21 us | (x5.5) |
| ar | NFD | NFC | UTF-8 | | 302.74 us |  |
| ar | NFC | NFD | UTF-16 | 46.405 us | 391.28 us | (x8.4) |
| ar | NFC | NFD | UTF-8 | | 470.15 us |  |
| ar | NFD | NFD | UTF-16 | 42.489 us | 249.78 us | (x5.9) |
| ar | NFD | NFD | UTF-8 | | 318.81 us | |
| de | NFC | NFC | UTF-16 | 76.972 us | 1.7980 ms | (x23.2) |
| de | NFC | NFC | UTF-8 | | 1.7830 ms |  |
| de | NFD | NFC | UTF-16 | 94.661 us | 1.1210 ms | (x11.9) |
| de | NFD | NFC | UTF-8 | | 1.1002 ms |  |
| de | NFC | NFD | UTF-16 | 132.27 us | 1.8075 ms | (x13.6) |
| de | NFC | NFD | UTF-8 | | 1.8072 ms |  |
| de | NFD | NFD | UTF-16 | 96.353 us | 1.1102 ms | (x11.5) |
| de | NFD | NFD | UTF-8 | | 1.0919 ms |  |
| en | NFC | NFC | UTF-16 | 65.217 us | 1.5867 ms | (x24.4) |
| en | NFC | NFC | UTF-8 | | 1.5546 ms | |
| en | NFD | NFC | UTF-16 | 64.187 us | 873.03 us | (x13.6) |
| en | NFD | NFC | UTF-8 | | 884.41 us | |
| en | NFC | NFD | UTF-16 | 62.624 us | 1.5472 ms | (x24.7) |
| en | NFC | NFD | UTF-8 | | 1.4711 ms | |
| en | NFD | NFD | UTF-16 | 67.357 us | 856.90 us | (x12.7) |
| en | NFD | NFD | UTF-8 | | 896.31 us | |
| ko | NFC | NFC | UTF-16 | 20.629 us | 368.37 us | (x17.8) |
| ko | NFC | NFC | UTF-8 | | 399.63 us | |
| ko | NFD | NFC | UTF-16 | 106.02 us | 247.49 us | (x2.3) |
| ko | NFD | NFC | UTF-8 | | 358.79 us | |
| ko | NFC | NFD | UTF-16 | 92.915 us | 465.07 us | (x5.0) |
| ko | NFC | NFD | UTF-8 | | 513.15 us | |
| ko | NFD | NFD | UTF-16 | 58.509 us | 303.24 us | (x5.1) |
| ko | NFD | NFD | UTF-8 | | 387.68 us | |
| ru | NFC | NFC | UTF-16 | 138.41 us | 1.8304 ms | (x13.2) |
| ru | NFC | NFC | UTF-8 | | 2.2583 ms | |
| ru | NFD | NFC | UTF-16 | 198.54 us | 1.2005 ms | (x6.0) |
| ru | NFD | NFC | UTF-8 | | 1.5329 ms | |
| ru | NFC | NFD | UTF-16 | 183.29 us | 1.8699 ms | (x10.1) |
| ru | NFC | NFD | UTF-8 | | 2.3132 ms | |
| ru | NFD | NFD | UTF-16 | 189.12 us | 1.2479 ms | (x6.6) |
| ru | NFD | NFD | UTF-8 | | 1.5129 ms | |
| vi | NFC | NFC | UTF-16 | 97.061 us | 2.0190 ms | (x20.8) |
| vi | NFC | NFC | UTF-8 | | 2.2570 ms | |
| vi | NFD | NFC | UTF-16 | 364.88 us | 1.3493 ms | (x3.6) |
| vi | NFD | NFC | UTF-8 | | 1.4905 ms | |
| vi | NFC | NFD | UTF-16 | 1.0147 ms | 2.2458 ms | (x2.2) |
| vi | NFC | NFD | UTF-8 | | 2.2110 ms | |
| vi | NFD | NFD | UTF-16 | 370.88 us | 1.2600 ms | (x3.4) |
| vi | NFD | NFD | UTF-8 | | 1.4762 ms | |

| Locale | Operation | Source | Encoding | C++ | Rust | Diff |
| --------: | ------------: | ---------: | -------------| -----: | -----: | ----: |
| vi | NFC | orthographic | UTF-16 | 911.77 us | 2.2167 ms | (x2.4) |
| vi | NFC | orthographic | UTF-8 | | 2.1625 ms | |
| vi | NFD | orthographic | UTF-16 | 403.16 us | 1.3254 ms | (x3.3) |
| vi | NFD | orthographic | UTF-8 | | 1.5354 ms | |

# Summary

* In all collected results ICU is 2-25 times faster than `unicode-normalization`
* The biggest differences can be observed in NFC->NFC operations
* The UTF-8 vs UTF-16 doesn't yield any significant differences

I encourage everyone to evaluate the source code to validate the code used for benchmarks.

**Comment by zbraniecki** [comment]
@Manishearth @hsivonen @sffc - can I get your thumbs up on the results?

I'd like to close this issue and get back to #40 once we confirm validity of the results.

We may also want to report the results to https://github.com/unicode-rs/unicode-normalization authors for evaluation (@Manishearth - can you facilitate this comms?)

**Comment by Manishearth** [comment]
Hmm, that's surprising, worth checking out what ICU does to get it such a perf win. unicode-normalization has not been vetted much for perf either.

Either way, seems like a from-scratch impl following the design of ICU might be better.

**Comment by Manishearth** [comment]
Oh, I see why, the tables are generated as giant match blocks instead of cached binary search tables which most of the other unicode crates use.

**Comment by zbraniecki** [comment]
This is now completed.

**Comment by zbraniecki** [comment]
Summary of the decision: We see a major performance difference in favor of ICU4C. Manish believes that the issue he filed would close the gap but said that between rewriting and fixing `unicode-normalize`, but isn't very opinionated on which we should do.

So, whoever will take this on can decide which route to take, and the harness is available to retest against a new target.

**Comment by nciric** [comment]
I think we need to discuss data loading issue with normalization. Would refitting existing crate with data provider interface be harder than writing one from scratch - as Manish said, normalization code is not very complex.
