### ISSUE TITLE
Programmatically check that Serde borrows everywhere it is required

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#935]
Follow-up from https://github.com/unicode-org/icu4x/pull/930

We should make `#[icu_provider::data_struct]` verify that data structs have `#[serde(borrow)]` everywhere that annotation is needed.

**Comment by sffc** [comment]
We should prioritize this.

**Comment by sffc** [comment]
A few options:

- Runtime test by instrumenting the global allocator
- Clippy lint? Might not be perfect.

**Comment by robertbastian** [comment]
Duplicate of #1661
