### ISSUE TITLE
Clean up uniset code

### ISSUE THREAD

**Issue by iainireland** [unicode-org/icu4x#944]
While working on the enumerated properties data provider, I've amassed a collection of small changes to the uniset code. Some of them merit further discussion. (I've already opened #940 to track using ResourceOptions for enum values instead of baking it into the key.) In no particular order:

1. As mentioned above, I think we should consider using ResourceOptions for enum values.
2. I think we should extend enum_props::GeneralCategory to include group properties (like Letter, which is a union of five subcategories). I expect that the higher-level categories like Letter and Number are going to be at least as useful, if not more useful, than the more specific versions. I don't see any value in exposing the internal data model to the user, particularly since CasedLetter would require a third tier in the hierarchy all to itself. Regarding the alignment of enum values between ICU4C and ICU4X, ICU4C already requires the user to pass in U_GET_GC_MASK(category) instead of the UCharCategory itself, precisely so that it can support higher-level categories. 
3. The list of scripts in enum_props::Script includes some scripts that don't have any associated entries in the PPUCD (like Cirth, Tolkien's runic alphabet, which is included in ISO 15924 but not in Unicode. Conversely, some scripts that exist in the PPUCD data exported from ICU4C aren't represented in the enum. 
4. We don't have a great story yet for making iterators available through FFI. Adding UnicodeSet::getRange makes it much less cumbersome to write a decent C++ FFI for irregexp. We can always deprecate it in the future if we come up with something better.
5. If we break the D: DataProvider<'data, ...> boilerplate in all the props.rs function signatures into a where clause, everything is much more readable, and it no longer seems necessary to have a rustfmt exemption. (Also there are some stale clippy exceptions that can be deleted without clippy complaining.)
6. We already support surrogate codepoints in UnicodeSet by virtue of UnicodeSetBuilder::add_u32. The data provider needs something like UnicodeSetBuilder::add_range_u32 to be able to support `General_Category=Surrogate`, because the endpoints of the range can't be represented as Rust `char`s. We can also add, for example, UnicodeSet::contains_range_u32; on the other hand, if the main use case for that would be checking for the presence of surrogates, maybe we should have something more direct.

**Comment by zbraniecki** [comment]
> We don't have a great story yet for making iterators available through FFI. 

I'd be interested in targeting it this quarter. I'm not sure how how soon we'll need it, but I am concerned about avoiding iterators and streams out of concern for FFI.

Here's my sync and async iterator implementation that goes from Rust, via C, C++ to WebIDL: https://searchfox.org/mozilla-central/source/intl/l10n/L10nRegistry.cpp#26-108

I'd be happy to work on abstracting it, and maybe it should even go into diplomat, alongside `Option` and `Result`?
