### ISSUE TITLE
Consider using litemap in locale extensions

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#969]
In the locale unicode and transform extensions code, we currently have data structures that look like:
```
pub struct Keywords(Option<Box<[(Key, Value)]>>);
```
where we have an array of key, value pairs that are kept in sorted order and are used like a HashMap. Since this code was originally written, we've added a `litemap` crate to util that works for these use cases. We should investigate switching over to using litemap to tidy things up. We'll want to be careful that this doesn't affect performance or memory footprint.

Suggested by Zibi in https://github.com/unicode-org/icu4x/pull/966#pullrequestreview-733283928.

**Comment by ozghimire** [comment]
I would like to work on this.

**Comment by sffc** [comment]
I did this in #1762.
