### ISSUE TITLE
Create a Collator component

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#971]
A collator does locale-sensitive string comparisons. The ICU4C implementation is documented [for C](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/ucol_8h.html) and for [C++ classes](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1Collator.html).

The ICU4X component should be able to back the ECMA-402 [`Intl.Collator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator). Most likely the ICU4X design will be inspired by this API.
 
@sffc brought up in our last weekly planning meeting that the Collator will need a Normalizer component (#972) as well.

This component will also need to coordinate with and rely upon the uniset component, so I'll include @echeran on this issue as well.

/cc @markusicu - We would love your thoughts on the requirements and direction for this component. I'm filing this issue to start tracking the work, but we'll need design work before we need the implementation. @hsivonen will be available on the Mozilla side to work on this. I'm available to help coordinate the efforts to make sure everyone gets what they needs to start work on this.

**Comment by hsivonen** [comment]
I think the items remaining for 1.0 are:

Under C-collator itself:
[ ] [Rearranging the NFD data bit allocations to accommodate NFKD also](https://github.com/unicode-org/icu4x/pull/1967)
[ ] [Simplifying the diacritic acceleration table and providing a way for a tailoring opt out of its use](https://github.com/unicode-org/icu4x/pull/1978) (none currently opt out)

Plus these provider items:
[ ] [Fallback to macrolanguage based on language subtag registry data](https://github.com/unicode-org/icu4x/issues/1963)
[ ] [Alias mapping for Traditional Chinese](https://github.com/unicode-org/icu4x/issues/1964)
[ ] [Other aliases from CLDR](https://github.com/unicode-org/icu4x/issues/1965)
[ ] [Verifying that de facto aliases that CLDR implements as copying imports get deduplicated; most likely already OK](https://github.com/unicode-org/icu4x/issues/1966)

Notably out of scope for 1.0:
[ ] [CLDR-compliant Hangul behavior for search collations](https://github.com/unicode-org/icu4x/issues/1941)
