### ISSUE TITLE
Add cargo-clippy linter for error prone constructs

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#98]
Based on #94 we want to have linting to enforcing code health.  [`cargo clippy`](https://github.com/rust-lang/rust-clippy) is the tool to catch error-prone constructs in Rust that are higher level than syntax (#95).

`cargo clippy` may return false positives but is configurable as to what is enabled.

@zbraniecki @sffc

**Comment by zbraniecki** [comment]
Yeah, I'm a fan of `cargo clippy` and `locale` component passes it clean.
