### ISSUE TITLE
Use FixedDecimalFormat in TimeZoneFormat

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#991]
When formatting digits for localized GMT formats in TimeZoneFormat, we should use FixedDecimalFormat to localize the digits as well. 

Currently, we format using `[0-9]` for all cases. 

This depends on FixedDecimalFormat having localizable digits.

**Comment by sffc** [comment]
@dminor to verify whether this is finished.

**Comment by dminor** [comment]
This was fixed at the same time as DateTimeFormat
