### ISSUE TITLE
Add supplemental CLDR metaZones.json to TimeZonesProvider

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#995]
CLDR [metaZones.json](https://github.com/unicode-org/cldr-json/blob/39205fdc027c935e52a268afcf01cd240f3c442d/cldr-json/cldr-core/supplemental/metaZones.json#L8) contains
* information on which time zones belong to which metazones at given time periods.
* information on which time zone is preferred for a metazone in a given territory.

We need this information in order to determine the metazone ID from a zoned timestamp, and to make informed decisions in non-location fallback formats.

**Comment by sffc** [comment]
@nordzilla Can you split "information on which time zone is preferred for a metazone in a given territory." into its own issue so we can mark this issue as fixed?

**Comment by sffc** [comment]
@nordzilla Please act on the above.

**Comment by nordzilla** [comment]
Created issue #2684
