### ISSUE TITLE
Add supplemental CLDR primaryZones.json to TimeZonesProvider

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#996]
CLDR [primaryZones.json](https://github.com/unicode-org/cldr-json/blob/39205fdc027c935e52a268afcf01cd240f3c442d/cldr-json/cldr-core/supplemental/primaryZones.json#L7) contains

* the primary zones for a given territory

This information is vital for performing region format, which occasionally uses the country itself name when formatting the primary zone for that country.

**Comment by robertbastian** [comment]
This is a datagen implementation detail and does not need to be tracked as an issue.
