### ISSUE TITLE
Add locale-specific CLDR territories.json to TimeZonesProvider

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#997]
CLDR [territories.json](https://github.com/unicode-org/cldr-json/blob/master/cldr-json/cldr-localenames-full/main/en/territories.json) contains

* localized names for territories in a given locale.

This is vital if we ever need to format the country or region name in various fallback formats.

**Comment by robertbastian** [comment]
This is a datagen implementation detail and does not need to be tracked as an issue.
